import { test, expect } from '@playwright/test'
import { login } from '../helpers/auth.mjs'

test('dashboard order placement and full-width search work on desktop and mobile', async ({page},testInfo) => {
  await login(page)
  await page.goto('/dashboard')
  await expect(page.getByRole('region', {name:'Action Center', exact:true})).toBeVisible()
  await expect(page.locator('.workspace-widget-grid')).toBeVisible()
  await page.getByRole('button',{name:'Search AIMS Ctrl K',exact:true}).click()
  const palette=page.locator('.command-palette'), search=page.locator('.command-palette-search')
  await expect(palette).toBeVisible()
  for (const width of [1366,390]) {
    await page.setViewportSize({width,height:844})
    expect(await search.evaluate(element => Math.abs(element.getBoundingClientRect().width-element.parentElement.getBoundingClientRect().width)<4)).toBeTruthy()
    expect(await page.getByRole('combobox',{name:'Search AIMS'}).evaluate(element=>element.getBoundingClientRect().width)).toBeGreaterThan(width===390 ? 200 : 500)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()
  }
  await page.screenshot({path:testInfo.outputPath('search-mobile.png')})
  await page.keyboard.press('Escape')
  await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
})

test('shared assistant explains workflows and reads stock and movements from real tools', async ({page},testInfo) => {
  test.setTimeout(90000)
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await login(page)
  await page.goto('/products')
  await page.getByRole('button',{name:'Ask AIMS',exact:true}).click()
  const assistant=page.locator('.aims-assistant')
  await expect(assistant).toBeVisible()
  await expect(assistant).toContainText('Browse product records')
  const question=page.getByLabel('Question for AIMS', {exact:true})
  await question.fill('stock for Laptop Stand')
  await question.press('Enter')
  await expect(assistant.locator('.assistant-facts')).toContainText('Available to sell')
  const movementResponse=page.waitForResponse(response=>response.url().includes('/intelligence-assistant/ask'))
  await assistant.getByRole('button',{name:'Recent movements',exact:true}).click()
  const movementReply=await (await movementResponse).json()
  expect(movementReply.cards.some(card=>card.tool==='get_stock_movements')).toBeTruthy()
  await expect(assistant.locator('.assistant-evidence-card').last()).toContainText('Stock movements')
  await question.fill('How do forecasts work?');await question.press('Enter')
  await expect(assistant).toContainText('advisory stock forecasts')
  await expect(assistant).toContainText('Choose a product and forecast period')
  await page.setViewportSize({width:390,height:844})
  await page.evaluate(async()=>{const {useSettingsStore}=window.__aimsCertification;useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})})
  await expect(assistant).toContainText('Pyet AIMS')
  expect(await assistant.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toBe('rgb(255, 255, 255)')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()
  await page.screenshot({path:testInfo.outputPath('assistant-mobile-dark.png')})
  await page.getByRole('button',{name:'Mbyll asistentin',exact:true}).click()
  await expect(assistant).toBeHidden()
  await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
  expect(errors).toEqual([])
})

test('assistant prevents duplicate requests, preserves errors and never fakes facts', async ({page}) => {
  await login(page);await page.goto('/products')
  await page.getByRole('button',{name:'Ask AIMS',exact:true}).click()
  let requests=0
  await page.route('**/api/intelligence-assistant/ask',async route=>{
    if(!/stock for/i.test(route.request().postDataJSON().question))return route.continue()
    requests++
    await new Promise(resolve=>setTimeout(resolve,300))
    await route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({message:'No permission to read this product.'})})
  })
  const input=page.getByLabel('Question for AIMS',{exact:true})
  await input.fill('stock for Laptop Stand');await input.press('Enter');await input.press('Enter')
  await expect(page.locator('.aims-assistant')).toContainText('No permission to read this product.')
  expect(requests).toBe(1)
  await expect(page.locator('.assistant-facts')).toHaveCount(0)
  await input.fill('Delete Laptop Stand');await input.press('Enter')
  await expect(page.locator('.aims-assistant')).toContainText(/read.only|explicit.*confirm|human.*confirm/i)
  expect(requests).toBe(1)
  await page.getByRole('button',{name:'Clear conversation',exact:true}).click()
  await expect(page.locator('.assistant-message')).toHaveCount(0)
})
