import {test,expect} from '@playwright/test'
import {spawnSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
test('V8 wholesale customer review creates one explicit draft and leaves balances and stock unchanged',async({page},testInfo)=>{
 test.setTimeout(90000)
 const database=fileURLToPath(new URL('../../../backend/database/e2e.sqlite',import.meta.url)),fixture=mode=>spawnSync('php',[fileURLToPath(new URL('../fixtures/customer-sales-intelligence.php',import.meta.url)),...(mode?[mode]:[])],{env:{...process.env,APP_ENV:'e2e',DB_CONNECTION:'sqlite',DB_DATABASE:database,DB_URL:'',CACHE_STORE:'array',SESSION_DRIVER:'array',QUEUE_CONNECTION:'sync',MAIL_MAILER:'array',BROADCAST_CONNECTION:'log'},encoding:'utf8'})
 const seed=fixture();expect(seed.status,seed.stderr||seed.stdout).toBe(0);const before=JSON.parse(fixture('verify').stdout),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/login');await page.getByLabel('Email address').fill('customer-v8@enterprise.test');await page.getByLabel('Password',{exact:true}).fill('password');await page.getByRole('button',{name:'Enter workspace'}).click();await expect(page).toHaveURL(/dashboard/)
 await page.goto('/customer-sales-intelligence');await page.getByRole('button',{name:'Refresh evidence',exact:true}).click();await expect(page.getByRole('button',{name:'Opportunities',exact:true})).toBeVisible();expect(JSON.parse(fixture('verify').stdout).business).toEqual(before.business)
 await page.getByRole('button',{name:'Opportunities',exact:true}).click();await page.getByRole('searchbox',{name:'Search customer evidence'}).fill('Furniture Company A');const card=page.locator('.csi-grid>article').filter({has:page.getByText('Fabric A',{exact:true})}).first();await expect(card).toContainText('1500');await card.getByRole('button',{name:'Review opportunity'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('€900.00');await expect(dialog).toContainText('Consistent recorded payments');await dialog.getByLabel('Your chosen quantity (m)').fill('2000');await dialog.getByRole('button',{name:'Review current price & stock'}).click();await expect(dialog).toContainText('€6,000.00');await dialog.getByRole('button',{name:'Confirm & Create Order Draft'}).evaluate(el=>{el.click();el.click()});await expect(dialog.getByRole('heading',{name:'Order draft created'})).toBeVisible();const after=JSON.parse(fixture('verify').stdout);expect(after.business).toEqual(before.business);expect(after.orders).toBe(1);await dialog.getByRole('link',{name:'Open Order Draft'}).click();await expect(page).toHaveURL(/fulfillment\?order=\d+/)
 await page.goto('/customer-sales-intelligence?view=affinity');await expect(page.getByRole('heading',{name:'Genuine basket associations'})).toBeVisible();await expect(page.locator('.csi-table')).toContainText('Related Fabric B');await page.getByRole('button',{name:'Data / Model Health'}).click();await expect(page.locator('.csi-panel')).toContainText('0/20 genuine timing outcomes')
 for(const width of [1366,768,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()}
 await page.evaluate(async()=>{const{useSettingsStore}=window.__aimsCertification;useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})});await expect(page.getByRole('heading',{name:'Inteligjenca e klientëve dhe shitjeve',exact:true})).toBeVisible();expect(await page.locator('.csi-panel').first().evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe('rgb(255, 255, 255)');await page.screenshot({path:testInfo.outputPath('customer-sales-mobile-dark.png')});expect(errors).toEqual([])
})
