import {test,expect} from '@playwright/test'
import {spawnSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
test('V10 learning evidence, sparse gates, future-only shadow and bilingual responsive UI',async({page},testInfo)=>{
 test.setTimeout(90000)
 const db=fileURLToPath(new URL('../../../backend/database/e2e.sqlite',import.meta.url)),fixture=mode=>spawnSync('php',[fileURLToPath(new URL('../fixtures/decision-learning.php',import.meta.url)),...(mode?[mode]:[])],{encoding:'utf8',env:{...process.env,APP_ENV:'e2e',DB_CONNECTION:'sqlite',DB_DATABASE:db,DB_URL:'',CACHE_STORE:'array',SESSION_DRIVER:'array',QUEUE_CONNECTION:'sync',MAIL_MAILER:'array',BROADCAST_CONNECTION:'log'}})
 const seeded=fixture();expect(seeded.status,seeded.stderr||seeded.stdout).toBe(0);const before=JSON.parse(fixture('verify').stdout),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/login');await page.getByLabel('Email address').fill('copilot-v9@enterprise.test');await page.getByLabel('Password',{exact:true}).fill('password');await page.getByRole('button',{name:'Enter workspace'}).click();await expect(page).toHaveURL(/dashboard/)
 await page.goto('/decision-learning');const main=page.locator('.learning-page');await expect(main.getByRole('heading',{name:'Decision Learning',exact:true})).toBeVisible();await expect(main).toContainText('Collecting decision outcomes');await expect(main).toContainText('Door handles')
 await main.getByRole('button',{name:'Human Decisions',exact:true}).click();await expect(main).toContainText('Human decisions and observed outcomes')
 await main.getByRole('button',{name:'Champion vs Challenger',exact:true}).click();await main.getByLabel('Advisory quantity multiplier').fill('0.8');await main.getByLabel('Review reason').fill('Review repeated human quantity reductions in future shadow only.');const create=main.getByRole('button',{name:'Create shadow experiment',exact:true});await create.evaluate(el=>{el.click();el.click()});await expect(main.getByRole('heading',{name:/Shadow experiment #/})).toHaveCount(1);await expect(main.getByRole('button',{name:'Review promotion',exact:true})).toBeDisabled();await expect(main).toContainText('0/50 independent windows');expect(JSON.parse(fixture('verify').stdout)).toEqual(before)
 await main.getByRole('button',{name:'Data Sufficiency',exact:true}).click();await expect(main).toContainText('No invented lost sales');await main.getByRole('button',{name:'Overview',exact:true}).click();await main.getByRole('button',{name:'View outcome',exact:true}).first().click();await expect(main).toContainText('Waiting for genuine outcome');await main.getByRole('button',{name:'Close outcome',exact:true}).click()
 await page.goto('/intelligence-assistant');const panel=page.locator('.aims-assistant.is-embedded'),input=panel.getByLabel('Question for AIMS',{exact:true});await input.fill('How good are inventory recommendations?');await input.press('Enter');await expect(panel).toContainText('Only the approved champion is production');await expect(panel.getByRole('link',{name:/Open source/}).first()).toHaveAttribute('href','/decision-learning')
 await page.goto('/decision-learning');await expect(main.getByRole('heading',{name:'Decision Learning',exact:true})).toBeVisible();for(const width of [1366,768,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()}
 await page.evaluate(async()=>{const{useSettingsStore}=await import('/src/store/settingsStore.js');useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})});await expect(main.getByRole('heading',{name:'Mësimi i vendimeve',exact:true})).toBeVisible();await expect(main.locator('.learning-metrics article')).toHaveCount(4);await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(1);await page.screenshot({path:testInfo.outputPath('decision-learning-dark-mobile.png')});expect(errors).toEqual([]);expect(JSON.parse(fixture('verify').stdout)).toEqual(before)
})
