import {test,expect} from '@playwright/test'
import {login} from '../helpers/auth.mjs'
test('V5 decisions evaluate genuine sparse records, compare read-only scenarios and review a PR draft',async({page})=>{
 test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page)
 // This is the isolated e2e database, never the installation's business data.
 const fixture=await page.evaluate(async()=>{const {apiRequest}=window.__aimsCertification;const categories=await apiRequest('/categories');const suppliers=await apiRequest('/suppliers');const supplier=(suppliers.data||suppliers)[0];const response=await apiRequest('/products',{method:'POST',body:JSON.stringify({name:'E2E Decision Handles',category_id:(categories.data||categories)[0].id,supplier_id:supplier.id,unit:'pcs',quantity:5,min_quantity:20,high_stock_threshold:1000,purchase_price:2,price:5,selling_price:5})});const p=response.product||response.data||response;const catalogue=await apiRequest('/product-suppliers?product_id='+p.id);const row=(catalogue.data||catalogue)[0];await apiRequest('/product-suppliers/'+row.id,{method:'PUT',body:JSON.stringify({purchase_price:2,currency:'EUR',usual_lead_time_days:3,pack_size:5,minimum_order_quantity:10,is_active:true})});return p})
 await page.goto('/inventory-intelligence?view=decisions');await expect(page.getByRole('heading',{name:'Decision Center',exact:true})).toBeVisible();await page.getByText('Evaluate a product',{exact:true}).click();await page.getByRole('combobox',{name:'Product to evaluate',exact:true}).selectOption({label:'E2E Decision Handles'});await page.getByRole('button',{name:'Evaluate evidence',exact:true}).click();await expect(page.locator('.decision-detail')).toBeVisible();await expect(page.locator('.decision-detail')).toContainText('Limited Intelligence');await expect(page.locator('.decision-detail')).toContainText('configured stock thresholds')
 await page.getByText('Compare your scenario · read-only',{exact:true}).click();await page.getByLabel('Quantity · inventory unit',{exact:true}).fill('25');await page.getByRole('button',{name:'Compare scenario',exact:true}).click();await expect(page.getByRole('heading',{name:'Your scenario',exact:true})).toBeVisible()
 await expect(page.locator('.decision-card').first()).toBeVisible();await page.getByRole('button',{name:'Review PR draft',exact:true}).click();await expect(page.getByRole('region',{name:'Purchase Request confirmation',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to alternatives',exact:true}).click();await page.getByRole('button',{name:'Review PR draft',exact:true}).click();await page.getByRole('button',{name:'Confirm draft',exact:true}).click();await expect(page.getByRole('link',{name:/Open Purchase Request/})).toBeVisible();await expect(page.locator('.intelligence-message').first()).toContainText('PR draft created')
 for(const width of [390,768,1366]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()}
 await page.evaluate(async()=>{const {useSettingsStore}=window.__aimsCertification;useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})});await expect(page.getByRole('heading',{name:'Qendra e vendimeve',exact:true})).toBeVisible();expect(await page.locator('.decision-detail').evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe('rgb(255, 255, 255)');await page.getByRole('button',{name:'Mbyll vendimin',exact:true}).click();await expect(page.locator('.decision-detail')).toHaveCount(0);expect(errors).toEqual([])
})
