import { test, expect } from '@playwright/test'
import { login } from '../helpers/auth.mjs'

test('purchase request edit → supplier quote → award review → created PO detail', async ({ page }) => {
  test.setTimeout(90_000)
  const errors=[]; page.on('pageerror',error=>errors.push(error.message))
  await login(page)
  await page.goto('/procurement')
  const form=page.locator('#purchase-request-form')
  await form.locator('select').first().selectOption({index:1})
  await form.getByPlaceholder('Quantity').fill('3')
  await form.getByPlaceholder('Estimated price').fill('10.10')
  const createdResponse=page.waitForResponse(r=>r.url().endsWith('/api/purchase-requests')&&r.request().method()==='POST')
  await form.getByRole('button',{name:'Create request',exact:true}).click()
  const created=await createdResponse; expect(created.ok()).toBeTruthy(); const request=await created.json()
  const row=page.getByRole('row').filter({hasText:request.request_number})
  await row.getByRole('button',{name:'Edit',exact:true}).click()
  await form.getByLabel('Notes').fill('Browser audited request')
  const saved=page.waitForResponse(r=>r.url().endsWith(`/api/purchase-requests/${request.id}`)&&r.request().method()==='PUT')
  await form.getByRole('button',{name:'Save',exact:true}).click()
  expect((await saved).ok()).toBeTruthy()
  await row.getByRole('button',{name:'Submit',exact:true}).click()
  await expect(page.locator('.supplier-choice')).toBeVisible()
  await page.locator('.supplier-choice input').first().check()
  await page.getByRole('button',{name:'Create & issue RFQ'}).click()
  const quoteForm=page.locator('form').filter({has:page.getByRole('heading',{name:'Record supplier quote'})})
  await expect(quoteForm).toBeVisible()
  await quoteForm.getByLabel('Supplier',{exact:true}).selectOption({index:1})
  await quoteForm.locator('input[type=checkbox]').first().check()
  await quoteForm.getByLabel('Unit price',{exact:true}).fill('9.99')
  await quoteForm.getByLabel('Lead time (days)').fill('3')
  expect(await quoteForm.evaluate(form=>form.checkValidity())).toBeTruthy()
  const quoteSaved=page.waitForResponse(r=>/\/api\/rfqs\/\d+\/quotes$/.test(r.url())&&r.request().method()==='POST')
  await quoteForm.getByRole('button',{name:'Save quote'}).click()
  expect((await quoteSaved).ok()).toBeTruthy()
  await page.locator('.comparison-head').getByRole('button',{name:'Confirm award'}).click()
  const review=page.getByRole('region',{name:'Review award'})
  await expect(review).toContainText('29.97')
  await review.getByRole('button',{name:'Back to selection'}).click()
  await expect(page.locator('.comparison-table input[type=radio]').first()).toBeChecked()
  await page.locator('.comparison-head').getByRole('button',{name:'Confirm award'}).click()
  const awarded=page.waitForResponse(r=>/\/api\/rfqs\/\d+\/award$/.test(r.url()))
  await review.getByRole('button',{name:'Confirm award'}).dblclick()
  expect((await awarded).ok()).toBeTruthy()
  await expect(page.locator('.comparison-table input[type=radio]').first()).toBeDisabled()
  const converted=page.waitForResponse(r=>/\/api\/rfqs\/\d+\/convert$/.test(r.url()))
  await page.getByRole('button',{name:'Create Purchase Orders',exact:true}).click()
  const result=await converted; expect(result.ok()).toBeTruthy(); const payload=await result.json()
  expect(payload.purchase_orders).toHaveLength(1)
  await page.getByRole('link',{name:'Open Purchase Order',exact:true}).click()
  await expect(page).toHaveURL(new RegExp(`/purchase-orders\\?po=${payload.purchase_orders[0].id}$`))
  await expect(page.locator('.main-content')).toContainText(payload.purchase_orders[0].po_number)
  expect(errors).toEqual([])
})

test('quality checklist create, edit, archive and restore remain usable', async ({ page }) => {
  await login(page)
  await page.goto('/quality')
  await page.getByRole('button',{name:'checklists',exact:true}).click()
  const form=page.locator('#quality-template-form'), name=`Browser checklist ${Date.now()}`
  await form.getByLabel('Name',{exact:true}).fill(name)
  await form.getByPlaceholder('Check name').fill('Package intact')
  await form.getByRole('button',{name:'Save checklist'}).click()
  const record=page.locator('.template-summary').filter({hasText:name})
  await expect(record).toBeVisible()
  await record.getByRole('button',{name:'Edit',exact:true}).click()
  await form.getByPlaceholder('Check name').fill('Package and label intact')
  const updated=page.waitForResponse(r=>/\/api\/quality\/templates\/\d+$/.test(r.url())&&r.request().method()==='PUT')
  await form.getByRole('button',{name:'Save checklist'}).click()
  expect((await updated).ok()).toBeTruthy()
  await record.getByRole('button',{name:'Archive',exact:true}).click()
  await expect(record).toContainText('Inactive')
  await record.getByRole('button',{name:'Restore',exact:true}).click()
  await expect(record).toContainText('Active')
})
