import {test,expect} from '@playwright/test'
import {spawnSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
test('V12 combined scenario, explicit review, silent updates, saved lineage and responsive bilingual workspace',async({page},testInfo)=>{
 test.setTimeout(120000)
 const db=fileURLToPath(new URL('../../../backend/database/e2e.sqlite',import.meta.url)),fixture=(...args)=>spawnSync('php',[fileURLToPath(new URL('../fixtures/strategic-simulation.php',import.meta.url)),...args],{encoding:'utf8',env:{...process.env,APP_ENV:'e2e',DB_CONNECTION:'sqlite',DB_DATABASE:db,DB_URL:'',CACHE_STORE:'array',SESSION_DRIVER:'array',QUEUE_CONNECTION:'sync',MAIL_MAILER:'array',BROADCAST_CONNECTION:'log'}})
 const seed=fixture();expect(seed.status,seed.stderr||seed.stdout).toBe(0);const ids=JSON.parse(seed.stdout),initial=JSON.parse(fixture('verify').stdout),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/login');await page.getByLabel('Email address').fill('simulation-v12@enterprise.test');await page.getByLabel('Password',{exact:true}).fill('password');await page.getByRole('button',{name:'Enter workspace'}).click();await expect(page).toHaveURL(/dashboard/)
 await page.goto('/strategic-simulation');const main=page.locator('.strategic-simulation');await expect(main.getByRole('heading',{name:'Strategic Simulation',exact:true})).toBeVisible();await main.getByLabel('Scenario name',{exact:true}).fill('China supply stress');const before=JSON.parse(fixture('verify').stdout)
 await main.getByText('Scope: products, warehouses and suppliers',{exact:true}).click();const warehousePicker=main.locator('.scope-picker-field').filter({has:page.getByText('Warehouses',{exact:true})});await warehousePicker.locator('summary').click();await warehousePicker.getByLabel('Main warehouse',{exact:true}).check();await warehousePicker.getByLabel('Branch warehouse',{exact:true}).check();await main.getByLabel('Declared transfer transit days (when history is missing)',{exact:true}).fill('2')
 const add=async(action,value,selectors={})=>{await main.getByLabel('What changes?',{exact:true}).selectOption(action);if(value!=null)await main.getByLabel(action.includes('delay')||action.includes('lead_days')?'Days':'Value',{exact:true}).fill(String(value));for(const [label,id]of Object.entries(selectors))await main.getByLabel(label,{exact:true}).selectOption(String(id));await main.getByRole('button',{name:'Add assumption',exact:true}).click()}
 await add('demand.percent',20);await add('supplier.lead_days',12,{'Supplier':ids.supplier_id});await add('logistics.delay',10,{'Shipment':ids.shipment_id});await add('customer.percent',30,{'Customer':ids.customer_id});await add('financial.collections_delay',7);await add('procurement.commitment_limit',90000)
 await main.getByRole('button',{name:'Review & run',exact:true}).click();const modal=page.getByRole('dialog');await expect(modal).toBeVisible();const confirm=modal.getByRole('button',{name:'Confirm & run simulation',exact:true});await expect(confirm).toBeDisabled();await modal.getByRole('button',{name:'Go back',exact:true}).click();await expect(main.locator('.simulation-chips>div')).toHaveCount(6);await main.getByRole('button',{name:'Review & run',exact:true}).click();await modal.getByLabel('I reviewed the scope, assumptions and limitations.',{exact:true}).check();let posts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/strategic-simulation'))posts++});const queued=page.waitForResponse(r=>r.url().endsWith('/api/strategic-simulation')&&r.request().method()==='POST');await confirm.evaluate(el=>{el.click();el.click()});const response=await queued;expect(response.status()).toBe(202);const run=(await response.json()).id;expect(posts).toBe(1)
 await main.getByLabel('Description (optional)',{exact:true}).fill('Keep this input while the background run finishes');const work=fixture('work',String(run));expect(work.status,work.stderr||work.stdout).toBe(0);await expect(main.getByRole('heading',{name:'3. Executive impact',exact:true})).toBeVisible({timeout:30000});await expect(main.getByLabel('Description (optional)',{exact:true})).toHaveValue('Keep this input while the background run finishes');const verified=JSON.parse(fixture('verify').stdout);expect(verified.business).toEqual(before.business);expect(verified.run.status,verified.run.error).toBe('COMPLETED');expect(verified.run.alternatives.length).toBeGreaterThan(0);for(const a of verified.run.alternatives)expect(Number(a.summary.commitment)).toBeLessThanOrEqual(90000);console.log('V12 REPRESENTATIVE',JSON.stringify(verified.run));
 await main.getByLabel('Values to test (2–15, comma separated)',{exact:true}).fill('0, 20, 40');await main.getByRole('button',{name:'Compare tested values',exact:true}).click();await expect(main.getByText('Discrete tested values, not an exact breakpoint.',{exact:true})).toBeVisible()
 await main.getByRole('button',{name:'Change assumptions',exact:true}).click();await main.getByRole('button',{name:'Review & run',exact:true}).click();await modal.getByLabel('I reviewed the scope, assumptions and limitations.',{exact:true}).check();const derived=page.waitForResponse(r=>r.url().endsWith(`/strategic-simulation/${run}/derive`));await modal.getByRole('button',{name:'Confirm & run simulation',exact:true}).click();expect((await derived).status()).toBe(202);expect(fixture('work').status).toBe(0);await expect(main.getByRole('heading',{name:'3. Executive impact',exact:true})).toBeVisible({timeout:30000});await expect(main.getByRole('link',{name:`Original run #${run}`,exact:true})).toBeVisible();expect(JSON.parse(fixture('verify').stdout).business).toEqual(before.business)
 const strategy=main.locator('.simulation-strategies button').filter({has:page.getByText('Balanced response',{exact:true})});await strategy.click();await main.getByRole('button',{name:'Prepare Response Plan',exact:true}).click();await modal.getByLabel('I reviewed the scope, assumptions and limitations.',{exact:true}).check();const prepared=page.waitForResponse(r=>r.url().endsWith('/response')&&r.request().method()==='POST');await modal.getByRole('button',{name:'Open fresh purchasing review',exact:true}).click();expect((await prepared).status()).toBe(202);await expect(main.getByRole('link',{name:'Open current-data purchasing review ↗',exact:true})).toHaveAttribute('href',/supply-optimizer\?plan=\d+/)
 for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()}
 await page.evaluate(async()=>{const{useSettingsStore}=window.__aimsCertification;useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})});await expect(main.getByRole('heading',{name:'Simulimi strategjik',exact:true})).toBeVisible();await page.screenshot({path:testInfo.outputPath('strategic-simulation-dark-mobile.png')});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:testInfo.outputPath('strategic-simulation-dark-desktop.png')});expect(errors).toEqual([])
})
