import {test,expect} from '@playwright/test'
import {spawnSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
test('V11 real solver, comparison, explicit review, safe drafts and responsive bilingual UI',async({page},testInfo)=>{
 test.setTimeout(90000)
 const db=fileURLToPath(new URL('../../../backend/database/e2e.sqlite',import.meta.url)),fixture=(...args)=>spawnSync('php',[fileURLToPath(new URL('../fixtures/supply-optimizer.php',import.meta.url)),...args],{encoding:'utf8',env:{...process.env,APP_ENV:'e2e',DB_CONNECTION:'sqlite',DB_DATABASE:db,DB_URL:'',CACHE_STORE:'array',SESSION_DRIVER:'array',QUEUE_CONNECTION:'sync',MAIL_MAILER:'array',BROADCAST_CONNECTION:'log'}})
 const seeded=fixture();expect(seeded.status,seeded.stderr||seeded.stdout).toBe(0);const before=JSON.parse(fixture('verify').stdout),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/login');await page.getByLabel('Email address').fill('optimizer-v11@enterprise.test');await page.getByLabel('Password',{exact:true}).fill('password');await page.getByRole('button',{name:'Enter workspace'}).click();await expect(page).toHaveURL(/dashboard/)
 await page.goto('/supply-optimizer');const main=page.locator('.supply-optimizer');await expect(main.getByRole('heading',{name:'Supply Optimizer',exact:true})).toBeVisible();await main.getByLabel('Purchasing commitment limit',{exact:true}).fill('2000');const queued=page.waitForResponse(r=>r.url().endsWith('/api/supply-optimizer')&&r.request().method()==='POST');await main.getByRole('button',{name:'Generate plans',exact:true}).click();const response=await queued;expect(response.status()).toBe(202);const id=(await response.json()).id;const done=fixture('work',String(id));expect(done.status,done.stderr||done.stdout).toBe(0);await expect(main).toContainText('Optimal within candidate set');await expect(main.locator('.optimizer-table-wrap tbody tr')).toHaveCount(3);expect(JSON.parse(fixture('verify').stdout).business).toEqual(before.business)
 await main.getByText('Choose a stress scenario',{exact:true}).click();await main.getByLabel('Supplier delay (days)',{exact:true}).fill('10');await main.getByLabel('Supplier affected',{exact:true}).selectOption({index:1});const stressed=page.waitForResponse(r=>r.url().endsWith(`/supply-optimizer/${id}/stress`));await main.getByRole('button',{name:'Inspect stress scenario',exact:true}).click();expect((await stressed).status()).toBe(200);expect(JSON.parse(fixture('verify').stdout).business).toEqual(before.business)
 await main.getByRole('button',{name:'Review & prepare drafts',exact:true}).click();const modal=page.getByRole('dialog');await expect(modal).toBeVisible();await expect(modal).toBeFocused();const confirm=modal.getByRole('button',{name:'Confirm & prepare drafts',exact:true});await expect(confirm).toBeDisabled();await modal.getByRole('button',{name:'Go back',exact:true}).click();await expect(modal).not.toBeVisible();await main.getByRole('button',{name:'Review & prepare drafts',exact:true}).click();await modal.getByLabel('I reviewed these proposals and want workflow drafts only.').check();await confirm.evaluate(el=>{el.click();el.click()});await expect(main).toContainText('Reviewed drafts prepared — not executed');await expect(main.getByRole('link',{name:/Open Purchase Request/})).toHaveCount(3);const after=JSON.parse(fixture('verify').stdout);expect(after.business).toEqual(before.business);expect(after.purchase_requests).toBe(3);expect(after.transfers).toBe(0)
 for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBeTruthy()}
 await page.evaluate(async()=>{const{useSettingsStore}=window.__aimsCertification;useSettingsStore.getState().applyPreferences({theme:'dark',language:'sq'})});await expect(main.getByRole('heading',{name:'Optimizuesi i furnizimit',exact:true})).toBeVisible();await page.screenshot({path:testInfo.outputPath('supply-optimizer-dark-mobile.png')});expect(errors).toEqual([])
})
