import {test,expect} from '@playwright/test'
import {mkdirSync} from 'node:fs'
import path from 'node:path'
import {login} from '../helpers/auth.mjs'

const output=path.resolve('../output/pm2')
const widget=(page,id)=>page.locator(`[data-widget="${id}"]`)
const order=page=>page.locator('[data-widget]').evaluateAll(nodes=>nodes.map(n=>n.dataset.widget))
const preferences=(page,theme,language)=>page.evaluate(async values=>{
  const {useSettingsStore}=await import('/src/store/settingsStore.js')
  useSettingsStore.getState().applyPreferences(values)
},{theme,language})
async function start(page,role='admin') {
  await login(page,role)
  await expect(page.getByRole('button',{name:'Customize Dashboard',exact:true})).toBeEnabled()
  await page.evaluate(async()=>{
    const {apiRequest}=await import('/src/api/client.js')
    const {useAuthStore}=await import('/src/store/authStore.js')
    const {defaultDashboard}=await import('/src/config/dashboardWidgets.js')
    const {defaultNavigation}=await import('/src/config/workspaceNavigation.js')
    const auth=useAuthStore.getState(),saved=await apiRequest('/settings/workspace')
    await apiRequest('/settings/workspace',{method:'PUT',body:JSON.stringify({revision:saved.revision,dashboard:defaultDashboard(auth.permissions,auth.role),navigation:defaultNavigation(auth.role)})})
  })
  await page.reload()
  await expect(page.getByRole('button',{name:'Customize Dashboard',exact:true})).toBeEnabled()
}
const edit=page=>page.getByRole('button',{name:'Customize Dashboard',exact:true}).click()
async function add(page,title) {
  await page.getByLabel('Search widgets',{exact:true}).fill(title)
  await page.locator('.widget-library-items').getByRole('button',{name:new RegExp(title)}).click()
}

test('dashboard editing, drag handles, resize, save across devices, cancel and confirmed reset',async({page,browser})=>{
  test.setTimeout(120000);await start(page)
  const initial=await order(page)
  for(const id of ['today-sales','orders-overview','low-stock','receivables','shipments','action-center']) await expect(widget(page,id)).toBeAttached()
  await edit(page)
  await widget(page,'product-count').getByRole('button',{name:'Remove widget: Products in inventory',exact:true}).click()
  await expect(widget(page,'product-count')).toHaveCount(0)
  await add(page,'Products in inventory')
  await expect(page.locator('.widget-library-items').getByRole('button',{name:/Products in inventory/})).toBeDisabled()
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  expect(await order(page)).toEqual(initial)
  await edit(page)
  for(const name of ['Supplier reliability','Cash outlook','Supply Optimizer summary']) await add(page,name)
  await page.getByLabel('Search widgets',{exact:true}).fill('')
  await widget(page,'sales-trend').getByRole('combobox',{name:'Size',exact:true}).selectOption('large')
  await widget(page,'sales-trend').getByRole('combobox',{name:'Period',exact:true}).selectOption('month')
  const supplier=widget(page,'supplier-reliability').getByRole('combobox',{name:'Supplier',exact:true})
  await supplier.scrollIntoViewIfNeeded()
  await expect(supplier).toBeEnabled()
  const options=await supplier.locator('option').allTextContents()
  expect(options.length).toBeGreaterThan(1)
  await supplier.selectOption({index:1})
  while((await order(page)).indexOf('cash-outlook')>4) await widget(page,'cash-outlook').getByRole('button',{name:'Move earlier: Cash outlook',exact:true}).click()
  // Native HTML drag/drop uses only the dedicated handle, not action-bearing headers.
  const beforeDrag=await order(page)
  await widget(page,'product-count').getByRole('button',{name:'Drag to reorder: Products in inventory',exact:true}).dragTo(widget(page,'receivables'),{targetPosition:{x:20,y:20}})
  await expect.poll(()=>order(page)).not.toEqual(beforeDrag)
  await expect(widget(page,'sales-trend').locator('.workspace-widget-content')).toHaveAttribute('inert','')
  const arranged=await order(page)
  let writes=0
  await page.route('**/api/settings/workspace',async route=>{
    if(route.request().method()==='PUT'){writes++;await new Promise(resolve=>setTimeout(resolve,250))}
    await route.continue()
  })
  await page.getByRole('button',{name:'Save',exact:true}).dblclick()
  await expect(page.getByRole('status').filter({hasText:'Dashboard saved.'})).toBeVisible()
  expect(writes).toBe(1)
  await page.unroute('**/api/settings/workspace')
  await page.reload();await expect(page.getByRole('button',{name:'Customize Dashboard',exact:true})).toBeEnabled()
  expect(await order(page)).toEqual(arranged)
  await expect(widget(page,'sales-trend')).toHaveClass(/widget-size-large/)
  const other=await browser.newContext(),device=await other.newPage()
  await login(device);await expect(device.getByRole('button',{name:'Customize Dashboard',exact:true})).toBeEnabled()
  expect(await order(device)).toEqual(arranged)
  await expect(widget(device,'cash-outlook')).toBeAttached()
  await other.close()
  await edit(page);await page.getByRole('button',{name:'Reset to Default',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Reset dashboard?'})
  await expect(dialog).toBeVisible();expect(await order(page)).toEqual(arranged)
  await dialog.getByRole('button',{name:'Reset to Default',exact:true}).click()
  expect(await order(page)).toEqual(initial)
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByRole('button',{name:'Customize Dashboard',exact:true})).toBeVisible()
})

test('navigation hide, favorites, constrained reorder, searchable hidden pages and restore',async({page})=>{
  await start(page)
  await page.getByRole('button',{name:'Customize Navigation',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Customize Navigation'})
  for(const id of ['automation-studio','decision-learning','analytics']) await dialog.locator(`[data-nav-item="${id}"]`).getByRole('checkbox').uncheck()
  await expect(dialog.locator('[data-nav-item="dashboard"]').getByRole('checkbox')).toBeDisabled()
  await dialog.getByRole('button',{name:'Pin: Products',exact:true}).click()
  await dialog.locator('[data-nav-item="stock"]').getByRole('button',{name:/Move earlier:/}).click()
  await dialog.getByRole('button',{name:'Save',exact:true}).click()
  await expect(dialog).toBeHidden()
  await expect(page.locator('.sidebar-favorites a[href="/products"]')).toBeVisible()
  await page.getByRole('button',{name:'Intelligence & reports',exact:true}).click()
  await expect(page.locator('.sidebar a[href="/analytics"]')).toHaveCount(0)
  await page.keyboard.press('Control+k')
  const search=page.getByRole('dialog').locator('input[role=combobox]')
  await search.fill('analytics')
  await page.getByRole('option').filter({hasText:'Open Analytics'}).click()
  await expect(page).toHaveURL(/\/analytics$/)
  await page.getByRole('button',{name:'Customize Navigation',exact:true}).click()
  const restored=page.getByRole('dialog',{name:'Customize Navigation'})
  await restored.getByRole('combobox',{name:'Show',exact:true}).selectOption('hidden')
  await restored.locator('[data-nav-item="analytics"]').getByRole('checkbox').click()
  await expect(restored.locator('[data-nav-item="analytics"]')).toHaveCount(0)
  await restored.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.locator('.sidebar a[href="/analytics"]')).toBeVisible()
  await page.reload()
  await expect(page.locator('.sidebar-favorites a[href="/products"]')).toBeVisible()
  await page.getByRole('button',{name:'Customize Navigation',exact:true}).click()
  await page.keyboard.press('Escape')
  expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
})

test('a failed widget is isolated and retryable; permissions revoke saved widgets safely',async({page})=>{
  await page.route('**/api/order-hub/overview',r=>r.fulfill({status:503,json:{message:'Orders temporarily unavailable'}}))
  await start(page)
  const orders=widget(page,'orders-overview')
  await orders.scrollIntoViewIfNeeded()
  await expect(orders).toContainText('Orders temporarily unavailable')
  await expect(widget(page,'product-count').locator('.widget-metric strong')).not.toHaveText('—')
  await page.unroute('**/api/order-hub/overview')
  await orders.getByRole('button',{name:'Try again',exact:true}).click()
  await expect(orders.locator('.widget-error')).toHaveCount(0)
  await page.evaluate(async()=>{
    const {useAuthStore}=await import('/src/store/authStore.js')
    useAuthStore.setState({permissions:useAuthStore.getState().permissions.filter(p=>p!=='analytics.finance'&&p!=='fulfillment.view')})
  })
  await expect(widget(page,'inventory-value')).toHaveCount(0)
  await expect(widget(page,'orders-overview')).toHaveCount(0)
  await edit(page)
  await page.getByLabel('Search widgets',{exact:true}).fill('Cash outlook')
  await expect(page.locator('.widget-library-items button')).toHaveCount(0)
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
})

test('responsive grid, EN/SQ, themes, keyboard editing and mobile restoration',async({page})=>{
  test.setTimeout(90000);mkdirSync(output,{recursive:true})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.emulateMedia({reducedMotion:'reduce'});await start(page)
  for(const width of [1920,1366,768,390]) {
    await page.setViewportSize({width,height:width<500?844:768})
    for(const [theme,language] of [['light','en'],['dark','sq']]) {
      await preferences(page,theme,language)
      await expect(page.locator('.personal-dashboard h1')).toHaveText(language==='en'?'Dashboard':'Paneli')
      await page.evaluate(()=>document.fonts.ready)
      await page.waitForTimeout(120)
      expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+2)
      const grid=await page.locator('.workspace-widget-grid').boundingBox(),boxes=await page.locator('[data-widget]').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}}))
      for(const b of boxes){expect(b.x).toBeGreaterThanOrEqual(grid.x-1);expect(b.x+b.width).toBeLessThanOrEqual(grid.x+grid.width+1)}
      if(width<700)for(const b of boxes) expect(b.width).toBeCloseTo(grid.width,0)
      for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x+a.width<=b.x+1||b.x+b.width<=a.x+1||a.y+a.height<=b.y+1||b.y+b.height<=a.y+1).toBeTruthy()}
      await page.screenshot({path:path.join(output,`dashboard-${width}-${theme}-${language}.png`),animations:'disabled'})
    }
  }
  await preferences(page,'dark','en');await edit(page)
  const arrow=widget(page,'product-count').getByRole('button',{name:'Move earlier: Products in inventory',exact:true})
  const initial=await order(page);await arrow.focus();await page.keyboard.press('Enter')
  expect((await order(page))[0]).toBe('product-count')
  await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await order(page)).toEqual(initial)
  await page.getByRole('button',{name:'Toggle navigation',exact:true}).click()
  await page.getByRole('button',{name:'Customize Navigation',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Customize Navigation'})).toBeVisible()
  await page.screenshot({path:path.join(output,'navigation-390-dark.png'),animations:'disabled'})
  await page.keyboard.press('Escape')
  expect(errors).toEqual([])
})
