import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {apiRequest} from '../api/client'
import {useAuthStore} from '../store/authStore'
import {useTranslation} from '../hooks/useTranslation'
import {customerSalesAccess,customerSalesLabel,customerSalesMoney} from '../pages/customerSalesPresentation'
import '../pages/CustomerSalesIntelligence.css'

export default function CustomerSalesSummary({customerId=null,decisionCenter=false}){
 const permissions=useAuthStore(s=>s.permissions),allowed=customerSalesAccess(permissions),{language}=useTranslation(),t=(a,b)=>language==='sq'?b:a,[data,setData]=useState(null)
 useEffect(()=>{if(!allowed)return;let active=true;apiRequest('/customer-sales-intelligence'+(customerId?`/customers/${customerId}`:'')).then(r=>{if(active)setData(r)}).catch(()=>{});return()=>{active=false}},[allowed,customerId])
 if(!allowed||!data||data.state!=='ready')return null
 const profile=data.profile,opportunities=customerId?data.opportunities:(data.evidence?.opportunities||[]).slice(0,3),label=k=>customerSalesLabel(k,language),money=v=>customerSalesMoney(v,data.evidence?.currency||'EUR',language)
 return <section className="csi-panel"><h2>{customerId?t('Customer intelligence','Inteligjenca e klientit'):decisionCenter?t('Commercial decisions • customer evidence','Vendimet tregtare • të dhënat e klientit'):t('Customers to review today','Klientët për rishikim sot')}</h2>{!customerId&&(data.evidence?.profiles||[]).filter(p=>['AT_RISK','INACTIVE'].includes(p.state)).slice(0,Math.max(0,3-opportunities.length)).map(p=><p key={p.id}><Link to={`/customer-debts?customer=${p.id}`}>{p.name}</Link> • {label('CUSTOMER_INACTIVITY')} • {label(p.state)}</p>)}{decisionCenter&&<p>{label('CUSTOMER_CONCENTRATION')}: {t('Top 5 customer share','Pjesa e 5 klientëve kryesorë')} {data.evidence?.concentration?.top_shares?.[5]??'—'}% • <Link to="/customer-sales-intelligence?view=concentration">{t('Review recorded concentration','Rishiko përqendrimin e regjistruar')}</Link></p>}{profile&&<><p>{label(profile.state)} • {label(profile.segment)} • {label(profile.trend.state)}</p><p>{t('First / last purchase in analysed history','Blerja e parë / fundit në historikun e analizuar')}: {profile.first_purchase||'—'} / {profile.last_purchase||'—'} • {profile.purchase_count} {t('recorded baskets','blerje të regjistruara')}</p><p>{t('Recorded net sales','Shitjet neto të regjistruara')}: {money(profile.summary.revenue)} • {t('Returns','Kthimet')}: {money(profile.summary.return_value)}</p>{profile.summary.gross_profit!==undefined&&<p>{t('Gross contribution context','Konteksti i kontributit bruto')}: {money(profile.summary.gross_profit)}</p>}<p>{t('Preferred products','Produktet e preferuara')}: {profile.products.slice(0,4).map(p=>p.name).join(', ')||'—'}</p><p>{t('Payment context','Konteksti i pagesave')}: {profile.financial_context?.payment_segment?label(profile.financial_context.payment_segment):t('Restricted / unknown','I kufizuar / i panjohur')}</p></>}{opportunities.map(o=><div key={o.key} className="csi-tags"><span>{o.customer} • {o.product}</span><span className="csi-badge">{label(o.kind)}</span>{o.inventory.constrained&&<span className="csi-badge">{label('SALES_INVENTORY_CONFLICT')}</span>}{o.financial_context?.review_required&&<span className="csi-badge">{label('CUSTOMER_FINANCIAL_CONFLICT')}</span>}</div>)}{!customerId&&!opportunities.length&&<p>{t('No supported reorder signals yet.','Ende nuk ka sinjale të mbështetura të riporositjes.')}</p>}<Link to="/customer-sales-intelligence?view=opportunities">{t('Review Customer & Sales Intelligence','Rishiko inteligjencën e klientëve dhe shitjeve')} →</Link></section>
}
