export const decisionLabels={
 REPLENISHMENT_DECISION:['Replenishment required','Kërkohet rifurnizim'],TRANSFER_VS_PURCHASE:['Transfer or purchase','Transferim apo blerje'],SUPPLIER_SELECTION:['Supplier trade-off','Krahasim furnitorësh'],PURCHASE_TIMING:['Purchasing timing','Koha e blerjes'],INCOMING_STOCK_RISK:['Incoming stock at risk','Furnizimi në rrezik'],EXCESS_INVENTORY_ACTION:['Review excess inventory','Rishiko inventarin e tepërt'],
 purchase:['Prepare a Purchase Request','Përgatit kërkesë blerjeje'],transfer_purchase:['Transfer and prepare the remaining purchase','Transfero dhe përgatit blerjen e mbetur'],transfer:['Review warehouse transfer','Rishiko transferimin ndërmjet depove'],monitor:['Monitor without new replenishment','Monitoro pa rifurnizim të ri'],reduce_future_purchase:['Reduce or postpone future purchasing','Ul ose shty blerjet e ardhshme'],review_excess_transfer:['Review redistribution of excess stock','Rishiko shpërndarjen e stokut të tepërt'],review_incoming:['Review shipment and receipt expectations','Rishiko dërgesën dhe afatet e pranimit'],
 critical:['Critical','Kritik'],high:['High','I lartë'],warning:['Review','Rishiko'],normal:['Normal','Normal'],moderate:['Moderate intelligence','Inteligjencë mesatare'],limited:['Limited Intelligence','Inteligjencë e kufizuar'],confidence_high:['High intelligence','Inteligjencë e lartë'],
 open:['Open','I hapur'],reviewed:['Reviewed','I rishikuar'],accepted:['Accepted','I pranuar'],modified:['Modified','I ndryshuar'],dismissed:['Dismissed','I refuzuar'],superseded:['Superseded','I zëvendësuar'],resolved:['Resolved','I zgjidhur'],created:['Created','I krijuar'],created_pr:['PR draft created','Drafti i kërkesës u krijua'],
 forecast_unavailable:['Insufficient historical data for a forecast-supported recommendation. Threshold-based review remains available.','Historik i pamjaftueshëm për rekomandim me parashikim. Rishikimi sipas kufijve të stokut mbetet i disponueshëm.'],warehouse_demand_unavailable:['Warehouse-level demand is unavailable.','Kërkesa në nivel depoje nuk është e disponueshme.'],supplier_variability_unknown:['Supplier lead-time variability is unknown.','Ndryshueshmëria e afatit të furnitorit është e panjohur.'],cash_completeness_unknown:['Recorded cash is incomplete or unavailable; affordability is not inferred.','Paraja e regjistruar është e paplotë ose e padisponueshme; aftësia paguese nuk supozohet.'],delay_attribution_uncertain:['Delay source uncertain — supplier, carrier, customs and receiving are not assumed interchangeable.','Burimi i vonesës është i pasigurt — furnitori, transportuesi, dogana dhe pranimi nuk konsiderohen të njëjta.'],transfer_arrival_unknown:['Transfer arrival date is unknown; confirm it in the transfer workflow.','Data e mbërritjes së transferimit është e panjohur; konfirmoje në rrjedhën e transferimit.'],
 transfer_requires_separate_authorization:['Transfer requires separate human authorization.','Transferimi kërkon autorizim njerëzor të veçantë.'],configured_threshold_not_forecast:['Based on configured stock thresholds, not a demand forecast.','Bazuar në kufijtë e konfiguruar të stokut, jo në parashikimin e kërkesës.'],no_new_replenishment:['No new stock is introduced.','Nuk shtohet stok i ri.'],do_not_cancel_existing_commitments_automatically:['Existing commitments are not cancelled automatically.','Angazhimet ekzistuese nuk anulohen automatikisht.'],destination_need_requires_review:['The destination warehouse requirement must be reviewed.','Nevoja e depos së destinacionit duhet të rishikohet.'],
 configured_company_floor_for_review_not_a_local_demand_forecast:['Donor stock is protected by a configured floor only; local demand is unknown and requires human review.','Stoku i depos burimore mbrohet vetëm me minimumin e konfiguruar; kërkesa lokale është e panjohur dhe kërkon rishikim njerëzor.'],
 stockout:['Stockout exposure','Ekspozimi ndaj mungesës'],availability:['Expected availability','Disponueshmëria e pritshme'],delay:['Delivery delay','Vonesa e dorëzimit'],quality:['Quality uncertainty','Pasiguria e cilësisë'],cost:['Relative purchase cost','Kostoja relative e blerjes'],excess:['Excess-stock exposure','Ekspozimi ndaj stokut të tepërt'],commitment:['Recorded cash context','Konteksti i parasë së regjistruar'],
 shipment_eta_late:['Shipment ETA later than promised receipt','Dërgesa pritet pas afatit të premtuar'],overdue_receipt:['Recorded receipt date passed','Data e regjistruar e pranimit ka kaluar'],undated_receipt:['Receipt has no expected date','Pranimi nuk ka datë të pritshme'],milestone_delay:['Recorded milestone risk','Rrezik nga etapat e regjistruara'],recorded_promise:['Recorded expected receipt','Pranimi i pritshëm i regjistruar'],
 forecast_and_operational_evidence:['Demand evidence and operational constraints indicate a decision is needed.','Të dhënat e kërkesës dhe kufizimet operative tregojnë nevojë për vendim.'],configured_threshold_and_operational_evidence:['Current operational records and configured stock thresholds require review.','Të dhënat aktuale operative dhe kufijtë e stokut kërkojnë rishikim.'],
 completed_observation:['Completed observation','Vëzhgim i përfunduar'],pending_or_incomplete:['Outcome pending or incomplete','Rezultati në pritje ose i paplotë'],
}
export function decisionLabel(key,language='en'){return decisionLabels[key]?.[language==='sq'?1:0]||key}
export function decisionScenario(form){const numeric=new Set(['base_quantity','supplier_id','delay_days','demand_multiplier','source_warehouse_id','transfer_days']);return Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''&&v!==null&&v!==undefined).map(([k,v])=>[k,numeric.has(k)?Number(v):v]))}
export function draftable(option){return Boolean(option?.feasible&&option.base_quantity>0&&option.supplier_id&&option.unit_price!==null&&option.unit_price!==undefined)}
