import {useEffect,useRef,useState} from 'react'
import WorkflowGuide from './WorkflowGuide'
import CustomerSalesSummary from './CustomerSalesSummary'
import {Link,useSearchParams} from 'react-router-dom'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import {decisionLabel,decisionScenario,draftable} from './decisionPresentation'
import './DecisionCenter.css'

const root='/analytics/decisions'
const blank=()=>({type:'purchase',base_quantity:'',supplier_id:'',delay_days:'0',demand_multiplier:'1',source_warehouse_id:'',transfer_days:''})
export default function DecisionCenter(){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,label=k=>decisionLabel(k,language),permissions=useAuthStore(s=>s.permissions)
 const [params,setParams]=useSearchParams(),id=params.get('decision'),[list,setList]=useState(null),[detail,setDetail]=useState(null),[revision,setRevision]=useState(0)
 const linkedProduct=params.get('product')||'',linkedWarehouse=params.get('warehouse_id')||''
 const [view,setView]=useState('attention'),[q,setQ]=useState(''),[page,setPage]=useState(1),[warehouse,setWarehouse]=useState(linkedWarehouse),[product,setProduct]=useState(linkedProduct),[severity,setSeverity]=useState('')
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState(''),[review,setReview]=useState(null),[confirmTransfer,setConfirmTransfer]=useState(false),[created,setCreated]=useState(null),[note,setNote]=useState(''),[transferId,setTransferId]=useState('')
 const [scenario,setScenario]=useState(blank()),[comparison,setComparison]=useState(null),pending=useRef(false),detailRef=useRef(null)
 const canManage=permissions.includes('procurement.manage'),canFinance=permissions.includes('analytics.finance')
 const n=v=>v===null||v===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(Number(v))
 const money=(v,c)=>v===null||v===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{style:'currency',currency:c||'EUR'}).format(Number(v))
 const date=v=>v?new Date(v).toLocaleString(language==='sq'?'sq-AL':'en-GB'):t('Unknown','E panjohur')
 useEffect(()=>{setProduct(linkedProduct);setWarehouse(linkedWarehouse);setPage(1)},[linkedProduct,linkedWarehouse])
 useEffect(()=>{let live=true;const timer=setTimeout(()=>apiRequest(root+'?'+new URLSearchParams({q,page,product_id:linkedProduct,warehouse_id:warehouse,view,severity})).then(r=>live&&setList(r)).catch(e=>live&&setError(e.message)),150);return()=>{live=false;clearTimeout(timer)}},[q,page,linkedProduct,warehouse,view,severity,revision])
 useEffect(()=>{setReview(null);setComparison(null);setCreated(null);setNote('');setTransferId('');setScenario(blank());setDetail(null);setSelected('');setError('');if(!id)return;let live=true;apiRequest(`${root}/${id}`).then(r=>{if(live){setDetail(r);setSelected(r.alternatives[0]?.key||'')}}).catch(e=>live&&setError(e.message));return()=>{live=false}},[id])
 useEffect(()=>{if(!id)return;let live=true;apiRequest(`${root}/${id}`).then(r=>live&&setDetail(r)).catch(e=>live&&setError(e.message));return()=>{live=false}},[id,revision])
 useEffect(()=>{if(detail?.id)detailRef.current?.scrollIntoView({block:'start',behavior:'instant'})},[detail?.id])
 async function act(fn,reload=false){if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await fn();if(reload)setRevision(v=>v+1)}catch(e){setError(e.errors?Object.values(e.errors).flat().join(' '):e.message)}finally{pending.current=false;setBusy(false)}}
 const post=(path,body)=>apiRequest(root+path,{method:'POST',body:JSON.stringify(body)})
 function choose(d){setParams(p=>{p.set('decision',d.id);return p})}
 function close(){setParams(p=>{p.delete('decision');return p});setReview(null);setError('');setMessage('')}
 const option=detail?.alternatives.find(o=>o.key===selected),e=detail?.evidence
 function actionSummary(o,unit=o?.unit){if(!o)return '—';return <><strong>{label(o.action)}</strong>{o.transfer_quantity>0&&<span>{n(o.transfer_quantity)} {unit} · {o.transfer?.source_warehouse_name}</span>}{o.base_quantity>0&&<span>{n(o.base_quantity)} {unit} · {o.supplier_name||t('Supplier unknown','Furnitor i panjohur')}</span>}</>}
 function impact(o){return <dl className="decision-metrics"><div><dt>{t('Stockout before → after','Mungesa para → pas')}</dt><dd>{o?.impact?.stockout_before||'—'} → {o?.impact?.stockout_after||'—'}</dd></div><div><dt>{t('Projected coverage after arrival','Mbulimi i parashikuar pas mbërritjes')}</dt><dd>{n(o?.impact?.days_of_supply)} {t('days','ditë')}</dd></div><div><dt>{t('Expected arrival','Mbërritja e pritshme')}</dt><dd>{o?.impact?.arrival||'—'}</dd></div>{canFinance&&<div><dt>{t('Approximate commitment · company currency','Angazhimi i përafërt · monedha e kompanisë')}</dt><dd>{money(o?.base_cost,e?.finance?.base_currency)}</dd></div>}<div><dt>{t('Projected excess','Teprica e parashikuar')}</dt><dd>{n(o?.impact?.excess_quantity)}</dd></div></dl>}
 async function record(action){await act(async()=>{await post(`/${id}/feedback`,{action,note,...(transferId?{stock_transfer_id:Number(transferId)}:{})});setMessage(t('Decision recorded. No automatic operational action.','Vendimi u regjistrua. Pa veprim automatik operativ.'))},true)}
 return <main className="intelligence-page decision-center">
  <CustomerSalesSummary decisionCenter />
  <header><div><p className="eyebrow">{t('RECOMMENDED NEXT ACTIONS','VEPRIMET E REKOMANDUARA')}</p><h1>{t('Decision Center','Qendra e vendimeve')}</h1><p>{t('Understand the evidence, compare actions and decide. Operational approval stays with you.','Kupto provat, krahaso veprimet dhe vendos. Miratimi operativ mbetet te ti.')}</p></div><Link to="/decision-learning">{t('Decision Learning · policy and outcomes','Mësimi i vendimeve · politika dhe rezultatet')} →</Link></header>
  <WorkflowGuide workflow="decisions"/>
  {error&&<p role="alert" className="intelligence-error">{error}</p>}{message&&<p role="status" className="intelligence-message">{message}</p>}
  {linkedProduct&&<p>{t('Decisions for','Vendimet për')}: {list?.products.find(p=>String(p.id)===linkedProduct)?.name||'#'+linkedProduct} <button onClick={()=>setParams(p=>{p.delete('product');return p})}>{t('Clear product filter','Hiq filtrin e produktit')}</button></p>}
  <nav className="decision-views" aria-label={t('Decision views','Pamjet e vendimeve')}>{[['attention','Needs attention','Kërkojnë vëmendje'],['inventory','Inventory','Inventari'],['suppliers','Suppliers','Furnitorët'],['incoming','Incoming','Furnizimet'],...(canFinance?[['finance','Financial context','Konteksti financiar']]:[]),['history','History','Historiku']].map(([v,en,sq])=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setPage(1)}}>{t(en,sq)}</button>)}</nav>
  <div className="intelligence-toolbar"><label>{t('Search decisions','Kërko vendimet')}<input type="search" value={q} onChange={x=>{setQ(x.target.value);setPage(1)}}/></label><label>{t('Warehouse','Depoja')}<select value={warehouse} onChange={x=>{setWarehouse(x.target.value);setPage(1)}}><option value="">{t('All scopes','Të gjitha fushat')}</option>{list?.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>{t('Priority','Përparësia')}<select value={severity} onChange={x=>{setSeverity(x.target.value);setPage(1)}}><option value="">{t('All priorities','Të gjitha përparësitë')}</option>{['critical','high','warning','normal'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label></div>
  <details className="decision-refresh"><summary>{t('Evaluate a product','Vlerëso një produkt')}</summary><p>{t('Background workers refresh changed records. This control evaluates one product now; opening a decision does not recompute it.','Punëtorët në sfond përditësojnë të dhënat e ndryshuara. Ky kontroll vlerëson një produkt tani; hapja e vendimit nuk e rillogarit atë.')}</p><div className="intelligence-toolbar"><label>{t('Product to evaluate','Produkti për vlerësim')}<select value={product} onChange={x=>setProduct(x.target.value)}><option value="">{t('Choose product','Zgjedh produktin')}</option>{list?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy||!product} onClick={()=>act(async()=>{const r=await post(`/products/${product}/refresh`,{warehouse_id:warehouse?Number(warehouse):null});setMessage(t('Evidence evaluated.','Provat u vlerësuan.'));if(r.decisions[0])choose(r.decisions[0]);setReview(null)},true)}>{busy?t('Processing…','Duke përpunuar…'):t('Evaluate evidence','Vlerëso provat')}</button></div></details>
  {list&&<details className="decision-quality"><summary>{t('Decision activity and observational outcomes','Aktiviteti i vendimeve dhe rezultatet e vëzhguara')}</summary><dl className="decision-metrics"><div><dt>{t('Generated','Të krijuara')}</dt><dd>{n(list.quality.generated)}</dd></div>{['reviewed','accepted','modified','dismissed'].map(s=><div key={s}><dt>{label(s)}</dt><dd>{n(list.summary[s]||0)}</dd></div>)}<div><dt>{t('Unresolved','Të pazgjidhura')}</dt><dd>{n((list.summary.open||0)+(list.summary.reviewed||0))}</dd></div><div><dt>{t('Data-limited decisions','Vendime me të dhëna të kufizuara')}</dt><dd>{n(list.quality.limited)}</dd></div><div><dt>{t('Completed observations','Vëzhgime të përfunduara')}</dt><dd>{n(list.quality.completed_outcomes)}</dd></div><div><dt>{t('Observed stockouts','Mungesa të vëzhguara')}</dt><dd>{n(list.quality.observed_stockouts)}</dd></div></dl><p>{t('These are recorded outcomes, not proven causal savings or stockout prevention.','Këto janë rezultate të regjistruara, jo kursime shkakësore ose parandalim i provuar i mungesës.')}</p></details>}
  <section className="decision-grid" aria-label={t('Decisions','Vendimet')}>{list?.rows.map(d=><article key={d.id} className="decision-card"><div className="decision-badges"><span data-severity={d.severity}>{label(d.severity)}</span><span>{label(d.status)}</span></div><h2>{d.evidence.product.name}</h2><h3>{label(d.decision_type)}</h3><small>{d.evidence.warehouse?.name||t('Company-wide','Në nivel kompanie')}</small><div className="decision-action">{actionSummary(d.recommended,d.evidence.product.unit)}</div><p>{label(d.reasoning.why)}</p><small>{d.recommended?.impact?.projection_supported?t('Projected stockout before → after','Mungesa e parashikuar para → pas')+': '+(d.recommended.impact.stockout_before||'—')+' → '+(d.recommended.impact.stockout_after||'—'):t('Threshold requirement','Nevoja sipas kufirit')+': '+n(d.evidence.required_quantity)+' '+d.evidence.product.unit}</small><p>{label(d.confidence==='high'?'confidence_high':d.confidence)}{d.stale?' · '+t('Evidence needs refresh','Provat kërkojnë përditësim'):''}</p><small>{t('Evaluated','Vlerësuar')}: {date(d.last_checked_at)}</small><button onClick={()=>choose(d)}>{t('Review Decision','Rishiko vendimin')} →</button></article>)}</section>
  {list&&!list.rows.length&&<p className="decision-empty">{t('No decisions in this view. Evaluate a product or allow the background reconciliation to run.','Nuk ka vendime në këtë pamje. Vlerëso një produkt ose lejo pajtimin në sfond.')}</p>}
  {list?.last_page>1&&<div className="decision-buttons"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>‹</button><span>{page} / {list.last_page}</span><button disabled={page>=list.last_page} onClick={()=>setPage(v=>v+1)}>›</button></div>}
  {detail&&<section className="intelligence-detail decision-detail" ref={detailRef} aria-label={t('Decision details','Detajet e vendimit')}>
   <p>{t('Frozen policy version','Versioni i ngrirë i politikës')}: <code>{detail.reasoning?.policy_version}</code> · <Link to={'/decision-learning?tab=outcomes&decision='+detail.id}>{t('Human response & observed outcome','Përgjigjja e përdoruesit dhe rezultati i vëzhguar')}</Link></p>
   {e.financial_intelligence&&<details><summary>{t('Purchase versus cash · Financial Intelligence','Blerja kundrejt parasë · Inteligjenca financiare')}</summary><p>{t('Frozen financial evidence as of','Të dhënat financiare të ruajtura më')} {e.financial_intelligence.as_of} · <Link to="/financial-intelligence">{t('Open cash forecast and scenarios','Hap parashikimin e parasë dhe skenarët')} →</Link></p><dl className="decision-metrics"><div><dt>{t('Expected 30-day inflows','Hyrjet e pritshme 30-ditore')}</dt><dd>{money(e.financial_intelligence.cash_forecast?.inflows,e.financial_intelligence.currency)}</dd></div><div><dt>{t('Expected 30-day outflows','Daljet e pritshme 30-ditore')}</dt><dd>{money(e.financial_intelligence.cash_forecast?.outflows,e.financial_intelligence.currency)}</dd></div><div><dt>{t('Expected cash · recorded accounts','Paraja e pritshme · llogaritë e regjistruara')}</dt><dd>{money(e.financial_intelligence.cash_forecast?.expected_closing_cash,e.financial_intelligence.currency)}</dd></div></dl>{!e.financial_intelligence.cash_complete&&<p>{t('Complete cash position unavailable.','Pozicioni i plotë i parasë nuk është i disponueshëm.')}</p>}<p>{t('These purchases are additional potential commitments, not supplier payables yet. Compare payment timing without letting lower cash outlay override inventory safety.','Këto blerje janë angazhime të mundshme shtesë, ende jo detyrime ndaj furnitorit. Krahaso afatet e pagesës pa lejuar që shpenzimi më i ulët të tejkalojë sigurinë e inventarit.')}</p></details>}
   {e.financial_intelligence?.purchase_tradeoffs?.length>0&&<details><summary>{t('Purchase alternatives · cash and stock risk','Alternativat e blerjes · paraja dhe rreziku i stokut')}</summary><p>{t('Hypothetical full payment inside the 30-day forecast. It is not a supplier payment schedule. The operational ranking remains unchanged.','Pagesë e plotë hipotetike brenda parashikimit 30-ditor. Nuk është plan pagese i furnitorit. Renditja operative mbetet e pandryshuar.')}</p><div className="decision-financial-table"><table><thead><tr>{[t('Action','Veprimi'),t('Purchase quantity','Sasia për blerje'),t('Additional commitment','Angazhimi shtesë'),t('Expected cash if paid','Paraja e pritshme nëse paguhet'),t('Stockout after action','Mungesa e stokut pas veprimit')].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{e.financial_intelligence.purchase_tradeoffs.map(option=><tr key={option.key}><td>{label(option.action)}{option.transfer_quantity>0&&<small>{t('Transfer','Transferim')}: {n(option.transfer_quantity)} {e.product.unit}</small>}</td><td>{n(option.quantity)} {e.product.unit}</td><td>{money(option.additional_purchase,e.financial_intelligence.currency)}</td><td>{money(option.expected_cash_if_paid_within_horizon,e.financial_intelligence.currency)}</td><td>{option.coverage_supported?(option.stockout_after||t('None in supported horizon','Asnjë në periudhën e mbuluar')):t('Insufficient inventory history','Histori e pamjaftueshme e inventarit')}</td></tr>)}</tbody></table></div></details>}
   <header><div><h2>{e.product.name} · {label(detail.decision_type)}</h2><p>{label(detail.status)} · {label(detail.confidence==='high'?'confidence_high':detail.confidence)} · {t('Evidence cutoff','Kufiri kohor i provave')}: {date(detail.evidence_cutoff_at)}</p></div><button aria-label={t('Close decision','Mbyll vendimin')} onClick={close}>×</button></header>
   {detail.stale&&<p className="decision-warning">{t('Evidence is stale or changed. Confidence is reduced; evaluate again. Draft confirmation always revalidates live records.','Provat janë të vjetruara ose të ndryshuara. Besueshmëria u ul; vlerëso përsëri. Konfirmimi i draftit rivlerëson gjithmonë të dhënat aktuale.')}</p>}
   <h3>{t('Situation · observed facts','Situata · faktet e vëzhguara')}</h3><p>{label(detail.reasoning.why)}</p><dl className="decision-metrics">{[['available','Usable stock','Stoku i përdorshëm'],['reserved','Reserved','I rezervuar'],['committed_outgoing','Unreserved commitments','Angazhime pa rezervim'],['incoming','Recorded incoming · dates matter','Furnizim i regjistruar · datat kanë rëndësi'],['quarantine','Quarantine','Karantina'],['blocked','Blocked inventory','Inventari i bllokuar']].map(([k,en,sq])=><div key={k}><dt>{t(en,sq)}</dt><dd>{n(e.inventory[k])} {e.product.unit}</dd></div>)}<div><dt>{t('Inventory position','Pozicioni i inventarit')}</dt><dd>{n(e.inventory_position.position)} {e.product.unit}</dd></div><div><dt>{t('Replenishment requirement','Nevoja për rifurnizim')}</dt><dd>{n(e.required_quantity)} {e.product.unit}</dd></div></dl>
   <h3>{t('Predictions · not guarantees','Parashikimet · jo garanci')}</h3>{e.forecast.available?<dl className="decision-metrics"><div><dt>{t('Projected stockout','Mungesa e parashikuar')}</dt><dd>{e.forecast.stockout_date||'—'}</dd></div><div><dt>{t('Remaining coverage','Mbulimi i mbetur')}</dt><dd>{n(e.forecast.days_of_supply)} {t('days','ditë')}</dd></div><div><dt>{t('Forecast horizon','Horizonti i parashikimit')}</dt><dd>{n(e.forecast.horizon)} {t('days','ditë')}</dd></div></dl>:<p className="decision-warning">{label('forecast_unavailable')}</p>}
   {e.purchase_timing&&<p>{t('Suggested purchasing date','Data e sugjeruar e blerjes')}: {e.purchase_timing.reorder_date||t('Requires review — no supported forecast','Kërkon rishikim — pa parashikim të mbështetur')} · {t('Planning lead time','Afati i planifikimit')}: {n(e.purchase_timing.lead_days)} {t('days','ditë')}</p>}
   <h3>{t('Recommendation and alternatives','Rekomandimi dhe alternativat')}</h3><p>{t('Ranked by weighted risk: stockout and availability take priority. Unknowns carry uncertainty, not zero risk. Scores are not probabilities.','Renditur sipas rrezikut të ponderuar: mungesa dhe disponueshmëria kanë përparësi. Të panjohurat mbajnë pasiguri, jo rrezik zero. Pikët nuk janë probabilitete.')}</p>
   <div className="decision-alternatives">{detail.alternatives.map(o=><article key={o.key} className={o.key===selected?'selected':''}><label className="decision-option"><input type="radio" name="decision-alternative" value={o.key} checked={selected===o.key} onChange={()=>{setSelected(o.key);setReview(null);setConfirmTransfer(false)}}/><strong>#{o.rank} · {label(o.action)}</strong></label><div className="decision-action">{actionSummary(o)}</div>{!o.feasible&&<p className="decision-warning">{t('Not feasible under current constraints','Nuk është i realizueshëm me kufizimet aktuale')}</p>}{impact(o)}{o.supplier_risk&&<p>{t('Lead time','Afati')}: {n(o.supplier_risk.lead_days)} {t('days','ditë')} · {t('Historical late deliveries','Dorëzime historike të vonuara')}: {n(o.supplier_risk.late_delivery_percent)}%</p>}<details><summary>{t('Why this rank?','Pse kjo renditje?')} {n(o.risk_score)}</summary><ul>{o.score_components?.map(c=><li key={c.criterion}>{label(c.criterion)} · {t('risk','rreziku')} {n(c.risk)} · {t('weight','pesha')} {c.weight}</li>)}</ul></details></article>)}</div>
   <details><summary>{t('Constraints, assumptions and unknowns','Kufizimet, supozimet dhe të panjohurat')}</summary><dl className="decision-metrics"><div><dt>{t('Safety stock','Stoku i sigurisë')}</dt><dd>{n(e.safety_stock)}</dd></div><div><dt>{t('Reorder point / configured floor','Pika e riporositjes / minimumi')}</dt><dd>{n(e.reorder_point??e.threshold_target)}</dd></div><div><dt>{t('Selected MOQ','MOQ e zgjedhur')}</dt><dd>{n(option?.constraints?.moq)}</dd></div><div><dt>{t('Order step','Hapi i porositjes')}</dt><dd>{n(option?.constraints?.step)}</dd></div></dl><ul>{[...new Set([...(e.unknowns||[]),...(option?.assumptions||[])])].map(a=><li key={a}>{label(a)}</li>)}</ul><p>{t('Changing stock, reservations, prices, supplier availability, receipt dates, policies or forecast health can change the recommendation.','Ndryshimi i stokut, rezervimeve, çmimeve, disponueshmërisë së furnitorit, datave të pranimit, politikave ose shëndetit të parashikimit mund të ndryshojë rekomandimin.')}</p></details>
   {e.finance&&<details><summary>{t('Financial context · advisory only','Konteksti financiar · vetëm këshillues')}</summary><dl className="decision-metrics">{[['recorded_cash','Recorded cash','Paraja e regjistruar'],['open_po_commitments','Open PO commitments','Angazhimet e hapura të blerjeve'],['po_outstanding','Outstanding PO obligations','Detyrimet e papaguara të blerjeve'],['unlinked_supplier_documents','Separate supplier documents','Dokumentet e veçanta të furnitorit']].map(([k,en,sq])=><div key={k}><dt>{t(en,sq)}</dt><dd>{money(e.finance[k],e.finance.base_currency)}</dd></div>)}</dl><p>{t('Source totals are separate to avoid double-counting. Cash completeness, credit availability and affordability are not inferred. No money is reserved or posted.','Totalet e burimeve mbahen veçmas për të shmangur numërimin e dyfishtë. Plotësia e parasë, kredia dhe aftësia paguese nuk supozohen. Nuk rezervohet apo postohet para.')}</p>{e.finance.upcoming_po_payments.map((p,i)=><p key={i}><Link to={p.url}>{p.reference}</Link> · {p.due_date} · {money(p.amount,e.finance.base_currency)}</p>)}</details>}
   {e.procurement&&<details><summary>{t('Incoming stock and existing requests','Furnizimet dhe kërkesat ekzistuese')}</summary>{e.procurement.orders.map(o=><p key={o.id}><Link to={`/purchase-orders?po=${o.id}`}>{o.reference}</Link> · {n(o.remaining_quantity)} {e.product.unit} · {o.expected_at||'—'} · {label(o.reason)}{o.at_risk?' · '+label('delay_attribution_uncertain'):''}</p>)}{e.procurement.requests.map(r=><p key={r.id}><Link to={`/procurement?request=${r.id}`}>{r.request_number}</Link> · {r.status}</p>)}{e.logistics?.map(s=><p key={s.id}><Link to={`/shipments/my-shipments?shipment=${s.id}`}>{s.reference||'#'+s.id}</Link> · {s.status} · ETA {s.eta||'—'} · {s.destination||'—'}{s.containers.map(c=><span key={c.id}> · {c.container_number}: {c.status}</span>)}</p>)}</details>}
   <details className="decision-simulation"><summary>{t('Compare your scenario · read-only','Krahaso skenarin tënd · vetëm lexim')}</summary><form onSubmit={x=>{x.preventDefault();act(async()=>{setComparison(await post(`/${id}/simulate`,{scenarios:[decisionScenario(scenario)]}))})}}><div className="intelligence-toolbar"><label>{t('Scenario type','Lloji i skenarit')}<select value={scenario.type} onChange={x=>{setScenario(v=>({...v,type:x.target.value}));setComparison(null)}}><option value="purchase">{t('Purchase','Blerje')}</option><option value="transfer">{t('Transfer','Transferim')}</option></select></label><label>{t('Quantity · inventory unit','Sasia · njësia e inventarit')}<input type="number" min="0" step="0.001" value={scenario.base_quantity} onChange={x=>setScenario(v=>({...v,base_quantity:x.target.value}))}/></label>{scenario.type==='purchase'?<label>{t('Supplier','Furnitori')}<select value={scenario.supplier_id} onChange={x=>setScenario(v=>({...v,supplier_id:x.target.value}))}><option value="">{t('Planning default','Zgjedhja e planifikimit')}</option>{e.supplier_options.map(s=><option key={s.supplier_id} value={s.supplier_id}>{s.name}</option>)}</select></label>:<label>{t('Source warehouse','Depoja burimore')}<select required value={scenario.source_warehouse_id} onChange={x=>setScenario(v=>({...v,source_warehouse_id:x.target.value}))}><option value="">{t('Choose','Zgjedh')}</option>{list?.warehouses.filter(w=>w.id!==detail.warehouse_id).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>}<label>{t('Expected delay days','Ditët e vonesës së pritshme')}<input type="number" min="0" max="180" value={scenario.delay_days} onChange={x=>setScenario(v=>({...v,delay_days:x.target.value}))}/></label>{scenario.type==='transfer'&&<label>{t('Assumed transit days','Ditët e supozuara të transitit')}<input type="number" min="0" max="180" value={scenario.transfer_days} onChange={x=>setScenario(v=>({...v,transfer_days:x.target.value}))}/></label>}<label>{t('Demand multiplier','Shumëzuesi i kërkesës')}<input type="number" min="0.1" max="5" step="0.1" value={scenario.demand_multiplier} onChange={x=>setScenario(v=>({...v,demand_multiplier:x.target.value}))}/></label></div><button disabled={busy}>{t('Compare scenario','Krahaso skenarin')}</button></form>{comparison&&<div className="decision-grid"><article><h4>{t('AIMS recommendation','Rekomandimi i AIMS')}</h4>{impact(comparison.recommended)}</article>{comparison.comparison.scenarios.map((s,i)=><article key={i}><h4>{t('Your scenario','Skenari yt')}</h4>{impact({base_cost:s.base_cost,impact:{stockout_before:s.stockout_date,stockout_after:s.scenario_stockout_date,days_of_supply:s.post_arrival_days_of_supply,arrival:s.expected_arrival,excess_quantity:s.excess_quantity}})}<p>{s.coverage_supported?t('Projected, not guaranteed','I parashikuar, jo i garantuar'):label('forecast_unavailable')}</p></article>)}</div>}</details>
   <h3>{t('Next actions · human controlled','Veprimet e ardhshme · të kontrolluara nga njeriu')}</h3><div className="decision-buttons">{permissions.includes('inventory.view')&&<Link to="/warehouse-operations">{t('Open Transfer Workflow','Hap rrjedhën e transferimit')}</Link>}{option?.supplier_id&&permissions.includes('suppliers.manage')&&<Link to={`/suppliers?supplier=${option.supplier_id}`}>{t('Review Supplier','Rishiko furnitorin')}</Link>}{canManage&&canFinance&&detail.can_act&&draftable(option)&&<button disabled={busy} onClick={()=>act(async()=>{setReview(await post(`/${id}/review`,{alternative_key:selected}));setConfirmTransfer(false)})}>{t('Review PR draft','Rishiko draftin e kërkesës')}</button>}</div>
   {review&&<section className="decision-review" role="region" aria-label={t('Purchase Request confirmation','Konfirmimi i kërkesës për blerje')}><h3>{t('Confirm a Purchase Request draft','Konfirmo draftin e kërkesës për blerje')}</h3><p>{review.product.name} · {review.alternative.supplier_name} · {n(review.alternative.quantity)} {review.alternative.unit}</p><p>{t('Unit price','Çmimi për njësi')}: {money(review.alternative.unit_price,review.alternative.currency)} · {t('Company-currency commitment','Angazhimi në monedhën e kompanisë')}: {money(review.alternative.base_cost,e.finance?.base_currency)}</p><p>{t('Expected arrival','Mbërritja e pritshme')}: {review.alternative.impact.arrival||'—'} · {label(review.confidence==='high'?'confidence_high':review.confidence)}</p>{review.existing_requests.length>0&&<p className="decision-warning">{t('An existing open PR prevents another draft. Review it first.','Një kërkesë ekzistuese e hapur pengon draftin tjetër. Rishikoje fillimisht.')}</p>}{review.confidence==='limited'&&<p className="decision-warning">{label('forecast_unavailable')}</p>}{review.requires_transfer_confirmation&&<label className="decision-option"><input type="checkbox" checked={confirmTransfer} onChange={x=>setConfirmTransfer(x.target.checked)}/>{t('I understand the transfer needs separate review and authorization; this draft does not move stock.','E kuptoj se transferimi kërkon rishikim dhe autorizim të veçantë; ky draft nuk lëviz stok.')}</label>}<p>{t('Only a draft will be created. Existing procurement and approval rules still apply.','Krijohet vetëm një draft. Rregullat ekzistuese të prokurimit dhe miratimit vazhdojnë të vlejnë.')}</p><div className="decision-buttons"><button disabled={busy||review.existing_requests.length>0||(review.requires_transfer_confirmation&&!confirmTransfer)} onClick={()=>act(async()=>{const r=await post(`/${id}/purchase-request`,{alternative_key:selected,review_token:review.review_token,confirm_transfer_assumption:confirmTransfer});setCreated(r.purchase_request);setReview(null);setMessage(t('PR draft created. Open it for review and approval.','Drafti i kërkesës u krijua. Hape për rishikim dhe miratim.'))},true)}>{busy?t('Processing…','Duke përpunuar…'):t('Confirm draft','Konfirmo draftin')}</button><button disabled={busy} onClick={()=>setReview(null)}>{t('Back to alternatives','Kthehu te alternativat')}</button></div></section>}
   {(created||detail.purchase_request)&&<p className="intelligence-message" role="status"><Link to={`/procurement?request=${(created||detail.purchase_request).id}`}>{t('Open Purchase Request','Hap kërkesën për blerje')} · {(created||detail.purchase_request).request_number} →</Link></p>}
   {canManage&&detail.can_act&&<div className="decision-feedback"><label>{t('Decision note','Shënim i vendimit')}<textarea maxLength={1000} value={note} onChange={x=>setNote(x.target.value)}/></label><label>{t('Optional actual dispatched transfer ID','ID opsionale e transferimit të dërguar')}<input type="number" min="1" value={transferId} onChange={x=>setTransferId(x.target.value)}/></label><div className="decision-buttons">{['reviewed','accepted','modified','dismissed'].map(s=><button key={s} disabled={busy} onClick={()=>record(s)}>{label(s)}</button>)}</div></div>}
   <details><summary>{t('Source references and intelligence versions','Referencat e burimeve dhe versionet e inteligjencës')}</summary><pre>{JSON.stringify({sources:e.sources,versions:e.versions},null,2)}</pre></details>
   <details><summary>{t('History and outcomes','Historiku dhe rezultatet')}</summary><ol className="decision-history">{detail.history.map((h,i)=><li key={i}>{label(h.action)} · {date(h.at)}{h.note&&<p>{h.note}</p>}{h.base_quantity!==undefined&&<span> · {n(h.base_quantity)} {e.product.unit}</span>}</li>)}</ol>{detail.outcome&&<><p>{label(detail.outcome.state)} · {t('Observational only; AIMS does not claim it caused the result.','Vetëm vëzhgim; AIMS nuk pretendon se e shkaktoi rezultatin.')}</p><dl className="decision-metrics"><div><dt>{t('Actual quantity ordered','Sasia e porositur realisht')}</dt><dd>{n(detail.outcome.actual_ordered_quantity)}</dd></div><div><dt>{t('Received quantity','Sasia e pranuar')}</dt><dd>{n(detail.outcome.received_quantity)}</dd></div><div><dt>{t('Receipt dates','Datat e pranimit')}</dt><dd>{detail.outcome.actual_receipt_dates.join(', ')||'—'}</dd></div><div><dt>{t('Stockout observed','Mungesë e vëzhguar')}</dt><dd>{detail.outcome.stockout_occurred===null?'—':detail.outcome.stockout_occurred?t('Yes','Po'):t('No','Jo')}</dd></div><div><dt>{t('Quality issue observed','Problem cilësie i vëzhguar')}</dt><dd>{detail.outcome.quality_issue_occurred===null?'—':detail.outcome.quality_issue_occurred?t('Yes','Po'):t('No','Jo')}</dd></div></dl></>}</details>
  </section>}
 </main>
}
