import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { assistantFeedback, confirmAssistantDraft } from '../api/assistant'
import { safeRecordPath } from './assistantPresentation'
import { canOpenPage } from '../config/pageAccess'
import { useAuthStore } from '../store/authStore'
import { decisionLabel } from './decisionPresentation'
import { optimizerLabel } from '../pages/supplyOptimizerPresentation'
import { simulationLabel } from '../pages/strategicSimulationPresentation'

export const evidenceValue = value => value == null || value === '' ? '—' : typeof value === 'boolean' ? (value ? '✓' : '—') : String(value)
const labels = {
  create_simulation_scenario:['Strategic scenario','Skenari strategjik'],run_strategic_simulation:['Strategic simulation','Simulimi strategjik'],get_simulation_result:['Simulation result','Rezultati i simulimit'],compare_simulations:['Scenario comparison','Krahasimi i skenarëve'],get_simulation_impact:['Scenario impact','Ndikimi i skenarit'],run_sensitivity_analysis:['Sensitivity comparison','Krahasimi i ndjeshmërisë'],get_simulation_bottlenecks:['Scenario constraints','Kufizimet e skenarit'],optimize_simulation_response:['Simulated supply response','Përgjigjja e simuluar e furnizimit'],explain_simulation_result:['Scenario explanation','Shpjegimi i skenarit'],
  get_supply_optimization_summary:['Supply plans','Planet e furnizimit'],get_optimization_plan:['Supply plan evidence','Dëshmitë e planit të furnizimit'],compare_optimization_plans:['Supply plan comparison','Krahasimi i planeve të furnizimit'],optimize_supply_plan:['Local supply optimization','Optimizimi lokal i furnizimit'],simulate_commitment_limit:['Purchasing limit scenario','Skenari i kufirit të blerjeve'],explain_optimization_decision:['Supply quantity trade-offs','Kompromiset e sasive të furnizimit'],stress_test_supply_plan:['Supply plan stress test','Testi i stresit të planit të furnizimit'],get_stale_optimization_plans:['Stale supply plans','Planet e vjetruara të furnizimit'],
  get_decision_learning_summary:['Decision learning evidence','Dëshmitë e mësimit të vendimeve'],get_recommendation_performance:['Observed recommendation outcomes','Rezultatet e vëzhguara të rekomandimeve'],get_decision_outcome:['Decision outcome','Rezultati i vendimit'],compare_policy_versions:['Estimated policy comparison','Krahasimi i vlerësuar i politikave'],get_challenger_status:['Experimental challenger status','Gjendja e kandidatit eksperimental'],get_override_patterns:['Observed human choices','Zgjedhjet e vëzhguara të përdoruesve'],get_policy_suggestions:['Suggested policy review','Rishikimi i sugjeruar i politikës'],
  simulate_customer_payment_delay:['Customer payment scenario','Skenari i pagesës së klientit'],simulate_shipment_delay:['Shipment delay scenario','Skenari i vonesës së dërgesës'],get_customer_supply_capacity:['Customer supply capacity','Kapaciteti i furnizimit të klientit'],
  get_open_decisions:['Priority decisions','Vendimet prioritare'],get_critical_decisions:['Critical decisions','Vendimet kritike'],get_replenishment_decisions:['Purchase decisions','Vendimet e blerjes'],get_supplier_decisions:['Supplier decisions','Vendimet e furnitorëve'],get_decision:['Decision evidence','Dëshmitë e vendimit'],get_decision_changes:['Recorded changes','Ndryshimet e regjistruara'],get_products_needing_replenishment:['What to buy','Çfarë të blej'],get_inventory_intelligence_recommendations:['Stockout risks','Rreziqet e mungesës'],get_at_risk_shipments:['Shipment risks','Rreziqet e dërgesave'],get_shipment_intelligence:['Shipment evidence','Dëshmitë e dërgesës'],get_cash_forecast:['Cash forecast','Parashikimi i parasë'],get_receivable_intelligence:['Receivables','Të arkëtueshmet'],get_financial_pressure_periods:['Cash pressure dates','Datat e presionit financiar'],get_at_risk_customers:['Inactive / at-risk customers','Klientët joaktivë / në rrezik'],get_sales_opportunities:['Sales opportunities','Mundësitë e shitjeve'],get_customer_intelligence:['Customer evidence','Dëshmitë e klientit'],get_pending_approvals:['Waiting approvals','Miratimet në pritje'],get_sales_analytics:['Recorded sales','Shitjet e regjistruara'],get_product_availability:['Product availability','Disponueshmëria e produktit'],get_stock_movements:['Stock movements','Lëvizjet e stokut'],get_demand_forecast:['Demand forecast','Parashikimi i kërkesës'],get_inventory_plan:['Inventory plan','Plani i inventarit'],get_supplier_options:['Supplier alternatives','Alternativat e furnitorëve'],simulate_inventory_scenario:['Inventory scenario','Skenari i inventarit'],simulate_decision_change:['Decision scenario','Skenari i vendimit'],simulate_purchase_cash_impact:['Cash scenario','Skenari financiar'],compare_decision_alternatives:['Alternative comparison','Krahasimi i alternativave'],get_customer:['Customer credit','Kredia e klientit'],get_supplier:['Supplier','Furnitori'],get_supplier_performance:['Supplier performance','Performanca e furnitorit'],get_task:['Task evidence','Dëshmitë e detyrës'],get_product_incoming_risk:['Incoming shipment risk','Rreziku i furnizimit në ardhje'],
}
export const toolLabel = (tool,sq=false) => labels[tool]?.[sq?1:0] || (sq?'Dëshmi burimore':'Source evidence')
function EvidenceTree({value}) {
  if(value==null||typeof value!=='object')return <span>{evidenceValue(value)}</span>
  return <dl className="assistant-evidence-tree">{Object.entries(value).map(([key,item])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{item!=null&&typeof item==='object'?<details><summary>…</summary><EvidenceTree value={item}/></details>:evidenceValue(item)}</dd></div>)}</dl>
}
export default function IntelligenceReply({reply,language,onSelect,busy}) {
  const sq=language==='sq',t=(en,al)=>sq?al:en,permissions=useAuthStore(s=>s.permissions)
  const [feedback,setFeedback]=useState(null),[feedbackBusy,setFeedbackBusy]=useState(false),[reason,setReason]=useState(''),[confirming,setConfirming]=useState(false),[transfer,setTransfer]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(null),latch=useRef(false)
  const safe=path=>safeRecordPath(path)&&canOpenPage(path,permissions)
  async function vote(helpful){if(feedbackBusy)return;setFeedbackBusy(true);try{await assistantFeedback({response_id:reply.id,helpful,reason:helpful?null:reason||null});setFeedback(helpful)}catch(e){setError(e.message)}finally{setFeedbackBusy(false)}}
  async function confirm(){if(latch.current||created)return;latch.current=true;setConfirming(true);setError('');try{setCreated(await confirmAssistantDraft({token:reply.action.token,confirm:true,confirm_transfer_assumption:transfer}))}catch(e){setError(e.message)}finally{latch.current=false;setConfirming(false)}}
  const review=reply.action?.review,o=review?.alternative
  return <>
    {['unavailable','invalid_response','invalid_local_configuration'].includes(reply.provider)&&<small className="assistant-source">{t('Local language support unavailable · deterministic evidence remains available.','Gjuha lokale nuk është e disponueshme · dëshmitë deterministe mbeten të disponueshme.')}</small>}
    {reply.scenario&&<strong className="assistant-scenario-label">{t('Hypothetical scenario · no records changed','Skenar hipotetik · asnjë regjistrim nuk ndryshoi')}</strong>}<p>{reply.text}</p>
    {reply.choices?.length>0&&<div className="assistant-choices">{reply.choices.map(c=><button key={`${c.type}-${c.id}`} disabled={busy} onClick={()=>onSelect({type:c.type,id:c.id})}><strong>{c.title}</strong></button>)}</div>}
    {reply.context&&<small>{t('Conversation context','Konteksti i bisedës')}: {reply.context.type} #{reply.context.id}</small>}
    <div className="assistant-evidence-cards">{reply.cards?.map((card,i)=><section className="assistant-evidence-card" key={`${card.tool}-${i}`}>
      <small>{toolLabel(card.tool,sq)}</small><h4>{card.title===card.tool?toolLabel(card.tool,sq):card.title}</h4>{card.status&&<span className="assistant-status">{(card.url?.startsWith('/strategic-simulation')?simulationLabel(String(card.status),language):card.url?.startsWith('/supply-optimizer')?optimizerLabel(String(card.status),language):decisionLabel(String(card.status),language)).replaceAll('_',' ')}</span>}{card.confidence&&<small> · {t('Confidence','Besueshmëria')}: {decisionLabel(evidenceValue(card.confidence),language)}</small>}
      {card.evidence?.reason&&card.url?.startsWith('/supply-optimizer')&&<p>{optimizerLabel(card.evidence.reason,language)}</p>}
      {card.evidence?.reasoning?.why&&<p>{decisionLabel(card.evidence.reasoning.why,language)}</p>}
      {card.evidence?.recommended?.action&&<p><strong>{t('Recommended action','Veprimi i rekomanduar')}:</strong> {decisionLabel(card.evidence.recommended.action,language)}</p>}
      {card.stale&&<p className="assistant-stale">{t('Stale or changed evidence — review the source before acting.','Dëshmi të vjetruara ose të ndryshuara — rishiko burimin para veprimit.')}</p>}
      {card.metrics?.length>0&&<dl className="assistant-facts">{card.metrics.map((m,j)=><div key={j}><dt>{m.label}</dt><dd>{evidenceValue(m.value)} {m.value!=null?m.unit:''}</dd></div>)}</dl>}
      <div className="assistant-links">{safe(card.url)&&<Link to={card.url}>{t('Open source','Hap burimin')} ↗</Link>}{card.entity&&<button disabled={busy} onClick={()=>onSelect(card.entity,'Explain this record')}>{t('Explain why','Shpjego pse')}</button>}{card.tool==='get_product_availability'&&reply.context?.type==='product'&&<button disabled={busy} onClick={()=>onSelect(reply.context,'Show recent stock movements')}>{t('Recent movements','Lëvizjet e fundit')}</button>}</div><details><summary>{t('Evidence, assumptions & alternatives','Dëshmi, supozime dhe alternativa')}</summary><EvidenceTree value={card.evidence}/></details>
    </section>)}</div>
    {reply.action&&<section className="assistant-action-review" aria-label={t('Review Purchase Request draft','Rishiko draftin e kërkesës për blerje')}>
      <h4>{t('Review Purchase Request draft','Rishiko draftin e kërkesës për blerje')}</h4><strong>{review.product?.name}</strong><dl className="assistant-facts">{[[t('Supplier','Furnitori'),o.supplier_name],[t('Quantity','Sasia'),`${o.quantity} ${o.unit}`],[t('Unit price','Çmimi për njësi'),`${evidenceValue(o.unit_price)} ${o.currency||''}`],[t('Estimated total','Totali i vlerësuar'),`${evidenceValue(o.base_cost)} ${o.currency||''}`],[t('Confidence','Besueshmëria'),review.confidence]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>
      <p>{t('Draft only. Existing submission and approval rules remain in force. Nothing is ordered, paid or moved.','Vetëm draft. Rregullat ekzistuese të dorëzimit dhe miratimit mbeten në fuqi. Asgjë nuk porositet, paguhet ose lëvizet.')}</p>{review.requires_transfer_confirmation&&<label className="assistant-check"><input type="checkbox" checked={transfer} onChange={e=>setTransfer(e.target.checked)}/>{t('A separate transfer needs its own review and authorization.','Transferimi i veçantë kërkon rishikim dhe autorizim të vet.')}</label>}
      {!created?<button type="button" disabled={confirming||review.requires_transfer_confirmation&&!transfer} onClick={confirm}>{confirming?t('Creating draft…','Duke krijuar draftin…'):t('Confirm — create Purchase Request draft','Konfirmo — krijo draftin e kërkesës')}</button>:<p role="status">{t('Draft created','Drafti u krijua')}: {created.purchase_request.request_number} · {safe(created.url)&&<Link to={created.url}>{t('Open Purchase Request','Hap kërkesën për blerje')} ↗</Link>}</p>}
    </section>}
    {reply.limitations?.length>0&&<details className="assistant-limitations" open={reply.state!=='success'}><summary>{t('Limitations & missing data','Kufizimet dhe të dhënat që mungojnë')}</summary><ul>{reply.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul></details>}
    {reply.sources?.length>0&&<details><summary>{t('Sources & freshness','Burimet dhe freskia')}</summary>{reply.sources.map((s,i)=><div className="assistant-source" key={i}>{safe(s.url)&&<Link to={s.url}>{toolLabel(s.tool,sq)}</Link>} · {t('Evidence cutoff','Kufiri i dëshmive')}: {s.as_of||t('Not supplied by source','Nuk jepet nga burimi')} · {t('Read','Lexuar')}: {s.read_at}</div>)}</details>}
    <div className="assistant-feedback">{feedback===null?<><button disabled={feedbackBusy} onClick={()=>vote(true)}>{t('Helpful','E dobishme')}</button><select aria-label={t('Feedback reason','Arsyeja e vlerësimit')} value={reason} onChange={e=>setReason(e.target.value)}><option value="">{t('Feedback reason (optional)','Arsyeja (opsionale)')}</option>{[['incorrect','Incorrect','E pasaktë'],['unclear','Unclear','E paqartë'],['missing_data','Missing data','Mungojnë të dhëna'],['not_useful','Not useful','Jo e dobishme']].map(([v,en,al])=><option key={v} value={v}>{t(en,al)}</option>)}</select><button disabled={feedbackBusy} onClick={()=>vote(false)}>{t('Not helpful','Jo e dobishme')}</button></>:<small>{t('Feedback recorded','Vlerësimi u regjistrua')}</small>}</div>{error&&<p role="alert">{error}</p>}
  </>
}
