import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import IntelligenceGovernance from './IntelligenceGovernance'

export default function IntelligencePerformance({product,horizon,revision,onChange}){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,permissions=useAuthStore(s=>s.permissions)
 const canManage=permissions.includes('analytics.ml_datasets')&&permissions.includes('analytics.finance')
 const [data,setData]=useState(null),[version,setVersion]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[days,setDays]=useState('30'),[selectedWindow,setSelectedWindow]=useState('')
 const lock=useRef(false)
 const n=v=>v==null?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:2}).format(v)
 const pct=v=>v==null?'—':n(v)+'%'
 const labels={not_enough_observations:t('More observed days are required.','Nevojiten më shumë ditë të vëzhguara.'),low_history_coverage:t('Too many recent days are missing or censored.','Mungojnë ose janë të paplota shumë ditë të fundit.'),not_enough_validation_windows:t('Not enough complete validation periods.','Nuk ka mjaft periudha të plota validimi.'),worse_than_baseline:t('The simple baseline performs better.','Modeli i thjeshtë bazë jep rezultat më të mirë.'),production_changed:t('Production changed; prepare a new comparison.','Modeli aktiv ndryshoi; përgatit krahasim të ri.'),production_not_beaten:t('No comparable evidence of equal or better performance than production.','Nuk ka prova të krahasueshme për rezultat të barabartë ose më të mirë se modeli aktiv.'),unit_changed:t('Inventory unit changed.','Njësia e inventarit ndryshoi.')}
 useEffect(()=>{setVersion('');setReview(null);setData(null);setSelectedWindow('');setError('')},[product,horizon])
 labels.insufficient_improvement=t('The challenger does not meet the configured minimum improvement over the champion.','Kandidati nuk arrin përmirësimin minimal të konfiguruar ndaj modelit aktiv.')
 useEffect(()=>{let live=true;apiRequest(`/analytics/intelligence/products/${product}/performance?${new URLSearchParams({horizon,...(version?{model_version:version}:{})})}`).then(r=>{if(live){setData(r);setError('')}}).catch(e=>live&&setError(e.message));return()=>{live=false}},[product,horizon,revision,version])
 async function act(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fn();setReview(null);onChange();if(r.warning)setError(r.warning)}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 function begin(model,action){setReview({model,action});setReason('');setConfirmed(false)}
 function collectHistory(){
  const end=new Date();end.setDate(end.getDate()-1)
  const start=new Date();start.setDate(start.getDate()-Number(days))
  const fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
  return act(()=>apiRequest(`/analytics/intelligence/products/${product}/observations`,{method:'POST',body:JSON.stringify({from:fmt(start),to:fmt(end)})}))
 }
 if(!data)return <p role="status">{error||t('Loading measured performance…','Duke ngarkuar performancën e matur…')}</p>
 const candidates=data.models.filter(m=>m.status==='candidate'),production=data.models.find(m=>m.version===data.production_version)
 const chosen=data.evaluations.find(e=>String(e.id)===selectedWindow)
 const chart=chosen?.actual?.days?.map(d=>({date:d.date,actual:d.actual,predicted:d.predicted,baseline:d.baseline}))||data.evaluations.filter(e=>e.evaluation?.version===2&&e.evaluation?.eligible).slice().reverse().map(e=>({date:e.evaluation.to,actual:e.evaluation.actual_total,predicted:e.evaluation.predicted_total}))
 return <details className="intelligence-performance"><summary>{t('Forecast setup & accuracy','Konfigurimi dhe saktësia e parashikimit')}</summary>
  <p>{t('Optional advanced controls. Prepare a candidate using Update forecast, review its evidence, then explicitly approve activation. Everyday stock decisions stay above. MAE is the average quantity error; WAPE is the total error relative to actual sales; bias shows over- or under-estimation.','Kontrolle të avancuara opsionale. Përgatit kandidatin me Përditëso parashikimin, rishiko provat dhe mirato aktivizimin. Vendimet ditore të stokut janë më sipër. MAE është gabimi mesatar në sasi; WAPE është gabimi krahasuar me shitjet; devijimi tregon mbivlerësim ose nënvlerësim.')}</p>
  <p>{t('Accuracy measures completed forecasts against recorded sales—not synthetic tests or promises of future accuracy. Stock availability is sampled; lost demand is not estimated.','Saktësia krahason parashikimet e përfunduara me shitjet e regjistruara—jo me teste sintetike ose premtime për të ardhmen. Disponueshmëria e stokut matet me mostra; kërkesa e humbur nuk vlerësohet.')}</p>
  {error&&<p role="alert" className="intelligence-error">{error}</p>}
  <IntelligenceGovernance data={data}/>
  <div className="intelligence-metrics">{[[t('Completed periods','Periudha të përfunduara'),n(data.summary.completed_windows)],['MAE',n(data.summary.mae)],['WAPE',pct(data.summary.wape)],[t('Forecast bias','Devijimi i parashikimit'),n(data.summary.bias)],[t('Usable / captured days','Ditë të përdorshme / regjistruara'),`${data.coverage.usable_days} / ${data.coverage.captured_days}`],[t('Stockout days','Ditë pa stok'),n(data.coverage.stockout_days)]].map(([key,value])=><article key={key}><span>{key}</span><strong>{value}</strong></article>)}</div>
  {data.summary.status==='insufficient_real_data'&&<p role="status">{t('Insufficient real data. Accuracy appears only after complete forecast periods have usable observations.','Të dhëna reale të pamjaftueshme. Saktësia shfaqet vetëm pas përfundimit të periudhave me vëzhgime të përdorshme.')}</p>}
  <div className="intelligence-toolbar"><label>{t('Model version','Versioni i modelit')}<select value={version} onChange={e=>setVersion(e.target.value)}><option value="">{t('All versions — current inventory unit','Të gjitha versionet — njësia aktuale')}</option>{data.models.map(m=><option key={m.id} value={m.version}>{m.algorithm} · {m.version.slice(0,8)} · {m.inventory_unit}</option>)}</select></label><label>{t('Forecast window','Periudha e parashikimit')}<select value={selectedWindow} onChange={e=>setSelectedWindow(e.target.value)}><option value="">{t('Completed-period trend','Prirja e periudhave të përfunduara')}</option>{data.evaluations.filter(e=>e.evaluation?.version===2).map(e=><option key={e.id} value={e.id}>{e.evaluation.from} – {e.evaluation.to}</option>)}</select></label></div>
  {chart.length>0&&<div className="intelligence-chart"><ResponsiveContainer width="100%" height={250}><LineChart data={chart}><CartesianGrid stroke="var(--border-color)" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={40} stroke="var(--text-muted)"/><YAxis stroke="var(--text-muted)"/><Tooltip contentStyle={{background:'var(--card-bg)',color:'var(--text-color)',border:'1px solid var(--border-color)'}}/><Line dataKey="actual" name={t('Actual sales','Shitjet reale')} stroke="#16a085" dot={false} isAnimationActive={false}/><Line dataKey="predicted" name={t('Forecast','Parashikimi')} stroke="#469ff5" dot={false} isAnimationActive={false}/><Line dataKey="baseline" name={t('Simple baseline','Modeli i thjeshtë bazë')} stroke="#d49d45" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}
  <div className="intelligence-table"><table><thead><tr>{[t('Period / version','Periudha / versioni'),t('Actual / forecast','Real / parashikim'),'MAE','WAPE',t('Baseline MAE','MAE bazë'),t('Data quality','Cilësia e të dhënave')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.evaluations.map(e=><tr key={e.id}><td>{e.evaluation.from||'—'} – {e.evaluation.to||'—'}<small>{e.model_version.slice(0,8)}</small></td><td>{n(e.evaluation.actual_total)} / {n(e.evaluation.predicted_total)}</td><td>{n(e.evaluation.mae)}</td><td>{pct(e.evaluation.wape)}</td><td>{n(e.evaluation.baseline_mae)}</td><td>{e.evaluation.version!==2?t('Legacy evaluation','Vlerësim i mëparshëm'):e.evaluation.eligible?t('Complete · sampled availability','E plotë · stok i matur me mostra'):t('Incomplete · excluded from accuracy','Jo e plotë · përjashtohet nga saktësia')}<small>{n(e.evaluation.excluded_days)} {t('excluded days','ditë të përjashtuara')}</small></td></tr>)}</tbody></table></div>
  {data.alerts.length>0&&<section aria-label={t('Measured warnings','Paralajmërime të matura')}><h3>{t('Recommended review','Rishikimi i rekomanduar')}</h3>{data.alerts.map(a=><article className="intelligence-error" key={a.id}><strong>{({data_quality:t('Missing or stockout-censored observations','Vëzhgime që mungojnë ose me mungesë stoku'),accuracy_degraded:t('Sustained accuracy deterioration','Përkeqësim i vazhdueshëm i saktësisë'),persistent_bias:t('Persistent over/underforecasting','Mbivlerësim/nënvlerësim i vazhdueshëm'),demand_shift:t('Demand changed over two weeks','Kërkesa ndryshoi gjatë dy javëve')})[a.code]}</strong><p>{a.code==='data_quality'?`${a.evidence.unusable_days} / ${a.evidence.period_days} ${t('unusable days; threshold','ditë të papërdorshme; pragu')}: ${a.evidence.threshold_days}`:a.code==='demand_shift'?`${pct(a.evidence.first_week_change_percent)} / ${pct(a.evidence.second_week_change_percent)} · ${t('weekly changes; threshold','ndryshime javore; pragu')} ${a.evidence.threshold_percent}%`:`${a.evidence.windows} ${t('independent completed periods','periudha të pavarura të përfunduara')} · WAPE ${pct(a.evidence.wape)} · ${t('bias','devijim')} ${pct(a.evidence.signed_bias_percent)}`}</p></article>)}</section>}
  <h3>{t('Production and candidate review','Modeli aktiv dhe rishikimi i kandidatëve')}</h3><p>{production?`${t('Active model','Modeli aktiv')}: ${production.algorithm} · ${production.version.slice(0,8)}`:t('No production model approved yet. Review an eligible candidate to activate forecasting.','Ende nuk është miratuar model aktiv. Rishiko një kandidat të përshtatshëm për të aktivizuar parashikimin.')}</p>
  <p>{t('Candidate scores below are time-ordered historical validation, not completed production accuracy. Promotion is always a human decision.','Rezultatet e kandidatëve më poshtë janë validim historik sipas kohës, jo saktësi reale pas përdorimit. Aktivizimi është gjithmonë vendim i përdoruesit.')}</p>
  {candidates.map(m=><article className="intelligence-candidate" key={m.id}><h4>{m.algorithm==='ridge'?t('Learned model','Model i mësuar'):t('Simple seasonal model','Model i thjeshtë sezonal')} · {m.version.slice(0,8)}</h4><p>{t('Training through','Trajnuar deri më')} {m.training_cutoff.slice(0,10)} · {t('Recent coverage','Mbulimi i fundit')}: {pct(m.gate.recent_coverage)}</p><div className="intelligence-table"><table><thead><tr><th>{t('Comparison on matching periods','Krahasimi në periudha të njëjta')}</th><th>MAE</th><th>WAPE</th><th>{t('Periods','Periudhat')}</th></tr></thead><tbody>{[[t('Candidate','Kandidati'),m.metrics],[t('Production','Modeli aktiv'),m.comparison.incumbent],[t('Baseline','Modeli bazë'),m.comparison.seasonal_mean]].map(([name,metric])=><tr key={name}><td>{name}</td><td>{n(metric?.mae)}</td><td>{pct(metric?.wape)}</td><td>{n(metric?.blocks)}</td></tr>)}</tbody></table></div>{m.gate.reasons.map(code=><p key={code}>{labels[code]||code}</p>)}<button disabled={!canManage||busy||!m.gate.eligible} onClick={()=>begin(m,'promote')}>{t('Review promotion','Rishiko aktivizimin')}</button></article>)}
  {!candidates.length&&<p>{t('No pending candidate. Use Update forecasts / prepare review above.','Nuk ka kandidat në pritje. Përdor Përditëso parashikimet / përgatit rishikimin më sipër.')}</p>}
  {data.rollback_target&&<button disabled={!canManage||busy} onClick={()=>begin(data.rollback_target,'rollback')}>{t('Review rollback to previous model','Rishiko kthimin te modeli i mëparshëm')} · {data.rollback_target.version.slice(0,8)}</button>}
  {review&&<form className="intelligence-review" onSubmit={e=>{e.preventDefault();if(!confirmed)return;act(()=>apiRequest(`/analytics/intelligence/models/${review.model.id}/${review.action}`,{method:'POST',body:JSON.stringify({reason,expected_production_version:data.production_version})}))}}><h4>{review.action==='promote'?t('Confirm production model change','Konfirmo ndryshimin e modelit aktiv'):t('Confirm rollback','Konfirmo kthimin')}</h4><p>{t('Future forecasts will use this version. Historical forecasts remain unchanged. No purchase is created.','Parashikimet e ardhshme do të përdorin këtë version. Historiku nuk ndryshon. Nuk krijohet asnjë blerje.')} {review.model.version}</p><label>{t('Review reason','Arsyeja e rishikimit')}<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="intelligence-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{t('I reviewed the measured evidence and limitations.','I rishikova provat e matura dhe kufizimet.')}</span></label><button disabled={busy||!confirmed||reason.trim().length<3}>{t('Confirm','Konfirmo')}</button><button type="button" disabled={busy} onClick={()=>setReview(null)}>{t('Cancel','Anulo')}</button></form>}
  <details><summary>{t('Observation collection and retraining','Mbledhja e vëzhgimeve dhe ritrajnimi')}</summary><p>{t('Daily collection and finished-period evaluation run automatically while the server/app is running. Missing historical stock is never invented. Retraining prepares candidates only.','Mbledhja ditore dhe vlerësimi i periudhave të përfunduara bëhen automatikisht kur serveri/aplikacioni punon. Stoku historik që mungon nuk shpiket. Ritrajnimi vetëm përgatit kandidatë.')}</p><p>{t('New usable days','Ditë të reja të përdorshme')}: {data.retraining.new_observed_days} · {t('Automatic candidates','Kandidatë automatikë')}: {data.retraining.automatic_enabled?t('Enabled','Aktiv'):t('Disabled','Jo aktiv')} · {data.retraining.justified?t('Retraining is justified.','Ritrajnimi është i arsyeshëm.'):t('No justified retraining yet.','Ende nuk arsyetohet ritrajnimi.')}</p><div className="intelligence-toolbar"><label>{t('Completed days to collect','Ditë të përfunduara për regjistrim')}<select value={days} onChange={e=>setDays(e.target.value)}>{[14,30,90].map(d=><option key={d}>{d}</option>)}</select></label><button disabled={!canManage||busy} onClick={collectHistory}>{t('Collect available history','Regjistro historikun e disponueshëm')}</button></div></details>
  <details><summary>{t('Recommendation outcomes and decisions','Rezultatet e rekomandimeve dhe vendimet')}</summary><p>{t('Stock changes are observations, not proof of improvement caused by a recommendation. Supplier delays and other business activity are separate influences.','Ndryshimet e stokut janë vëzhgime, jo provë përmirësimi të shkaktuar nga rekomandimi. Vonesat e furnitorëve dhe aktivitetet e tjera ndikojnë veçmas.')}</p>{data.outcomes.map(r=><article key={r.id}><strong>#{r.id} · {({accepted:t('Accepted','Pranuar'),adjusted:t('Adjusted','Përshtatur'),dismissed:t('Dismissed','Mbyllur')})[r.outcome.decision]}</strong><p>{t('Available before / after','Në dispozicion para / pas')}: {n(r.outcome.before_available)} / {n(r.outcome.after_available)} · {t('Supplier delays','Vonesa furnitorësh')}: {r.outcome.supplier_delays}</p>{r.outcome.purchase_request_id&&<Link to={`/procurement?request=${r.outcome.purchase_request_id}`}>PR #{r.outcome.purchase_request_id}</Link>}{r.outcome.purchase_orders.map(po=><p key={po.id}><Link to={`/purchase-orders?po=${po.id}`}>{po.reference}</Link> · {po.status} · {po.expected_at||'—'}</p>)}</article>)}{data.decisions.map(d=><p key={d.id}>{d.created_at.slice(0,10)} · {d.action==='promote'?t('Promoted','Aktivizuar'):t('Rolled back','Kthyer')} · {d.reason}</p>)}</details>
 </details>
}
