import {useEffect,useRef,useState} from 'react'
import WorkflowGuide from './WorkflowGuide'
import {Link,useSearchParams} from 'react-router-dom'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import {planningLabels,scenarioPayload,purchasableItems} from './planningPresentation'
import './InventoryPlanning.css'

const root='/analytics/planning'
const blank=()=>({type:'purchase',order_date:'',supplier_id:'',base_quantity:'',delay_days:'0',demand_multiplier:'1',service_level:'0.95',budget:'',source_warehouse_id:'',transfer_days:''})
export default function InventoryPlanning(){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en
 const permissions=useAuthStore(s=>s.permissions),canManage=permissions.includes('procurement.manage'),canFinance=permissions.includes('analytics.finance')
 const [params,setParams]=useSearchParams(),product=params.get('product'),warehouse=params.get('warehouse_id')||''
 const [list,setList]=useState(null),[detail,setDetail]=useState(null),[q,setQ]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[supplier,setSupplier]=useState(''),[unit,setUnit]=useState('')
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[policy,setPolicy]=useState(null),[scenarios,setScenarios]=useState([blank(),blank()]),[results,setResults]=useState(null)
 const [selected,setSelected]=useState([]),[budget,setBudget]=useState(''),[review,setReview]=useState(null),[created,setCreated]=useState([]),pending=useRef(false),detailKey=useRef('')
 const [view,setView]=useState('all'),[decision,setDecision]=useState({action:'accepted',note:'',base_quantity:'',supplier_id:'',until:'',transfer_id:''})
 const n=v=>v===null||v===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(Number(v))
 const label=x=>planningLabels[x]?.[language==='sq'?1:0]||x
 const scope=scenarioPayload({warehouse_id:warehouse,supplier_id:supplier,unit})
 useEffect(()=>{let live=true;const timer=setTimeout(()=>apiRequest(root+'?'+new URLSearchParams({q,page,warehouse_id:warehouse,view})).then(r=>live&&setList(r)).catch(e=>live&&setError(e.message)),180);return()=>{live=false;clearTimeout(timer)}},[q,page,warehouse,view,revision])
 useEffect(()=>{if(!product){setDetail(null);return}let live=true;const key=[product,warehouse,supplier,unit].join(':');if(detailKey.current!==key){setDetail(null);setResults(null);detailKey.current=key}apiRequest(`${root}/products/${product}?${new URLSearchParams(scope)}`).then(r=>{if(live){setDetail(r);setPolicy(r.plan.policy)}}).catch(e=>live&&setError(e.message));return()=>{live=false}},[product,warehouse,supplier,unit,revision])
 function choose(id){setError('');setResults(null);setSupplier('');setUnit('');setDecision({action:'accepted',note:'',base_quantity:'',supplier_id:'',until:'',transfer_id:''});setParams(p=>{p.set('product',id);p.delete('recommendation');return p})}
 function changeScope(id){setSelected([]);setReview(null);setResults(null);setParams(p=>{id?p.set('warehouse_id',id):p.delete('warehouse_id');return p})}
 async function act(fn,reload=false){if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await fn();if(reload)setRevision(v=>v+1)}catch(e){setError(e.errors?Object.values(e.errors).flat().join(' '):e.message)}finally{pending.current=false;setBusy(false)}}
 const post=(path,body)=>apiRequest(root+path,{method:'POST',body:JSON.stringify(body)})
 async function save(){await act(async()=>{const r=await post(`/products/${product}/save`,scope);setMessage(t('Plan saved for review.','Plani u ruajt për rishikim.'));if(['open','viewed'].includes(r.status))setSelected(v=>[...v.filter(id=>id!==r.recommendation_id),r.recommendation_id]);setReview(null)},true)}
 function setScenario(index,key,value){setScenarios(v=>v.map((s,i)=>i===index?{...s,[key]:value}:s));setResults(null)}
 const plan=detail?.plan,items=purchasableItems(review),allItems=review?.groups.flatMap(g=>g.items)||[]
 function timeline(r){return <div className="intelligence-chart"><ResponsiveContainer><LineChart data={r.timeline}><CartesianGrid stroke="var(--border-color)" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={50} tick={{fill:'var(--text-muted)',fontSize:11}}/><YAxis tick={{fill:'var(--text-muted)',fontSize:11}}/><Tooltip contentStyle={{background:'var(--card-bg)',color:'var(--text-color)',borderColor:'var(--border-color)'}}/><Line isAnimationActive={false} type="monotone" dataKey="baseline" name={t('Existing stock plan','Plani i stokut ekzistues')} stroke="#f0a04b" dot={false}/><Line isAnimationActive={false} type="monotone" dataKey="with_order" name={t('With proposed arrival','Me mbërritjen e propozuar')} stroke="#32a7dd" dot={false}/></LineChart></ResponsiveContainer></div>}
 return <main className="intelligence-page planning-workspace">
  <header><div><p className="eyebrow">{t('STOCK & PURCHASING','STOKU DHE BLERJET')}</p><h1>{t('Inventory Planning','Planifikimi i inventarit')}</h1><p>{t('Stock targets, purchasing scenarios and reviewed PR drafts. No automatic spending.','Objektiva stoku, skenarë blerjesh dhe kërkesa të rishikuara. Pa shpenzime automatike.')}</p></div><Link to="/procurement">{t('Procurement & approvals','Prokurimi dhe miratimet')} →</Link></header>
  <WorkflowGuide workflow="planning"/>
  <div className="intelligence-toolbar"><label>{t('Search products','Kërko produktet')}<input type="search" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><label>{t('Planning scope','Fusha e planifikimit')}<select disabled={busy} value={warehouse} onChange={e=>changeScope(e.target.value)}><option value="">{t('All warehouses / company','Të gjitha depot / kompania')}</option>{list?.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button disabled={busy} onClick={()=>{setReview(null);setRevision(v=>v+1)}}>{t('Refresh evidence','Përditëso provat')}</button></div>
  <nav className="planning-views" aria-label={t('Optimization views','Pamjet e optimizimit')}>{[['all',t('All products','Të gjitha produktet')],['attention',t('Needs attention','Kërkojnë vëmendje')],['replenishment',t('Replenishment','Rifurnizimi')],['excess',t('Excess stock','Stoku i tepërt')],['warehouses',t('Warehouse opportunities','Mundësi ndërmjet depove')],['suppliers',t('Supplier options','Opsionet e furnitorëve')],['scenarios',t('Scenarios','Skenarët')]].map(([key,title])=><button key={key} aria-pressed={view===key} onClick={()=>{setView(key);setPage(1)}}>{title}</button>)}</nav>
  {['warehouses','suppliers','scenarios'].includes(view)&&<p>{t('Choose a product below to review these options using its current evidence.','Zgjidh një produkt më poshtë për të rishikuar këto opsione me provat e tij aktuale.')}</p>}
  {error&&<p role="alert" className="intelligence-error">{error}</p>}{message&&<p role="status" className="intelligence-message">{message}</p>}
  {!list&&<p role="status">{t('Loading planning overview…','Duke ngarkuar planifikimin…')}</p>}
  <section className="intelligence-table"><table><thead><tr>{[t('Select','Zgjidh'),t('Product','Produkti'),t('State','Gjendja'),t('Stockout','Mungesa'),t('Order quantity','Sasia e porosisë'),t('Priority','Prioriteti'),t('Review','Rishiko')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list?.rows.map(r=><tr key={r.product.id}><td><input className="planning-check" aria-label={`${t('Select','Zgjidh')} ${r.product.name}`} type="checkbox" disabled={!r.recommendation_id||!['open','viewed'].includes(r.status)||busy} checked={selected.includes(r.recommendation_id)} onChange={()=>{setSelected(v=>v.includes(r.recommendation_id)?v.filter(id=>id!==r.recommendation_id):[...v,r.recommendation_id]);setReview(null)}}/></td><td><Link to={`/products?product=${r.product.id}`}>{r.product.name}</Link><small>{r.status==='accepted'||r.status==='adjusted'?t('PR drafted','Kërkesa u përgatit'):r.plan?label(r.plan.scope):t('Not planned yet','Ende pa plan')}</small></td><td>{label(r.plan?.optimization_state||r.plan?.risk||'insufficient_data')}</td><td>{r.plan?.stockout_date||'—'}</td><td>{n(r.plan?.quantity)} {r.plan?.unit}</td><td>{n(r.plan?.priority)}</td><td><button disabled={busy} onClick={()=>choose(r.product.id)}>{t('Review product','Rishiko produktin')}</button></td></tr>)}{list?.rows.length===0&&<tr><td colSpan="7">{t('No saved recommendations match this view. Review a product in All products; scheduled planning also updates these views.','Asnjë rekomandim i ruajtur nuk përputhet. Rishiko një produkt te Të gjitha produktet; planifikimi i programuar i përditëson këto pamje.')}</td></tr>}</tbody></table></section>
  {list?.last_page>1&&<div className="intelligence-toolbar"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>‹</button>{page}/{list.last_page}<button disabled={page>=list.last_page} onClick={()=>setPage(v=>v+1)}>›</button></div>}
  {product&&!detail&&<p role="status">{t('Calculating current evidence…','Duke llogaritur provat aktuale…')}</p>}
  {plan&&<section className="intelligence-detail"><header><div><h2>{plan.product.name}</h2><p>{label(plan.scope)} · {label(plan.risk)} · {label(plan.method)}</p></div>{detail.can_manage&&<button disabled={busy} onClick={save}>{t('Save recommendation','Ruaj rekomandimin')}</button>}</header>
   <p className="planning-quality"><strong>{label(plan.optimization_state)}</strong> · {label(plan.confidence_state)} · {t('Logic version','Versioni i llogaritjes')} {plan.logic_version}</p>
   <p>{t('Why this recommendation?','Pse ky rekomandim?')} {t('Usable stock','Stoku i përdorshëm')}: {n(plan.inventory_position.usable_on_hand)} − {t('unreserved commitments','angazhime të parezervuara')} {n(plan.inventory_position.unreserved_commitments)} + {t('confirmed dated incoming','furnizim i konfirmuar me datë')} {n(plan.inventory_position.confirmed_dated_incoming)} = <strong>{n(plan.inventory_position.position)} {plan.product.unit}</strong>. {t('Expected lead-time demand','Kërkesa e pritshme gjatë afatit')}: {n(plan.expected_lead_demand)}. {t('Safety target','Objektivi i sigurisë')}: {n(plan.safety_stock)}.</p>
   <p>{t('Mathematical requirement','Nevoja matematikore')}: {n(plan.required_base_quantity)} {plan.product.unit} → {t('Practical purchase','Blerja praktike')}: {n(plan.quantity)} {plan.unit} / {n(plan.base_quantity)} {plan.product.unit}. {t('Fixed conversion','Konvertimi fiks')}: 1 {plan.unit} = {n(plan.factor)} {plan.product.unit}; MOQ {n(plan.moq)}, {t('order increment','hapi i porosisë')} {n(plan.step)} {plan.product.unit}.</p>
   {detail.changes.length>0&&<details open><summary>{t('What changed since the saved recommendation?','Çfarë ndryshoi nga rekomandimi i ruajtur?')}</summary>{detail.changes.map(c=><p key={c.field}>{label(c.field)}: {typeof c.previous==='string'?label(c.previous):n(c.previous)} → {typeof c.current==='string'?label(c.current):n(c.current)}</p>)}</details>}
   <div className="intelligence-toolbar"><label>{t('Supplier','Furnitori')}<select disabled={busy} value={supplier||plan.supplier_id||''} onChange={e=>{setSupplier(e.target.value);setReview(null)}}><option value="">—</option>{detail.suppliers.map(s=><option value={s.supplier_id} key={s.supplier_id}>{s.name}</option>)}</select></label><label>{t('Purchase unit','Njësia e blerjes')}<select disabled={busy} value={unit||plan.unit} onChange={e=>{setUnit(e.target.value);setReview(null)}}><option value={plan.product.unit}>{plan.product.unit}</option>{detail.units.filter(u=>u.code!==plan.product.unit).map(u=><option key={u.code} value={u.code}>{u.code}</option>)}</select></label>{plan.supplier_id&&<Link to={`/suppliers?supplier=${plan.supplier_id}`}>{t('Supplier evidence','Provat e furnitorit')} →</Link>}<Link to="/warehouse-operations">{t('Warehouses & transfers','Depot dhe transferimet')} →</Link></div>
   <div className="intelligence-metrics">{[[t('Available','I disponueshëm'),plan.stock.available],[t('Reserved','I rezervuar'),plan.stock.reserved],[t('Incoming POs','Porositë në ardhje'),plan.stock.incoming],[t('Safety stock','Stoku i sigurisë'),plan.safety_stock],[t('Reorder point','Pika e riporositjes'),plan.reorder_point],[t('Lead-time demand','Kërkesa gjatë afatit'),plan.expected_lead_demand],[t('Days of supply','Ditë mbulimi'),plan.days_of_supply],[t('After arrival: days','Pas mbërritjes: ditë'),plan.post_arrival_days_of_supply],[t('Suggested quantity','Sasia e sugjeruar'),plan.quantity]].map(([k,v])=><article key={k}><span>{k}</span><strong>{n(v)}</strong></article>)}</div>
   <p>{t('Expected arrival','Mbërritja e pritshme')}: {plan.expected_arrival||'—'} · {t('Order by','Porosit deri më')}: {plan.reorder_date||'—'} · {t('Estimated investment','Investimi i vlerësuar')}: {n(plan.base_cost)} {plan.base_currency}</p>
   <p className="planning-quality">{t('Recorded usable days','Ditë të përdorshme të regjistruara')}: {plan.quality.observed_days}/{plan.quality.history_days} · {t('History coverage','Mbulimi i historikut')}: {n(plan.quality.coverage*100)}% · {t('Service target','Objektivi i shërbimit')}: {n(plan.service_level*100)}%. {t('Requested target, not a measured service guarantee. Missing/censored days are not zero demand.','Objektiv i kërkuar, jo garanci e matur. Ditët e panjohura/me mungesë stoku nuk janë kërkesë zero.')}</p>
   {timeline(plan)}
   <section id="planning-suppliers"><h3>{t('Supplier trade-offs','Krahasimi i furnitorëve')}</h3><div className="planning-options">{detail.supplier_options.map(s=><article key={s.supplier_id}><h4>{s.name}</h4><p>{t('Price per inventory unit','Çmimi për njësi inventari')}: {n(s.unit_price)} {s.currency} · {t('Base-currency price','Çmimi në monedhën bazë')}: {n(s.base_unit_price)} {s.base_currency}</p><p>{t('Lead time / conservative range','Afati / vlerësimi konservativ')}: {n(s.lead_days)} / {n(s.lead_p90)} {t('days','ditë')} · {t('Variability','Ndryshueshmëria')}: {n(s.lead_variability)}</p><p>{t('Historical late delivery','Vonesa historike')}: {n(s.late_delivery_percent)}% · {t('Quality acceptance','Pranimi i cilësisë')}: {n(s.quality_acceptance_percent)}% ({s.quality_inspections} {t('inspections','inspektime')}) · {t('Claims','Pretendime')}: {s.claims}</p><p>MOQ {n(s.minimum_order_quantity)} · {t('Fixed pack','Paketim fiks')} {n(s.pack_size)} {plan.product.unit} · {s.samples} {t('completed delivery samples','pranime të përfunduara')}</p>{s.tradeoffs.map((x,k)=><small key={k}>{label(x.advantage==='lead_days'?'lead_days_advantage':x.advantage)} {t('versus','krahasuar me')} {detail.supplier_options.find(p=>p.supplier_id===x.compared_with)?.name}. </small>)}<button disabled={busy} onClick={()=>{setSupplier(String(s.supplier_id));setReview(null)}}>{t('Review this supplier','Rishiko këtë furnitor')}</button></article>)}</div><small>{t('These are recorded trade-offs, not an automatic winner. Missing evidence stays unknown.','Këto janë dallime të regjistruara, jo fitues automatik. Provat që mungojnë mbeten të panjohura.')}</small></section>
   <section id="planning-transfers"><h3>{t('Warehouse opportunities','Mundësi ndërmjet depove')}</h3>{detail.transfer_opportunities.length===0?<p>{t('No transfer opportunity is supported by sufficient measured warehouse demand. Choose a warehouse scope or use a read-only transfer scenario below.','Asnjë mundësi transferimi nuk mbështetet nga kërkesë e mjaftueshme e matur e depos. Zgjidh një depo ose përdor një skenar transferimi vetëm për lexim.')}</p>:detail.transfer_opportunities.map(r=><article className="planning-group" key={r.source_warehouse_id}><strong>{r.source_warehouse_name} → {plan.warehouse.name}</strong><p>{n(r.quantity)} {r.unit} · {t('Arrival','Mbërritja')}: {r.expected_arrival||t('Unknown — review transit time','E panjohur — rishiko afatin e transportit')}</p><Link to={r.url}>{t('Review normal transfer workflow','Rishiko procesin e transferimit')} →</Link></article>)}</section>
   {detail.financial_context&&<details><summary>{t('Recorded finance context','Konteksti financiar i regjistruar')}</summary><div className="intelligence-metrics">{[['recorded_cash',t('Recorded cash/bank balances','Bilancet e regjistruara arkë/bankë')],['po_outstanding',t('Outstanding PO payments','Pagesat e mbetura të porosive')],['open_po_commitments',t('Open PO commitments','Angazhimet e porosive të hapura')],['unlinked_supplier_documents',t('Supplier documents without a PO','Dokumente furnitori pa porosi')]].map(([key,name])=><article key={key}><span>{name}</span><strong>{n(detail.financial_context[key])} {detail.financial_context.base_currency}</strong></article>)}</div><p>{t('Separate source totals; do not add linked documents twice. Recorded cash is not a complete affordability assessment.','Totale burimesh të veçanta; mos i numëro dokumentet e lidhura dy herë. Paratë e regjistruara nuk provojnë aftësinë e plotë për blerje.')}</p>{detail.financial_context.upcoming_po_payments.map((r,k)=><p key={k}><Link to={r.url}>{r.reference}</Link> · {n(r.amount)} {detail.financial_context.base_currency} · {r.due_date}</p>)}</details>}
   {detail.can_manage&&detail.recommendation&&<details><summary>{t('Recommendation decision & history','Vendimi dhe historiku i rekomandimit')}</summary><p>{label(detail.recommendation.status)}</p>{!detail.recommendation.purchase_request_id&&!['dismissed','superseded'].includes(detail.recommendation.status)&&<form className="planning-form" onSubmit={e=>{e.preventDefault();act(async()=>{await post(`/recommendations/${detail.recommendation.id}/feedback`,scenarioPayload(decision));setSelected(v=>v.filter(id=>id!==detail.recommendation.id));setReview(null);setMessage(t('Decision recorded. It is not proof of model accuracy.','Vendimi u regjistrua. Nuk është provë e saktësisë së modelit.'))},true)}}><label>{t('Decision','Vendimi')}<select value={decision.action} onChange={e=>setDecision({...decision,action:e.target.value})}>{['accepted','quantity_changed','supplier_changed','postponed','dismissed','transferred'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>{t('Note','Shënim')}<input maxLength="1000" value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value})}/></label>{decision.action==='quantity_changed'&&<label>{t('Chosen quantity (inventory unit)','Sasia e zgjedhur (njësia e inventarit)')}<input required type="number" min={.001} step={.001} value={decision.base_quantity} onChange={e=>setDecision({...decision,base_quantity:e.target.value})}/></label>}{decision.action==='supplier_changed'&&<label>{t('Chosen supplier','Furnitori i zgjedhur')}<select required value={decision.supplier_id} onChange={e=>setDecision({...decision,supplier_id:e.target.value})}><option value="">—</option>{detail.suppliers.map(s=><option key={s.supplier_id} value={s.supplier_id}>{s.name}</option>)}</select></label>}{decision.action==='postponed'&&<label>{t('Review again on','Rishiko përsëri më')}<input required type="date" value={decision.until} onChange={e=>setDecision({...decision,until:e.target.value})}/></label>}{decision.action==='transferred'&&<label>{t('Actual transfer ID','ID e transferimit real')}<input required type="number" min="1" step="1" value={decision.transfer_id} onChange={e=>setDecision({...decision,transfer_id:e.target.value})}/></label>}<button disabled={busy}>{t('Record decision','Regjistro vendimin')}</button></form>}{(detail.recommendation.feedback?.history||[]).map((r,k)=><p key={k}>{new Date(r.at).toLocaleDateString()} · {label(r.action)} · {r.note} {r.base_quantity?`${n(r.base_quantity)} ${plan.product.unit}`:''}</p>)}</details>}
   <details><summary>{t('Evidence, constraints and assumptions','Provat, kufizimet dhe supozimet')}</summary><p>{t('Current inventory units and confirmed PO remainders are used. Reservations are not deducted twice. Risky, overdue and undated receipts are excluded from firm coverage. Returns are separate; internal transfers are not customer demand.','Përdoren njësitë aktuale dhe sasitë e mbetura të porosive të konfirmuara. Rezervimet nuk zbriten dy herë. Pranimet me rrezik, të vonuara ose pa datë përjashtohen. Kthimet janë veçmas; transferimet nuk janë kërkesë e klientëve.')}</p><p>{t('Physical free storage and available company credit are unknown. A declared stock ceiling or explicit budget is a planning constraint, not a bank balance. Historical landed costs are an allowance, not a future quote.','Kapaciteti i lirë dhe kredia e kompanisë janë të panjohura. Kufiri i stokut dhe buxheti janë kufizime planifikimi, jo bilanc bankar. Kostot historike shtesë janë vlerësim, jo ofertë e ardhshme.')}</p><p>MOQ {n(plan.moq)} · {t('Pack increment','Hapi i paketimit')} {n(plan.step)} {plan.product.unit} · {t('Historical landed estimate','Vlerësimi historik me kosto shtesë')} {n(plan.estimated_landed_cost)} {plan.base_currency}</p>{plan.at_risk_purchase_orders.map(id=><p key={id}><Link to={`/purchase-orders?po=${id}`}>{t('At-risk PO','Porosi me rrezik')} #{id}</Link></p>)}{plan.incoming_transfers.map(r=><p key={r.id}>{t('Transfer','Transferimi')} #{r.id}: {n(r.quantity)} · {r.estimated_at||t('arrival unknown','mbërritje e panjohur')}</p>)}{plan.scope==='declared_company_allocation'&&<p>{t('User-declared warehouse share','Pjesa e depos e deklaruar nga përdoruesi')}: {n(plan.policy.allocation_share*100)}%</p>}</details>
   {detail.can_manage&&policy&&<details><summary>{t('Planning policy','Politika e planifikimit')}</summary><form className="planning-form" onSubmit={e=>{e.preventDefault();act(async()=>{await post(`/products/${product}/policy`,{...policy,warehouse_id:warehouse||null,maximum_stock:policy.maximum_stock||null,allocation_share:policy.allocation_share===''?null:policy.allocation_share});setReview(null);setMessage(t('New policy version saved.','U ruajt versioni i ri i politikës.'))},true)}}><label>{t('Service target','Objektivi i shërbimit')}<select value={policy.service_level} onChange={e=>setPolicy({...policy,service_level:Number(e.target.value)})}>{[.9,.95,.98,.99].map(s=><option value={s} key={s}>{s*100}%</option>)}</select></label>{[['priority',t('Priority 1–5','Prioriteti 1–5'),1,5,1],['review_days',t('Review days','Ditë rishikimi'),1,60,1],['maximum_stock',t('Optional stock ceiling','Kufi opsional i stokut'),0,100000000,.001],...(warehouse?[['allocation_share',t('Company demand share 0–1','Pjesa e kërkesës së kompanisë 0–1'),0,1,.01]]:[])].map(([key,name,min,max,step])=><label key={key}>{name}<input type="number" min={min} max={max} step={step} value={policy[key]??''} onChange={e=>setPolicy({...policy,[key]:e.target.value})}/></label>)}<button disabled={busy}>{t('Save policy version','Ruaj versionin e politikës')}</button></form><small>{t('Immutable policy history','Historik i pandryshueshëm i politikave')}: {detail.policies.map(p=><span key={p.id}> {new Date(p.created_at).toLocaleDateString()} · {p.version.slice(0,8)} </span>)}</small></details>}
   <section><h3>{t('What-if comparison · read-only','Krahasimi Çfarë-nëse · vetëm lexim')}</h3><div className="planning-scenarios">{scenarios.map((s,index)=><article key={index}><h4>{t('Scenario','Skenari')} {index+1}</h4><div className="planning-form"><label>{t('Source','Burimi')}<select value={s.type} onChange={e=>setScenario(index,'type',e.target.value)}><option value="purchase">{t('Purchase','Blerje')}</option>{warehouse&&<option value="transfer">{t('Transfer','Transferim')}</option>}</select></label>{s.type==='purchase'?<label>{t('Supplier','Furnitori')}<select value={s.supplier_id||plan.supplier_id||''} onChange={e=>setScenario(index,'supplier_id',e.target.value)}>{detail.suppliers.map(p=><option key={p.supplier_id} value={p.supplier_id}>{p.name}</option>)}</select></label>:<><label>{t('Source warehouse','Depoja burimore')}<select value={s.source_warehouse_id} onChange={e=>setScenario(index,'source_warehouse_id',e.target.value)}><option value="">—</option>{detail.warehouses.filter(w=>String(w.id)!==warehouse).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>{t('Transit days (assumption)','Ditë transporti (supozim)')}<input type="number" min="0" value={s.transfer_days} onChange={e=>setScenario(index,'transfer_days',e.target.value)}/></label></>}
    <label>{t('Order date','Data e porosisë')}<input type="date" value={s.order_date} onChange={e=>setScenario(index,'order_date',e.target.value)}/></label>{[['base_quantity',t('Quantity in inventory unit (blank = suggested)','Sasia në njësinë e inventarit (bosh = sugjerim)'),0,.001],['delay_days',t('Extra delay days','Ditë vonesë shtesë'),0,1],['demand_multiplier',t('Demand multiplier','Shumëzuesi i kërkesës'),.1,.1],...(detail.can_finance?[['budget',t('Explicit budget in base currency','Buxheti në monedhën bazë'),0,.01]]:[])].map(([key,name,min,step])=><label key={key}>{name}<input type="number" min={min} step={step} value={s[key]} onChange={e=>setScenario(index,key,e.target.value)}/></label>)}<label>{t('Service target','Objektivi i shërbimit')}<select value={s.service_level} onChange={e=>setScenario(index,'service_level',e.target.value)}>{[.9,.95,.98,.99].map(v=><option value={v} key={v}>{v*100}%</option>)}</select></label></div></article>)}</div><div className="intelligence-toolbar"><button disabled={busy||scenarios.length>=4} onClick={()=>setScenarios(v=>[...v,blank()])}>{t('Add scenario','Shto skenar')}</button><button disabled={busy} onClick={()=>act(async()=>setResults((await post(`/products/${product}/scenarios`,{scenarios:scenarios.map(s=>scenarioPayload(s,scope))})).scenarios))}>{t('Compare scenarios','Krahaso skenarët')}</button></div>
   {results&&<div className="planning-scenarios">{results.map((r,i)=><article key={i}><h4>{t('Scenario','Skenari')} {i+1}</h4><p>{t('Arrival','Mbërritja')}: {r.expected_arrival||'—'}</p><p>{n(r.quantity)} {r.unit} · {n(r.base_cost)} {r.base_currency}</p><p>{t('Stockout days before / after','Ditë mungese para / pas')}: {r.stockout_days} / {r.scenario_stockout_days}</p><p>{t('Unmet target','Objektivi i paplotësuar')}: {n(r.shortfall)} {r.product.unit}</p><p>{r.feasible?t('Feasible increments','Hapa të realizueshëm'):t('Not feasible: review constraints','Jo i realizueshëm: rishiko kufizimet')}</p>{r.constraints.map(x=><small key={x}>{label(x)} · </small>)}{timeline(r)}{detail.can_manage&&r.type==='purchase'&&<button disabled={busy||!r.feasible||!r.coverage_supported} onClick={()=>act(async()=>{await post(`/products/${product}/save`,scenarioPayload(scenarios[i],scope));setMessage(t('Scenario saved as a recommendation; select it for PR review.','Skenari u ruajt si rekomandim; zgjidhe për rishikimin e kërkesës.'));setReview(null)},true)}>{t('Save this scenario for review','Ruaj këtë skenar për rishikim')}</button>}</article>)}</div>}</section>
   {detail.outcomes.length>0&&<details><summary>{t('Measured planning outcomes','Rezultatet e matura të planifikimit')}</summary>{detail.outcomes.map(o=><article key={o.recommendation_id}><p>#{o.recommendation_id} · {o.state==='completed_observation'?t('Completed observation','Vëzhgim i përfunduar'):t('Pending / incomplete evidence','Prova në pritje / të paplota')}</p><p>{t('Recommended / chosen / received','Rekomanduar / zgjedhur / pranuar')}: {n(o.recommended_quantity)} / {n(o.chosen_quantity)} / {n(o.received_quantity)} · {t('Stockout days','Ditë mungese')} {o.stockout_days}</p><p>{t('Recorded investment','Investimi i regjistruar')}: {n(o.recorded_purchase_investment)} · {t('Observational only; no proven savings claimed.','Vetëm vëzhgim; nuk pretendohet kursim i provuar.')}</p></article>)}</details>}
  </section>}
  <section className="intelligence-detail"><h2>{t('Consolidated purchasing review','Rishikimi i përbashkët i blerjeve')}</h2><p>{selected.length} {t('recommendations selected. Priority first, then earliest stockout; MOQ and fixed packs remain enforced.','rekomandime të zgjedhura. Prioriteti fillimisht, pastaj mungesa më e hershme; MOQ dhe paketimet fikse respektohen.')}</p><div className="intelligence-toolbar"><label>{t('Optional purchasing budget (base currency)','Buxheti opsional i blerjeve (monedha bazë)')}<input type="number" min="0" step=".01" value={budget} onChange={e=>{setBudget(e.target.value);setReview(null)}}/></label><button disabled={busy||!selected.length} onClick={()=>act(async()=>{setReview(await post('/consolidate',{recommendations:selected,...(budget!==''?{budget}: {})}));setCreated([])})}>{t('Review selected plan','Rishiko planin e zgjedhur')}</button></div>
   {review&&<><p>{t('Estimated base-currency commitment','Angazhimi i vlerësuar në monedhën bazë')}: {n(review.base_commitment)} {review.base_currency} · {t('Unspent budget','Buxheti i pashpenzuar')}: {n(review.unspent_budget)}</p>{review.groups.map((g,index)=><article className="planning-group" key={index}><h3>{g.supplier_name} · {g.delivery_period}</h3><p>{g.currency} {n(g.estimated_commitment)}</p>{g.items.map(r=><p key={r.recommendation_id}>{r.product.name} · {n(r.quantity)} {r.unit} · {t('Priority','Prioriteti')} {r.priority} · {t('Unmet target','Objektivi i paplotësuar')} {n(r.shortfall)} · {r.base_quantity>0&&r.feasible&&r.coverage_supported?t('Ready for draft','Gati për kërkesë'):t('Not draftable','Nuk mund të përgatitet')}</p>)}</article>)}
    {items.length!==allItems.length&&<button disabled={busy} onClick={()=>{setSelected(items.map(i=>i.recommendation_id));setReview(null);setMessage(t('Unfunded or infeasible items removed. Review the reduced selection again.','Artikujt e pafinancuar ose të parealizueshëm u hoqën. Rishiko zgjedhjen përsëri.'))}}>{t('Remove unfunded / infeasible items','Hiq artikujt e pafinancuar / të parealizueshëm')}</button>}
    {canManage&&canFinance&&<button disabled={busy||items.length!==allItems.length||!items.length} onClick={()=>act(async()=>{const r=await post('/purchase-requests',{recommendations:selected,budget:budget===''?null:budget,review_fingerprint:review.review_fingerprint});setCreated(r.purchase_requests);setSelected([]);setReview(null);setMessage(t('PR drafts created. Open Procurement to review and submit for approval.','Kërkesat u përgatitën. Hap Prokurimin për rishikim dhe dorëzim në miratim.'))},true)}>{busy?t('Processing…','Duke përpunar…'):t('Confirm & create PR drafts','Konfirmo dhe krijo kërkesat')}</button>}
   </>}{created.map(pr=><p key={pr.id}><Link to={`/procurement?request=${pr.id}`}>{pr.request_number} · {t('Open Purchase Request','Hap kërkesën e blerjes')} →</Link></p>)}
  </section>
 </main>
}
