import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { orderHub } from '../api/orderHub'
import * as fulfillment from '../api/fulfillment'
import { getFinancialAccounts } from '../api/advancedOperations'
import { downloadInvoicePdf } from '../api/invoices'

export default function OrderConnections({detail,t,language,permissions,busy,run}) {
  const navigate=useNavigate(),o=detail.order,c=detail.connections||{},[verified,setVerified]=useState(false),[recipient,setRecipient]=useState(''),[accounts,setAccounts]=useState([]),[payment,setPayment]=useState({amount:'',financial_account_id:'',payment_method:'cash',transaction_date:new Date().toLocaleDateString('en-CA')})
  const paymentKey=useRef(crypto.randomUUID()),readyKey=useRef(crypto.randomUUID()),dispatchKey=useRef(crypto.randomUUID())
  const canPay=permissions.includes('debts.payments')&&permissions.includes('financial_accounts.adjust')&&permissions.includes('fulfillment.manage')
  useEffect(()=>{if(canPay)getFinancialAccounts().then(r=>setAccounts(Array.isArray(r)?r:r.data||[])).catch(()=>{})},[canPay])
  if(!o)return null
  const actions={confirm:t('Confirm the order','Konfirmo porosinë'),stock_review:t('Resolve stock shortage','Zgjidh mungesën e stokut'),prepare:t('Verify products and mark ready','Verifiko produktet dhe shëno gati'),dispatch:t('Dispatch order','Nis porosinë'),deliver:t('Mark delivered','Shëno të dorëzuar'),documents:t('View sale, invoice or return','Shiko shitjen, faturën ose kthimin'),none:t('No further action','Nuk kërkohet veprim')}
  return <section className="fulfillment-panel order-connections"><h2>{t('Next action','Veprimi i radhës')}: {actions[c.next_action]||t('Review order','Shqyrto porosinë')}</h2>
    {c.next_action==='stock_review'&&<Link to={`/fulfillment?order=${o.id}`}>{t('Review availability and backorder','Shqyrto disponueshmërinë dhe stokun në pritje')}</Link>}
    {c.next_action==='prepare'&&permissions.includes('fulfillment.manage')&&permissions.includes('fulfillment.pick')&&<div><label className="fulfillment-check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>{t('I verified these products and quantities are ready.','Verifikova se këto produkte dhe sasi janë gati.')}</label><button disabled={busy||!verified} onClick={()=>run(()=>orderHub.action(detail.id,'ready',{verified:true,idempotency_key:readyKey.current}))}>{t('Mark ready','Shëno gati')}</button><p>{t('Tracked lots and partial dispatches use the warehouse scanning workflow.','Lotet e gjurmuara dhe nisjet e pjesshme përdorin rrjedhën e skanimit në depo.')}</p></div>}
    {c.next_action==='dispatch'&&permissions.includes('fulfillment.dispatch')&&<div><p>{o.payment_type==='cash'?t('By dispatching, you confirm cash has been received. The Daily Sale and stock movement are created together, once.','Me nisjen konfirmoni se pagesa në dorë është pranuar. Shitja ditore dhe lëvizja e stokut krijohen së bashku, një herë.'):t('Dispatch records the sale and applies customer credit/advance under the existing rules.','Nisja regjistron shitjen dhe zbaton kredinë/parapagimin sipas rregullave ekzistuese.')}</p><button disabled={busy} onClick={()=>run(()=>fulfillment.action(o.id,'dispatch',{idempotency_key:dispatchKey.current,package_ids:o.packages.filter(p=>!p.outbound_dispatch_id).map(p=>p.id)}))}>{o.payment_type==='cash'?t('Confirm cash received & dispatch','Konfirmo pagesën në dorë & nis'):t('Dispatch order','Nis porosinë')}</button></div>}
    {c.next_action==='deliver'&&permissions.includes('fulfillment.dispatch')&&<form onSubmit={e=>{e.preventDefault();run(async()=>{for(const d of o.dispatches.filter(d=>d.status!=='delivered'))await fulfillment.action(o.id,'delivery',{idempotency_key:`deliver-${d.id}-${crypto.randomUUID()}`,dispatch_id:d.id,recipient})})}}><label>{t('Recipient','Pranuesi')}<input required value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><button disabled={busy}>{t('Confirm full delivery','Konfirmo dorëzimin e plotë')}</button><Link to={`/fulfillment?order=${o.id}`}>{t('Partial or failed delivery','Dorëzim i pjesshëm ose i dështuar')}</Link></form>}
    {canPay&&o.customer_id&&o.payment_type!=='cash'&&o.status!=='cancelled'&&detail.states.payment!=='paid'&&<details><summary>{t('Record payment / advance','Regjistro pagesë / parapagim')}</summary><p>{t('Payments use the existing customer ledger: oldest unpaid debt first, then advance. They are not earmarked to this order.','Pagesat përdorin regjistrin ekzistues: borxhi më i vjetër fillimisht, pastaj parapagimi. Nuk rezervohen vetëm për këtë porosi.')}</p><form className="fulfillment-grid" onSubmit={e=>{e.preventDefault();run(async()=>{const result=await orderHub.action(detail.id,'payment',{...payment,idempotency_key:paymentKey.current});paymentKey.current=crypto.randomUUID();setPayment(p=>({...p,amount:''}));return result})}}>
      <label>{t('Amount','Shuma')}<input required type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>{t('Payment date','Data e pagesës')}<input required type="date" value={payment.transaction_date} onChange={e=>setPayment({...payment,transaction_date:e.target.value})}/></label>
      <label>{t('Cash / bank account','Llogaria në dorë / bankë')}<select required value={payment.financial_account_id} onChange={e=>setPayment({...payment,financial_account_id:e.target.value})}><option value="">—</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label><label>{t('Method','Mënyra')}<select value={payment.payment_method} onChange={e=>setPayment({...payment,payment_method:e.target.value})}><option value="cash">{t('Cash','Në dorë')}</option><option value="bank_transfer">{t('Bank transfer','Transfer bankar')}</option><option value="card">{t('Card','Kartë')}</option></select></label><button disabled={busy}>{t('Record payment','Regjistro pagesën')}</button>
    </form></details>}
    <h3>{t('Connected sale & invoice','Shitja & fatura e lidhur')}</h3>{!c.sales?.length&&<p>{t('No sale yet. Reserving or preparing goods does not deduct stock; dispatch creates the Daily Sale automatically.','Ende nuk ka shitje. Rezervimi ose përgatitja nuk ul stokun; nisja krijon automatikisht shitjen ditore.')}</p>}
    {(c.sales||[]).map(s=>{const inv=(c.invoices||[]).find(i=>i.daily_sale_id===s.id);return <div className="fulfillment-task" key={s.id}><div><Link to={`/daily-sales?date=${s.sale_date.slice(0,10)}&sale=${s.id}`}>{s.sale_number}</Link><p>{s.total_amount} {o.currency}</p></div>{permissions.includes('invoices.manage')&&(inv?<div><Link to={`/invoices?invoice=${inv.id}`}>{t('View invoice','Shiko faturën')} {inv.invoice_number||`#${inv.id}`}</Link>{inv.status!=='draft'&&<button disabled={busy} onClick={()=>run(()=>downloadInvoicePdf(inv.id,inv.invoice_number,language))}>{t('Download / print invoice','Shkarko / shtyp faturën')}</button>}</div>:<button disabled={busy} onClick={()=>run(async()=>{const inv=await orderHub.action(detail.id,'invoice',{daily_sale_id:s.id});navigate(`/invoices?invoice=${inv.id}`);return inv})}>{t('Create invoice','Krijo faturë')}</button>)}</div>})}
    {(c.credit_notes||[]).map(note=><p key={note.id}><Link to={`/invoices?invoice=${note.id}`}>{t('Return credit note','Notë kreditore e kthimit')} {note.invoice_number}</Link> · {note.grand_total} {o.currency}</p>)}
    {(c.payments||[]).map(p=><p key={p.id}>{t('Payment','Pagesa')} #{p.id}: {p.amount} {o.currency} · {p.transaction_date?.slice(0,10)} <Link to={`/customer-debts?customer=${o.customer_id}`}>{t('Open payment history','Hap historinë e pagesave')}</Link></p>)}
    <div className="fulfillment-toolbar"><button disabled={busy} onClick={()=>run(()=>fulfillment.slip(o.id))}>{t('Download / print packing slip','Shkarko / shtyp fletëpaketimin')}</button><Link to={`/fulfillment?order=${o.id}`}>{t('Warehouse details & returns','Hollësitë e depos & kthimet')}</Link></div>
  </section>
}
