import {useEffect,useState} from 'react'
import {orderHub as api} from '../api/orderHub'

export function OrderHubActions({rows,filters,t,language,manage,run,busy}){
  const [selected,setSelected]=useState([]),[action,setAction]=useState('retry'),[results,setResults]=useState(null)
  useEffect(()=>setSelected(ids=>ids.filter(id=>rows.some(r=>r.id===id))),[rows])
  return <details className="fulfillment-panel"><summary>{t('Export & batch actions','Eksporto & veprime në grup')}</summary><div className="fulfillment-toolbar">{['csv','xlsx','pdf'].map(format=><button key={format} disabled={busy} onClick={()=>run(()=>api.export(filters,format,language))}>{t('Export','Eksporto')} {format.toUpperCase()}</button>)}</div>{manage&&<><p>{t('Select orders on this page. Each result is reported separately; all normal validation remains enforced.','Zgjidhni porositë në këtë faqe. Çdo rezultat raportohet veçmas; të gjitha validimet mbeten në fuqi.')}</p><div className="hub-batch-list">{rows.map(row=><label key={row.id} className="fulfillment-check"><input type="checkbox" checked={selected.includes(row.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,row.id]:ids.filter(id=>id!==row.id))}/>{row.order?.order_number||row.external_id||`#${row.id}`}</label>)}</div><div className="fulfillment-toolbar"><select aria-label={t('Batch action','Veprimi në grup')} value={action} onChange={e=>setAction(e.target.value)}><option value="retry">{t('Retry matching','Riprovo përputhjen')}</option><option value="confirm">{t('Confirm & reserve','Konfirmo & rezervo')}</option><option value="cancel">{t('Cancel orders','Anulo porositë')}</option></select><button disabled={busy||!selected.length} onClick={()=>{const reason=action==='cancel'?prompt(t('Cancellation reason','Arsyeja e anulimit')):null;if(action==='cancel'&&!reason)return;if(!confirm(t(`Apply ${action} to ${selected.length} selected orders?`,`Zbato veprimin në ${selected.length} porosi të zgjedhura?`)))return;run(async()=>setResults((await api.bulk({ids:selected,action,...(reason?{reason}:{})})).results))}}>{t('Apply to selected','Zbato te të zgjedhurat')} ({selected.length})</button></div>{results&&<ul aria-live="polite">{results.map(r=><li key={r.id}>#{r.id} · {r.success?t('Completed','Përfunduar'):r.message}</li>)}</ul>}</>}</details>
}

export function OrderAcceptanceRule({t,run,busy}){
  const [rule,setRule]=useState({rule_type:'order_acceptance',is_active:false,threshold_amount:'',required_role:'manager',separation_of_duties:true}),[error,setError]=useState('')
  useEffect(()=>{let live=true;api.rules().then(rows=>{const existing=rows.find(r=>r.rule_type==='order_acceptance');if(live&&existing)setRule(existing)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[])
  return <details className="fulfillment-panel"><summary>{t('Company order approval rule','Rregulli i miratimit të porosive')}</summary>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();run(async()=>setRule(await api.saveRule({...rule,threshold_amount:rule.threshold_amount===''?null:rule.threshold_amount,required_user_id:null})))}}><p>{t('Optional. Orders at or above the threshold need approval in the existing Approval Engine. Blank threshold means all orders.','Opsionale. Porositë mbi ose në prag kërkojnë miratim në sistemin ekzistues. Pragu bosh përfshin të gjitha porositë.')}</p><div className="fulfillment-grid"><label>{t('Approval threshold (company currency)','Pragu i miratimit (valuta e kompanisë)')}<input type="number" min="0" step="0.01" value={rule.threshold_amount??''} onChange={e=>setRule({...rule,threshold_amount:e.target.value})}/></label><label>{t('Approver role','Roli i miratuesit')}<select value={rule.required_role||'manager'} onChange={e=>setRule({...rule,required_role:e.target.value})}><option value="manager">{t('Manager','Menaxher')}</option><option value="admin">{t('Administrator','Administrator')}</option></select></label></div><label className="fulfillment-check"><input type="checkbox" checked={!!rule.is_active} onChange={e=>setRule({...rule,is_active:e.target.checked})}/>{t('Require order approval','Kërko miratimin e porosive')}</label><label className="fulfillment-check"><input type="checkbox" checked={!!rule.separation_of_duties} onChange={e=>setRule({...rule,separation_of_duties:e.target.checked})}/>{t('Prevent self-approval','Parandalo vetë-miratimin')}</label><button disabled={busy}>{t('Save approval rule','Ruaj rregullin e miratimit')}</button></form></details>
}
