import { useEffect,useState } from 'react'
import { orderHub as api } from '../api/orderHub'

export function OrderHubPresets({t,filters,intakeId,onView,onOrder,run,busy}){
  const [presets,setPresets]=useState([]),[name,setName]=useState('')
  useEffect(()=>{api.presets().then(setPresets).catch(()=>{})},[])
  const save=()=>run(async()=>{await api.savePreset({name,kind:intakeId?'template':'view',...(intakeId?{intake_id:Number(intakeId)}:{filters})});setName('');setPresets(await api.presets())})
  return <details className="fulfillment-panel"><summary>{t('Saved views & order templates','Pamjet e ruajtura & modelet e porosive')}</summary><div className="fulfillment-toolbar"><input aria-label={t('Saved view or template name','Emri i pamjes ose modelit')} placeholder={t('Name this view or order list','Emërto këtë pamje ose listë porosie')} value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()} onClick={save}>{intakeId?t('Save order template','Ruaj modelin e porosisë'):t('Save view','Ruaj pamjen')}</button></div>{presets.map(p=><div className="fulfillment-task" key={p.id}><strong>{p.name}</strong><button disabled={busy} onClick={()=>p.kind==='view'?onView(p.payload):run(async()=>{const result=await api.action(p.payload.intake_id,'reorder');onOrder(result.id)})}>{p.kind==='view'?t('Open view','Hap pamjen'):t('Create fresh draft','Krijo draft të ri')}</button><button disabled={busy} onClick={()=>run(async()=>{await api.deletePreset(p.id);setPresets(await api.presets())})}>{t('Delete','Fshi')}</button></div>)}</details>
}
export function OrderHubImport({t,channels,run,busy,onImported}){
  const [preview,setPreview]=useState(null),[channel,setChannel]=useState('')
  return <details className="fulfillment-panel"><summary>{t('Import orders from CSV','Importo porosi nga CSV')}</summary><p>{t('Required headers: external_id, customer_email, sku, quantity. Optional: unit, unit_price, order_date, payment_type. Preview before committing.','Kolonat e detyrueshme: external_id, customer_email, sku, quantity. Opsionale: unit, unit_price, order_date, payment_type. Kontrolloni para regjistrimit.')}</p><label>{t('CSV file','Skedari CSV')}<input type="file" accept=".csv,.txt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>setPreview(await api.preview(file)))}}/></label>{preview&&<><p>{preview.count} {t('orders','porosi')} · {preview.lines} {t('lines','rreshta')}</p><div className="fulfillment-table"><table><thead><tr><th>{t('Reference','Referenca')}</th><th>{t('Customer','Klienti')}</th><th>{t('Products','Produktet')}</th></tr></thead><tbody>{preview.orders.map(o=><tr key={o.external_id}><td>{o.external_id}</td><td>{o.customer.email}</td><td>{o.items.map(i=>`${i.sku} × ${i.quantity}`).join(', ')}</td></tr>)}</tbody></table></div><label>{t('Import channel','Kanali i importit')}<select aria-label={t('Import channel','Kanali i importit')} value={channel} onChange={e=>setChannel(e.target.value)}><option value="">—</option>{channels.filter(c=>c.enabled).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy||!channel} onClick={()=>run(async()=>{await api.import(channel,preview.orders);setPreview(null);onImported()})}>{t('Confirm import','Konfirmo importin')}</button></>}</details>
}
export function OrderHubReport({t,run,busy}){
  const now=new Date(),[from,setFrom]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`),[to,setTo]=useState(now.toLocaleDateString('en-CA')),[report,setReport]=useState(null)
  return <details className="fulfillment-panel"><summary>{t('Channel performance & health','Performanca & gjendja e kanaleve')}</summary><form className="fulfillment-toolbar" onSubmit={e=>{e.preventDefault();run(async()=>setReport(await api.report({from,to})))}}><label>{t('From','Nga')}<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('To','Deri')}<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy}>{t('Show report','Shfaq raportin')}</button></form>{report&&<><p>{t('Order value is demand, not revenue. Dispatched value is gross recorded sales before returns. No marketing attribution is estimated.','Vlera e porosive është kërkesë, jo e ardhur. Vlera e nisur është shitja bruto e regjistruar para kthimeve. Nuk vlerësohet atribuimi i marketingut.')}</p><div className="fulfillment-table"><table><thead><tr>{[t('Channel','Kanali'),t('Orders','Porositë'),t('Accepted','Pranuar'),t('Cancelled','Anuluar'),t('Delivered','Dorëzuar'),t('Order value','Vlera e porosive'),t('Dispatched value','Vlera e nisur'),t('Health','Gjendja')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.channels.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.orders}</td><td>{c.accepted}</td><td>{c.cancelled}</td><td>{c.delivered}</td><td>{c.order_value} {report.currency}</td><td>{c.dispatched_value} {report.currency}</td><td>{({connected:t('Connected','Lidhur'),offline:t('No received data','Pa të dhëna të pranuara'),disabled:t('Disabled','Joaktiv'),degraded:t('Needs review','Kërkon shqyrtim')})[c.health]}</td></tr>)}</tbody></table></div></>}</details>
}
