import {useEffect,useState} from 'react'
import {orderHub as api} from '../api/orderHub'

export default function OrderChannelMappings({channel,t,run,busy}){
  const [kind,setKind]=useState('product'),[search,setSearch]=useState(''),[choices,setChoices]=useState([]),[entity,setEntity]=useState(''),[external,setExternal]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState('')
  useEffect(()=>{let live=true;api.mappings(channel.id).then(r=>{if(live)setRows(r.data)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[channel.id])
  useEffect(()=>{let live=true;const timer=setTimeout(()=>api.lookups(kind,search).then(r=>{if(live)setChoices(r)}).catch(e=>{if(live)setError(e.message)}),200);return()=>{live=false;clearTimeout(timer)}},[kind,search])
  return <section className="fulfillment-panel"><h3>{channel.name} · {t('External mappings','Përputhjet e jashtme')}</h3>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await api.map(channel.id,{kind,external_id:external,entity_id:Number(entity)});setRows(result.data);setExternal('')})}}><div className="fulfillment-grid"><label>{t('Mapping type','Lloji i përputhjes')}<select value={kind} onChange={e=>{setKind(e.target.value);setEntity('')}}><option value="product">{t('Product','Produkti')}</option><option value="customer">{t('Customer','Klienti')}</option></select></label><label>{t('Find existing record','Gjej regjistrimin ekzistues')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('AIMS record','Regjistrimi AIMS')}<select aria-label={t('AIMS record','Regjistrimi AIMS')} required value={entity} onChange={e=>setEntity(e.target.value)}><option value="">—</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name}{x.sku?` · ${x.sku}`:''}</option>)}</select></label><label>{t('External identifier','Identifikuesi i jashtëm')}<input required maxLength={150} value={external} onChange={e=>setExternal(e.target.value)}/></label></div><button disabled={busy}>{t('Save mapping','Ruaj përputhjen')}</button></form><p>{t('Existing external identifiers are updated explicitly. Retry matching on affected orders after saving.','Identifikuesit ekzistues përditësohen shprehimisht. Riprovo përputhjen te porositë e prekura pas ruajtjes.')}</p><div className="fulfillment-table"><table><thead><tr><th>{t('Type','Lloji')}</th><th>{t('External identifier','Identifikuesi i jashtëm')}</th><th>{t('AIMS ID','ID në AIMS')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.kind==='product'?t('Product','Produkti'):t('Customer','Klienti')}</td><td>{r.external_id}</td><td>{r.product_id||r.customer_id}</td></tr>)}</tbody></table></div></section>
}
