const labels={
 recorded_completion:['Recorded completion','Përfundim i regjistruar'],
 supplier_dispatch:['Supplier dispatch','Dërgimi nga furnitori'],customs_started:['Customs started','Fillimi i doganës'],landed_cost_finalized:['Landed cost finalized','Kostoja e importit e përfunduar'],
 ON_TRACK:['On track','Në kohë'],WATCH:['Watch','Në vëzhgim'],AT_RISK:['At risk','Në rrezik'],DELAYED:['Delayed','Me vonesë'],CRITICAL:['Critical','Kritike'],INSUFFICIENT_DATA:['Insufficient data','Të dhëna të pamjaftueshme'],
 critical_inventory_exposure:['Critical inventory exposed','Inventar kritik i ekspozuar'],arrival_after_inventory_requirement:['Arrival after inventory requirement','Mbërritje pas nevojës së inventarit'],milestone_or_schedule_overdue:['Milestone or schedule overdue','Etapë ose afat i vonuar'],tracking_not_fresh:['Tracking data is not fresh','Të dhënat e gjurmimit nuk janë të freskëta'],recorded_schedule_or_route_evidence:['Recorded schedule or historical route evidence','Afat i regjistruar ose historik i itinerarit'],insufficient_milestones:['Insufficient milestone evidence','Të dhëna të pamjaftueshme të etapave'],
 SUPPLIER_PREPARATION:['Supplier preparation','Përgatitja nga furnitori'],ORIGIN_LOGISTICS:['Origin logistics','Logjistika e nisjes'],INTERNATIONAL_TRANSIT:['International transit','Transporti ndërkombëtar'],TRANSSHIPMENT:['Transshipment','Transit ndërmjet porteve'],DESTINATION_PORT:['Destination port','Porti i destinacionit'],CUSTOMS:['Customs','Dogana'],INLAND_TRANSPORT:['Inland transport','Transporti tokësor'],RECEIVING:['Receiving','Pranimi'],UNKNOWN:['Unknown','E panjohur'],
 purchase_order:['Purchase order','Porosia e blerjes'],supplier_confirmation:['Supplier confirmation','Konfirmimi i furnitorit'],supplier_production:['Supplier production','Prodhimi nga furnitori'],cargo_ready:['Cargo ready','Ngarkesa gati'],container_booking:['Container booking','Rezervimi i kontejnerit'],container_loaded:['Container loaded','Kontejneri i ngarkuar'],origin_port:['Origin port','Porti i nisjes'],vessel_departure:['Departure','Nisja'],sea_transit:['International transit','Transporti ndërkombëtar'],transshipment:['Transshipment','Transit ndërmjet porteve'],destination_port:['Destination port','Porti i destinacionit'],customs_cleared:['Customs cleared','Dogana e përfunduar'],inland_transport:['Inland transport','Transporti tokësor'],warehouse_arrival:['Warehouse arrival','Mbërritja në depo'],goods_receipt:['Goods receipt','Pranimi i mallrave'],inventory_available:['Inventory available','Inventari në dispozicion'],
 fresh:['Fresh AIS position','Pozicion i freskët AIS'],last_known:['Last-known AIS position','Pozicioni i fundit i njohur AIS'],stale:['Stale AIS position','Pozicion AIS i vjetruar'],missing:['Waiting for AIS data','Në pritje të të dhënave AIS'],invalid_mmsi:['Invalid MMSI','MMSI e pavlefshme'],not_applicable:['AIS not applicable','AIS nuk zbatohet'],
 warehouse_transfer:['Review warehouse transfer','Rishiko transferimin ndërmjet depove'],existing_incoming:['Review other incoming PO','Rishiko porosinë tjetër në ardhje'],procurement_review:['Review supplier / purchasing alternatives','Rishiko alternativat e furnitorit / blerjes'],customer_order_review:['Review exposed customer orders','Rishiko porositë e ekspozuara të klientëve'],operational_follow_up:['Operational follow-up','Ndjekje operative'],
 recorded_warehouse_schedule:['Recorded warehouse schedule','Afati i regjistruar i depos'],carrier_schedule:['Carrier schedule','Afati i transportuesit'],operational_schedule:['Operational schedule','Afati operativ'],historical_departure_to_warehouse:['Observed departure-to-warehouse history','Historiku i regjistruar nga nisja në depo'],historical_route_with_recorded_schedule:['Route history and recorded schedule','Historiku i itinerarit dhe afati i regjistruar'],actual_port_arrival:['Recorded port arrival','Mbërritja e regjistruar në port'],actual_warehouse_arrival:['Recorded warehouse arrival','Mbërritja e regjistruar në depo'],unavailable:['Unavailable','Pa të dhëna'],
 limited:['Limited evidence','Të dhëna të kufizuara'],moderate:['Moderate confidence','Besueshmëri mesatare'],warehouse:['Warehouse','Depo'],port:['Port','Port'],
 limited_historical_evidence:['Limited historical evidence','Historik i pamjaftueshëm'],warehouse_arrival_unknown:['Customs / inland / receiving timing remains unknown','Afati i doganës / transportit tokësor / pranimit mbetet i panjohur'],eta_unavailable:['ETA unavailable','ETA nuk është në dispozicion'],ais_tracking_not_fresh:['AIS is not currently fresh','AIS nuk është aktualisht i freskët'],
 ocean:['Ocean','Detar'],road:['Road','Rrugor'],rail:['Rail','Hekurudhor'],air:['Air','Ajror'],multimodal:['Multimodal','Multimodal'],
 customs_inland_and_receiving_duration_unknown:['No qualified customs / inland / receiving duration','Nuk ka kohëzgjatje të besueshme të doganës / transportit tokësor / pranimit'],expected_date_passed_without_arrival:['Expected date passed; a new arrival estimate is not yet supported','Afati ka kaluar; nuk ka ende të dhëna për një afat të ri'],schedule_not_statistical_confidence_interval:['A recorded schedule, not a calibrated prediction interval','Afat i regjistruar, jo interval statistikor i kalibruar'],
}
export function shipmentIntelligenceLabel(key,language='en'){
 if(!key)return '—'
 if(key.endsWith('_plus_observed_inland_receiving'))return shipmentIntelligenceLabel(key.replace('_plus_observed_inland_receiving',''),language)+(language==='sq'?' + historiku i transportit tokësor / pranimit':' + observed inland / receiving history')
 return labels[key]?.[language==='sq'?1:0]||key.replaceAll('_',' ')
}
export function shipmentTimeline(product){
 return [{key:'stock',date:null,quantity:product.stock?.available_to_promise},
  {key:'safety',date:product.safety_date,quantity:product.safety_stock},
  {key:'stockout',date:product.requirement_date,quantity:null},
  {key:'arrival',date:product.arrival,quantity:product.quantity}]
}
export function etaRange(eta){if(!eta?.predicted)return '—';return eta.range_start&&eta.range_end&&eta.range_start!==eta.range_end?`${eta.range_start} – ${eta.range_end}`:eta.predicted}
