import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {Package,Search,Ship} from 'lucide-react'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import {ShipmentRouteMap} from './tracking/GlobalVesselMap'
import {etaRange,shipmentIntelligenceLabel} from './shipmentIntelligencePresentation'
import {cargoGroups,logisticsProgress,projectedReceiptBalance} from './shipmentCargoPresentation'
import {businessDate,businessNumber} from '../utils/businessFormat'
import './ShipmentWorkspace.css'

export default function ShipmentWorkspace({shipment}){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,permissions=useAuthStore(s=>s.permissions)
 const [intelligence,setIntelligence]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState('')
 useEffect(()=>{setQuery('');setIntelligence(null)},[shipment.id])
 useEffect(()=>{let alive=true;setError('');apiRequest('/shipment-intelligence/'+shipment.id).then(data=>{if(alive)setIntelligence(data)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[shipment.id,shipment.updated_at])
 const num=value=>businessNumber(value,language)
 const date=value=>businessDate(value,language)
 const label=key=>shipmentIntelligenceLabel(key,language)
 const cargo=shipment.cargo,groups=cargoGroups(cargo,query),impact=intelligence?.impact
 const fact=(name,value)=><div key={name}><dt>{name}</dt><dd>{value||'—'}</dd></div>
 return <section className="shipment-workspace" aria-label={t('Vessel and incoming stock','Anija dhe stoku në ardhje')}>
  <header className="cargo-heading"><div><small><Ship size={15}/>{shipment.tracking_number||shipment.tracking_reference}</small><h2>{shipment.vessel_name||t('Vessel details pending','Në pritje të detajeve të anijes')}</h2></div><span className="cargo-status" data-state={intelligence?.risk}>{intelligence?.risk?label(intelligence.risk):shipment.status?.replaceAll('_',' ')}</span></header>
  <div className="shipment-overview"><dl className="shipment-key-facts">{fact(t('Current location','Vendndodhja aktuale'),shipment.last_location_label)}{fact(t('Origin → destination','Nisja → destinacioni'),`${shipment.origin_port||'—'} → ${shipment.destination_port||'—'}`)}{fact(t('Recorded ETA','ETA e regjistruar'),date(shipment.eta))}{fact(intelligence?.eta?.target==='warehouse'?t('AIMS warehouse ETA','ETA AIMS në depo'):t('AIMS port ETA','ETA AIMS në port'),etaRange(intelligence?.eta,date))}{fact(t('Destination warehouse','Depoja e destinacionit'),shipment.warehouse?.name||cargo?.groups?.[0]?.destination)}{fact(t('Last tracking update','Përditësimi i fundit i gjurmimit'),shipment.position_updated_at?businessDate(shipment.position_updated_at,language,true):t('No position received','Pa pozicion të pranuar'))}</dl>
   <div className="shipment-compact-map"><ShipmentRouteMap shipment={shipment} pendingLabel={shipment.tracking_provider==='synthetic'?t('Synthetic logistics record — no live AIS position.','Regjistrim logjistik sintetik — pa pozicion të drejtpërdrejtë AIS.'):t('Waiting for an AIS position.','Në pritje të pozicionit AIS.')}/></div>
  </div>
  <section className="shipment-cargo" aria-label={t('Incoming Stock','Stoku në ardhje')}><header className="cargo-section-header"><h3><Package size={18}/>{t('Incoming Stock','Stoku në ardhje')}</h3><label className="cargo-search"><Search size={16}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search cargo','Kërko ngarkesën')} aria-label={t('Search cargo','Kërko ngarkesën')}/></label></header>
   {!cargo?<p role="status">{t('Loading cargo…','Duke ngarkuar ngarkesën…')}</p>:cargo.restricted?<p>{t('Purchase order permission is required to view cargo.','Kërkohet leja e porosive të blerjes për ngarkesën.')}</p>:<>
    <div className="cargo-totals"><span>{t('Products','Produktet')}: <strong>{cargo.product_count}</strong></span>{cargo.quantities?.map(row=><span key={row.unit}><strong>{num(row.quantity)} {row.unit}</strong> {t('allocated','të ndara')}</span>)}</div>
    {!cargo.allocation_known&&<p className="cargo-warning">{t('PO products are shown below. Quantities on this shipment have not been allocated — the full order is not assumed to be on board.','Produktet e porosisë janë më poshtë. Sasitë për këtë dërgesë nuk janë ndarë — porosia e plotë nuk supozohet në bord.')}</p>}
    {groups.map((group,index)=><section className="cargo-po-group" key={group.reference||index}><header><div>{group.url?<Link to={group.url}>{group.reference} ↗</Link>:<strong>{t('Cargo without PO','Ngarkesë pa porosi')}</strong>}<small>{group.supplier||'—'} · {group.destination||'—'}</small></div>{group.purchase_value!=null&&<small>{t('Full PO value','Vlera e porosisë së plotë')}: <strong>{num(group.purchase_value)} {group.currency}</strong></small>}</header>
     <div className="cargo-product-list">{group.items.map((row,i)=><article className="cargo-product" key={`${row.product_id}-${i}`}>
      <div className="cargo-product-name">{row.image_url&&<img src={row.image_url} alt="" loading="lazy"/>}<div>{row.url&&permissions.includes('inventory.view')?<Link to={row.url}>{row.name}</Link>:<strong>{row.name}</strong>}<small>{row.sku||'—'}</small></div></div>
      <div className="cargo-quantity">{row.allocation_quantities?.length>1?row.allocation_quantities.map(q=><strong key={q.unit}>{num(q.quantity)} {q.unit}</strong>):<strong>{num(row.allocated)} {row.allocated!=null?row.unit:''}</strong>}<small>{t('On this shipment · allocated','Në këtë dërgesë · e ndarë')}{row.loaded!=null?` · ${t('Loaded','Ngarkuar')}: ${num(row.loaded)} ${row.unit}`:''}</small></div>
      <div className="cargo-order-quantity"><span>{t('Ordered','Porositur')}: {num(row.ordered)} {row.ordered!=null?row.order_unit:''}</span><span>{t('PO received','Pranuar nga porosia')}: {num(row.received)} {row.received!=null?row.order_unit:''}</span></div>
      <span className="cargo-status" data-state={row.status}>{t({ordered:'Ordered',in_transit:'In transit',partially_received:'Partially received',received:'Received'}[row.status],{ordered:'Porositur',in_transit:'Në transport',partially_received:'Pranuar pjesërisht',received:'Pranuar'}[row.status])}</span>
      {row.other_shipments?.length>0&&<details className="cargo-splits"><summary>{t('Other shipment allocations','Ndarjet në dërgesa të tjera')}</summary>{row.other_shipments.map(s=><Link key={`${s.url}-${s.unit}`} to={s.url}>{s.reference} · {num(s.quantity)} {s.unit}</Link>)}{row.unallocated!=null&&<p>{t('PO not allocated to any shipment','Porosia e pandarë në dërgesa')}: {num(row.unallocated)} {row.order_unit}</p>}</details>}
     </article>)}</div>
     {group.receipts?.length>0&&<details className="cargo-receipts"><summary>{t('PO → shipment → receipt history','Porosia → dërgesa → historiku i pranimit')} · {group.receipts.length}</summary><p>{t('These receipts belong to the PO. Shipment-specific receiving attribution is not recorded.','Këto pranime i përkasin porosisë. Lidhja e pranimit me dërgesën konkrete nuk është regjistruar.')}</p>{group.receipts.map(r=><div key={r.url}><Link to={r.url}>{r.reference} ↗</Link> · {date(r.received_at)}{r.quantities.map(v=><small key={v.unit}>{t('Accepted','Pranuar')}: {num(v.accepted)} {v.unit} · {t('Damaged','Dëmtuar')}: {num(v.damaged)} {v.unit}</small>)}</div>)}</details>}
    </section>)}
    {!groups.length&&<p>{query?t('No cargo matches this search.','Nuk ka ngarkesë që përputhet me kërkimin.'):t('No purchase order or cargo allocation is linked yet.','Nuk është lidhur ende porosi blerjeje ose ndarje ngarkese.')}</p>}
   </>}
  </section>
  <section className="cargo-impact"><header className="cargo-section-header"><h3>{t('Expected Stock Impact & Delay Risk','Ndikimi në stok dhe rreziku i vonesës')}</h3><Link to={`/shipments/my-shipments?view=intelligence&shipment=${shipment.id}`}>{t('Review impact','Rishiko ndikimin')} ↗</Link></header>
   {error?<p role="alert">{error}</p>:!intelligence?<p role="status">{t('Loading inventory evidence…','Duke ngarkuar të dhënat e inventarit…')}</p>:intelligence.pending?<p>{t('No evaluated inventory impact yet. Open the review to evaluate this shipment.','Ndikimi në inventar nuk është vlerësuar ende. Hap rishikimin për vlerësim.')}</p>:impact?.restricted?<p>{t('Inventory permission required.','Kërkohet leja e inventarit.')}</p>:<>
    {intelligence.stale&&<p className="cargo-warning">{t('Evidence is stale. Review updated evidence before acting.','Të dhënat janë të vjetruara. Rishiko përditësimet para veprimit.')}</p>}
    <p>{impact?.exposed_products??0} {t('products may be exposed before arrival.','produkte mund të ekspozohen para mbërritjes.')}</p>
<div className="cargo-impact-grid">{impact?.products?.map(p=><article key={`${p.product.id}-${p.warehouse?.id||0}`}><Link to={`/inventory-intelligence?view=planning&product=${p.product.id}${p.warehouse?`&warehouse_id=${p.warehouse.id}`:''}`}>{p.product.name} ↗</Link><span className="cargo-status" data-state={p.exposed?'AT_RISK':'ON_TRACK'}>{p.exposed?t('At risk','Në rrezik'):t('No recorded exposure','Pa ekspozim të regjistruar')}</span><dl>{fact(t('Available to promise','Në dispozicion për premtim'),`${num(p.stock?.available_to_promise)} ${p.product.unit}`)}{fact(t('This shipment (remaining)','Kjo dërgesë (e mbetur)'),`${num(p.quantity)} ${p.product.unit}`)}{fact(t('Projected after receipt · forecast','Pas pranimit · parashikim'),projectedReceiptBalance(p)==null?'—':`${num(projectedReceiptBalance(p))} ${p.product.unit}`)}{fact(t('Potential stockout','Mungesa e mundshme'),date(p.requirement_date))}{fact(p.arrival_target==='warehouse'?t('Usable arrival','Mbërritja e përdorshme'):t('Port arrival · warehouse unknown','Mbërritja në port · depoja e panjohur'),date(p.arrival))}</dl>{p.warehouse_arrival_unknown&&<small>{t('Port ETA is not warehouse availability. Customs/inland timing is unknown.','ETA në port nuk është disponueshmëri në depo. Afati i doganës/transportit tokësor është i panjohur.')}</small>}</article>)}</div>
    {!impact?.products?.length&&<p>{t('No authoritative product impact is available.','Nuk ka ndikim të konfirmuar për produktet.')}</p>}
   </>}
  </section>
  <section className="cargo-progress"><h3>{t('Shipment progress','Ecuria e dërgesës')}</h3><ol>{logisticsProgress(shipment,intelligence?.evidence).map(s=><li key={s.key} data-state={s.state}><strong>{t(s.en,s.sq)}</strong><small>{t({completed:'Completed',current:'Current',upcoming:'Not yet confirmed',delayed:'Delayed'}[s.state],{completed:'Përfunduar',current:'Aktuale',upcoming:'Ende pa konfirmim',delayed:'Me vonesë'}[s.state])}</small>{s.date&&<time>{date(s.date)}</time>}</li>)}</ol></section>
  {cargo?.costs?.length>0&&<details className="cargo-costs"><summary>{t('Cost Details · posted landed costs','Detajet e kostos · kosto të postuara')}</summary>{cargo.costs.map((c,i)=><article key={i}><Link to={c.url}>{c.reference||c.type.replaceAll('_',' ')} ↗</Link> · {num(c.amount)} {c.currency}{c.allocations.map((a,j)=><p key={j}>{a.product} · {t('Allocation','Ndarja')}: {num(a.amount)} {c.currency} · {t('Purchase → final unit cost','Blerja → kostoja finale për njësi')}: {num(a.purchase_unit_cost)} → {num(a.final_unit_cost)}</p>)}</article>)}</details>}
 </section>
}
