import {useEffect,useRef,useState} from 'react'
import WorkflowGuide from './WorkflowGuide'
import {Link} from 'react-router-dom'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import {deliveryTrend} from './supplierEvidence'
import './SupplierIntelligence.css'

export default function SupplierIntelligence({suppliers,initialSupplier}) {
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en
 const permissions=useAuthStore(s=>s.permissions)
 const [supplier,setSupplier]=useState(initialSupplier||''),[product,setProduct]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[reason,setReason]=useState(''),[feedback,setFeedback]=useState({})
 const lock=useRef(false),request=useRef(0),loaded=useRef('')
 const [segment,setSegment]=useState({category_id:'',origin:'',destination:'',mode:''})
 const [visible,setVisible]=useState(25)
 const allowed=permissions.includes('supplier_performance.view')&&permissions.includes('purchase_orders.view')
 useEffect(()=>{if(initialSupplier)setSupplier(initialSupplier)},[initialSupplier])
 useEffect(()=>{const token=++request.current;if(!supplier||!allowed){setData(null);return}if(loaded.current!==supplier){setData(null);loaded.current=supplier}setError('');const query=new URLSearchParams(Object.entries({product_id:product,...segment}).filter(([,v])=>v));const load=()=>apiRequest(`/suppliers/${supplier}/intelligence?${query}`).then(r=>{if(token===request.current)setData(r)}).catch(e=>{if(token===request.current)setError(e.message)});load();const timer=setInterval(()=>{if(!document.hidden&&!lock.current)load()},60000);return()=>{++request.current;clearInterval(timer)}},[supplier,product,segment,revision,allowed])
 async function act(path,body={}) {if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const r=await apiRequest(path,{method:'POST',body:JSON.stringify(body)});setMessage(['insufficient_data','insufficient_new_outcomes'].includes(r.status)?t('Not enough new completed orders. Historical evidence remains available.','Nuk ka mjaft porosi të reja të përfunduara. Provat historike mbeten të disponueshme.'):t('Saved. Evidence refreshed.','U ruajt. Provat u përditësuan.'));setRevision(v=>v+1)}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 const n=v=>v==null?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:2}).format(v)
 const labels={high:t('High risk','Rrezik i lartë'),warning:t('Review timing','Rishiko afatin'),normal:t('No detected delay','Pa vonesë të zbuluar'),closed:t('Closed / inactive','Mbyllur / joaktive'),insufficient_data:t('Limited evidence','Prova të kufizuara'),unknown:t('Unknown cause','Shkak i panjohur'),preparation:t('Preparation','Përgatitja'),dispatch:t('Dispatch','Nisja'),transit:t('Transit','Transporti'),customs:t('Customs','Dogana'),local_transport:t('Local transport','Transporti lokal'),receiving:t('Receiving','Pranimi')}
 labels.origin_logistics=t('Origin logistics','Logjistika e nisjes')
 if(!allowed)return null
 const d=data?.distribution,products=[...new Set(data?.orders.flatMap(o=>o.lines.map(l=>l.product_id)).filter(Boolean)||[])],trend=deliveryTrend(data?.orders||[])
 return <section className="card supplier-intelligence" aria-labelledby="supplier-intelligence-title">
  <header><div><h2 id="supplier-intelligence-title">{t('Supplier Intelligence','Inteligjenca e furnitorëve')}</h2><p>{t('Delivery evidence and procurement decisions — no automatic purchasing.','Prova të dorëzimit dhe vendime të blerjes — pa blerje automatike.')}</p></div></header>
  <WorkflowGuide workflow="suppliers"/>
  <div className="si-controls"><label>{t('Supplier','Furnitori')}<select value={supplier} disabled={busy} onChange={e=>{setSupplier(e.target.value);setProduct('');setReason('');setFeedback({})}}><option value="">{t('Select supplier','Zgjidh furnitorin')}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   {!!supplier&&<label>{t('Product evidence / comparison','Provat / krahasimi sipas produktit')}<select value={product} disabled={busy} onChange={e=>setProduct(e.target.value)}><option value="">{t('All products','Të gjitha produktet')}</option>{products.map(id=><option key={id} value={id}>{data?.orders.flatMap(o=>o.lines).find(l=>l.product_id===id)?.product_name||`#${id}`}</option>)}</select></label>}
   {!!supplier&&<button disabled={busy} onClick={()=>act(`/suppliers/${supplier}/intelligence/refresh`)}>{busy?t('Working…','Duke punuar…'):t('Refresh delivery evidence','Përditëso provat e dorëzimit')}</button>}</div>
  {!!data&&<details><summary>{t('Segment delivery history','Filtro historinë e dorëzimeve')}</summary><div className="si-controls">{[['category_id',t('Category ID','ID e kategorisë'),[...new Set(data.orders.flatMap(o=>o.lines.map(l=>l.category_id)).filter(Boolean))]],['origin',t('Origin','Origjina'),[...new Set(data.orders.flatMap(o=>o.shipments.map(s=>s.origin_port)).filter(Boolean))]],['destination',t('Destination','Destinacioni'),[...new Set(data.orders.flatMap(o=>o.shipments.map(s=>s.destination_port)).filter(Boolean))]],['mode',t('Transport mode','Mënyra e transportit'),[...new Set(data.orders.flatMap(o=>o.shipments.map(s=>s.transport_mode)).filter(Boolean))]]].map(([key,label,options])=><label key={key}>{label}<select disabled={busy} value={segment[key]} onChange={e=>setSegment(v=>({...v,[key]:e.target.value}))}><option value="">{t('All','Të gjitha')}</option>{options.map(o=><option value={o} key={o}>{o}</option>)}</select></label>)}</div></details>}
  {error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status">{message}</p>}
  {supplier&&!data&&!error&&<p role="status">{t('Loading evidence…','Duke ngarkuar provat…')}</p>}
  {data&&<>
   <div className="si-metrics">{[[t('Completed orders','Porosi të përfunduara'),d.samples],[t('Median days','Ditët mediane'),d.median_days],[t('Historical range (days)','Intervali historik (ditë)'),`${n(d.p10_days)} – ${n(d.p90_days)}`],[t('On time %','Në kohë %'),d.on_time_percent],[t('Original promises known','Premtime fillestare të njohura'),d.promised_samples],[t('Orders with multiple receipts','Porosi me disa pranime'),d.partial_orders]].map(([label,value])=><article key={label}><span>{label}</span><strong>{typeof value==='string'?value:n(value)}</strong></article>)}</div>
   <p className="si-muted">{t('Ranges describe completed history, not guaranteed arrival or a calibrated probability. Incomplete orders are excluded. A delayed stage does not establish supplier fault.','Intervalet përshkruajnë historinë e përfunduar, jo mbërritje të garantuar ose probabilitet të kalibruar. Porositë e papërfunduara përjashtohen. Një fazë e vonuar nuk përcakton fajin e furnitorit.')}</p>
   {trend.rows.length>1&&<figure className="si-trend"><figcaption>{t('Last completed deliveries — days from order to full receipt','Dorëzimet e fundit të përfunduara — ditët nga porosia deri te pranimi i plotë')}</figcaption><svg viewBox="0 0 300 105" role="img" aria-label={t('Measured delivery lead-time trend','Trendi i matur i kohës së dorëzimit')}><path d="M10 10V90H290" fill="none" stroke="var(--border-color)"/><polyline points={trend.points} fill="none" stroke="#469ff5" strokeWidth="2"/>{trend.points.split(' ').map((point,i)=><circle key={i} cx={point.split(',')[0]} cy={point.split(',')[1]} r="2" fill="#469ff5"><title>{trend.rows[i].reference}: {trend.rows[i].lead_days} {t('days','ditë')}</title></circle>)}</svg><small>0 – {trend.maximum} {t('days','ditë')} · {trend.rows[0].completion_date} → {trend.rows.at(-1).completion_date}</small></figure>}
   {!d.eligible&&<p>{t('Too few completed orders for a reliable forecast. Record real receipts and original commitments.','Shumë pak porosi të përfunduara për parashikim të besueshëm. Regjistro pranimet reale dhe premtimet fillestare.')}</p>}
   <div className="si-table"><table><caption>{t('Promised, predicted and actual delivery','Dorëzimi i premtuar, parashikuar dhe real')}</caption><thead><tr>{[t('Order','Porosia'),t('Original / revised promise','Premtimi fillestar / ndryshuar'),t('Prediction / actual','Parashikimi / realja'),t('Risk / evidence','Rreziku / provat')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.orders.slice(0,visible).map(o=><tr key={o.order_id}><td><Link to={`/purchase-orders?po=${o.order_id}`}>{o.reference}</Link><small>{o.ordered_at||'—'} · {n(o.partial_receipt_count)} {t('receipts','pranime')}</small></td><td>{o.original_promise||t('Unknown','E panjohur')}<small>{o.current_promise||'—'}</small></td><td>{o.prediction?.value?.expected_date||'—'}<small>{o.completion_date||t('Not completed','E papërfunduar')} · {n(o.lead_days)} {t('days','ditë')}</small></td><td><span className={`si-badge si-${o.risk.risk}`}>{labels[o.risk.risk]}</span><small>{o.risk.causes.map(c=>labels[c]).join(', ')}</small><details><summary>{t('Evidence and actions','Provat dhe veprimet')}</summary>
    {!!o.risk.window&&<p>{t('Historical window','Intervali historik')}: {o.risk.window.from} – {o.risk.window.to}</p>}
    {o.risk.reasons.map((r,i)=><p key={i}>{r.code==='milestone_delay'?`${labels[o.risk.causes[0]]}: ${r.milestone.type.replaceAll('_',' ')} · ${r.milestone.planned.slice(0,10)}`:r.code==='shipment_eta_after_promise'?t('Recorded ETA is later than original promise','ETA e regjistruar është pas premtimit fillestar'):t('Recorded delivery commitment is overdue','Afati i regjistruar i dorëzimit ka kaluar')}</p>)}
    {o.lines.map((l,i)=><p key={i}><Link to={`/inventory-intelligence?product=${l.product_id}`}>{t('Review stockout exposure','Rishiko rrezikun e mungesës së stokut')} #{l.product_id}</Link> · {n(l.remaining)} {l.unit} {t('remaining','të mbetura')}</p>)}
    {o.shipments.map(s=><p key={s.id}><Link to={`/shipments/my-shipments?shipment=${s.id}`}>{s.tracking_number||`#${s.id}`}</Link></p>)}
    <p>{t('Recorded inspections / claims','Inspektime / ankesa të regjistruara')}: {o.inspections.length} / {o.claims.length}</p>
    {Object.entries(o.stages).map(([key,value])=><small key={key}>{({supplier_preparation_days:t('Preparation','Përgatitja'),transit_days:t('Transit','Transporti'),customs_days:t('Customs','Dogana'),local_receiving_days:t('Local transport + receiving','Transporti lokal + pranimi')})[key]}: {n(value)} {t('days','ditë')}</small>)}
    {!!o.revisions.length&&<p>{t('Recorded promise revisions','Ndryshimet e regjistruara të premtimit')}: {o.revisions.map(r=>`${r.old||'—'} → ${r.new||'—'}`).join('; ')}</p>}
    {o.risk_id&&data.can_feedback&&<div className="si-feedback"><label>{t('Decision note','Shënimi i vendimit')}<input maxLength={1000} value={feedback[o.order_id]||''} onChange={e=>setFeedback(v=>({...v,[o.order_id]:e.target.value}))}/></label>{[['accepted',t('Review / accept advice','Rishiko / prano këshillën')],['modified',t('Modify approach','Ndrysho qasjen')],['dismissed',t('Dismiss','Refuzo')]].map(([decision,label])=><button key={decision} disabled={busy||(feedback[o.order_id]||'').trim().length<3} onClick={()=>act(`/supplier-intelligence/risks/${o.risk_id}/feedback`,{decision,note:feedback[o.order_id]})}>{label}</button>)}</div>}
    {o.feedback.map((f,i)=><p key={i}>{({accepted:t('Accepted','Pranuar'),modified:t('Modified','Ndryshuar'),dismissed:t('Dismissed','Refuzuar')})[f.decision]} · {f.at.slice(0,10)} · {f.note}{f.outcome?.completion_after_decision&&<small>{t('Subsequent receipt, not proof of decision impact','Pranim pasues, jo provë e ndikimit të vendimit')}: {f.outcome.completion_after_decision}</small>}</p>)}
   </details></td></tr>)}</tbody></table></div>
   {data.orders.length>visible&&<button onClick={()=>setVisible(v=>v+25)}>{t('Show more orders','Shfaq më shumë porosi')}</button>}
   {!!data.comparison.length&&<section><h3>{t('Existing supplier alternatives','Alternativat ekzistuese të furnitorëve')}</h3><p>{t('Compare the same inventory unit. Different currencies are not ranked. Quality and coverage must be considered with price.','Krahasoni të njëjtën njësi inventari. Monedhat e ndryshme nuk renditen. Cilësia dhe mbulimi duhen konsideruar bashkë me çmimin.')}</p><div className="si-metrics">{data.comparison.map(c=><article key={c.supplier_id}><Link to={`/suppliers?supplier=${c.supplier_id}`}>{c.name}</Link><strong>{n(c.purchase_price)} {c.currency}</strong><span>{t('Median / samples','Mediana / mostra')}: {n(c.delivery.median_days)} / {c.delivery.samples}</span><span>{t('Catalogue lead days','Ditët sipas katalogut')}: {n(c.usual_lead_time_days)}</span><span>{t('Minimum / pack size','Minimumi / madhësia e pakos')}: {n(c.minimum_order_quantity)} / {n(c.pack_size)}</span><span>{t('Quality inspections / acceptance %','Inspektime të cilësisë / pranimi %')}: {n(c.quality?.inspections)} / {n(c.quality?.acceptance_percent)}</span><span>{t('Defect % / claims','Defekte % / ankesa')}: {n(c.quality?.defect_rate)} / {n(c.quality?.claim_count)}</span></article>)}</div></section>}
   <details><summary>{t('Forecast performance and model review','Performanca e parashikimit dhe rishikimi i modelit')}</summary><p>{data.coverage.ml_eligible} {t('completed orders with usable decision-time features. Accuracy below uses only outcomes recorded after prediction.','porosi të përfunduara me të dhëna të përdorshme nga koha e vendimit. Saktësia më poshtë përdor vetëm rezultate të regjistruara pas parashikimit.')}</p>
    <p>{t('Model health','Shëndeti i modelit')}: {({insufficient_evidence:t('More completed outcomes needed','Nevojiten më shumë rezultate të përfunduara'),review_required:t('Review model — recent errors exceed baseline','Rishiko modelin — gabimet e fundit tejkalojnë bazën'),measured:t('Measured outcomes available','Rezultatet e matura janë të disponueshme')})[data.health?.state]}</p>
    {!Object.keys(data.performance).length&&<p>{t('No completed prospective predictions to score yet.','Ende nuk ka parashikime me rezultate të përfunduara për vlerësim.')}</p>}
    {Object.entries(data.performance).map(([version,p])=><p key={version}>{version.slice(0,12)} · {p.orders} {t('orders','porosi')} · MAE {n(p.mae_days)} / {t('baseline','baza')} {n(p.baseline_mae_days)} {t('days','ditë')}</p>)}
    {data.can_manage&&<><button disabled={busy} onClick={()=>act(`/suppliers/${supplier}/intelligence/train`)}>{t('Prepare candidate from recorded history','Përgatit kandidat nga historia e regjistruar')}</button><label>{t('Model decision reason','Arsyeja e vendimit për modelin')}<input maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}
    {data.models.map(m=><article className="si-model" key={m.id}><strong>{m.version.slice(0,8)} · {({candidate:t('Candidate','Kandidat'),active:t('Active','Aktiv'),archived:t('Archived','Arkivuar'),superseded:t('Previous','I mëparshëm')})[m.status]}</strong><p>{t('Historical holdout, not production accuracy','Validim historik, jo saktësi reale e përdorimit')}: MAE {n(m.metrics?.mae)} / {t('baseline','baza')} {n(m.comparison?.baseline?.mae)} · {n(m.metrics?.samples)} {t('orders','porosi')}</p>{m.status==='candidate'&&!m.gate.eligible&&<p>{t('Not eligible: insufficient evidence, improvement, or a changed champion.','Jo i përshtatshëm: prova ose përmirësim i pamjaftueshëm, ose modeli aktiv ka ndryshuar.')}</p>}{data.can_manage&&['candidate','superseded'].includes(m.status)&&<button disabled={busy||reason.trim().length<3||(m.status==='candidate'&&!m.gate.eligible)} onClick={()=>act(`/supplier-intelligence/models/${m.id}/${m.status==='candidate'?'promote':'rollback'}`,{reason,expected_production_version:data.active_version})}>{m.status==='candidate'?t('Approve model','Mirato modelin'):t('Restore previous model','Rikthe modelin e mëparshëm')}</button>}</article>)}
    {data.decisions.map(d=><p key={d.id}>{d.created_at?.slice(0,10)} · {d.reason}</p>)}
   </details>
  </>}
 </section>
}
