import {useEffect,useState} from 'react'
import {useAuthStore} from '../store/authStore'
import {useTranslation} from '../hooks/useTranslation'
import {apiRequest} from '../api/client'
export default function TaskManagement({tasks,onChanged}){
  const permissions=useAuthStore(s=>s.permissions),canManage=permissions.includes('tasks.manage'),canAssign=permissions.includes('tasks.assign'),{language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en
  const [selected,setSelected]=useState(null),[users,setUsers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState('')
  useEffect(()=>{if(!canAssign)return;let active=true;apiRequest('/task-assignees').then(x=>active&&setUsers(x)).catch(()=>{});return()=>{active=false}},[canAssign])
  const eligible=tasks.filter(x=>x.can_complete)
  if(!eligible.length)return null
  const save=async(status)=>{if(busy)return;setBusy(true);setError('');try{const data=canManage?{title:selected.title,description:selected.description,priority:selected.priority,due_at:selected.due_at || null}:{};if(canAssign){data.assigned_user_id=selected.assigned_user_id || null;data.assigned_role=selected.assigned_role || null}if(status){data.status=status;data.outcome_note=note}await apiRequest(`/operational-tasks/${selected.id}`,{method:'PATCH',body:JSON.stringify(data)});await onChanged();setSelected(null);setNote('')}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <details className="auto-panel"><summary>{t('Manage task / record outcome','Menaxho detyrën / regjistro rezultatin')}</summary><label>{t('Choose task','Zgjidh detyrën')}<select value={selected?.id || ''} onChange={e=>{setSelected(eligible.find(x=>x.id===Number(e.target.value)) || null);setNote('')}}><option value="">{t('Select…','Zgjidh…')}</option>{eligible.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{selected&&<>{canManage&&<><label>{t('Title','Titulli')}<input value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></label><label>{t('Instructions','Udhëzime')}<textarea value={selected.description || ''} onChange={e=>setSelected({...selected,description:e.target.value})}/></label><label>{t('Due date','Afati')}<input type="date" value={selected.due_at?.slice(0,10)||''} onChange={e=>setSelected({...selected,due_at:e.target.value})}/></label></>}{canAssign&&<><label>{t('Responsible user','Përdoruesi përgjegjës')}<select value={selected.assigned_user_id || ''} onChange={e=>setSelected({...selected,assigned_user_id:e.target.value?Number(e.target.value):null})}><option value="">{t('No specific user','Pa përdorues të caktuar')}</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>{t('Responsible role','Roli përgjegjës')}<select value={selected.assigned_role || ''} onChange={e=>setSelected({...selected,assigned_role:e.target.value || null})}><option value="">—</option><option value="admin">{t('Administrator','Administratori')}</option><option value="manager">{t('Manager','Menaxheri')}</option><option value="staff">{t('Staff','Stafi')}</option></select></label></>}<label>{t('Outcome note','Shënim mbi rezultatin')}<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="auto-buttons">{canManage&&<button disabled={busy} onClick={()=>save()}>{t('Save changes','Ruaj ndryshimet')}</button>}<button disabled={busy} onClick={()=>save('completed')}>{t('Complete with note','Përfundo me shënim')}</button><button disabled={busy} onClick={()=>save('cancelled')}>{t('Cancel with reason','Anulo me arsyetim')}</button></div></>}{error&&<p role="alert" className="page-error">{error}</p>}</details>
}
