import {test,expect} from '@playwright/test'
import {mkdirSync,writeFileSync} from 'node:fs'
import path from 'node:path'
test.use({actionTimeout:20000})
test.setTimeout(180000)
const output=path.resolve('../output/pm4')
const api=(page,url)=>page.evaluate(async url=>{const {apiRequest}=await import('/src/api/client.js');return apiRequest(url)},url)
const prefs=(page,theme,language)=>page.evaluate(async values=>{const {useSettingsStore}=await import('/src/store/settingsStore.js');await useSettingsStore.getState().savePreferences(values)},{theme,language})
async function login(page,email='owner@aims-demo.test'){
  await page.goto('/login')
  await page.locator('#email-address').fill(email)
  await page.locator('input[type=password]').fill('AimsDemo.Test.2026!')
  await page.locator('button[type=submit]').click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await prefs(page,'light','en')
}
test('PM4 populated owner workflow: menus, protected forms, sticky customization, count and Orders',async({page})=>{
  mkdirSync(output,{recursive:true})
  const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message))
  await login(page)
  const saved=await api(page,'/settings/workspace')
  try{
    await page.evaluate(async()=>{
      const {widgetCatalog}=await import('/src/config/dashboardWidgets.js')
      const {useWorkspaceStore}=await import('/src/store/workspaceStore.js')
      await useWorkspaceStore.getState().save('dashboard',{version:1,widgets:widgetCatalog.slice(0,18).map((w,position)=>({id:w.id,size:w.defaultSize,settings:w.settings,position}))})
    })
    await page.reload()
    await expect(page.locator('[data-refresh-state]')).toHaveAttribute('data-refresh-state','healthy')
    await page.getByRole('button',{name:'Customize Dashboard',exact:true}).click()
    const toolbar=page.getByRole('region',{name:'Dashboard editing'})
    await expect(toolbar.getByRole('button',{name:'Save',exact:true})).toBeDisabled()
    await page.locator('[data-widget]').last().scrollIntoViewIfNeeded()
    let box=await toolbar.boundingBox();expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThan(900)
    await page.getByRole('button',{name:/Move earlier:/}).last().click()
    const size=page.locator('.widget-settings select').first()
    await size.selectOption(await size.locator('option').last().getAttribute('value'))
    const widgetCount=await page.locator('[data-widget]').count()
    await toolbar.getByRole('button',{name:'Add Widget',exact:true}).click()
    await page.locator('.widget-library-items button:not([disabled])').first().click()
    await expect(page.locator('[data-widget]')).toHaveCount(widgetCount+1)
    await page.getByRole('dialog',{name:'Widget library'}).getByRole('button',{name:'Close',exact:true}).click()
    await toolbar.getByRole('button',{name:'Cancel',exact:true}).click()
    await expect(page.getByRole('dialog',{name:'Discard dashboard changes?'})).toBeVisible()
    await page.getByRole('button',{name:'Keep Editing',exact:true}).click()
    await toolbar.getByRole('button',{name:'Save',exact:true}).click()
    await expect(toolbar).toHaveCount(0)
    const menu=page.locator('details.widget-menu').first()
    await menu.locator('summary').click();await expect(menu).toHaveAttribute('open','')
    await page.getByRole('heading',{name:'Dashboard',exact:true}).click();await expect(menu).not.toHaveAttribute('open','')
    await menu.locator('summary').click();await page.keyboard.press('Escape');await expect(menu).not.toHaveAttribute('open','')
    await expect(menu.locator('summary')).toBeFocused()
    await menu.locator('summary').click()
    const another=page.locator('details.widget-menu').nth(1)
    await another.locator('summary').click()
    await expect(menu).not.toHaveAttribute('open','')
    await page.keyboard.press('Escape')
    await page.getByRole('button',{name:'Customize Navigation',exact:true}).click()
    const navigation=page.getByRole('dialog',{name:'Customize Navigation',exact:true})
    await navigation.locator('.navigation-editor-row').last().scrollIntoViewIfNeeded()
    box=await navigation.locator('.navigation-sticky-toolbar').boundingBox();expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThan(900)
    await navigation.locator('button[aria-label^="Pin:"]').first().click()
    await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Discard navigation changes?'})).toBeVisible()
    await page.getByRole('button',{name:'Keep Editing',exact:true}).click()
    await navigation.getByRole('button',{name:'Save',exact:true}).click();await expect(navigation).toHaveCount(0)
    checks.push('healthy refresh, long dashboard/navigation sticky controls, add/move/resize/save/discard, outside/Escape menus')

    await page.goto('/action-center')
    await page.getByRole('button',{name:'New task',exact:true}).click()
    await page.getByLabel('Title',{exact:true}).fill('PM4 unsaved request')
    await page.locator('.workspace-modal-overlay').click({position:{x:2,y:2}})
    await expect(page.getByRole('dialog',{name:'Discard unsaved changes?'})).toBeVisible()
    await page.getByRole('button',{name:'Keep Editing',exact:true}).click()
    await expect(page.getByLabel('Title',{exact:true})).toHaveValue('PM4 unsaved request')
    await page.keyboard.press('Escape');await page.getByRole('button',{name:'Discard',exact:true}).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('button',{name:'New task',exact:true})).toBeFocused()
    expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
    checks.push('unsaved modal outside-click and Escape preserve form, scroll restored')

    await page.goto('/operations-center?tab=counts')
    const newCount=page.locator('.ops-layout aside form')
    await expect(newCount.getByLabel(/^Warehouse/)).toBeVisible()
    const warehouse=(await api(page,'/warehouses')).find(w=>w.is_active)
    await newCount.getByLabel(/^Warehouse/).selectOption(String(warehouse.id))
    await newCount.getByLabel(/^Notes/).fill('PM4 browser lifecycle review')
    const created=page.waitForResponse(r=>r.url().includes('/api/inventory-counts')&&r.request().method()==='POST')
    await newCount.getByRole('button',{name:'Create',exact:true}).click()
    const count=await (await created).json()
    await page.getByRole('button').filter({hasText:count.count_number}).click()
    await page.getByLabel('Action reason',{exact:true}).fill('PM4 review complete; no count work needed')
    await page.getByRole('button',{name:'Cancel request',exact:true}).click()
    await expect(page.locator('.ops-panel').last()).toContainText('Stock-count request cancelled.')
    const cancelled=await api(page,`/inventory-counts/${count.id}`)
    expect(cancelled.status).toBe('cancelled');expect(cancelled.items.every(i=>!i.adjustment_movement_id)).toBe(true)
    checks.push('count created/cancelled; no adjustment movement; audit retained')
    await newCount.getByLabel(/^Notes/).fill('PM4 unused draft deletion')
    await newCount.getByLabel(/^Warehouse/).selectOption(String(warehouse.id))
    const draftResponse=page.waitForResponse(r=>r.url().includes('/api/inventory-counts')&&r.request().method()==='POST')
    await newCount.getByRole('button',{name:'Create',exact:true}).click()
    const draft=await (await draftResponse).json()
    await page.getByRole('button').filter({hasText:draft.count_number}).click()
    await page.getByRole('button',{name:'Delete Draft',exact:true}).click()
    const deletion=page.getByRole('dialog',{name:'Delete stock-count draft?'})
    await expect(deletion).toContainText('This cannot be undone.')
    await deletion.getByRole('button',{name:'Delete Draft',exact:true}).click()
    await expect(deletion).toHaveCount(0)
    await expect(page.locator('.ops-panel').last()).toContainText('Stock-count draft deleted.')
    checks.push('unused count draft deletion requires explicit domain confirmation')

    const orders=await api(page,'/order-hub?per_page=5')
    await page.goto(`/order-hub?intake=${orders.data[0].id}`)
    await expect(page.locator('.hub-overview')).toContainText(orders.data[0].order.order_number)
    for(const fact of ['Customer','Order date','Order value','Paid','Remaining order value','Fulfillment','Warehouse'])await expect(page.locator('.hub-overview')).toContainText(fact)
    await expect(page.locator('.order-connections')).toContainText('Next action')
    await expect(page.locator('.hub-overview')).not.toContainText('Not assigned yet')
    await page.screenshot({path:path.join(output,'order-summary.png'),animations:'disabled'})
    checks.push('Order summary/payment/warehouse/status explanation and contextual next action')
    await page.getByRole('button',{name:'New order',exact:true}).click()
    await page.getByLabel('Walk-in / contact name',{exact:true}).fill('PM4 unsaved buyer')
    page.once('dialog',dialog=>dialog.dismiss())
    await page.getByRole('button',{name:'Back to inbox',exact:true}).click()
    await expect(page.getByLabel('Walk-in / contact name',{exact:true})).toHaveValue('PM4 unsaved buyer')
    page.once('dialog',dialog=>dialog.accept())
    await page.locator('.order-entry').getByRole('button',{name:'Cancel',exact:true}).click()
    await expect(page.locator('.order-entry')).toHaveCount(0)
    checks.push('Order draft discard guard preserves unsaved customer/input')

    for(const width of [1920,1366,1024,768,390]){
      await page.setViewportSize({width,height:900})
      await prefs(page,width>=1024?'light':'dark',width===768?'sq':'en')
      await page.goto('/dashboard')
      await page.getByRole('button',{name:width===768?'Personalizo panelin':'Customize Dashboard',exact:true}).click()
      await page.locator('[data-widget]').last().scrollIntoViewIfNeeded()
      const bar=page.locator('.workspace-sticky-toolbar'),rect=await bar.boundingBox()
      expect(rect.y).toBeGreaterThanOrEqual(0);expect(rect.y+rect.height).toBeLessThan(900)
      expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+2)
      await page.screenshot({path:path.join(output,`sticky-${width}.png`),animations:'disabled'})
      await bar.getByRole('button',{name:width===768?'Anulo':'Cancel',exact:true}).click()
      if(await page.locator('.mobile-menu-toggle').isVisible())await page.locator('.mobile-menu-toggle').click()
      await page.locator('.sidebar-customize').click()
      const nav=page.locator('.workspace-modal').filter({has:page.locator('.navigation-sticky-toolbar')})
      await nav.locator('.navigation-editor-row').last().scrollIntoViewIfNeeded()
      const navBar=nav.locator('.navigation-sticky-toolbar'),navRect=await navBar.boundingBox()
      expect(navRect.y).toBeGreaterThanOrEqual(0);expect(navRect.y+navRect.height).toBeLessThan(900)
      await expect(navBar.getByRole('button',{name:width===768?'Ruaj':'Save',exact:true})).toBeDisabled()
      await page.screenshot({path:path.join(output,`navigation-sticky-${width}.png`),animations:'disabled'})
      await navBar.getByRole('button',{name:width===768?'Anulo':'Cancel',exact:true}).click()
    }
    checks.push('1920/1366/1024/768/390 sticky controls, English/Albanian, light/dark')
    await prefs(page,'light','en')
    for(const route of ['/intelligence-assistant','/inventory-intelligence','/suppliers?view=intelligence','/financial-intelligence','/customer-sales-intelligence','/inventory-intelligence?view=decisions','/decision-learning','/supply-optimizer','/strategic-simulation']){
      await page.goto(route);await expect(page.locator('#workspace-main h1')).toBeVisible()
      await expect(page.locator('#workspace-main')).not.toContainText('Something went wrong')
    }
    checks.push('all nine existing intelligence surfaces render; advanced disclosures retained')
  }finally{
    await prefs(page,'light','en')
    await page.evaluate(async saved=>{const {apiRequest}=await import('/src/api/client.js');const current=await apiRequest('/settings/workspace');await apiRequest('/settings/workspace',{method:'PUT',body:JSON.stringify({revision:current.revision,dashboard:saved.dashboard,navigation:saved.navigation})})},saved)
    writeFileSync(path.join(output,'verification.json'),JSON.stringify({checks,errors},null,2))
  }
  expect(errors).toEqual([])
})
test('PM4 financial forms ignore outside click and protect unsaved Escape',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await login(page)
  await page.goto('/finance')
  await page.getByRole('button',{name:/^New expense/}).first().click()
  const expense=page.locator('.finance-modal')
  await expense.getByLabel(/^Notes/).fill('PM4 protected financial draft')
  await page.locator('.finance-modal-layer').click({position:{x:2,y:2}})
  await expect(expense.getByLabel(/^Notes/)).toHaveValue('PM4 protected financial draft')
  page.once('dialog',dialog=>dialog.dismiss());await page.keyboard.press('Escape')
  await expect(expense).toBeVisible()
  page.once('dialog',dialog=>dialog.accept());await page.keyboard.press('Escape')
  await expect(expense).toHaveCount(0)
  await page.goto('/invoices')
  await page.getByRole('button',{name:'New invoice',exact:true}).first().click()
  const invoice=page.locator('.invoice-dialog'),date=invoice.locator('input[type=date]').first()
  await date.fill('2026-10-10')
  await page.locator('.invoice-overlay').click({position:{x:2,y:2}})
  await expect(date).toHaveValue('2026-10-10')
  page.once('dialog',dialog=>dialog.dismiss());await page.keyboard.press('Escape')
  await expect(invoice).toBeVisible()
  page.once('dialog',dialog=>dialog.accept());await page.keyboard.press('Escape')
  await expect(invoice).toHaveCount(0)
  expect(errors).toEqual([])
})
test('PM4 unsaved Order browser Back preserves the draft',async({page})=>{
  await login(page)
  await page.goto('/order-hub')
  await page.getByRole('button',{name:'New order',exact:true}).click()
  await page.getByLabel('Walk-in / contact name',{exact:true}).fill('PM4 protected browser history')
  page.once('dialog',dialog=>dialog.dismiss())
  await page.goBack()
  await expect(page).toHaveURL(/new=1/)
  await expect(page.getByLabel('Walk-in / contact name',{exact:true})).toHaveValue('PM4 protected browser history')
  page.once('dialog',dialog=>dialog.accept())
  await page.locator('.order-entry').getByRole('button',{name:'Cancel',exact:true}).click()
})
for(const [profile,routes]of [
  ['manager',['/dashboard','/order-hub','/operations-center?tab=counts','/inventory-intelligence']],
  ['sales',['/dashboard','/order-hub','/daily-sales']],
  ['warehouse',['/dashboard','/warehouse-mobile','/operations-center?tab=counts']],
  ['purchasing',['/dashboard','/purchase-orders','/suppliers']],
])test(`PM4 ${profile} employee workspace`,async({page})=>{
  await login(page,`${profile}@aims-demo.test`)
  for(const route of routes){await page.goto(route);await expect(page.locator('#workspace-main h1')).toBeVisible();await expect(page.locator('#workspace-main')).not.toContainText('Something went wrong')}
})
