import {test,expect} from '@playwright/test'
import {mkdirSync,writeFileSync} from 'node:fs'
import path from 'node:path'
const output=path.resolve('../output/pm5')
const api=(page,url)=>page.evaluate(async url=>{const {apiRequest}=await import('/src/api/client.js');return apiRequest(url)},url)
const measure=(page,url)=>page.evaluate(async url=>{const {apiRequest}=await import('/src/api/client.js');const start=performance.now(),data=await apiRequest(url);return {url,ms:Math.round(performance.now()-start),bytes:new TextEncoder().encode(JSON.stringify(data)).length,data}},url)
const prefs=(page,theme,language)=>page.evaluate(async values=>{const {useSettingsStore}=await import('/src/store/settingsStore.js');await useSettingsStore.getState().savePreferences(values)},{theme,language})
async function login(page,email='manager@aims-demo.test'){page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(20000);await page.goto('/login');await page.locator('#email-address').fill(email);await page.locator('input[type=password]').fill('AimsDemo.Test.2026!');await page.locator('button[type=submit]').click();await expect(page).toHaveURL(/dashboard$/);await expect(page.getByText(/SYNTHETIC \/ TEST DATA — isolated PM3 company|TË DHËNA SINTETIKE \/ TEST — kompani e izoluar PM3/)).toBeVisible()}
async function ready(page){await expect(page.locator('#workspace-main h1').first()).toBeVisible();await page.waitForLoadState('networkidle',{timeout:15000});await expect(page.locator('.shipments-intro')).toHaveCount(0)}
async function selectSearch(page,term){await page.locator('.global-search-trigger').click();await page.getByRole('combobox',{name:/Search AIMS|Kërko në AIMS/}).fill(term);await expect(page.locator('.command-result-copy').filter({hasText:term}).first()).toBeVisible()}
async function go(page,url,timings){const start=Date.now();await page.goto(url);await ready(page);timings.push({url,ms:Date.now()-start})}

test('PM5 new manager: connected workflow, search, list memory, assistant and explicit workspace presets',async({page})=>{
 test.setTimeout(300000);mkdirSync(output,{recursive:true});const errors=[],timings=[];page.on('pageerror',e=>errors.push(e.message));await login(page);await prefs(page,'light','en')
 const original=await page.evaluate(async()=>{const {apiRequest}=await import('/src/api/client.js');const {defaultDashboard}=await import('/src/config/dashboardWidgets.js');const {defaultNavigation}=await import('/src/config/workspaceNavigation.js');const saved=await apiRequest('/settings/workspace'),user=await apiRequest('/me');return {...saved,dashboard:saved.dashboard||defaultDashboard(user.permissions,user.role),navigation:saved.navigation||defaultNavigation(user.role)}})
 try{
  await ready(page);await selectSearch(page,'Milano 01');await expect(page.locator('.command-result-copy').first()).toContainText('SKU');await page.getByRole('combobox',{name:'Search AIMS',exact:true}).press('Enter');await expect(page.locator('.product-detail-modal')).toBeVisible();await expect(page.locator('.product-detail-modal')).toContainText('Milano 01')
  await page.getByRole('link',{name:/^Find storage location/}).click();await expect(page).toHaveURL(/warehouse-operations\?product=/);await expect(page.locator('.stock-locator-panel')).toBeVisible();await expect(page.locator('.stock-locator-overview')).toBeVisible();await expect(page.locator('.stock-locator-overview')).toContainText('Milano 01')
  await go(page,'/products',timings);const search=page.getByPlaceholder('Search by name or SKU');await search.fill('Milano');await expect(page.locator('.product-table tbody tr').first()).toContainText('Milano');await page.locator('.product-table tbody tr').first().getByRole('button',{name:'View',exact:true}).click();await expect(page.locator('.product-detail-modal')).toBeVisible();await page.getByRole('button',{name:'Close product details',exact:true}).click();await expect(page.locator('.product-detail-modal')).toHaveCount(0);expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
  await go(page,'/customer-debts',timings);await page.locator('tbody tr').first().getByRole('button',{name:/Open sheet/}).click();await expect(page).toHaveURL(/customer=/);await expect(page.locator('#workspace-main')).toContainText('Record payment');await page.goBack();await expect(page).not.toHaveURL(/customer=/)
  await go(page,'/order-hub',timings);await page.getByRole('button',{name:'New order',exact:true}).click();await expect(page.locator('.order-entry')).toBeVisible();await page.locator('.order-entry').getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.hub-orders-table tbody tr').first()).toBeVisible();await page.getByRole('button',{name:'Open order',exact:true}).first().click();await expect(page.locator('.order-hub')).toContainText('Products & availability');await page.getByRole('button',{name:'Back to inbox',exact:true}).click()
  await go(page,'/suppliers',timings);await expect(page.locator('tbody tr').first()).toBeVisible()
  await go(page,'/purchase-orders',timings);await page.locator('tbody tr').first().getByRole('button',{name:/View details/}).click();await expect(page).toHaveURL(/po=/);await expect(page.locator('#workspace-main')).toContainText('Supplier');await page.goBack();await expect(page).not.toHaveURL(/po=/)
  const shipments=await api(page,'/shipments'),shipment=shipments.find(s=>s.tracking_number==='PM4-CARGO-REVIEW-TEST');expect(shipment).toBeTruthy();await go(page,'/shipments/my-shipments?shipment='+shipment.id,timings);await expect(page.locator('.cargo-product')).toHaveCount(3);await expect(page.locator('.cargo-po-group')).toHaveCount(3)
  await go(page,'/action-center?view=mine&status=active',timings);await expect(page.locator('.auto-filterbar select').first()).toHaveValue('mine')
  await go(page,'/intelligence-assistant',timings);const askStarted=Date.now();const reply=page.waitForResponse(r=>r.url().includes('/intelligence-assistant/ask')&&r.request().method()==='POST');await page.getByRole('textbox',{name:'Question for AIMS'}).fill('Which products may run out?');await page.getByRole('button',{name:'Send question',exact:true}).click();const answerResponse=await reply;expect(answerResponse.status()).toBe(200);timings.push({url:'/intelligence-assistant/ask',ms:Date.now()-askStarted,bytes:new TextEncoder().encode(JSON.stringify(await answerResponse.json())).length});await expect(page.locator('.assistant-working')).toHaveCount(0);await expect(page.locator('.assistant-message').last()).toContainText('Sources & freshness');await expect(page.locator('.assistant-suggestions button')).toHaveCount(4)
  await go(page,'/inventory-intelligence?view=decisions',timings);await expect(page.locator('#workspace-main')).toContainText(/Decision|decision/)
  await go(page,'/dashboard',timings);await page.getByRole('button',{name:'Customize Dashboard',exact:true}).click();await page.getByRole('combobox',{name:'Work profile',exact:true}).selectOption('manager');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByText('Dashboard saved.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Customize Navigation',exact:true}).click();await page.getByRole('combobox',{name:'Work profile',exact:true}).selectOption('manager');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'manager-workspace.png')})
  await go(page,'/products',timings);await expect(page.getByPlaceholder('Search by name or SKU')).toHaveValue('Milano');await search.fill('')
  expect(errors).toEqual([])
 }finally{await page.evaluate(async original=>{const {apiRequest}=await import('/src/api/client.js');const current=await apiRequest('/settings/workspace');await apiRequest('/settings/workspace',{method:'PUT',body:JSON.stringify({revision:current.revision,dashboard:original.dashboard,navigation:original.navigation})})},original);await prefs(page,'light','en')}
 writeFileSync(path.join(output,'new-user.json'),JSON.stringify({timings,errors},null,2))
})

test('PM5 owner and employee role workspaces, responsive bilingual light/dark review',async({browser})=>{
 test.setTimeout(600000);mkdirSync(output,{recursive:true});const report=[]
 const workflows={owner:['/dashboard','/action-center','/customer-debts','/finance'],warehouse:['/warehouse-mobile','/warehouse-operations?tab=transfers','/operations-center?tab=counts','/action-center'],sales:['/products','/order-hub','/daily-sales','/customer-debts'],purchasing:['/inventory-intelligence?view=planning','/procurement','/purchase-orders','/shipments/my-shipments'],finance:['/customer-debts','/finance','/money-accounts','/accounting']}
 for(const [profile,urls] of Object.entries(workflows)){
  const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page,profile==='owner'?'owner@aims-demo.test':'manager@aims-demo.test');const original=await page.evaluate(async()=>{const {apiRequest}=await import('/src/api/client.js');const {defaultDashboard}=await import('/src/config/dashboardWidgets.js');const {defaultNavigation}=await import('/src/config/workspaceNavigation.js');const saved=await apiRequest('/settings/workspace'),user=await apiRequest('/me');return {...saved,dashboard:saved.dashboard||defaultDashboard(user.permissions,user.role),navigation:saved.navigation||defaultNavigation(user.role)}})
  try{await prefs(page,'light','en');await page.getByRole('button',{name:'Customize Dashboard',exact:true}).click();await page.getByRole('combobox',{name:'Work profile',exact:true}).selectOption(profile);const save=page.getByRole('button',{name:'Save',exact:true});if(await save.isEnabled())await save.click();else await page.getByRole('button',{name:'Cancel',exact:true}).click()
   for(const url of urls){console.log('PM5 profile',profile,url);const start=Date.now();await page.goto(url);await ready(page);await expect(page.locator('#workspace-main')).not.toContainText(/SQLSTATE|PDOException|You do not have permission|Access denied/);report.push({profile,url,width:1366,ms:Date.now()-start})}
   for(const [width,theme,language] of [[1366,'dark','sq'],[768,'light','en'],[390,'dark','en'],[390,'light','sq']]){await page.setViewportSize({width,height:768});await prefs(page,theme,language);for(const url of urls){console.log('PM5 responsive',profile,width,theme,language,url);await page.goto(url);await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),profile+' '+url+' '+width).toBe(true)}await page.screenshot({path:path.join(output,`${profile}-${width}-${theme}-${language}.png`)})}
   expect(errors).toEqual([])
  }finally{await page.evaluate(async original=>{const {apiRequest}=await import('/src/api/client.js');const current=await apiRequest('/settings/workspace');await apiRequest('/settings/workspace',{method:'PUT',body:JSON.stringify({revision:current.revision,dashboard:original.dashboard})})},original);await prefs(page,'light','en');await context.close()}
 }
 writeFileSync(path.join(output,'roles.json'),JSON.stringify(report,null,2))
})

test('PM5 working-session history, record search and representative payload measurements',async({page})=>{
 test.setTimeout(180000);mkdirSync(output,{recursive:true});const errors=[],measurements=[],searches=[];page.on('pageerror',e=>errors.push(e.message));await login(page);await prefs(page,'light','en');await page.setViewportSize({width:1366,height:768})
 await page.goto('/products');await ready(page);await page.getByPlaceholder('Search by name or SKU').fill('');await page.locator('.pagination').getByRole('button',{name:'Next',exact:true}).click();await expect(page.locator('.pagination')).toContainText('Page 2')
 const last=page.locator('.product-table tbody tr').last();await last.scrollIntoViewIfNeeded();const before=await page.evaluate(()=>window.scrollY);expect(before).toBeGreaterThan(100);await last.getByRole('button',{name:'View',exact:true}).click();await expect(page.locator('.product-detail-modal')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.product-detail-modal')).toHaveCount(0);expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe('hidden')
 await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search AIMS',exact:true}).fill('Action Center');await page.getByRole('option').filter({hasText:'Action Center'}).first().click();await expect(page).toHaveURL(/action-center$/);await page.goBack();await expect(page).toHaveURL(/products/);await expect(page.locator('.pagination')).toContainText('Page 2');await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(before-50)
 const products=await api(page,'/products?per_page=50'),product=products.data.find(p=>p.name==='Milano 01');expect(product).toBeTruthy()
 const customers=await api(page,'/customers'),suppliers=await api(page,'/suppliers'),orders=await api(page,'/order-hub?per_page=5'),pos=await api(page,'/purchase-orders?per_page=5'),shipments=await api(page,'/shipments'),documents=await api(page,'/documents');const rows=x=>Array.isArray(x)?x:x.data
 for(const [term,type] of [[product.name,'products'],['Milano','products'],[product.sku,'products'],[rows(customers)[0].name,'customers'],[rows(suppliers)[0].name,'suppliers'],[pos.data[0].po_number,'purchase_orders'],[orders.data[0].order.order_number,'order_hub'],[shipments[0].tracking_number,'shipments'],[shipments.find(s=>s.vessel_name).vessel_name,'shipments'],[rows(documents)[0].title,'documents'],['stockout','decisions'],['Milnao 01','products']]){
  const result=await measure(page,'/search?q='+encodeURIComponent(term));expect(result.data[type]?.length,term+' '+type).toBeGreaterThan(0);expect(result.data[type].every(r=>r.title&&r.url.startsWith('/'))).toBe(true);searches.push({term,type,ms:result.ms,bytes:result.bytes});if(term==='Milnao 01')expect(result.data.products.some(p=>p.similar_match)).toBe(true)
 }
 for(const url of ['/products/'+product.id,'/order-hub?per_page=20','/shipments/'+shipments[0].id,'/action-center?status=active','/financial-intelligence?horizon=30','/financial-intelligence?horizon=30&summary_only=1','/customer-sales-intelligence','/customer-sales-intelligence?summary_only=1']){const result=await measure(page,url);measurements.push({url,ms:result.ms,bytes:result.bytes})}
 const size=url=>measurements.find(r=>r.url===url).bytes;expect(size('/financial-intelligence?horizon=30&summary_only=1')).toBeLessThan(size('/financial-intelligence?horizon=30'));expect(size('/customer-sales-intelligence?summary_only=1')).toBeLessThan(size('/customer-sales-intelligence'))
 expect(errors).toEqual([]);writeFileSync(path.join(output,'performance.json'),JSON.stringify({environment:'Local Vite development server, isolated PM3 SQLite company; not a production benchmark',measurements,searches,scrollRestored:true,errors},null,2))
})

test('PM5 warehouse staff navigation and profiles never grant unauthorized permissions',async({page})=>{
 await login(page,'warehouse@aims-demo.test');await prefs(page,'dark','en');await page.goto('/warehouse-mobile');await ready(page);const user=await api(page,'/me');expect(user.role).toBe('staff')
 const result=await page.evaluate(async user=>{const {profileDashboard,profileNavigation}=await import('/src/config/workProfiles.js');const {widgetById}=await import('/src/config/dashboardWidgets.js');const {canOpenPage}=await import('/src/config/pageAccess.js');const {permittedNavigation}=await import('/src/config/navigation.js');const dashboard=profileDashboard('finance',user.permissions),navigation=profileNavigation('finance',user.permissions,user.role,false),items=permittedNavigation(user.permissions,false,user.role).flatMap(g=>g.items);return {widgetsAllowed:dashboard.widgets.every(w=>widgetById[w.id].permissions.every(p=>user.permissions.includes(p))),navigationAllowed:navigation.favorites.every(id=>items.some(i=>i.id===id)&&canOpenPage(items.find(i=>i.id===id).path,user.permissions))}},user)
 expect(result.widgetsAllowed).toBe(true);expect(result.navigationAllowed).toBe(true);await expect(page.locator('#workspace-main')).not.toContainText(/SQLSTATE|PDOException/);await prefs(page,'light','en')
})

test('PM5 inline validation, PO creation continuity and readable financial/cargo facts',async({page})=>{
 test.setTimeout(180000);mkdirSync(output,{recursive:true});await login(page);await prefs(page,'light','en');await page.setViewportSize({width:1366,height:768});await page.goto('/products');await ready(page);await page.getByRole('button',{name:'Add product',exact:true}).click();const form=page.locator('.product-form');await form.getByRole('button',{name:'Save product',exact:true}).click();expect(await form.evaluate(f=>f.checkValidity())).toBe(false)
 const category=form.locator('[name=category_id]');await category.selectOption(await category.locator('option').nth(1).getAttribute('value'));await form.locator('[name=name]').fill('PM5 rejected product — no data written');await form.locator('[name=sku]').fill('EXISTING-SKU');await form.locator('[name=quantity]').fill('1');await form.locator('[name=min_quantity]').fill('1');await form.locator('[name=purchase_price]').fill('2');await form.locator('[name=selling_price]').fill('3');expect(await form.evaluate(f=>f.checkValidity())).toBe(true)
 let rejected=0;await page.route('**/api/products',async route=>{if(route.request().method()==='POST'){rejected++;await route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({message:'This SKU is already used by another product.',errors:{sku:['This SKU is already used by another product.']}})})}else await route.continue()});await form.getByRole('button',{name:'Save product',exact:true}).click();await expect(form.locator('[name=sku]')).toHaveAttribute('aria-invalid','true');await expect(form.locator('[name=sku]')).toBeFocused();await expect(form.locator('[name=sku]').locator('..')).toContainText('already used');expect(rejected).toBe(1);await expect(page.locator('.success-animation')).toHaveCount(0);await form.locator('[name=sku]').fill('CORRECTED-SKU');await expect(form.locator('[name=sku]')).not.toHaveAttribute('aria-invalid','true');await page.unroute('**/api/products');page.on('dialog',dialog=>dialog.accept())
 const po=await api(page,'/purchase-orders?per_page=1');await page.goto('/purchase-orders?po='+po.data[0].id);await ready(page);await page.getByRole('button',{name:'New purchase order',exact:true}).click();await expect(page).toHaveURL(/new=1/);await expect(page).not.toHaveURL(/po=/);await expect(page.locator('form.form-grid')).toBeVisible()
 for(const [width,theme,language] of [[1366,'light','en'],[1366,'dark','sq'],[390,'dark','en'],[390,'light','sq']]){
  await page.setViewportSize({width,height:768});await prefs(page,theme,language);await page.goto('/finance');await ready(page);const metrics=page.locator('.finance-metric strong');expect(await metrics.count()).toBeGreaterThan(0);expect(await metrics.evaluateAll(nodes=>nodes.every(n=>getComputedStyle(n).textOverflow!=='ellipsis'&&n.scrollWidth<=n.clientWidth+1))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:path.join(output,`finance-facts-${width}-${theme}-${language}.png`)});await page.goto('/shipments/my-shipments?shipment=69');await ready(page);await expect(page.locator('.shipment-key-facts')).not.toContainText(/2026-10-|10\/19\/2026/);await page.screenshot({path:path.join(output,`cargo-facts-${width}-${theme}-${language}.png`)})
 }
 await prefs(page,'light','en')
})
