<?php

namespace App\Services;

use App\Models\{AccountingAccount,AccountingException,AccountingPeriod,AccountingPostingMapping,JournalEntry};
use App\Support\{CompanyCurrency,Money};
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\{Auth,DB};
use Illuminate\Validation\ValidationException;

class AccountingService
{
    public const DEFAULTS = [
        ['100','Assets','asset',null,'debit',false,true,null],
        ['1000','Cash','asset','100','debit',true,true,'operating'], ['1010','Bank','asset','100','debit',true,true,'operating'],
        ['1100','Accounts Receivable','asset','100','debit',true,true,'operating'], ['1150','Recoverable Input VAT','asset','100','debit',true,true,'operating'], ['1200','Inventory','asset','100','debit',true,true,'operating'],
        ['1300','Supplier Advances','asset','100','debit',true,true,'operating'], ['1400','Inventory Received Not Invoiced','asset','100','debit',true,true,'operating'],
        ['200','Liabilities','liability',null,'credit',false,true,null], ['2000','Accounts Payable','liability','200','credit',true,true,'operating'],
        ['2100','Goods Receipt Clearing','liability','200','credit',true,true,'operating'], ['2150','Output VAT Payable','liability','200','credit',true,true,'operating'], ['2200','Customer Advances','liability','200','credit',true,true,'operating'],
        ['300','Equity','equity',null,'credit',false,true,null], ['3000','Owner Equity','equity','300','credit',true,true,'financing'], ['3100','Retained Earnings','equity','300','credit',true,true,'financing'],
        ['400','Revenue','revenue',null,'credit',false,true,null], ['4000','Sales Revenue','revenue','400','credit',true,true,'operating'], ['4200','Realized FX Gain','revenue','400','credit',true,true,'operating'],
        ['500','Cost of Sales','expense',null,'debit',false,true,null], ['5000','Cost of Goods Sold','expense','500','debit',true,true,'operating'],
        ['600','Operating Expenses','expense',null,'debit',false,true,null], ['6000','Operating Expense','expense','600','debit',true,true,'operating'],
        ['6100','Inventory Adjustments','expense','600','debit',true,true,'operating'], ['6200','Inventory Loss and Damage','expense','600','debit',true,true,'operating'],
        ['6300','Realized FX Loss','expense','600','debit',true,true,'operating'], ['6400','Freight and Handling','expense','600','debit',true,true,'operating'],
    ];
    public const MAPPINGS=['cash'=>'1000','bank'=>'1010','accounts_receivable'=>'1100','input_vat'=>'1150','inventory'=>'1200','supplier_advances'=>'1300','inventory_received_not_invoiced'=>'1400','accounts_payable'=>'2000','goods_receipt_clearing'=>'2100','output_vat'=>'2150','customer_advances'=>'2200','equity'=>'3000','retained_earnings'=>'3100','sales_revenue'=>'4000','fx_gain'=>'4200','cost_of_goods_sold'=>'5000','operating_expense'=>'6000','inventory_adjustments'=>'6100','inventory_loss_damage'=>'6200','fx_loss'=>'6300','freight'=>'6400','customs'=>'1200','landed_cost'=>'1200'];

    public function initialize(): array
    {
        $company=(int)Auth::user()->company_id;
        return DB::transaction(function()use($company){
            $byCode=AccountingAccount::query()->get()->keyBy('code');
            foreach(self::DEFAULTS as [$code,$name,$type,$parentCode,$normal,$posting,$system,$cashFlow]){
                $parent=$parentCode?$byCode->get($parentCode):null;
                $account=AccountingAccount::query()->firstOrCreate(['company_id'=>$company,'code'=>$code],['name'=>$name,'type'=>$type,'parent_id'=>$parent?->id,'normal_balance'=>$normal,'is_posting'=>$posting,'is_system'=>$system,'is_active'=>true,'cash_flow_class'=>$cashFlow]);
                $byCode->put($code,$account);
            }
            foreach(self::MAPPINGS as $key=>$code){$account=$byCode->get($code);AccountingPostingMapping::query()->firstOrCreate(['company_id'=>$company,'mapping_key'=>$key],['accounting_account_id'=>$account->id,'updated_by'=>Auth::id()]);}
            return ['accounts'=>$this->accounts(),'mappings'=>$this->mappings()];
        });
    }

    public function accounts(): array{return AccountingAccount::query()->with('parent:id,code,name')->withCount('lines')->orderBy('code')->get()->all();}
    public function mappings(): array{return AccountingPostingMapping::query()->with('account:id,code,name,type,is_posting,is_active')->orderBy('mapping_key')->get()->all();}
    public function saveAccount(array $data,?AccountingAccount $account=null):AccountingAccount
    {
        $account??=new AccountingAccount(['company_id'=>Auth::user()->company_id]);
        if(!empty($data['parent_id'])){$parent=AccountingAccount::query()->findOrFail($data['parent_id']);if(!$parent||($account->exists&&$parent->id===$account->id))throw ValidationException::withMessages(['parent_id'=>['Choose a valid parent account.']]);}
        if(($data['is_posting']??$account->is_posting)===false&&$account->exists&&$account->lines()->exists())throw ValidationException::withMessages(['is_posting'=>['An account with journal history must remain a posting account.']]);
        $account->fill($data);$account->company_id=Auth::user()->company_id;$account->save();return $account->fresh('parent');
    }
    public function archiveAccount(AccountingAccount $account):AccountingAccount{if($account->children()->where('is_active',true)->exists())throw ValidationException::withMessages(['account'=>['Deactivate active subaccounts first.']]);$account->update(['is_active'=>false]);return $account;}
    public function saveMappings(array $rows):array{$before=$this->mappings();DB::transaction(function()use($rows){foreach($rows as $key=>$id){$a=AccountingAccount::query()->findOrFail($id);if(!$a->is_active||!$a->is_posting)throw ValidationException::withMessages([$key=>['Mapping requires an active posting account.']]);AccountingPostingMapping::query()->updateOrCreate(['company_id'=>Auth::user()->company_id,'mapping_key'=>$key],['accounting_account_id'=>$a->id,'updated_by'=>Auth::id()]);}});$after=$this->mappings();$this->audit('accounting.posting_mappings.updated',Auth::user()->company,$before,$after);return $after;}
    public function controls():array{$company=Auth::user()->company;return ['supplier_match_quantity_tolerance'=>(string)($company->supplier_match_quantity_tolerance??config('procurement.matching.quantity_tolerance',.001)),'supplier_match_price_tolerance'=>(string)($company->supplier_match_price_tolerance??config('procurement.matching.unit_price_tolerance',.02)),'supplier_match_tax_tolerance'=>(string)($company->supplier_match_tax_tolerance??config('procurement.matching.tax_tolerance',.02))];}
    public function saveControls(array $data):array{$company=Auth::user()->company;$before=$this->controls();$company->update($data);$after=$this->controls();$this->audit('accounting.controls.updated',$company,$before,$after);return $after;}

    public function periods():array{return AccountingPeriod::query()->orderByDesc('starts_at')->get()->all();}
    public function savePeriod(array $data):AccountingPeriod
    {if(AccountingPeriod::query()->where(fn($q)=>$q->whereBetween('starts_at',[$data['starts_at'],$data['ends_at']])->orWhereBetween('ends_at',[$data['starts_at'],$data['ends_at']])->orWhere(fn($x)=>$x->where('starts_at','<=',$data['starts_at'])->where('ends_at','>=',$data['ends_at'])))->exists())throw ValidationException::withMessages(['period'=>['Accounting periods cannot overlap.']]);return AccountingPeriod::create([...$data,'company_id'=>Auth::user()->company_id,'status'=>'open']);}
    public function setPeriodStatus(AccountingPeriod $period,string $status,string $reason):AccountingPeriod
    {if(!in_array($status,['open','soft_closed','closed'],true))throw ValidationException::withMessages(['status'=>['Invalid period status.']]);if($status==='closed'&&$period->status!=='closed'){$readiness=$this->periodReadiness($period);if(!$readiness['ready_to_close'])throw ValidationException::withMessages(['period'=>['This period is not ready to close: '.collect($readiness['checks'])->where('passed',false)->pluck('label')->implode('; ')]]);}$old=$period->status;$values=['status'=>$status,'change_reason'=>$reason];if($status==='closed')$values+=['closed_by'=>Auth::id(),'closed_at'=>now()];if($old==='closed'&&$status!=='closed')$values+=['reopened_by'=>Auth::id(),'reopened_at'=>now()];$period->update($values);$this->audit('accounting.period.'.$status,$period,['from'=>$old],['to'=>$status,'reason'=>$reason]);$event=$status==='closed'?'accounting.period_closed':(($old==='closed'&&$status!=='closed')?'accounting.period_reopened':null);if($event)app(BusinessEventService::class)->record($event,$period,$period->name,['from'=>$old,'to'=>$status,'reason'=>$reason],"accounting-period:{$period->id}:{$status}:".$period->updated_at?->timestamp);return $period;}
    public function periodReadiness(AccountingPeriod $period):array
    {
        $this->scanIntegrity();$to=$period->ends_at->toDateString();$trial=$this->trialBalance(null,$to);$balance=$this->balanceSheet($to);$reconciliation=$this->reconciliation(false);
        $drafts=JournalEntry::query()->where('status','draft')->whereBetween('posting_date',[$period->starts_at->toDateString(),$to])->count();
        $bankRows=\App\Models\BankStatementRow::query()->whereIn('status',['unmatched','suggested'])->whereDate('transaction_date','<=',$to)->count();
        $pendingLanded=\App\Models\LandedCost::query()->where('status','draft')->whereDate('created_at','<=',$to)->count();
        $critical=AccountingException::query()->where('status','open')->where('severity','critical')->count();
        $checks=[
            ['code'=>'trial_balance','label'=>'Trial Balance is balanced','passed'=>$trial['balanced'],'count'=>$trial['balanced']?0:1],
            ['code'=>'balance_sheet','label'=>'Balance Sheet is balanced','passed'=>$balance['balanced'],'count'=>$balance['balanced']?0:1],
            ['code'=>'control_accounts','label'=>'AR, AP, advances, inventory and cash/bank reconcile','passed'=>$reconciliation['all_reconciled'],'count'=>collect($reconciliation['rows'])->where('reconciled',false)->count()],
            ['code'=>'bank_rows','label'=>'No unreconciled bank statement rows','passed'=>$bankRows===0,'count'=>$bankRows],
            ['code'=>'draft_journals','label'=>'No open draft journals in the period','passed'=>$drafts===0,'count'=>$drafts],
            ['code'=>'landed_costs','label'=>'No pending landed costs through period end','passed'=>$pendingLanded===0,'count'=>$pendingLanded],
            ['code'=>'critical_exceptions','label'=>'No open critical accounting exceptions','passed'=>$critical===0,'count'=>$critical],
        ];
        return ['period'=>$period,'checked_at'=>now()->toIso8601String(),'ready_to_close'=>collect($checks)->every(fn($check)=>$check['passed']),'checks'=>$checks,'reconciliation'=>$reconciliation,'retained_earnings_policy'=>'Current earnings are derived dynamically from posted revenue and expense journals. No closing journal is generated, preventing duplicate closes.'];
    }
    public function assertDateOpen(string $date,bool $allowSoft=false):void
    {$start=Auth::user()?->company?->accounting_start_date;if($start&&$date<$start->toDateString())throw ValidationException::withMessages(['posting_date'=>["The posting date is before the company accounting start date {$start->toDateString()}."]]);$period=AccountingPeriod::query()->whereDate('starts_at','<=',$date)->whereDate('ends_at','>=',$date)->first();if($period?->status==='closed'||($period?->status==='soft_closed'&&!$allowSoft))throw ValidationException::withMessages(['posting_date'=>["Accounting period {$period->name} is {$period->status}; posting is locked."]]);}

    public function journals(array $filters=[]){return JournalEntry::query()->with(['lines.account:id,code,name,type','creator:id,name','poster:id,name'])->when($filters['from']??null,fn($q,$v)=>$q->whereDate('posting_date','>=',$v))->when($filters['to']??null,fn($q,$v)=>$q->whereDate('posting_date','<=',$v))->when($filters['status']??null,fn($q,$v)=>$q->where('status',$v))->latest('posting_date')->latest('id')->paginate($filters['per_page']??50);}
    public function createDraft(array $data):JournalEntry
    {return DB::transaction(function()use($data){$this->assertDateOpen($data['posting_date'],true);$company=(int)Auth::user()->company_id;$module=$data['source_module']??'manual';$sourceKey=$data['source_key']??('manual:'.(string)\Illuminate\Support\Str::uuid());if($existing=JournalEntry::query()->where('source_module',$module)->where('source_key',$sourceKey)->first())return $existing->load('lines.account');$currency=strtoupper($data['currency']??CompanyCurrency::forCompanyId($company));$rate=Money::normalizeDecimal($data['exchange_rate']??1,8);$entry=JournalEntry::create(['company_id'=>$company,'journal_number'=>$this->nextNumber(),'posting_date'=>$data['posting_date'],'reference_number'=>$data['reference_number']??null,'description'=>$data['description'],'source_module'=>$module,'source_type'=>$data['source_type']??null,'source_id'=>$data['source_id']??null,'source_key'=>$sourceKey,'currency'=>$currency,'exchange_rate'=>$rate,'status'=>'draft','created_by'=>Auth::id()]);foreach($data['lines'] as $i=>$line){$account=AccountingAccount::query()->findOrFail($line['accounting_account_id']);if(!$account->is_active||!$account->is_posting)throw ValidationException::withMessages(["lines.$i.accounting_account_id"=>['Choose an active posting account.']]);$debit=Money::normalize($line['debit']??0);$credit=Money::normalize($line['credit']??0);if((Money::compare($debit,'0')>0)===(Money::compare($credit,'0')>0))throw ValidationException::withMessages(["lines.$i"=>['Each journal line must contain either a debit or a credit.']]);$entry->lines()->create([...$line,'line_number'=>$i+1,'debit'=>$debit,'credit'=>$credit,'foreign_debit'=>Money::normalize($line['foreign_debit']??0),'foreign_credit'=>Money::normalize($line['foreign_credit']??0)]);}$entry=$this->recalculate($entry);if($module==='manual')$this->audit('accounting.manual_journal.created',$entry,null,['journal_number'=>$entry->journal_number,'debit'=>$entry->total_debit,'credit'=>$entry->total_credit]);return $entry;});}
    public function post(JournalEntry $entry):JournalEntry
    {return DB::transaction(function()use($entry){$entry=JournalEntry::query()->lockForUpdate()->findOrFail($entry->id);if($entry->status==='posted')return $entry->load('lines.account');if($entry->status!=='draft')throw ValidationException::withMessages(['journal'=>['Only a draft journal can be posted.']]);$this->assertDateOpen($entry->posting_date->toDateString());$entry=$this->recalculate($entry);if(Money::compare($entry->total_debit,'0')<=0||Money::compare($entry->total_debit,$entry->total_credit)!==0)throw ValidationException::withMessages(['journal'=>['Total debits must equal total credits and be greater than zero.']]);$entry->update(['status'=>'posted','posted_by'=>Auth::id(),'posted_at'=>now()]);$this->audit('accounting.journal_posted',$entry,null,['debit'=>$entry->total_debit,'credit'=>$entry->total_credit]);app(BusinessEventService::class)->record('accounting.journal_posted',$entry,$entry->journal_number,['source_module'=>$entry->source_module,'source_type'=>$entry->source_type,'source_id'=>$entry->source_id,'total'=>$entry->total_debit],"journal:{$entry->id}:posted");return $entry->fresh(['lines.account','poster:id,name']);});}
    public function createAndPost(array $data):JournalEntry{return $this->post($this->createDraft($data));}
    public function reverse(JournalEntry $entry,string $date,string $reason):JournalEntry
    {return DB::transaction(function()use($entry,$date,$reason){$entry=JournalEntry::query()->with('lines')->lockForUpdate()->findOrFail($entry->id);if($entry->status==='reversed')return $entry->reversal;if($entry->status!=='posted')throw ValidationException::withMessages(['journal'=>['Only a posted journal can be reversed.']]);$reverse=$this->createDraft(['posting_date'=>$date,'reference_number'=>'REV-'.$entry->journal_number,'description'=>'Reversal: '.$reason,'source_module'=>'accounting','source_type'=>'journal_entry','source_id'=>$entry->id,'source_key'=>'reversal:'.$entry->id,'currency'=>$entry->currency,'exchange_rate'=>$entry->exchange_rate,'lines'=>$entry->lines->map(fn($l)=>['accounting_account_id'=>$l->accounting_account_id,'description'=>'Reversal: '.$l->description,'debit'=>$l->credit,'credit'=>$l->debit,'foreign_debit'=>$l->foreign_credit,'foreign_credit'=>$l->foreign_debit])->all()]);$reverse->update(['reversal_of_id'=>$entry->id]);$reverse=$this->post($reverse);$entry->update(['status'=>'reversed','reversed_by'=>Auth::id(),'reversed_at'=>now(),'reversal_reason'=>$reason]);$this->audit('accounting.journal_reversed',$entry,null,['reversal_journal_id'=>$reverse->id,'reason'=>$reason]);app(BusinessEventService::class)->record('accounting.journal_reversed',$entry,$entry->journal_number,['reversal_journal_id'=>$reverse->id,'reason'=>$reason],"journal:{$entry->id}:reversed");return $reverse->fresh('lines.account');});}

    public function postMapped(string $module,string $sourceType,int $sourceId,string $sourceKey,string $date,string $description,array $lines,string $currency='EUR',mixed $rate=1):JournalEntry
    {$required=collect($lines)->pluck('mapping')->filter()->unique();$configured=AccountingPostingMapping::query()->whereIn('mapping_key',$required)->count();if($configured<$required->count())$this->initialize();$mapped=collect($this->mappings())->keyBy('mapping_key');$resolved=array_map(function($line)use($mapped){if(isset($line['accounting_account_id']))return $line;$mapping=$mapped->get($line['mapping']);if(!$mapping)throw ValidationException::withMessages(['mapping'=>["Posting account '{$line['mapping']}' is not configured."]]);unset($line['mapping']);return ['accounting_account_id'=>$mapping->accounting_account_id,...$line];},$lines);return $this->createAndPost(['posting_date'=>$date,'description'=>$description,'source_module'=>$module,'source_type'=>$sourceType,'source_id'=>$sourceId,'source_key'=>$sourceKey,'currency'=>$currency,'exchange_rate'=>$rate,'lines'=>$resolved]);}

    public function postCustomerDebt(\App\Models\CustomerDebtTransaction $transaction):JournalEntry
    {
        $amount=Money::normalize($transaction->amount);$lines=[];
        if(in_array($transaction->type,['debt_added','positive_adjustment','opening_balance'],true)){
            $creditApplied=Money::normalize(data_get($transaction->metadata,'credit_applied','0'));$receivable=Money::subtract($amount,$creditApplied);
            if(Money::compare($receivable,'0')>0)$lines[]=['mapping'=>'accounts_receivable','debit'=>$receivable];
            if(Money::compare($creditApplied,'0')>0)$lines[]=['mapping'=>'customer_advances','debit'=>$creditApplied];
            $lines[]=['mapping'=>$transaction->type==='opening_balance'?'equity':'sales_revenue','credit'=>$amount];
        }elseif($transaction->source==='customer_return'){
            $debtApplied=Money::minimum($amount,$transaction->balance_before);$advance=Money::subtract($amount,$debtApplied);
            $lines[]=['mapping'=>'sales_revenue','debit'=>$amount];
            if(Money::compare($debtApplied,'0')>0)$lines[]=['mapping'=>'accounts_receivable','credit'=>$debtApplied];
            if(Money::compare($advance,'0')>0)$lines[]=['mapping'=>'customer_advances','credit'=>$advance];
        }else{
            $debtApplied=Money::minimum($amount,$transaction->balance_before);$advance=Money::subtract($amount,$debtApplied);
            $settlement=['mapping'=>in_array($transaction->payment_method,['bank','bank_transfer','card','cheque'],true)?'bank':'cash','debit'=>$amount];if($transaction->financial_account_id){$financial=\App\Models\FinancialAccount::query()->findOrFail($transaction->financial_account_id);$settlement=['accounting_account_id'=>$this->ensureFinancialAccount($financial)->id,'debit'=>$amount];}$lines[]=$settlement;
            if(Money::compare($debtApplied,'0')>0)$lines[]=['mapping'=>'accounts_receivable','credit'=>$debtApplied];
            if(Money::compare($advance,'0')>0)$lines[]=['mapping'=>'customer_advances','credit'=>$advance];
        }
        $entry=$this->postMapped('customer_credit','customer_debt_transaction',$transaction->id,'customer-debt:'.$transaction->id,$transaction->transaction_date->toDateString(),'Customer ledger · '.($transaction->note?:$transaction->type),$lines,CompanyCurrency::forCompanyId($transaction->company_id),1);if($transaction->financial_account_transaction_id)\App\Models\FinancialAccountTransaction::query()->whereKey($transaction->financial_account_transaction_id)->update(['journal_entry_id'=>$entry->id]);if(in_array($transaction->type,['debt_added','positive_adjustment','opening_balance'],true))app(BusinessEventService::class)->record('customer.receivable_recognized',$transaction,$transaction->reference_number,['journal_entry_id'=>$entry->id,'amount'=>$amount],"customer-receivable:{$transaction->id}");return $entry;
    }
    public function postExpense(\App\Models\Expense $expense):JournalEntry
    {
        $gross=Money::normalize(abs((float)$expense->gross_amount_eur));$deductible=Money::normalize(abs((float)$expense->deductible_vat_amount_eur));$expenseAmount=Money::subtract($gross,$deductible);$creditNote=$expense->document_type==='credit_note';$lines=[];
        $expenseMapping=$expense->category==='inventory'&&$expense->purchase_order_id?'goods_receipt_clearing':'operating_expense';
        if(Money::compare($expenseAmount,'0')>0)$lines[]=['mapping'=>$expenseMapping,$creditNote?'credit':'debit'=>$expenseAmount];
        if(Money::compare($deductible,'0')>0)$lines[]=['mapping'=>'input_vat',$creditNote?'credit':'debit'=>$deductible];
        $lines[]=['mapping'=>'accounts_payable',$creditNote?'debit':'credit'=>$gross];
        $entry=$this->postMapped('supplier_accounting','expense',$expense->id,'expense:'.$expense->id,$expense->invoice_date->toDateString(),'Supplier document '.$expense->document_number,$lines,$expense->currency,$expense->exchange_rate);if(!$creditNote)app(BusinessEventService::class)->record('supplier.payable_recognized',$expense,$expense->document_number,['journal_entry_id'=>$entry->id,'amount'=>$gross],"supplier-payable:{$expense->id}");return $entry;
    }
    public function postExpensePayment(\App\Models\ExpensePayment $payment):JournalEntry
    {$expense=$payment->expense;$cash=Money::normalize($payment->amount_eur);$carrying=Money::multiply($payment->amount,$expense->exchange_rate?:1);$settlement=['mapping'=>in_array($payment->payment_method,['bank','bank_transfer','card','cheque'],true)?'bank':'cash','credit'=>$cash];if($payment->financial_account_id){$financial=\App\Models\FinancialAccount::query()->findOrFail($payment->financial_account_id);$settlement=['accounting_account_id'=>$this->ensureFinancialAccount($financial)->id,'credit'=>$cash];}$lines=[['mapping'=>'accounts_payable','debit'=>$carrying],$settlement];$difference=Money::subtract($cash,$carrying);if(Money::compare($difference,'0')>0)$lines[]=['mapping'=>'fx_loss','debit'=>$difference];elseif(Money::compare($difference,'0')<0)$lines[]=['mapping'=>'fx_gain','credit'=>Money::normalize(abs((float)$difference))];$entry=$this->postMapped('supplier_accounting','expense_payment',$payment->id,'expense-payment:'.$payment->id,$payment->payment_date->toDateString(),'Supplier payment '.$expense->document_number,$lines,$expense->currency,$payment->exchange_rate);if($payment->financial_account_transaction_id)\App\Models\FinancialAccountTransaction::query()->whereKey($payment->financial_account_transaction_id)->update(['journal_entry_id'=>$entry->id]);return $entry;}
    public function reverseSource(string $module,string $key,string $date,string $reason):?JournalEntry{$entry=JournalEntry::query()->where('source_module',$module)->where('source_key',$key)->first();return $entry&&$entry->status==='posted'?$this->reverse($entry,$date,$reason):null;}
    public function ensureFinancialAccount(\App\Models\FinancialAccount $financial):AccountingAccount
    {if($financial->accounting_account_id&&($existing=AccountingAccount::query()->find($financial->accounting_account_id)))return $existing;if(AccountingAccount::query()->doesntExist())$this->initialize();$parentCode=$financial->type==='bank'?'1010':'1000';$parent=AccountingAccount::query()->where('code',$parentCode)->firstOrFail();$account=AccountingAccount::query()->firstOrCreate(['company_id'=>$financial->company_id,'code'=>($financial->type==='bank'?'BANK-':'CASH-').$financial->id],['name'=>$financial->name,'type'=>'asset','parent_id'=>$parent->id,'normal_balance'=>'debit','is_posting'=>true,'is_system'=>true,'is_active'=>true,'cash_flow_class'=>'operating']);$financial->update(['accounting_account_id'=>$account->id]);return $account;}
    public function postFinancialTransfer(\App\Models\FinancialAccountTransfer $transfer,\App\Models\FinancialAccount $source,\App\Models\FinancialAccount $destination):?JournalEntry
    {$base=CompanyCurrency::forCompanyId($source->company_id);if($source->currency!==$base){$this->exception('unposted-financial-transfer:'.$transfer->id,'missing_fx_snapshot','critical','A foreign-currency account transfer needs an explicit base-currency exchange-rate snapshot before GL posting.',['financial_account_transfer_id'=>$transfer->id,'currency'=>$source->currency,'base_currency'=>$base]);return null;}$from=$this->ensureFinancialAccount($source);$to=$this->ensureFinancialAccount($destination);return $this->createAndPost(['posting_date'=>$transfer->transfer_date->toDateString(),'reference_number'=>$transfer->reference_number,'description'=>'Money transfer '.$source->name.' → '.$destination->name,'source_module'=>'banking','source_type'=>'financial_account_transfer','source_id'=>$transfer->id,'source_key'=>'financial-transfer:'.$transfer->id,'currency'=>$source->currency,'exchange_rate'=>1,'lines'=>[['accounting_account_id'=>$to->id,'debit'=>$transfer->amount],['accounting_account_id'=>$from->id,'credit'=>$transfer->amount]]]);}
    public function postFinancialOpening(\App\Models\FinancialAccount $financial):?JournalEntry
    {$amount=Money::normalize($financial->opening_balance);if(Money::compare($amount,'0')===0||!$financial->opening_date)return null;$base=CompanyCurrency::forCompanyId($financial->company_id);if($financial->currency!==$base){$this->exception('unposted-financial-opening:'.$financial->id,'missing_fx_snapshot','critical','A foreign-currency opening balance needs an exchange-rate snapshot.',['financial_account_id'=>$financial->id]);return null;}$account=$this->ensureFinancialAccount($financial);$equity=collect($this->mappings())->firstWhere('mapping_key','equity');$positive=Money::compare($amount,'0')>0;$absolute=Money::normalize(abs((float)$amount));return $this->createAndPost(['posting_date'=>$financial->opening_date->toDateString(),'description'=>'Opening balance · '.$financial->name,'source_module'=>'opening','source_type'=>'financial_account','source_id'=>$financial->id,'source_key'=>'financial-opening:'.$financial->id,'currency'=>$base,'lines'=>[['accounting_account_id'=>$account->id,$positive?'debit':'credit'=>$absolute],['accounting_account_id'=>$equity->accounting_account_id,$positive?'credit':'debit'=>$absolute]]]);}

    public function postFinancialTransaction(\App\Models\FinancialAccountTransaction $transaction,?int $counterAccountId):?JournalEntry
    {
        if(!$counterAccountId){$this->exception('unclassified-financial-transaction:'.$transaction->id,'unclassified_bank_transaction','warning','A cash/bank transaction is not classified to a General Ledger counter-account.',['source_type'=>'financial_account_transaction','source_id'=>$transaction->id,'amount'=>$transaction->amount,'currency'=>$transaction->currency]);return null;}
        $financial=$transaction->account;$base=CompanyCurrency::forCompanyId($transaction->company_id);$rate=$transaction->currency===$base?'1':$transaction->exchange_rate;if(!$rate){$this->exception('unposted-financial-transaction:'.$transaction->id,'missing_fx_snapshot','critical','A foreign-currency cash/bank transaction needs an exchange-rate snapshot.',['source_type'=>'financial_account_transaction','source_id'=>$transaction->id,'currency'=>$transaction->currency]);return null;}
        $cash=$this->ensureFinancialAccount($financial);$counter=AccountingAccount::query()->findOrFail($counterAccountId);if(!$counter->is_active||!$counter->is_posting)throw ValidationException::withMessages(['counter_accounting_account_id'=>['Choose an active posting account.']]);$amount=Money::multiply($transaction->amount,$rate);$in=in_array($transaction->type,['inflow','transfer_in','adjustment_in','refund_in'],true);$entry=$this->createAndPost(['posting_date'=>$transaction->transaction_date->toDateString(),'reference_number'=>$transaction->reference_number,'description'=>$transaction->description?:'Classified money-account transaction','source_module'=>'banking','source_type'=>'financial_account_transaction','source_id'=>$transaction->id,'source_key'=>'financial-transaction:'.$transaction->id,'currency'=>$transaction->currency,'exchange_rate'=>$rate,'lines'=>[['accounting_account_id'=>$cash->id,$in?'debit':'credit'=>$amount],['accounting_account_id'=>$counter->id,$in?'credit':'debit'=>$amount]]]);$transaction->update(['journal_entry_id'=>$entry->id]);$this->resolveException('unclassified-financial-transaction:'.$transaction->id);return $entry;
    }

    public function trialBalance(?string $from,?string $to):array
    {$to??=now()->toDateString();$accounts=AccountingAccount::query()->orderBy('code')->get();$rows=$accounts->map(function($a)use($from,$to){$base=$from?$a->lines()->whereHas('journalEntry',fn($q)=>$q->whereIn('status',['posted','reversed'])->whereDate('posting_date','<',$from))->selectRaw('COALESCE(SUM(debit),0) d,COALESCE(SUM(credit),0) c')->first():(object)['d'=>0,'c'=>0];$move=$a->lines()->whereHas('journalEntry',fn($q)=>$q->whereIn('status',['posted','reversed'])->when($from,fn($x)=>$x->whereDate('posting_date','>=',$from))->whereDate('posting_date','<=',$to))->selectRaw('COALESCE(SUM(debit),0) d,COALESCE(SUM(credit),0) c')->first();$opening=Money::subtract($base->d,$base->c);$closing=Money::add($opening,Money::subtract($move->d,$move->c));return ['id'=>$a->id,'code'=>$a->code,'name'=>$a->name,'type'=>$a->type,'parent_id'=>$a->parent_id,'opening_balance'=>$opening,'debit_movement'=>Money::normalize($move->d),'credit_movement'=>Money::normalize($move->c),'closing_balance'=>$closing];});$debit=Money::decimal($rows->sum(fn($r)=>Money::minor($r['debit_movement'])));$credit=Money::decimal($rows->sum(fn($r)=>Money::minor($r['credit_movement'])));return ['from'=>$from,'to'=>$to,'currency'=>CompanyCurrency::forCompanyId(Auth::user()->company_id),'rows'=>$rows,'total_debit'=>$debit,'total_credit'=>$credit,'balanced'=>Money::compare($debit,$credit)===0];}
    public function profitAndLoss(?string $from,?string $to):array{$tb=$this->trialBalance($from,$to);$rows=collect($tb['rows']);$revenue=$rows->filter(fn($r)=>$r['type']==='revenue'&&$r['code']!=='4200')->sum(fn($r)=>Money::minor($r['credit_movement'])-Money::minor($r['debit_movement']));$otherGains=$rows->where('code','4200')->sum(fn($r)=>Money::minor($r['credit_movement'])-Money::minor($r['debit_movement']));$cogs=$rows->filter(fn($r)=>str_starts_with($r['code'],'5'))->sum(fn($r)=>Money::minor($r['debit_movement'])-Money::minor($r['credit_movement']));$expense=$rows->filter(fn($r)=>$r['type']==='expense'&&!str_starts_with($r['code'],'5')&&$r['code']!=='6300')->sum(fn($r)=>Money::minor($r['debit_movement'])-Money::minor($r['credit_movement']));$otherLosses=$rows->where('code','6300')->sum(fn($r)=>Money::minor($r['debit_movement'])-Money::minor($r['credit_movement']));$operating=$revenue-$cogs-$expense;$other=$otherGains-$otherLosses;return ['from'=>$from,'to'=>$to,'revenue'=>Money::decimal($revenue),'cost_of_goods_sold'=>Money::decimal($cogs),'gross_profit'=>Money::decimal($revenue-$cogs),'operating_expenses'=>Money::decimal($expense),'operating_profit'=>Money::decimal($operating),'other_gains'=>Money::decimal($otherGains),'other_losses'=>Money::decimal($otherLosses),'other_gains_losses'=>Money::decimal($other),'net_profit'=>Money::decimal($operating+$other),'accounts'=>$rows->whereIn('type',['revenue','expense'])->values()];}
    public function balanceSheet(?string $to):array{$tb=$this->trialBalance(null,$to);$rows=collect($tb['rows']);$assets=$rows->where('type','asset')->sum(fn($r)=>Money::minor($r['closing_balance']));$liabilities=$rows->where('type','liability')->sum(fn($r)=>-Money::minor($r['closing_balance']));$equity=$rows->where('type','equity')->sum(fn($r)=>-Money::minor($r['closing_balance']));$pl=$this->profitAndLoss(null,$to);$earnings=Money::minor($pl['net_profit']);$difference=$assets-$liabilities-$equity-$earnings;return ['to'=>$to,'assets'=>Money::decimal($assets),'liabilities'=>Money::decimal($liabilities),'equity'=>Money::decimal($equity),'current_earnings'=>Money::decimal($earnings),'difference'=>Money::decimal($difference),'balanced'=>$difference===0,'accounts'=>$rows->whereIn('type',['asset','liability','equity'])->values()];}
    public function cashFlow(?string $from,?string $to):array
    {
        $to ??= now()->toDateString();
        $cashIds = $this->cashAccountIds();
        $entries = JournalEntry::query()->with(['lines.account'])
            ->whereIn('status',['posted','reversed'])
            ->when($from,fn($q)=>$q->whereDate('posting_date','>=',$from))
            ->whereDate('posting_date','<=',$to)->get();
        $totals=['operating'=>0,'investing'=>0,'financing'=>0];
        foreach($entries as $entry){
            if($entry->source_module==='banking'&&$entry->source_type==='financial_account_transfer')continue;
            $cash=$entry->lines->whereIn('accounting_account_id',$cashIds)->sum(fn($l)=>Money::minor($l->debit)-Money::minor($l->credit));
            if($cash===0)continue;
            $class=$entry->lines->whereNotIn('accounting_account_id',$cashIds)->pluck('account.cash_flow_class')->filter()->first()??'operating';
            $totals[in_array($class,array_keys($totals),true)?$class:'operating']+=$cash;
        }
        $net=array_sum($totals);$opening=$from?Money::minor($this->cashGlBalance(CarbonImmutable::parse($from)->subDay()->toDateString())):0;$closing=Money::minor($this->cashGlBalance($to));$actualChange=$closing-$opening;$difference=$net-$actualChange;
        return ['from'=>$from,'to'=>$to,'operating'=>Money::decimal($totals['operating']),'investing'=>Money::decimal($totals['investing']),'financing'=>Money::decimal($totals['financing']),'net_cash_change'=>Money::decimal($net),'opening_cash'=>Money::decimal($opening),'closing_cash'=>Money::decimal($closing),'actual_cash_change'=>Money::decimal($actualChange),'difference'=>Money::decimal($difference),'reconciles'=>$difference===0];
    }
    public function overview(?string $from,?string $to):array{$pl=$this->profitAndLoss($from,$to);$bs=$this->balanceSheet($to);$tb=$this->trialBalance($from,$to);$reconciliation=$this->reconciliation(false);$company=Auth::user()->company;$open=AccountingException::query()->where('status','open')->count();$critical=AccountingException::query()->where('status','open')->where('severity','critical')->count();$healthy=$tb['balanced']&&$bs['balanced']&&$reconciliation['all_reconciled']&&$open===0;return ['currency'=>$tb['currency'],'cash'=>$this->cashGlBalance($to),'accounts_receivable'=>$this->accountBalance('1100',$to),'accounts_payable'=>-$this->accountBalance('2000',$to),'inventory_value'=>$this->accountBalance('1200',$to),'revenue'=>$pl['revenue'],'cogs'=>$pl['cost_of_goods_sold'],'gross_profit'=>$pl['gross_profit'],'expenses'=>$pl['operating_expenses'],'net_profit'=>$pl['net_profit'],'trial_balance_ok'=>$tb['balanced'],'balance_sheet_ok'=>$bs['balanced'],'open_exceptions'=>$open,'critical_exceptions'=>$critical,'financial_integrity'=>$healthy?'healthy':($critical>0||!$tb['balanced']||!$bs['balanced']?'critical':'needs_attention'),'reconciliation'=>$reconciliation,'accounting_start_date'=>$company->accounting_start_date?->toDateString(),'opening_finalized'=>(bool)$company->accounting_opening_finalized_at,'current_period'=>AccountingPeriod::query()->whereDate('starts_at','<=',now())->whereDate('ends_at','>=',now())->first()];}
    public function integrity():array{$this->scanIntegrity();return ['exceptions'=>AccountingException::query()->where('status','open')->with(['attempts.user:id,name','attempts.journalEntry:id,journal_number,status'])->latest()->get(),'trial_balance'=>$this->trialBalance(null,null),'balance_sheet'=>$this->balanceSheet(null),'reconciliation'=>$this->reconciliation(false),'setup'=>$this->openingSetup()];}
    public function scanIntegrity():void
    {
        $start=Auth::user()->company->accounting_start_date?->toDateString();
        $drafts=JournalEntry::query()->where('status','draft')->withSum('lines as debit_sum','debit')->withSum('lines as credit_sum','credit')->get();
        foreach($drafts as $e){$key="unbalanced:{$e->id}";if(Money::compare($e->debit_sum??0,$e->credit_sum??0)!==0)$this->exception($key,'unbalanced_draft','critical',"Draft journal {$e->journal_number} is not balanced.",['journal_entry_id'=>$e->id]);else $this->resolveException($key);}
        $this->reconciliation(true);
        $checks=[
            ['sales','invoice',\App\Models\Invoice::query()->where('document_type','invoice')->whereIn('status',['issued','partially_paid','paid'])->whereNull('daily_sale_id')->when($start,fn($q)=>$q->whereDate('invoice_date','>=',$start))->pluck('id'),'invoice:'],
            ['landed_cost','landed_cost',\App\Models\LandedCost::query()->where('status','posted')->when($start,fn($q)=>$q->whereDate('posted_at','>=',$start))->pluck('id'),'landed-cost:'],
            ['supplier_accounting','expense',\App\Models\Expense::query()->where('status','posted')->when($start,fn($q)=>$q->whereDate('invoice_date','>=',$start))->pluck('id'),'expense:'],
        ];
        foreach($checks as [$module,$type,$ids,$prefix])foreach($ids as $id){$key="missing-posting:{$type}:{$id}";$exists=JournalEntry::query()->where('source_module',$module)->where('source_key',$prefix.$id)->exists();if(!$exists)$this->exception($key,'missing_accounting_entry','critical',"A financially finalized {$type} #{$id} has no journal entry.",['source_type'=>$type,'source_id'=>$id]);else $this->resolveException($key);}
        $financialMovementCodes=['opening_balance','manual_adjustment_in','manual_adjustment_out','import_adjustment_in','import_adjustment_out','purchase_receipt','daily_sale','daily_sale_reversal','invoice_sale','invoice_credit','reconciliation_adjustment','legacy_stock_in','legacy_stock_out','customer_return','supplier_return','damage_received','damage_writeoff','sample','internal_use','stock_count'];
        foreach(\App\Models\StockMovement::query()->where('affects_company_quantity',true)->whereNotNull('cost_total')->whereIn('movement_code',$financialMovementCodes)->when($start,fn($q)=>$q->whereDate('occurred_at','>=',$start))->get(['id','movement_code','cost_total']) as $movement){$key='missing-posting:stock-movement:'.$movement->id;$exists=JournalEntry::query()->where('source_module','inventory')->where('source_key','stock-movement:'.$movement->id)->exists();if(!$exists)$this->exception($key,'missing_accounting_entry','critical',"Inventory movement #{$movement->id} ({$movement->movement_code}) has no accounting entry.",['source_type'=>'stock_movement','source_id'=>$movement->id,'expected_amount'=>$movement->cost_total]);else $this->resolveException($key);}
        foreach(\App\Models\DailySale::query()->when($start,fn($q)=>$q->whereDate('sale_date','>=',$start))->get(['id','sale_number','total_amount']) as $sale){$key='missing-posting:daily-sale:'.$sale->id;$exists=JournalEntry::query()->where('source_module','sales')->where('source_type','daily_sale')->where('source_id',$sale->id)->exists();if(!$exists)$this->exception($key,'missing_accounting_entry','critical',"Daily sale {$sale->sale_number} has no revenue journal.",['source_type'=>'daily_sale','source_id'=>$sale->id,'expected_amount'=>$sale->total_amount]);else $this->resolveException($key);}
        foreach(JournalEntry::query()->where('status','reversed')->get() as $entry){$key='incomplete-reversal:'.$entry->id;if(!$entry->reversal()->where('status','posted')->exists())$this->exception($key,'incomplete_reversal','critical',"Reversed journal {$entry->journal_number} has no posted reversing entry.",['journal_entry_id'=>$entry->id]);else $this->resolveException($key);}
        foreach(JournalEntry::query()->where('status','posted')->whereNotNull('source_id')->select('source_module','source_type','source_id',DB::raw('COUNT(*) posting_count'))->groupBy('source_module','source_type','source_id')->havingRaw('COUNT(*) > 1')->get() as $duplicate){$key="duplicate-posting:{$duplicate->source_module}:{$duplicate->source_type}:{$duplicate->source_id}";$this->exception($key,'duplicate_source_posting','critical','More than one active journal exists for the same operational source.',['source_type'=>$duplicate->source_type,'source_id'=>$duplicate->source_id,'posting_count'=>$duplicate->posting_count,'recoverable'=>false]);}
        $sourceTables=['daily_sale'=>'daily_sales','invoice'=>'invoices','stock_movement'=>'stock_movements','landed_cost'=>'landed_costs','expense'=>'expenses','expense_payment'=>'expense_payments','purchase_order_payment'=>'purchase_order_payments','financial_account_transaction'=>'financial_account_transactions','financial_account_transfer'=>'financial_account_transfers','inventory_return'=>'inventory_returns'];
        foreach(JournalEntry::query()->whereIn('source_type',array_keys($sourceTables))->whereNotNull('source_id')->get(['id','journal_number','source_type','source_id']) as $entry){$key='orphaned-journal-source:'.$entry->id;$exists=DB::table($sourceTables[$entry->source_type])->where('id',$entry->source_id)->where('company_id',Auth::user()->company_id)->exists();if(!$exists)$this->exception($key,'orphaned_source_reference','critical',"Journal {$entry->journal_number} points to a source record that no longer exists.",['journal_entry_id'=>$entry->id,'source_type'=>$entry->source_type,'source_id'=>$entry->source_id,'recoverable'=>false]);else $this->resolveException($key);}
        $base=CompanyCurrency::forCompanyId((int)Auth::user()->company_id);
        foreach(\App\Models\FinancialAccountTransaction::query()->where('status','posted')->where('currency','!=',$base)->get() as $transaction){$key='invalid-fx:financial-transaction:'.$transaction->id;if(!$transaction->exchange_rate||!$transaction->exchange_rate_date)$this->exception($key,'invalid_fx_snapshot','critical','A posted foreign-currency money transaction has no complete historical FX snapshot.',['financial_account_transaction_id'=>$transaction->id,'currency'=>$transaction->currency]);else $this->resolveException($key);}
        foreach(\App\Models\FinancialAccount::query()->get(['id','name','accounting_account_id']) as $financial){$key='unmapped-financial-account:'.$financial->id;if(!$financial->accounting_account_id)$this->exception($key,'unmapped_account','critical',"Money account {$financial->name} is not mapped to the General Ledger.",['source_type'=>'financial_account','source_id'=>$financial->id]);else $this->resolveException($key);}
    }
    public function reconciliation(bool $recordExceptions=true):array
    {
        $invoiceDebt=\App\Models\Invoice::query()->where('document_type','invoice')->whereIn('status',['issued','partially_paid','paid'])
            ->whereNotIn('id',\App\Models\CustomerDebtTransaction::query()->whereNotNull('invoice_id')->select('invoice_id'))->get()
            ->sum(fn($invoice)=>max(0,(float)$invoice->remaining_balance));
        $ar=round((float)\App\Models\Customer::query()->sum('current_debt')+$invoiceDebt,2);
        $customerAdvances=round((float)\App\Models\Customer::query()->sum('current_credit'),2);
        $ap=round((float)\App\Models\Expense::query()->where('status','posted')->where('document_type','purchase_invoice')->get()->sum(fn($expense)=>(float)$expense->remaining_amount*(float)($expense->exchange_rate?:1)),2);
        $supplierAdvances=round((float)\App\Models\PurchaseOrderPayment::query()->where('status','completed')->with('allocations:id,purchase_order_payment_id,amount')->get()->sum(fn($payment)=>(float)$payment->unallocated_amount*(float)($payment->exchange_rate?:1)),2);
        $inventory=round((float)\App\Models\Product::query()->get()->sum(function($product){if($product->inventory_value!==null)return (float)$product->inventory_value;$cost=$product->weighted_average_cost??$product->purchase_price;return $cost===null?0:(float)$product->quantity*(float)$cost;}),2);
        $baseCurrency=CompanyCurrency::forCompanyId((int)Auth::user()->company_id);
        $cash=round((float)\App\Models\FinancialAccount::query()->get()->sum(function($account)use($baseCurrency){if($account->currency!==$baseCurrency)return $account->transactions()->where('status','posted')->get()->sum(function($transaction){if(!$transaction->exchange_rate)return 0;$sign=in_array($transaction->type,['inflow','transfer_in','adjustment_in','refund_in'],true)?1:-1;return $sign*(float)$transaction->amount*(float)$transaction->exchange_rate;});$in=$account->transactions()->where('status','posted')->whereIn('type',['inflow','transfer_in','adjustment_in','refund_in'])->sum('amount');$out=$account->transactions()->where('status','posted')->whereIn('type',['outflow','transfer_out','adjustment_out','refund_out'])->sum('amount');return (float)$account->opening_balance+(float)$in-(float)$out;})
            +(float)\App\Models\DailySale::query()->sum('total_amount')
            +(float)\App\Models\PaymentTransaction::query()->where('status','completed')->whereNull('financial_account_id')->sum('amount')
            +(float)\App\Models\CustomerDebtTransaction::query()->where('type','payment')->whereNull('financial_account_id')->sum('amount')
            -(float)\App\Models\ExpensePayment::query()->where('status','completed')->whereNull('financial_account_id')->sum('amount_eur')
            -(float)\App\Models\PurchaseOrderPayment::query()->where('status','completed')->whereNull('financial_account_id')->sum('amount_eur'),2);
        $rows=[
            'accounts_receivable'=>$this->reconciliationRow('accounts_receivable',$ar,$this->accountBalance('1100',null),['account_codes'=>['1100'],'drilldown_url'=>'/customer-debts','affected'=>\App\Models\Customer::query()->where('current_debt','>',0)->orderByDesc('current_debt')->limit(10)->get(['id','name','current_debt'])]),
            'customer_advances'=>$this->reconciliationRow('customer_advances',$customerAdvances,-$this->accountBalance('2200',null),['account_codes'=>['2200'],'drilldown_url'=>'/customer-debts','affected'=>\App\Models\Customer::query()->where('current_credit','>',0)->orderByDesc('current_credit')->limit(10)->get(['id','name','current_credit'])]),
            'accounts_payable'=>$this->reconciliationRow('accounts_payable',$ap,-$this->accountBalance('2000',null),['account_codes'=>['2000'],'drilldown_url'=>'/finance']),
            'supplier_advances'=>$this->reconciliationRow('supplier_advances',$supplierAdvances,$this->accountBalance('1300',null),['account_codes'=>['1300'],'drilldown_url'=>'/purchase-orders']),
            'inventory'=>$this->reconciliationRow('inventory',$inventory,$this->accountBalance('1200',null),['account_codes'=>['1200'],'drilldown_url'=>'/stock','affected'=>\App\Models\Product::query()->orderByDesc('inventory_value')->limit(10)->get(['id','name','sku','quantity','inventory_value'])]),
            'cash_bank'=>$this->reconciliationRow('cash_bank',$cash,$this->cashGlBalance(null),['account_codes'=>['1000','1010'],'drilldown_url'=>'/money-accounts']),
        ];
        if($recordExceptions)foreach($rows as $key=>$row){$exceptionKey='control-mismatch:'.$key;if(!$row['reconciled'])$this->exception($exceptionKey,$key.'_control_mismatch',abs((float)$row['difference'])>=100?'critical':'warning',ucwords(str_replace('_',' ',$key)).' subledger does not reconcile to the General Ledger.',$row);else $this->resolveException($exceptionKey);}
        return ['checked_at'=>now()->toIso8601String(),'rows'=>$rows,'all_reconciled'=>collect($rows)->every(fn($row)=>$row['reconciled'])];
    }

    public function openingSetup():array
    {
        $company=Auth::user()->company;
        return ['accounting_start_date'=>$company->accounting_start_date?->toDateString(),'finalized'=>(bool)$company->accounting_opening_finalized_at,'finalized_at'=>$company->accounting_opening_finalized_at?->toIso8601String(),'journal_entry_id'=>$company->accounting_opening_journal_id,'operational_balances'=>$this->reconciliation(false)['rows']];
    }

    public function finalizeOpening(string $startDate,array $balances):JournalEntry
    {
        $company=Auth::user()->company;
        if($company->accounting_opening_finalized_at)throw ValidationException::withMessages(['opening'=>['Opening balances have already been finalized and are immutable.']]);
        $lines=collect($balances)->map(function($row,$index){$account=AccountingAccount::query()->findOrFail($row['accounting_account_id']);if(!$account->is_active||!$account->is_posting)throw ValidationException::withMessages(["balances.$index.accounting_account_id"=>['Choose an active posting account.']]);return ['accounting_account_id'=>$account->id,'description'=>$row['description']??'Opening balance','debit'=>Money::normalize($row['debit']??0),'credit'=>Money::normalize($row['credit']??0)];})->filter(fn($row)=>Money::compare($row['debit'],'0')>0||Money::compare($row['credit'],'0')>0)->values();
        if($lines->count()<2)throw ValidationException::withMessages(['balances'=>['Enter at least two non-zero opening balance lines.']]);
        $debits=Money::decimal($lines->sum(fn($row)=>Money::minor($row['debit'])));$credits=Money::decimal($lines->sum(fn($row)=>Money::minor($row['credit'])));
        if(Money::compare($debits,$credits)!==0)throw ValidationException::withMessages(['balances'=>["Opening debits ({$debits}) must equal opening credits ({$credits})."]]);
        return DB::transaction(function()use($company,$startDate,$lines){$locked=\App\Models\Company::query()->lockForUpdate()->findOrFail($company->id);if($locked->accounting_opening_finalized_at)throw ValidationException::withMessages(['opening'=>['Opening balances have already been finalized.']]);$locked->update(['accounting_start_date'=>$startDate]);$entry=$this->createAndPost(['posting_date'=>$startDate,'description'=>'Controlled accounting opening balances','source_module'=>'opening','source_type'=>'company','source_id'=>$locked->id,'source_key'=>'company-opening:'.$locked->id,'currency'=>CompanyCurrency::forCompanyId($locked->id),'exchange_rate'=>1,'lines'=>$lines->all()]);$locked->update(['accounting_opening_finalized_at'=>now(),'accounting_opening_journal_id'=>$entry->id]);$this->audit('accounting.opening.finalized',$locked,null,['accounting_start_date'=>$startDate,'journal_entry_id'=>$entry->id]);return $entry->fresh('lines.account');});
    }

    private function reconciliationRow(string $control,float $operational,float $gl,array $details=[]):array{$difference=round($operational-$gl,2);return ['control'=>$control,'operational_amount'=>Money::normalize($operational),'gl_amount'=>Money::normalize($gl),'difference'=>Money::normalize($difference),'reconciled'=>abs($difference)<0.005,'status'=>abs($difference)<0.005?'reconciled':'mismatch',...$details];}
    public function resolveAccountingException(AccountingException $exception,string $resolution):void{$exception->update(['status'=>'resolved','resolved_at'=>now(),'resolved_by'=>Auth::id(),'resolution'=>$resolution]);}
    private function exception(string $key,string $type,string $severity,string $message,array $details=[]):void{AccountingException::query()->updateOrCreate(['company_id'=>Auth::user()->company_id,'exception_key'=>$key],['type'=>$type,'severity'=>$severity,'message'=>$message,'details'=>$details,'status'=>'open','resolved_at'=>null,'resolved_by'=>null,'resolution'=>null]);app(BusinessEventService::class)->record('accounting.exception_detected',AccountingException::query()->where('exception_key',$key)->first(),$key,['type'=>$type,'severity'=>$severity],"accounting-exception:{$key}:".sha1(json_encode($details)));}
    private function resolveException(string $key):void{AccountingException::query()->where('exception_key',$key)->where('status','open')->update(['status'=>'resolved','resolved_at'=>now(),'resolved_by'=>Auth::id(),'resolution'=>'The deterministic integrity check now passes.']);}
    private function recalculate(JournalEntry $entry):JournalEntry{$s=$entry->lines()->reorder()->selectRaw('COALESCE(SUM(debit),0) d,COALESCE(SUM(credit),0) c')->first();$entry->update(['total_debit'=>Money::normalize($s->d),'total_credit'=>Money::normalize($s->c)]);return $entry->fresh('lines.account');}
    private function nextNumber():string{$year=now()->year;$last=JournalEntry::query()->where('journal_number','like',"JE-{$year}-%")->lockForUpdate()->orderByDesc('id')->value('journal_number');$next=$last?((int)substr($last,-6)+1):1;return "JE-{$year}-".str_pad((string)$next,6,'0',STR_PAD_LEFT);}
    private function accountBalance(string $code,?string $to):float{$a=AccountingAccount::query()->where('code',$code)->first();if(!$a)return 0;$ids=$this->descendantAccountIds($a->id);$x=\App\Models\JournalLine::query()->whereIn('accounting_account_id',$ids)->whereHas('journalEntry',fn($q)=>$q->whereIn('status',['posted','reversed'])->when($to,fn($z)=>$z->whereDate('posting_date','<=',$to)))->selectRaw('COALESCE(SUM(debit),0)-COALESCE(SUM(credit),0) b')->value('b');return (float)$x;}
    private function descendantAccountIds(int $root):array{$ids=[$root];$frontier=[$root];while($frontier){$children=AccountingAccount::query()->whereIn('parent_id',$frontier)->pluck('id')->map(fn($id)=>(int)$id)->all();$frontier=array_values(array_diff($children,$ids));$ids=array_values(array_unique([...$ids,...$frontier]));}return $ids;}
    private function cashAccountIds():array{$roots=AccountingAccount::query()->whereIn('code',['1000','1010'])->pluck('id')->map(fn($id)=>(int)$id);return $roots->flatMap(fn($id)=>$this->descendantAccountIds($id))->unique()->values()->all();}
    private function cashGlBalance(?string $to):float{$ids=$this->cashAccountIds();if(!$ids)return 0;return (float)\App\Models\JournalLine::query()->whereIn('accounting_account_id',$ids)->whereHas('journalEntry',fn($q)=>$q->whereIn('status',['posted','reversed'])->when($to,fn($z)=>$z->whereDate('posting_date','<=',$to)))->selectRaw('COALESCE(SUM(debit),0)-COALESCE(SUM(credit),0) b')->value('b');}
    private function audit(string $action,object $entity,mixed $old,mixed $new):void{\App\Models\ActivityLog::create(['company_id'=>Auth::user()->company_id,'user_id'=>Auth::id(),'action'=>$action,'entity'=>class_basename($entity),'entity_id'=>$entity->id,'description'=>str_replace('.',' ',$action),'old_value'=>$old,'new_value'=>$new,'ip_address'=>request()?->ip()]);}
}
