<?php
namespace App\Services;
use App\Models\{Customer,Product,DailySale,Invoice,ShipmentIntelligence};
use App\Support\{Money,CompanyCurrency};
use Illuminate\Support\Facades\Date;

/** A derived adapter over the canonical ledger, never another sales ledger. */
final class CustomerSalesEvidence {
 private array $logistics=[];
 public function rows():\Illuminate\Support\Collection {
  $from=today()->subDays(config('customer_intelligence.history_days'))->toDateString();$to=today()->toDateString();
  $n=DailySale::whereDate('sale_date','>=',$from)->count()+Invoice::whereDate('invoice_date','>=',$from)->count();
  abort_if($n>config('customer_intelligence.max_rows'),422,'Customer history exceeds this bounded calculation. Narrow the configured history period.');
  $rows=app(AnalyticsSalesLedger::class)->rows($from,$to);abort_if($rows->count()>config('customer_intelligence.max_rows'),422,'Customer line history exceeds the configured calculation bound.');return $rows;
 }
 public function baskets($rows):array {
  $known=[];foreach(['sale'=>DailySale::class,'invoice'=>Invoice::class] as $prefix=>$class){$ids=$rows->pluck('sale_key')->filter(fn($k)=>str_starts_with($k,$prefix.':'))->map(fn($k)=>(int)substr($k,strlen($prefix)+1))->unique();foreach($class::whereIn('id',$ids)->get(['id','created_at','updated_at']) as $record)$known[$prefix.':'.$record->id]=max($record->created_at?->toIso8601String()??'',$record->updated_at?->toIso8601String()??'');}
  return $rows->where('return',false)->groupBy('sale_key')->map(function($lines,$key)use($known){$first=$lines->first();$products=[];$categories=[];foreach($lines as $r){if($r['product_id']){$id=$r['product_id'];$products[$id]??=['id'=>$id,'name'=>$r['product'],'unit'=>$r['unit'],'quantity'=>0,'value'=>'0.00'];$products[$id]['quantity']+=(float)$r['quantity'];$products[$id]['value']=Money::add($products[$id]['value'],$r['revenue']);}if($r['category_id'])$categories[$r['category_id']]=$r['category'];}
   return ['key'=>$key,'known_at'=>$known[$key]??null,'date'=>$first['date'],'customer_id'=>$first['customer_id'],'value'=>AnalyticsSalesLedger::sum($lines,'revenue'),'products'=>$products,'categories'=>$categories,'url'=>$first['url']];
  })->values()->all();
 }
 public function assemble(string $model):array {
  $this->logistics=[];$rows=$this->rows();$baskets=$this->baskets($rows);$math=app(CustomerSalesMath::class);$asOf=today()->toDateString();$products=Product::with('category')->get()->keyBy('id');$stock=app(InventorySnapshotService::class)->forProducts($products->values());
  foreach(ShipmentIntelligence::where('is_current',true)->latest('id')->limit(200)->get() as $shipment)foreach($shipment->impact['products']??[] as $impact){$id=$impact['product']['id']??null;if($id)$this->logistics[$id][]=['shipment_id'=>$shipment->shipment_id,'risk'=>$shipment->risk,'confidence'=>$shipment->confidence,'eta'=>$shipment->eta,'as_of'=>$shipment->checked_at?->toIso8601String()];}
  $affinity=['products'=>$math->affinities($baskets),'categories'=>$math->affinities($baskets,'categories')];
  foreach($affinity as $kind=>&$associations)foreach($associations as &$a){$a['source_name']=$kind==='products'?($products[$a['source_id']]->name??null):($products->firstWhere('category_id',$a['source_id'])?->category?->name);$a['target_name']=$kind==='products'?($products[$a['target_id']]->name??null):($products->firstWhere('category_id',$a['target_id'])?->category?->name);}unset($a,$associations);
  $profiles=[];$opportunities=[];$observations=[];$health=[];
  $grouped=collect($baskets)->groupBy('customer_id');$customerRows=$rows->groupBy('customer_id');
  foreach(Customer::withTrashed()->orderBy('id')->get() as $customer){
   $history=($grouped[$customer->id]??collect())->sortBy('date')->values()->all();$lines=$customerRows[$customer->id]??collect();$dates=array_column($history,'date');$cadence=$math->cadence($dates,$asOf,$model);$season=$math->seasonality($history,$asOf);$trend=$math->trend($history,$asOf,$season['seasonal']);$summary=app(AnalyticsSalesLedger::class)->summary($lines);if($lines->isEmpty()){$summary['gross_profit']=null;$summary['gross_margin']=null;}
   $prefs=[];foreach($lines->where('return',false)->groupBy('product_id') as $id=>$pLines){if(!$id)continue;$prefs[]=['id'=>(int)$id,'name'=>$pLines->first()['product'],'unit'=>$pLines->first()['unit'],'quantity'=>Money::normalizeDecimal($pLines->sum(fn($r)=>(float)$r['quantity']),3),'sales'=>AnalyticsSalesLedger::sum($pLines,'revenue'),'basket_count'=>$pLines->pluck('sale_key')->unique()->count()];}usort($prefs,fn($a,$b)=>Money::minor($b['sales'])<=>Money::minor($a['sales']));
   $categories=$lines->where('return',false)->whereNotNull('category_id')->groupBy('category_id')->map(fn($r,$id)=>['id'=>(int)$id,'name'=>$r->first()['category'],'sales'=>AnalyticsSalesLedger::sum($r,'revenue')])->sortByDesc(fn($r)=>Money::minor($r['sales']))->values()->all();
   $state=$season['off_season']?'SEASONAL_PAUSE':$cadence['state'];if(count($history)===1)$state='NEW';$active=$customer->is_active&&!$customer->trashed();
   $profiles[]=['id'=>$customer->id,'name'=>$customer->name,'active'=>$active,'state'=>$state,'first_purchase'=>$dates?min($dates):null,'last_purchase'=>$dates?max($dates):null,'purchase_count'=>count($history),'relationship_days'=>$dates?(int)Date::parse(min($dates))->diffInDays(today(),false):null,'summary'=>$summary,'return_rate_percent'=>Money::minor($summary['revenue'])+Money::minor($summary['return_value'])>0?round(100*Money::minor($summary['return_value'])/(Money::minor($summary['revenue'])+Money::minor($summary['return_value'])),1):null,'cadence'=>$cadence,'trend'=>$trend,'seasonality'=>$season,'products'=>array_slice($prefs,0,10),'categories'=>$categories,'recent_history'=>array_slice(array_reverse($history),0,20),'diagnostic_dates'=>$dates,'limitations'=>['Recorded business transactions only; missing identity is not inferred.','Cadence uses unique purchase dates; basket totals and returns are separate.']];
   if(!$active||$season['off_season'])continue;
   if($cadence['eligible']&&in_array($state,['AT_RISK','INACTIVE']))$observations[]=['key'=>'activity:'.$customer->id.':'.max($dates),'kind'=>'CUSTOMER_INACTIVITY','customer_id'=>$customer->id,'product_id'=>null,'anchor'=>max($dates),'window'=>['start'=>$asOf,'end'=>today()->addDays((int)ceil($cadence['q75_days']))->toDateString()],'baseline_window'=>null,'challenger_window'=>null,'cadence'=>$cadence,'qualification'=>'Future activity follow-up, not permanent churn or a guaranteed reorder.'];
   foreach($prefs as $pref){$p=$products[$pref['id']]??null;if(!$p||$p->lifecycle_status==='discontinued')continue;$h=array_values(array_filter($history,fn($b)=>isset($b['products'][$p->id])));$c=$math->cadence(array_column($h,'date'),$asOf,$model);if(!$c['eligible'])continue;$last=max(array_column($h,'date'));$quantities=array_map(fn($b)=>$b['products'][$p->id]['quantity'],$h);$values=array_map(fn($b)=>Money::minor($b['products'][$p->id]['value']),$h);
    $signal=['key'=>'reorder:'.$customer->id.':'.$p->id.':'.$last,'kind'=>'REORDER_OPPORTUNITY','customer_id'=>$customer->id,'customer'=>$customer->name,'product_id'=>$p->id,'product'=>$p->name,'unit'=>$p->unit,'anchor'=>$last,'window'=>$c['window'],'baseline_window'=>$c['baseline_window'],'challenger_window'=>$c['challenger_window'],'cadence'=>$c,'quantity_range'=>[$math->quantile($quantities,.25),$math->quantile($quantities,.75)],'value_range'=>[Money::decimal((int)round($math->quantile($values,.25))),Money::decimal((int)round($math->quantile($values,.75)))],'confidence'=>'moderate','drivers'=>['Personal product buying interval from '.count($h).' completed baskets.','Historical quantity/value ranges are context, not an order or guaranteed sale.']];
    if($c['window']['end']>=$asOf)$observations[]=$signal;
    if($c['window']['end']>=$asOf&&Date::parse($c['window']['start'])->subDays((int)ceil($c['median_days']/4))->toDateString()<=$asOf)$opportunities[]=$this->inventory($signal,$stock[$p->id]??[],$p);
   }
   foreach($affinity['products'] as $pair){$source=collect($prefs)->firstWhere('id',$pair['source_id']);if(!$source||$source['basket_count']<3||collect($prefs)->contains('id',$pair['target_id']))continue;$target=$products[$pair['target_id']]??null;if(!$target||$target->lifecycle_status==='discontinued')continue;$opportunities[]=$this->inventory(['key'=>'affinity:'.$customer->id.':'.$target->id.':'.($dates?max($dates):'none').':'.today()->format('Y-m'),'kind'=>'RELATED_PRODUCT','customer_id'=>$customer->id,'customer'=>$customer->name,'product_id'=>$target->id,'product'=>$target->name,'unit'=>$target->unit,'anchor'=>$dates?max($dates):null,'window'=>null,'quantity_range'=>null,'value_range'=>null,'confidence'=>'moderate','association'=>$pair,'drivers'=>['Customer purchased '.$source['name'].' in '.$source['basket_count'].' baskets.','Related item co-occurs in '.$pair['pair_baskets'].' baskets across '.$pair['customer_count'].' customers; no personal quantity prediction.']],$stock[$target->id]??[],$target);}
  }
  $valueQ=$math->quantile(array_map(fn($p)=>Money::minor($p['summary']['revenue']),array_filter($profiles,fn($p)=>$p['purchase_count']>=6)),.75);$frequencyQ=$math->quantile(array_filter(array_column(array_column($profiles,'cadence'),'median_days'),fn($x)=>$x!==null),.25);
  foreach($profiles as &$p){$p['segment']=$p['purchase_count']<6?'COLLECTING_HISTORY':(($valueQ!==null&&Money::minor($p['summary']['revenue'])>=$valueQ)?(($p['cadence']['median_days']??INF)<=$frequencyQ?'HIGH_VALUE_FREQUENT':'HIGH_VALUE_OCCASIONAL'):'ESTABLISHED_BUYER');$p['rfm']=['recency_days'=>$p['cadence']['days_since_last'],'median_interval_days'=>$p['cadence']['median_days'],'recorded_net_sales'=>$p['summary']['revenue'],'value_threshold'=>$valueQ===null?null:Money::decimal((int)round($valueQ)),'frequent_interval_threshold'=>$frequencyQ];}unset($p);
  usort($opportunities,fn($a,$b)=>[($a['kind']==='REORDER_OPPORTUNITY'?0:1),$a['window']['start']??'9999',-(float)($a['value_range'][1]??0)]<=>[($b['kind']==='REORDER_OPPORTUNITY'?0:1),$b['window']['start']??'9999',-(float)($b['value_range'][1]??0)]);
  $missing=$rows->whereNull('customer_id')->pluck('sale_key')->unique()->count();if($missing)$health[]=['code'=>'missing_customer_identity','count'=>$missing,'detail'=>'Unassigned sales remain in company totals but cannot support personal signals.'];$missingProducts=$rows->whereNull('product_id')->count();if($missingProducts)$health[]=['code'=>'missing_product_reference','count'=>$missingProducts,'detail'=>'These lines cannot support product affinity or reorder timing.'];
  $foreign=Invoice::whereNotNull('issued_at')->whereNull('voided_at')->where('currency','!=',CompanyCurrency::current())->whereDate('invoice_date','>=',today()->subDays(config('customer_intelligence.history_days')))->count();if($foreign)$health[]=['code'=>'foreign_currency_documents','count'=>$foreign,'detail'=>'Foreign-currency documents are excluded; no guessed FX conversion.'];
  $identityKeys=[];foreach(Customer::get(['id','name','email','fiscal_number','business_registration_number']) as $identity)foreach(['name','email','fiscal_number','business_registration_number'] as $field){$normalized=mb_strtolower(preg_replace('/[\s\p{P}]+/u','',trim((string)$identity->$field)));if($normalized!=='')$identityKeys[$field.':'.$normalized][]=$identity->id;}$duplicateNames=count(array_filter($identityKeys,fn($ids)=>count(array_unique($ids))>1));if($duplicateNames)$health[]=['code'=>'possible_duplicate_identity','count'=>$duplicateNames,'detail'=>'Review matching names manually; AIMS does not merge identities.'];
  $undated=DailySale::whereNull('sale_date')->count()+Invoice::whereNotNull('issued_at')->whereNull('invoice_date')->count();if($undated)$health[]=['code'=>'missing_transaction_date','count'=>$undated,'detail'=>'Undated transactions are not used for timing.'];$guestOrders=\App\Models\SalesOrder::whereNull('customer_id')->whereDate('order_date','>=',today()->subDays(config('customer_intelligence.history_days')))->count();if($guestOrders)$health[]=['code'=>'orders_without_customer_link','count'=>$guestOrders,'detail'=>'Identified cash guests are allowed but are not guessed into personal customer profiles.'];
  $recent=$rows->filter(fn($r)=>$r['date']>=today()->subDays(89)->toDateString());
  return ['calculation_version'=>config('customer_intelligence.version'),'as_of'=>$asOf,'history_from'=>today()->subDays(config('customer_intelligence.history_days'))->toDateString(),'currency'=>CompanyCurrency::current(),'canonical_baskets'=>count($baskets),'profiles'=>$profiles,'opportunities'=>$opportunities,'observations'=>$observations,'affinity'=>$affinity,'resource_trends'=>$this->resourceTrends($rows,$asOf),'concentration'=>$this->concentration($recent),'health'=>$health,'local_model'=>app(LocalCustomerSalesProvider::class)->analyze($profiles),'model'=>$model,'qualification'=>'Advisory statistical evidence. Customer signals explain company demand; they are not added to company forecasts. No outreach or business mutations.'];
 }
 private function inventory(array $signal,array $stock,Product $p):array {
  $low=$signal['quantity_range'][0]??null;$available=(float)($stock['available_to_promise']??$stock['available']??0);$conflict=$low!==null?$available<$low:$available<=(float)$p->min_quantity;
  $signal['inventory']=['available_to_promise'=>$available,'incoming'=>$stock['incoming']??0,'committed'=>$stock['committed_outgoing']??0,'incoming_schedule'=>$stock['incoming_schedule']??[],'shipments'=>$this->logistics[$p->id]??[],'constrained'=>$conflict,'qualification'=>'Current available-to-promise; incoming dates are not guarantees.'];$signal['decisions']=[$signal['kind']==='REORDER_OPPORTUNITY'?'REORDER_OPPORTUNITY':'RELATED_PRODUCT'];if($conflict)$signal['decisions'][]='SALES_INVENTORY_CONFLICT';
  return $signal;
 }
 private function concentration($rows):array {
  $total=Money::minor(AnalyticsSalesLedger::sum($rows,'revenue'));$groups=[];foreach(['customers'=>'customer_id','products'=>'product_id','categories'=>'category_id'] as $kind=>$key){$groups[$kind]=$rows->groupBy($key)->map(fn($r,$id)=>['id'=>$id?:null,'name'=>$r->first()[rtrim($kind,'s')]??($kind==='categories'?$r->first()['category']:null)??'Unassigned','revenue'=>AnalyticsSalesLedger::sum($r,'revenue'),'share_percent'=>$total>0?round(100*Money::minor(AnalyticsSalesLedger::sum($r,'revenue'))/$total,1):null])->sortByDesc(fn($r)=>Money::minor($r['revenue']))->values()->all();}
  $customers=array_values(array_filter($groups['customers'],fn($r)=>$r['id']!==null));return ['from'=>today()->subDays(89)->toDateString(),'to'=>today()->toDateString(),'net_sales'=>Money::decimal($total),'groups'=>$groups,'top_shares'=>collect([1,5,10])->mapWithKeys(fn($n)=>[$n=>$total>0?round(100*array_sum(array_map(fn($r)=>Money::minor($r['revenue']),array_slice($customers,0,$n)))/$total,1):null])->all(),'qualification'=>'Share of recorded net sales including unassigned sales and returns. Descriptive concentration, not a danger label.'];
 }
 private function resourceTrends($rows,string $asOf):array {
  $groups=[];$math=app(CustomerSalesMath::class);foreach(['products'=>'product_id','categories'=>'category_id'] as $kind=>$key){$groups[$kind]=[];foreach($rows->where('return',false)->whereNotNull($key)->groupBy($key) as $id=>$lines){$history=$lines->groupBy('sale_key')->map(fn($r,$sale)=>['key'=>$sale,'date'=>$r->first()['date'],'value'=>AnalyticsSalesLedger::sum($r,'revenue')])->values()->all();$season=$math->seasonality($history,$asOf);$groups[$kind][]=['id'=>(int)$id,'name'=>$lines->first()[$kind==='products'?'product':'category'],'basket_count'=>count($history),'trend'=>$math->trend($history,$asOf,$season['seasonal']),'seasonality'=>$season];}usort($groups[$kind],fn($a,$b)=>Money::minor($b['trend']['recent_sales'])<=>Money::minor($a['trend']['recent_sales']));}
  return $groups;
 }
}
