<?php
namespace App\Services;
use App\Models\{CustomerSalesSnapshot as Snapshot,CustomerIntelligencePolicy as Policy,CustomerSalesPrediction as Prediction,AnalyticsSnapshot,Customer,Product,SalesOrder,OrderChannel,Company,User,OperationalTask};
use App\Support\{Money,CompanyCurrency,RequestFingerprint};
use Illuminate\Support\Facades\{Auth,Cache,DB,Date,Log};
use Illuminate\Support\Str;

final class CustomerSalesIntelligenceService {
 public const PERMISSIONS=['analytics.view','customers.manage','daily_sales.manage'];
 public function allowed(?string $role=null):bool {foreach(self::PERMISSIONS as $p)if(!app(PermissionService::class)->roleHasPermission($role??Auth::user()?->role??'',$p))return false;return true;}
 public function authorize():void {abort_unless(Auth::user()?->company_id&&$this->allowed(),403,'Customer & Sales Intelligence requires customer, sales and analytics access.');}
 private function can(string $p):bool{return app(PermissionService::class)->roleHasPermission(Auth::user()->role,$p);}
 public function latest():array {
  $this->authorize();$r=Snapshot::whereNull('evidence->archived')->latest('id')->first();if(!$r)return ['state'=>'not_calculated','message'=>'Collecting customer history. Calculate evidence or wait for the scheduled refresh.'];
  $e=$r->evidence;unset($e['observations']);foreach($e['opportunities'] as &$op)if(!$this->can('shipments.view'))unset($op['inventory']['shipments']);unset($op);$ids=collect($e['opportunities'])->pluck('key');$predictions=Prediction::v8()->whereNull('value->archived')->whereIn('value->key',$ids)->get()->keyBy(fn($p)=>$p->value['key']);$drafts=SalesOrder::whereIn('idempotency_key',$predictions->pluck('id')->map(fn($id)=>'v8-draft-'.$id))->get(['id','idempotency_key','order_number','status'])->keyBy('idempotency_key');$profiles=collect($e['profiles'])->keyBy('id');
  foreach($e['opportunities'] as &$o){$o['prediction_id']=$predictions[$o['key']]->id??null;$o['financial_context']=$this->can('analytics.finance')&&$this->can('debts.view')?($profiles[$o['customer_id']]['financial_context']??['state'=>'unknown']):['state'=>'restricted'];if($o['financial_context']['review_required']??false)$o['decisions'][]='CUSTOMER_FINANCIAL_CONFLICT';$o['draft']=$o['prediction_id']?($drafts['v8-draft-'.$o['prediction_id']]??null)?->only(['id','order_number','status']):null;}unset($o);
  foreach($e['profiles'] as &$p){if(!$this->can('analytics.finance')){unset($p['summary']['gross_profit'],$p['summary']['gross_margin'],$p['summary']['cost_coverage_percent']);}if(!$this->can('analytics.finance')||!$this->can('debts.view'))$p['financial_context']=['state'=>'restricted'];}unset($p);
  return ['state'=>'ready','id'=>$r->id,'version'=>$r->version,'as_of'=>$r->as_of->toDateString(),'evidence_cutoff'=>$r->evidence_cutoff->toIso8601String(),'stale'=>$r->evidence_cutoff->lt(now()->subMinutes(config('customer_intelligence.refresh_minutes')))||Cache::has('customer-sales-dirty:'.Auth::user()->company_id),'evidence'=>$e,'model'=>$this->modelStatus(),'can_draft'=>$this->can('fulfillment.manage'),'can_model'=>$this->can('analytics.ml_datasets'),'read_only'=>true];
 }
 private function financial(int $id):array {
  if(!$this->can('debts.view')||!$this->can('analytics.finance'))return ['state'=>'restricted','qualification'=>'Financial context requires debt and financial analytics access.'];$c=Customer::withTrashed()->find($id);if(!$c)return ['state'=>'unknown'];
  $x=app(CustomerCreditService::class)->exposure($c);$h=app(FinancialPaymentTiming::class)->history($c);return ['state'=>'available','debt'=>$x['current_debt']??$c->current_debt,'advance'=>$x['customer_advance']??$c->current_credit,'exposure'=>$x['total_exposure'],'overdue'=>$x['overdue_amount']??$x['overdue']??0,'credit_status'=>$c->credit_status,'payment_segment'=>$h['segment'],'completed_payments'=>$h['count'],'median_delay_days'=>$h['median_delay'],'review_required'=>$c->credit_status==='blocked'||Money::minor($x['overdue_amount']??$x['overdue']??0)>0||($h['eligible']&&$h['median_delay']>14),'qualification'=>'Existing credit exposure and V7 completed-payment timing; not an automatic sale block.'];
 }
 public function customer(int $id):array {$this->authorize();Customer::withTrashed()->findOrFail($id);$r=$this->latest();return ['profile'=>collect($r['evidence']['profiles']??[])->firstWhere('id',$id),'opportunities'=>array_values(array_filter($r['evidence']['opportunities']??[],fn($o)=>$o['customer_id']===$id)),'as_of'=>$r['as_of']??null,'state'=>$r['state']];}
 public function section(string $key,?int $id=null):array {if($key==='affinity'&&$id){$c=$this->customer($id);$all=$this->latest();$owned=array_column($c['profile']['products']??[],'id');$categories=array_column($c['profile']['categories']??[],'id');return ['data'=>['products'=>array_values(array_filter($all['evidence']['affinity']['products']??[],fn($a)=>in_array($a['source_id'],$owned))),'categories'=>array_values(array_filter($all['evidence']['affinity']['categories']??[],fn($a)=>in_array($a['source_id'],$categories)))],'as_of'=>$c['as_of']];}$r=$id?$this->customer($id):$this->latest();return ['data'=>$id?($key==='opportunities'?$r['opportunities']:($key==='reorders'?array_values(array_filter($r['opportunities'],fn($o)=>$o['kind']==='REORDER_OPPORTUNITY')):($r['profile'][$key]??$r['profile']))):($key==='at_risk'?array_values(array_filter($r['evidence']['profiles']??[],fn($p)=>in_array($p['state'],['AT_RISK','INACTIVE']))):($r['evidence'][$key]??[])),'as_of'=>$r['as_of']??null];}
 public function refresh():array {
  $this->authorize();$lock=Cache::lock('customer-sales-refresh:'.Auth::user()->company_id,120);abort_unless($lock->get(),409,'Customer evidence is already being calculated.');
  try{DB::transaction(function(){DB::table('companies')->where('id',Auth::user()->company_id)->lockForUpdate()->first();$model=$this->modelStatus()['champion'];$e=app(CustomerSalesEvidence::class)->assemble($model);foreach($e['profiles'] as &$profile)$profile['financial_context']=$this->financial($profile['id']);unset($profile);$hash=hash('sha256',json_encode($e,JSON_PRESERVE_ZERO_FRACTION));$old=Snapshot::whereNull('evidence->archived')->latest('id')->first();$r=Snapshot::firstOrCreate(['fingerprint'=>$hash],['version'=>(string)Str::uuid(),'as_of'=>today(),'evidence_cutoff'=>now(),'evidence'=>$e]);
   $snapshots=[];foreach($e['profiles'] as $p)$snapshots[$p['id']]=(AnalyticsSnapshot::whereDate('snapshot_date',today())->where('entity_type','customer_sales_v8')->where('entity_id',$p['id'])->where('warehouse_id',0)->first()??AnalyticsSnapshot::create(['snapshot_date'=>today(),'entity_type'=>'customer_sales_v8','entity_id'=>$p['id'],'warehouse_id'=>0,'feature_version'=>config('customer_intelligence.version'),'observed_at'=>now(),'facts'=>$p]));
   foreach($e['observations'] as $o)$this->freeze($o,$snapshots[$o['customer_id']],$r,$model);
   // Affinity can be reviewed but is not evaluated as a personal reorder forecast.
   foreach($e['opportunities'] as $o)if($o['kind']==='RELATED_PRODUCT')$this->freeze($o,$snapshots[$o['customer_id']],$r,$model);
   $this->evaluate();if($r->wasRecentlyCreated)$this->events($r,$old);Cache::forget('customer-sales-dirty:'.Auth::user()->company_id);
  });return $this->latest();}finally{$lock->release();}
 }
 private function freeze(array $o,AnalyticsSnapshot $snapshot,Snapshot $summary,string $model):void {
  if(Prediction::v8()->where('value->key',$o['key'])->exists())return;
  Prediction::create(['prediction_type'=>$o['kind']==='CUSTOMER_INACTIVITY'?'activity_window':($o['kind']==='RELATED_PRODUCT'?'product_affinity':'reorder_window'),'entity_type'=>'customer','entity_id'=>$o['customer_id'],'model_key'=>'customer-sales-v8','model_version'=>$model,'input_feature_version'=>config('customer_intelligence.version'),'analytics_snapshot_id'=>$snapshot->id,'value'=>$o+['summary_id'=>$summary->id,'evidence_cutoff'=>now()->toIso8601String()],'confidence'=>null,'generated_at'=>now(),'valid_until'=>$o['window']?Date::parse($o['window']['end'])->endOfDay():today()->addDays(30)->endOfDay()]);
 }
 public function evaluate():void {
  $rows=app(CustomerSalesEvidence::class)->rows();$baskets=app(CustomerSalesEvidence::class)->baskets($rows);
  foreach(Prediction::v8()->whereNull('value->archived')->whereIn('prediction_type',['reorder_window','activity_window'])->where('valid_until','<',now())->get() as $p){$v=$p->value;$candidates=array_values(array_filter($baskets,fn($b)=>$b['customer_id']===$p->entity_id&&$b['date']>$p->generated_at->toDateString()&&!empty($b['known_at'])&&Date::parse($b['known_at'])->gt($p->generated_at)&&$b['date']>$v['anchor']&&($p->prediction_type==='activity_window'||isset($b['products'][$v['product_id']]))));usort($candidates,fn($a,$b)=>$a['date']<=>$b['date']);$actual=$candidates[0]??null;$evaluation=$p->evaluation??[];
   if(!$p->evaluated_at){$inWindow=collect($candidates)->contains(fn($b)=>$b['date']>=$v['window']['start']&&$b['date']<=$v['window']['end']);$evaluation=['outcome'=>$inWindow?'purchase_in_window':'no_purchase_in_window','window'=>$v['window'],'timing_qualified'=>false,'qualification'=>'Subsequent recorded purchase after observation date; absence is not permanent churn.'];}
   if($actual&&!isset($evaluation['subsequent_purchase'])){$center=fn($w)=>Date::parse($w['start'])->addDays((int)floor(Date::parse($w['start'])->diffInDays(Date::parse($w['end']))/2))->toDateString();$evaluation['subsequent_purchase']=['date'=>$actual['date'],'quantity'=>$p->prediction_type==='activity_window'?null:$actual['products'][$v['product_id']]['quantity'],'value'=>$p->prediction_type==='activity_window'?$actual['value']:$actual['products'][$v['product_id']]['value'],'source'=>$actual['key']];if($p->prediction_type==='reorder_window'){$evaluation['baseline_error']=abs((int)Date::parse($center($v['baseline_window']))->diffInDays(Date::parse($actual['date']),false));$evaluation['challenger_error']=abs((int)Date::parse($center($v['challenger_window']))->diffInDays(Date::parse($actual['date']),false));$evaluation['timing_qualified']=true;}}
   if($evaluation!==$p->evaluation)$p->update(['evaluation'=>$evaluation,'actual_value'=>$actual?['date'=>$actual['date']]:null,'evaluated_at'=>now()]);
  }
 }
 public function modelStatus():array {
  $all=Prediction::v8()->whereNull('value->archived')->where('prediction_type','reorder_window')->whereNotNull('evaluated_at')->where('generated_at','>=',today()->subDays(365))->latest('id')->limit(5000)->get();$outcomes=$all->filter(fn($p)=>$p->evaluation['timing_qualified']??false)->unique(fn($p)=>$p->entity_id.':'.$p->evaluation['subsequent_purchase']['source']);$n=$outcomes->count();$a=$n?$outcomes->avg(fn($p)=>$p->evaluation['baseline_error']):null;$b=$n?$outcomes->avg(fn($p)=>$p->evaluation['challenger_error']):null;
  return ['baseline'=>'interval_iqr_baseline','champion'=>Policy::latest('id')->first()?->settings['champion']??'interval_iqr_baseline','challenger'=>'median_mad','completed_windows'=>$all->count(),'genuine_timing_outcomes'=>$n,'baseline_mae_days'=>$a,'challenger_mae_days'=>$b,'window_hit_rate'=>$all->count()?$all->filter(fn($p)=>($p->evaluation['outcome']??null)==='purchase_in_window')->count()/$all->count():null,'eligible_for_promotion'=>$n>=config('customer_intelligence.promotion_samples')&&$b<$a*.95,'minimum_completed'=>config('customer_intelligence.promotion_samples'),'qualification'=>'Interpretable local statistics; no synthetic test accuracy or unsupported trained churn model.'];
 }
 public function selectModel(array $input):array {
  $this->authorize();abort_unless($this->can('analytics.ml_datasets'),403);$v=validator($input,['model'=>'required|in:interval_iqr_baseline,median_mad','reason'=>'required|string|min:5|max:500'])->validate();$s=$this->modelStatus();abort_if($v['model']==='median_mad'&&!$s['eligible_for_promotion'],422,'Promotion requires 20 genuine independent purchase outcomes and lower timing error.');Policy::create(['version'=>(string)Str::uuid(),'settings'=>['champion'=>$v['model'],'decision'=>['reason'=>$v['reason'],'previous'=>$s['champion'],'metrics'=>$s]],'created_by'=>Auth::id()]);app(AnalyticsDataService::class)->audit('customer.intelligence.model_selected',$v+['metrics'=>$s]);return $this->refresh();
 }
 public function review(int $prediction,array $input):array {
  $this->authorize();abort_unless($this->can('fulfillment.manage'),403);$v=validator($input,['quantity'=>'required|numeric|gt:0|max:100000000','acknowledge_shortage'=>'sometimes|boolean'])->validate();$p=Prediction::v8()->whereNull('value->archived')->findOrFail($prediction);abort_if($p->valid_until->lt(now()),422,'This opportunity window expired. Refresh and review current evidence.');$c=Customer::findOrFail($p->entity_id);abort_unless($c->is_active,422,'This customer is inactive.');$product=Product::findOrFail($p->value['product_id']);abort_if(in_array($product->lifecycle_status,['inactive','discontinued']),422,'This product is not available for a new draft.');$qty=Money::normalizeDecimal($v['quantity'],3);app(UnitConversionService::class)->assertPrecision((float)$qty,$product->unit);$stock=app(InventorySnapshotService::class)->forProduct($product);$channel=OrderChannel::where('type','manual')->where('name','Manual')->first();$price=$channel?app(OrderPriceService::class)->quote($product,$channel,$c,'1',$qty,today()->toDateString())['expected_price']:Money::normalize($product->selling_price??$product->price);$shortage=(float)$qty>(float)$stock['available_to_promise'];
  $r=['prediction_id'=>$p->id,'customer_id'=>$c->id,'customer'=>$c->name,'product_id'=>$product->id,'product'=>$product->name,'unit'=>$product->unit,'quantity'=>$qty,'unit_price'=>$price,'total'=>Money::multiply($price,$qty),'currency'=>CompanyCurrency::current(),'available_to_promise'=>$stock['available_to_promise'],'incoming'=>$stock['incoming'],'shortage'=>$shortage,'customer_status'=>$c->credit_status,'actor'=>Auth::id(),'on_date'=>today()->toDateString(),'acknowledge_shortage'=>$v['acknowledge_shortage']??false];$r['review_token']=RequestFingerprint::make($r);$r['financial_context']=$this->financial($c->id);$r['qualification']='Draft only: no stock reservation, receivable, discount or customer contact. Existing order confirmation rules still apply.';return $r;
 }
 public function draft(int $prediction,array $input):array {
  $this->authorize();abort_unless($this->can('fulfillment.manage'),403);$v=validator($input,['confirm'=>'required|accepted','quantity'=>'required|numeric|gt:0','review_token'=>'required|string|size:64','acknowledge_shortage'=>'sometimes|boolean'])->validate();return DB::transaction(function()use($prediction,$v){DB::table('companies')->where('id',Auth::user()->company_id)->lockForUpdate()->first();$protected=Prediction::v8()->whereNull('value->archived')->lockForUpdate()->findOrFail($prediction);Customer::whereKey($protected->entity_id)->lockForUpdate()->firstOrFail();Product::whereKey($protected->value['product_id'])->lockForUpdate()->firstOrFail();$r=$this->review($prediction,$v);abort_unless(hash_equals($r['review_token'],$v['review_token']),409,'Customer, price, quantity or available inventory changed. Review again before creating the draft.');abort_if($r['shortage']&&!$r['acknowledge_shortage'],422,'Acknowledge the stock shortage before creating a draft for human review.');$key='v8-draft-'.$prediction;$data=['customer_id'=>$r['customer_id'],'currency'=>$r['currency'],'payment_type'=>'cash','order_date'=>today()->toDateString(),'notes'=>'Human-reviewed Customer & Sales Intelligence opportunity #'.$prediction,'idempotency_key'=>$key,'items'=>[['product_id'=>$r['product_id'],'quantity'=>$r['quantity'],'unit'=>$r['unit'],'unit_price'=>$r['unit_price']]]];$order=app(OutboundService::class)->create($data);app(AnalyticsDataService::class)->audit('customer.intelligence.draft_reviewed',['prediction_id'=>$prediction,'order_id'=>$order->id,'quantity'=>$r['quantity']]);return ['order'=>$order->only(['id','order_number','status','total_amount']),'url'=>'/fulfillment?order='.$order->id,'qualification'=>$r['qualification']];});
 }
 private function events(Snapshot $r,?Snapshot $old):void {
  $before=collect($old?->evidence['profiles']??[])->keyBy('id');$events=[];foreach($r->evidence['profiles'] as $p)if(in_array($p['state'],['AT_RISK','INACTIVE'])&&($before[$p['id']]['state']??null)!==$p['state'])$events[]=['activity_changed',$p['id'],['state'=>$p['state'],'confidence'=>$p['cadence']['confidence']]];
  $keys=array_column($old?->evidence['opportunities']??[],'key');foreach($r->evidence['opportunities'] as $o)if(!in_array($o['key'],$keys))$events[]=[$o['kind']==='REORDER_OPPORTUNITY'?'reorder_window':'sales_opportunity',$o['customer_id'],['product_id'=>$o['product_id'],'confidence'=>$o['confidence']]];
  if($old&&abs(($r->evidence['concentration']['top_shares'][5]??0)-($old->evidence['concentration']['top_shares'][5]??0))>=5)$events[]=['concentration_changed',0,['change_points'=>round(($r->evidence['concentration']['top_shares'][5]??0)-($old->evidence['concentration']['top_shares'][5]??0),1)]];
  foreach($r->evidence['profiles'] as $profile)if(in_array($profile['state'],['AT_RISK','INACTIVE'])&&str_starts_with($profile['segment'],'HIGH_VALUE')&&($before[$profile['id']]['state']??null)!==$profile['state'])$events[]=['high_value_inactivity',$profile['id'],['state'=>$profile['state'],'confidence'=>$profile['cadence']['confidence']]];
  foreach($events as [$kind,$id,$meta]){app(BusinessEventService::class)->record('customer.intelligence.'.$kind,$r,'Customer sales review',$meta+['customer_id'=>$id],'customer-v8:'.$r->version.':'.$kind.':'.$id.':'.($meta['product_id']??0));$family=$kind==='high_value_inactivity'?'activity_changed':$kind;$key=hash('sha256','customer-v8:'.$r->company_id.':'.$family.':'.$id.':'.($meta['product_id']??0));$task=OperationalTask::firstOrCreate(['dedupe_key'=>$key],['title'=>'Review customer sales: '.str_replace('_',' ',$kind),'description'=>'Review evidence in Customer & Sales Intelligence. No automatic contact or order.','priority'=>'normal','assigned_role'=>'admin','source_type'=>'CustomerSalesSnapshot','source_id'=>$r->id,'created_by'=>Auth::id(),'due_at'=>today()->addDay()]);if(in_array($task->status,['completed','cancelled']))$task->update(['status'=>'open','source_id'=>$r->id,'completed_at'=>null]);}
 }
 public function scheduled(bool $force=false):int {$previous=Auth::user();$done=0;$start=microtime(true);try{foreach(Company::orderBy('id')->cursor() as $company){if(microtime(true)-$start>config('customer_intelligence.worker_seconds'))break;$actor=User::withoutGlobalScopes()->where('company_id',$company->id)->whereIn('role',['admin','manager'])->where('is_active',true)->first();if(!$actor)continue;Auth::setUser($actor);try{$r=Snapshot::whereNull('evidence->archived')->latest('id')->first();if($force||!$r||($r->evidence['calculation_version']??null)!==config('customer_intelligence.version')||$r->evidence_cutoff->lt(now()->subMinutes(60))||Cache::has('customer-sales-dirty:'.$company->id)){$this->refresh();$done++;}}catch(\Throwable $e){Log::warning('Customer intelligence refresh deferred.',['company_id'=>$company->id,'error'=>$e->getMessage()]);}}}finally{$previous?Auth::setUser($previous):Auth::forgetUser();}return $done;}
}
