<?php
namespace App\Services;
use App\Models\{Product,Supplier,FinancialIntelligencePolicy};
use App\Support\Money;
use Illuminate\Support\Facades\Date;
final class FinancialIntelligenceScenario {
 public function simulate(array $input):array {
  $service=app(FinancialIntelligenceService::class);$service->authorize();$v=validator($input,['horizon'=>'sometimes|in:7,30,60,90','collection_delay_days'=>'sometimes|integer|min:-30|max:180','supplier_delay_days'=>'sometimes|integer|min:-30|max:180','arrival_delay_days'=>'sometimes|integer|min:0|max:180','purchase_amount'=>'sometimes|numeric|min:0|max:1000000000','currency'=>'required|string|size:3|regex:/^[A-Z]{3}$/','purchase_date'=>'sometimes|date_format:Y-m-d|after_or_equal:today','product_id'=>'nullable|integer|min:1','supplier_id'=>'nullable|integer|min:1','warehouse_id'=>'nullable|integer|min:1','base_quantity'=>'sometimes|numeric|min:0|max:100000000','demand_multiplier'=>'sometimes|numeric|min:0.1|max:5','split_quantity'=>'sometimes|numeric|gt:0','split_delay_days'=>'required_with:split_quantity|integer|min:1|max:180'])->validate();
  foreach(['horizon','collection_delay_days','supplier_delay_days','arrival_delay_days','split_delay_days','product_id','supplier_id','warehouse_id'] as $key)if(isset($v[$key]))$v[$key]=(int)$v[$key];
  $f=$service->latest((int)($v['horizon']??30));abort_unless($f['state']==='ready',409,'Refresh financial evidence before running a scenario.');$e=$f['evidence'];$assumptions=[];
  foreach($e['receivables'] as &$r)if($r['expected_date']&&isset($v['collection_delay_days'])){$r['expected_date']=max($e['as_of'],Date::parse($r['expected_date'])->addDays($v['collection_delay_days'])->toDateString());$r['evidence_type']='scenario';}unset($r);
  foreach($e['commitments'] as &$r){$days=(int)($v['supplier_delay_days']??0);if($r['payment_basis']==='arrival')$days+=(int)($v['arrival_delay_days']??0);if($r['expected_date']&&$days){$r['expected_date']=max($e['as_of'],Date::parse($r['expected_date'])->addDays($days)->toDateString());$r['evidence_type']='scenario';}}unset($r);
  $inventory=null;$amount=Money::normalize($v['purchase_amount']??0);$date=$v['purchase_date']??today()->toDateString();$parts=[];
  if(!empty($v['product_id'])){Product::findOrFail($v['product_id']);if(!empty($v['supplier_id']))Supplier::findOrFail($v['supplier_id']);$options=array_intersect_key($v,array_flip(['supplier_id','warehouse_id','base_quantity','demand_multiplier']));$options['order_date']=$date;
   $plans=app(InventoryPlanningService::class)->scenarios($v['product_id'],['scenarios'=>[$options]])['scenarios'];$inventory=$plans[0];abort_unless($inventory['feasible'],422,'The quantity violates existing inventory planning or supplier constraints.');abort_if(isset($v['base_quantity'])&&abs($inventory['base_quantity']-$v['base_quantity'])>.0005,422,'Use a quantity that satisfies this supplier’s minimum and fixed-pack multiple.');abort_unless(($inventory['currency']??null)===$v['currency']&&$inventory['base_cost']!==null,422,'A priced supplier and compatible scenario currency are required.');$amount=Money::normalize($inventory['base_cost']);
   if(!empty($v['split_quantity'])){$supplier=$inventory['supplier_id']??null;$permission=FinancialIntelligencePolicy::latest('id')->first()?->settings['split_permissions'][$supplier]??null;abort_unless($permission['allowed']??false,422,'Split deliveries are not documented as permitted for this supplier.');abort_unless($v['split_quantity']<($v['base_quantity']??$inventory['base_quantity']),422,'The second split must be smaller than the total purchase.');$total=$v['base_quantity']??$inventory['base_quantity'];$later=Date::parse($date)->addDays($v['split_delay_days'])->toDateString();
    $split=app(InventoryPlanningService::class)->scenarios($v['product_id'],['scenarios'=>[array_replace($options,['base_quantity'=>$total-$v['split_quantity']]),array_replace($options,['base_quantity'=>$v['split_quantity'],'order_date'=>$later])]])['scenarios'];foreach($split as $index=>$p){$requested=$index===0?$total-$v['split_quantity']:$v['split_quantity'];abort_unless($p['feasible']&&abs($p['base_quantity']-$requested)<.0005,422,'Each split must satisfy MOQ and fixed unit/pack constraints.');}$parts=[['date'=>$date,'amount'=>Money::normalize($split[0]['base_cost'])],['date'=>$later,'amount'=>Money::normalize($split[1]['base_cost'])]];$amount=Money::add(...array_column($parts,'amount'));$inventory['split_views']=$split;
    $input=app(InventoryPlanningService::class)->decisionEvidence($v['product_id'],$options)['input'];foreach($split as $p)if($p['expected_arrival'])$input['firm_incoming'][]=['expected_at'=>$p['expected_arrival'],'quantity'=>$p['base_quantity'],'source'=>'hypothetical_split'];
    $combined=app(InventoryPlanningMath::class)->calculate($input,array_replace($options,['base_quantity'=>0]));$inventory['timeline']=$combined['timeline'];$inventory['scenario_stockout_date']=$combined['scenario_stockout_date'];$inventory['scenario_stockout_days']=$combined['scenario_stockout_days'];$inventory['coverage_supported']=$combined['coverage_supported'];$inventory['excess_quantity']=$combined['timeline']?max(0,last($combined['timeline'])['with_order']-$combined['safety_stock']):null;
    $assumptions[]='Combined V4 coverage uses both hypothetical receipt dates. Supplier split permission is documented; actual freight economics and delivery agreement still require human review.';
   }
  }else abort_if(!empty($v['split_quantity']),422,'Select a product and supplier to validate split-purchase constraints.');
  if(!$parts&&Money::minor($amount)>0)$parts=[['date'=>$date,'amount'=>$amount]];
  foreach($parts as $index=>$part)$e['commitments'][]=['key'=>'scenario:purchase:'.$index,'reference'=>'Hypothetical additional purchase','amount'=>$part['amount'],'currency'=>$v['currency'],'expected_date'=>$part['date'],'evidence_type'=>'scenario','direction'=>'outflow','payment_basis'=>'scenario','url'=>'/inventory-intelligence?view=planning'];
  if(isset($v['demand_multiplier']))$assumptions[]='Demand changes affect V4 coverage only. Uncontracted future sales are not invented as cash inflows.';
  if(!empty($v['supplier_delay_days']))$assumptions[]='Supplier payment timing change is hypothetical, not approved renegotiation.';
  if(!empty($v['arrival_delay_days']))$assumptions[]='Arrival delay shifts only documented arrival-dependent obligations with an existing warehouse ETA.';
  $assumptions[]='Additional purchase is incremental; it does not replace an existing PO/payable. Costs with no recorded price are not invented.';
  return ['base'=>$f['forecast'],'scenario'=>app(FinancialForecastMath::class)->calculate($e,(int)($v['horizon']??30)),'purchase_commitment'=>$amount,'currency'=>$v['currency'],'inventory'=>$inventory,'assumptions'=>$assumptions,'qualification'=>'Hypothetical, not a probability range. Lower cash outlay must not override stockout or safety-stock constraints.','read_only'=>true,'snapshot_id'=>$f['id']];
 }
}
