export const workspaceGuides = {
  'customer-sales-intelligence': ['Review personal buying patterns, supported reorder windows and related-product evidence. Check stock and financial caveats. An explicit reviewed draft uses the existing order workflow; no automatic customer contact or stock/debt changes.', 'Rishiko modelet personale të blerjeve, afatet e mbështetura të riporositjes dhe produktet e lidhura. Kontrollo stokun dhe paralajmërimet financiare. Drafti i konfirmuar përdor procesin ekzistues; nuk ka kontakt automatik ose ndryshime stoku/borxhi.', ['customer-debts','order-hub','financial-intelligence']],
  'financial-intelligence': ['Review recorded cash, expected collections and supplier requirements. Recommendations remain potential purchases. Compare scenarios before committing; this page never posts accounting or creates orders.', 'Rishiko paratë e regjistruara, arkëtimet e pritshme dhe detyrimet ndaj furnitorëve. Rekomandimet mbeten blerje të mundshme. Krahaso skenarët para vendimit; kjo faqe nuk regjistron kontabilitet ose porosi.', ['finance', 'money-accounts', 'inventory-planning']],
  categories: ['Create categories to organize products. Select a category when registering or editing a product, then use it in filters.', 'Krijo kategori për organizimin e produkteve. Zgjidh kategorinë gjatë regjistrimit ose ndryshimit, pastaj përdore në filtra.', ['products']],
  'warehouse-3d': ['Explore the configured warehouse layout and product locations. Edit the layout or use Stock Locator for accurate quantities; the visual map does not change stock.', 'Shiko planimetrinë dhe lokacionet e produkteve. Ndrysho planimetrinë ose përdor Gjetësin e stokut për sasi të sakta; harta nuk ndryshon stokun.', ['warehouse-layout', 'warehouse-operations']],
  'warehouse-layout': ['Configure warehouse sections, levels and positions. Locations are shared with Warehouses & Transfers and the 3D map.', 'Konfiguro seksionet, nivelet dhe pozicionet. Lokacionet ndahen me Depot dhe transferimet dhe hartën 3D.', ['warehouse-operations', 'warehouse-3d']],
  'shipments/global-map': ['Select a tracked vessel to view its latest received AIS position. Check the signal timestamp; an old position is not a live location.', 'Zgjidh anijen për pozicionin e fundit të marrë nga AIS. Kontrollo kohën e sinjalit; pozicioni i vjetër nuk është lokacion live.', ['shipments/my-shipments', 'shipments/alerts']],
  'shipments/alerts': ['Review shipment exceptions and open the linked tracking record. Clearing an alert does not change the shipment or its position.', 'Rishiko përjashtimet e dërgesave dhe hap regjistrimin e lidhur. Pastrimi i njoftimit nuk ndryshon dërgesën ose pozicionin.', ['shipments/my-shipments']],
  analytics: ['Choose the business area and date range. Read recorded results first; inspect source coverage before relying on trends. Missing data is not zero.', 'Zgjidh fushën dhe periudhën. Lexo rezultatet e regjistruara dhe kontrollo mbulimin e burimeve para përdorimit të prirjeve. Të dhënat që mungojnë nuk janë zero.', ['reports', 'inventory-intelligence']],
  users: ['Authorized company administrators manage users and their roles. Permissions determine which pages and actions each user may access.', 'Administratorët e autorizuar menaxhojnë përdoruesit dhe rolet. Lejet përcaktojnë faqet dhe veprimet që mund të përdoren.', []],
  'activity-logs': ['Filter the audit history to see who performed an operation and when. Open the original business record for its current state.', 'Filtro historikun e auditimit për të parë kush dhe kur kreu veprimin. Hap regjistrimin burimor për gjendjen aktuale.', ['reports']],
  cms: ['Manage published website content. Company preferences, language and appearance are in Settings.', 'Menaxho përmbajtjen e publikuar të faqes. Preferencat, gjuha dhe pamja e kompanisë gjenden te Cilësimet.', []],
  'system-integrity': ['Review consistency warnings and recovery guidance. Do not treat clearing a warning as repairing its underlying business record.', 'Rishiko paralajmërimet e konsistencës dhe udhëzimet e rikthimit. Pastrimi i paralajmërimit nuk riparon regjistrimin burimor.', ['reports']],
  dashboard: ['See today’s stock, sales, alerts and tasks. Open an item to act; background updates do not interrupt your work.', 'Shiko stokun, shitjet, njoftimet dhe detyrat e ditës. Hap një artikull për të vepruar; përditësimet në sfond nuk ndërpresin punën.', ['action-center', 'daily-sales']],
  products: ['Browse product records and prices. Open View for stock availability and warehouse balances; Edit changes the product, not recorded stock movements.', 'Shfleto produktet dhe çmimet. Te Shiko gjenden disponueshmëria dhe depot; Ndrysho përditëson produktin, jo lëvizjet e regjistruara të stokut.', ['warehouse-operations', 'stock']],
  stock: ['Review stock movements or record an adjustment. Use Warehouses & Transfers to locate stock or move it between warehouses.', 'Rishiko lëvizjet e stokut ose regjistro një rregullim. Përdor Depot dhe transferimet për të gjetur stokun ose transferuar mes depove.', ['warehouse-operations', 'operations-center']],
  'warehouse-operations': ['Locate products by warehouse, manage storage locations and transfer stock. Receiving from a Purchase Order preserves the supplier and order trail.', 'Gjej produktet sipas depos, menaxho lokacionet dhe transfero stokun. Pranimi nga porosia e blerjes ruan lidhjen me furnitorin dhe porosinë.', ['products', 'purchase-orders']],
  'warehouse-mobile': ['Scan or select a product, check the warehouse and confirm the operation. The server validates stock before an operation completes.', 'Skano ose zgjidh produktin, kontrollo depon dhe konfirmo veprimin. Serveri verifikon stokun para përfundimit.', ['warehouse-operations', 'fulfillment']],
  'order-hub': ['Manage incoming customer orders, review issues and hand confirmed orders to fulfillment. Daily Sales is for immediate recorded sales, not duplicate order entry.', 'Menaxho porositë e klientëve, rishiko problemet dhe dërgo porositë e konfirmuara te përmbushja. Shitjet ditore përdoren për shitje të menjëhershme, jo regjistrim të dyfishtë.', ['fulfillment', 'customer-debts']],
  fulfillment: ['Allocate available stock, pick, pack and dispatch confirmed customer orders. Returns remain linked to the original delivery.', 'Rezervo stokun, mblidh, paketo dhe dërgo porositë e konfirmuara. Kthimet mbeten të lidhura me dorëzimin fillestar.', ['order-hub', 'warehouse-mobile']],
  'daily-sales': ['Record each sale with one or more products. Stock updates on saving; payments and customer debt remain separate. Use the date to review earlier days.', 'Regjistro çdo shitje me një ose më shumë produkte. Stoku përditësohet kur ruhet; pagesat dhe borxhi mbeten të ndara. Zgjidh datën për ditët e kaluara.', ['customer-debts', 'finance']],
  'customer-debts': ['Open a customer’s sheet to add debt, record payments, review aging and manage credit controls. Customer advances are shown separately from unpaid debt.', 'Hap fletën e klientit për të shtuar borxh, regjistruar pagesa, parë vjetërsinë dhe menaxhuar kredinë. Parapagimet shfaqen veçmas nga borxhi.', ['daily-sales', 'finance']],
  suppliers: ['Manage supplier contact details. Open a scorecard or delivery intelligence when you need evidence for a purchasing decision.', 'Menaxho të dhënat e furnitorëve. Hap vlerësimin ose inteligjencën e dorëzimit kur nevojiten prova për vendimin e blerjes.', ['purchase-orders', 'procurement']],
  'purchase-orders': ['Record and edit supplier orders, track partial payments and receive goods. Payment and receipt status are independent; receiving updates inventory.', 'Regjistro dhe ndrysho porositë, ndiq pagesat e pjesshme dhe prano mallrat. Pagesa dhe pranimi janë të pavarura; pranimi përditëson inventarin.', ['procurement', 'shipments/my-shipments']],
  procurement: ['Create a purchase request, collect RFQ quotes, compare suppliers and review an award before creating Purchase Orders. Approvals follow existing company rules.', 'Krijo kërkesë blerjeje, mblidh oferta, krahaso furnitorët dhe shqyrto përzgjedhjen para krijimit të porosive. Miratimet ndjekin rregullat e kompanisë.', ['purchase-orders', 'suppliers']],
  finance: ['Review recorded sales, expenses and receivables for a chosen period. Separate source totals help avoid counting Daily Sales and invoices twice.', 'Rishiko shitjet, shpenzimet dhe detyrimet e periudhës. Burimet e ndara ndihmojnë të shmanget numërimi i dyfishtë i shitjeve dhe faturave.', ['invoices', 'money-accounts', 'accounting']],
  invoices: ['Create and manage customer invoices, payments and exports. Review company and buyer details before issuing a document.', 'Krijo dhe menaxho faturat, pagesat dhe eksportet. Kontrollo të dhënat e kompanisë dhe blerësit para lëshimit.', ['finance', 'customer-debts']],
  'money-accounts': ['Track cash and bank transactions and reconciliations. Accounting journals are managed separately in Accounting.', 'Ndiq transaksionet në arkë dhe bankë dhe rakordimet. Ditarët kontabël menaxhohen veçmas te Kontabiliteti.', ['finance', 'accounting']],
  accounting: ['Review posted journals, balances, periods and reconciliation exceptions. Operational transactions remain in their original modules.', 'Rishiko ditarët e postuar, bilancet, periudhat dhe përjashtimet e rakordimit. Transaksionet operative mbeten në modulet burimore.', ['finance', 'money-accounts']],
  'shipments/my-shipments': ['Find an AIS vessel, link it to a Purchase Order and review received position data. Missing signals are not live locations; alerts and shipment intelligence explain exceptions.', 'Gjej anijen me AIS, lidhe me porosinë e blerjes dhe shiko pozicionet e marra. Sinjalet që mungojnë nuk janë pozicione live; njoftimet dhe inteligjenca shpjegojnë përjashtimet.', ['shipments/global-map', 'shipments/alerts', 'control-tower']],
  'control-tower': ['Review shipment exceptions and the linked purchasing, receiving and financial context. Open the source record to perform the real operation.', 'Rishiko përjashtimet e dërgesave dhe lidhjet me blerjet, pranimet dhe financat. Hap burimin për veprimin real.', ['shipments/my-shipments', 'purchase-orders']],
  'inventory-intelligence': ['Review measured demand and advisory stock forecasts. Start with risk and replenishment; model diagnostics are optional. Recommendations never purchase automatically.', 'Rishiko kërkesën e matur dhe parashikimet këshilluese. Fillo me rrezikun dhe furnizimin; diagnostikimi është opsional. Rekomandimet nuk blejnë automatikisht.', ['inventory-planning', 'decision-center']],
  'inventory-planning': ['Review stock coverage, replenishment and transfer recommendations. Check quantities and constraints before creating a draft for human approval.', 'Rishiko mbulimin e stokut, furnizimin dhe transferimet e rekomanduara. Kontrollo sasitë dhe kufizimet para krijimit të draftit.', ['decision-center', 'procurement']],
  'decision-center': ['Prioritize evidence-backed business recommendations. Review the impact, uncertainty and source records before accepting an action.', 'Jep përparësi rekomandimeve të mbështetura në të dhëna. Rishiko ndikimin, pasigurinë dhe burimet para pranimit.', ['action-center', 'inventory-planning']],
  'operations-center': ['Control stock counts, batches, expiry, replenishment and landed cost. Quality Management handles receipt inspections, quarantine decisions and supplier claims.', 'Kontrollo numërimet, lotet, skadimin, furnizimin dhe koston përfundimtare. Cilësia menaxhon inspektimet, karantinën dhe reklamacione ndaj furnitorëve.', ['quality', 'warehouse-operations']],
  quality: ['Inspect received goods, record defects and resolve quarantine or supplier claims. Supply Control manages quantities, expiry and cost rather than inspection decisions.', 'Inspekto mallrat, regjistro defektet dhe zgjidh karantinën ose reklamacione. Kontrolli i furnizimit menaxhon sasi, skadim dhe kosto, jo vendimet e inspektimit.', ['operations-center', 'suppliers']],
  'action-center': ['Review assigned tasks, approvals and business exceptions. Open the linked record to resolve the issue; dismissing attention is not completing a business transaction.', 'Rishiko detyrat, miratimet dhe përjashtimet. Hap burimin për zgjidhje; mbyllja e njoftimit nuk përfundon transaksionin.', ['decision-center', 'automation-studio']],
  'automation-studio': ['Start with a disabled template, choose conditions and simulate its result. Enable only after reviewing the safe actions it will prepare.', 'Fillo me model joaktiv, zgjidh kushtet dhe simulo rezultatin. Aktivizo vetëm pasi të rishikosh veprimet që do përgatisë.', ['action-center']],
  documents: ['Keep documents and evidence linked to their business records. Review access, version and expiry rather than uploading the same document in several modules.', 'Ruaj dokumentet dhe dëshmitë të lidhura me regjistrimet. Rishiko qasjen, versionin dhe skadimin në vend të ngarkimit të dyfishtë.', ['purchase-orders', 'invoices']],
  reports: ['Review operational reports and export data. A portable backup is different from a CSV report; use backup and restore for moving company data safely.', 'Rishiko raportet dhe eksporto të dhënat. Kopja rezervë ndryshon nga raporti CSV; përdor kopjen dhe rikthimin për të bartur të dhënat.', ['analytics', 'finance']],
}

// Plain-language workflow guidance shared by the workspaces and the assistant.
export const intelligenceWorkflows = {
  forecasts: {
    en: ['What will I need in stock?', 'Choose a product and forecast period.', 'Review expected demand and shortage risk.', 'Review replenishment, or open forecast setup if there is not enough history.'],
    sq: ['Çfarë do të më duhet në stok?', 'Zgjidh produktin dhe periudhën e parashikimit.', 'Rishiko kërkesën e pritshme dhe rrezikun e mungesës.', 'Rishiko furnizimin, ose hap konfigurimin kur mungon historiku.'],
  },
  planning: {
    en: ['How much should I order or transfer?', 'Choose a product and warehouse.', 'Review stock coverage, supplier and suggested quantity.', 'Review a purchase-request draft; nothing is ordered automatically.'],
    sq: ['Sa duhet të porosis ose transferoj?', 'Zgjidh produktin dhe depon.', 'Rishiko mbulimin, furnitorin dhe sasinë e sugjeruar.', 'Rishiko draftin e kërkesës; asgjë nuk porositet automatikisht.'],
  },
  decisions: {
    en: ['Which action should I take first?', 'Open a recommendation that needs attention.', 'Compare the suggested action with the alternatives.', 'Choose an action and review its draft or source workflow before confirming.'],
    sq: ['Cilit veprim duhet t’i jap përparësi?', 'Hap rekomandimin që kërkon vëmendje.', 'Krahaso veprimin e sugjeruar me alternativat.', 'Zgjidh veprimin dhe rishiko draftin ose burimin para konfirmimit.'],
  },
  suppliers: {
    en: ['Can this supplier deliver on time?', 'Choose the supplier and delivery period.', 'Read measured delivery history and current risks.', 'Review the affected order or another supplier; forecasts are advisory.'],
    sq: ['A mund të dorëzojë furnitori në kohë?', 'Zgjidh furnitorin dhe periudhën.', 'Lexo historikun e matur dhe rreziqet aktuale.', 'Rishiko porosinë ose furnitor tjetër; parashikimet janë këshilluese.'],
  },
  shipments: {
    en: ['Will incoming stock arrive in time?', 'Open a tracked shipment.', 'Check signal freshness, estimated arrival and affected stock.', 'Open the purchase order or stock plan to handle the risk.'],
    sq: ['A do të mbërrijë furnizimi në kohë?', 'Hap dërgesën që po ndiqet.', 'Kontrollo freskinë e sinjalit, mbërritjen dhe stokun e prekur.', 'Hap porosinë ose planin e stokut për të trajtuar rrezikun.'],
  },
}

export const pageSteps = {
  products: {
    en: ['Choose Add product, enter the name, unit, purchase and selling prices, and opening quantity. An image and SKU are optional.', 'Save; only a successful backend response confirms creation.', 'Use View for the image, available stock and warehouse balances; Edit changes the product record.'],
    sq: ['Zgjidh Shto produkt, shkruaj emrin, njësinë, çmimet dhe sasinë fillestare. Fotoja dhe SKU janë opsionale.', 'Ruaj; vetëm përgjigjja e suksesshme e serverit konfirmon krijimin.', 'Përdor Shiko për foton, stokun dhe depot; Ndrysho për të dhënat e produktit.'],
  },
  'daily-sales': {
    en: ['Choose the date and add a sale. Each sale can contain several products.', 'Enter quantity, sale unit and price. Saving deducts stock immediately; cash, partial payments and debt are recorded separately.', 'Update the day’s note as needed. Close the day after finishing, and use the date selector to review older sales.'],
    sq: ['Zgjidh datën dhe shto shitjen. Çdo shitje mund të ketë disa produkte.', 'Shkruaj sasinë, njësinë dhe çmimin. Ruajtja zbrit stokun menjëherë; pagesat dhe borxhi regjistrohen veçmas.', 'Përditëso shënimin e ditës sipas nevojës. Mbyll ditën në përfundim dhe zgjidh datën për shitjet e kaluara.'],
  },
  'purchase-orders': {
    en: ['Create an order for the supplier, add products, quantities and dates, then save it.', 'Record partial or full payments independently from delivery. Edit eligible orders to change their products.', 'Use Receive products when goods arrive, review received quantities and warehouse, then confirm. The backend records receipt and updates inventory.'],
    sq: ['Krijo porosinë për furnitorin, shto produktet, sasitë dhe datat dhe ruaje.', 'Regjistro pagesat veçmas nga dorëzimi. Ndrysho porositë e lejuara për të ndryshuar produktet.', 'Përdor Prano produktet kur arrijnë, kontrollo sasitë dhe depon dhe konfirmo. Serveri regjistron pranimin dhe përditëson inventarin.'],
  },
  'warehouse-operations': {
    en: ['Start in Stock Locator: choose a warehouse or search/filter products to see where stock is recorded.', 'Use Warehouses to manage warehouse details and storage locations.', 'For a transfer, choose source, destination and items; review quantities and follow the existing dispatch/receipt confirmations. A draft alone does not move stock.'],
    sq: ['Fillo te Gjetësi i stokut: zgjidh depon ose kërko/filtro produktet për lokacionet e stokut.', 'Përdor Depot për të menaxhuar të dhënat dhe lokacionet.', 'Për transferim, zgjidh burimin, destinacionin dhe artikujt; rishiko sasitë dhe konfirmo dërgimin/pranimin. Drafti nuk lëviz stok.'],
  },
  'customer-debts': {
    en: ['Open or create a customer sheet. Add each unpaid purchase with its date, amount and notes.', 'Record each payment with its date; partial payments reduce unpaid obligations and excess payments remain an advance.', 'Review aging and credit controls. A blocked or over-limit debt transaction needs the existing override approval; the assistant cannot approve it.'],
    sq: ['Hap ose krijo fletën e klientit. Shto çdo blerje të papaguar me datën, shumën dhe shënimet.', 'Regjistro pagesat me datë; pagesat e pjesshme ulin detyrimet dhe teprica mbetet parapagim.', 'Rishiko vjetërsinë dhe kredinë. Transaksioni i bllokuar ose mbi limit kërkon miratim; asistenti nuk mund ta miratojë.'],
  },
}
