<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{Auth,DB,Cache};
use App\Models\{Customer,Category,Product,DailySale,Invoice,Company,User,CustomerSalesPrediction,CustomerSalesSnapshot,CustomerDebtTransaction,SalesOrder,BusinessEvent};
use App\Services\{AnalyticsPermissions,CustomerSalesMath,CustomerSalesIntelligenceService,LocalCustomerSalesProvider,AutomationRegistry};

class CustomerSalesIntelligenceTest extends TestCase {
 use RefreshDatabase;
 private function setupCompany():void {$this->actingAsApiUser();$this->getJson('/api/me')->assertOk();AnalyticsPermissions::install();$this->travelTo(now()->setDate(2026,10,5)->setTime(12,0));app()->instance(LocalCustomerSalesProvider::class,new class{public function analyze(array $p):array{return ['state'=>'available','trained_model'=>false];}});}
 private function product(string $name='Fabric A',string $unit='m',int $stock=10000):Product {return Product::create(['name'=>$name,'sku'=>'V8-'.Product::count(),'unit'=>$unit,'quantity'=>$stock,'min_quantity'=>50,'category_id'=>Category::firstOrCreate(['name'=>'Fabrics'])->id,'price'=>3,'selling_price'=>3,'purchase_price'=>2]);}
 private function sale(?Customer $c,int $days,array $items):DailySale {$s=DailySale::create(['sale_number'=>'V8-'.DailySale::count(),'sale_date'=>today()->subDays($days),'status'=>'finalized','inventory_applied_at'=>today()->subDays($days)->addHours(12),'customer_id'=>$c?->id,'customer_name'=>$c?->name,'total_amount'=>6000,'total_quantity'=>2000,'paid_amount'=>6000,'created_by'=>Auth::id()]);foreach($items as $i=>$line){[$p,$qty]=$line;$s->items()->create(['line_number'=>$i+1,'product_id'=>$p->id,'product_name'=>$p->name,'unit'=>$p->unit,'quantity'=>$qty,'base_quantity'=>$qty,'unit_price'=>3,'line_total'=>$qty*3,'cost_total'=>$qty*2]);}return $s;}
 private function history(Customer $c,Product $p,int $last=28,int $n=18):void {$days=$last;for($i=0;$i<$n;$i++){$this->sale($c,$days,[[$p,[1500,2000,2500][$i%3]]]);$days+=[20,25,30][$i%3];}}
 private function refresh():array {try{return $this->withoutExceptionHandling()->postJson('/api/customer-sales-intelligence/refresh')->assertOk()->json();}finally{$this->withExceptionHandling();}}
 private function businessState():array {return collect(['products','stock_movements','customer_debt_transactions','sales_orders','journal_entries','invoices'])->mapWithKeys(fn($t)=>[$t=>DB::table($t)->orderBy('id')->get()->toJson()])->all();}
 private function opportunity(array $r,int $customer):array{return collect($r['evidence']['opportunities'])->first(fn($o)=>$o['customer_id']===$customer&&$o['kind']==='REORDER_OPPORTUNITY');}
 public function test_representative_wholesale_cadence_inventory_and_payment_context_are_advisory():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Furniture Company A','current_debt'=>900]);$p=$this->product();$this->history($c,$p);$b=$this->product('Related Fabric B','m',15);$other=$this->product('Unrelated C');for($i=0;$i<3;$i++){$buyer=Customer::create(['name'=>'Other '.$i]);for($j=0;$j<10;$j++)$this->sale($buyer,1+$j*2,[[$p,100],[$b,100]]);}for($i=0;$i<30;$i++)$this->sale(null,2+$i,[[$other,100]]);
  $before=$this->businessState();$r=$this->refresh();$profile=collect($r['evidence']['profiles'])->firstWhere('id',$c->id);$this->assertSame(18,$profile['purchase_count']);$this->assertEquals(25,$profile['cadence']['median_days']);$this->assertSame('900.00',$profile['financial_context']['debt']);$related=collect($r['evidence']['opportunities'])->first(fn($o)=>$o['customer_id']===$c->id&&$o['kind']==='RELATED_PRODUCT');$this->assertNotNull($related);$this->assertTrue($related['inventory']['constrained']);$this->assertNull($related['quantity_range']);$this->assertGreaterThanOrEqual(1.2,$related['association']['lift']);$this->assertSame($before,$this->businessState());$this->assertSame(0,$r['model']['genuine_timing_outcomes']);
 }
 public function test_one_sale_and_linked_invoice_are_not_counted_twice():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$s=$this->sale($c,1,[[$p,100]]);$inv=Invoice::create(['invoice_number'=>'V8-INV','customer_id'=>$c->id,'customer_name'=>$c->name,'daily_sale_id'=>$s->id,'document_type'=>'invoice','status'=>'issued','currency'=>'EUR','invoice_date'=>today()->subDay(),'issued_at'=>now(),'grand_total'=>300,'total_amount'=>300]);$inv->items()->create(['line_number'=>1,'product_id'=>$p->id,'description'=>$p->name,'unit'=>'m','quantity'=>100,'base_quantity'=>100,'unit_price'=>3,'taxable_amount'=>300,'line_total'=>300,'cost_total'=>200]);$r=$this->refresh();$this->assertSame(1,$r['evidence']['canonical_baskets']);$this->assertSame('300.00',$r['evidence']['profiles'][0]['summary']['revenue']);
 }
 public function test_sparse_irregular_and_duplicate_days_do_not_produce_personal_predictions():void {
  $this->setupCompany();$m=app(CustomerSalesMath::class);$this->assertFalse($m->cadence(['2026-01-01','2026-02-01'],today()->toDateString())['eligible']);$this->assertFalse($m->cadence(['2026-01-01','2026-01-02','2026-01-03','2026-01-04','2026-01-05','2026-09-01'],today()->toDateString())['eligible']);$this->assertSame(2,$m->cadence(['2026-01-01','2026-01-01','2026-02-01'],today()->toDateString())['count']);$c=Customer::create(['name'=>'New']);$p=$this->product();$this->sale($c,1,[[$p,10]]);$r=$this->refresh();$this->assertEmpty($r['evidence']['opportunities']);$this->assertSame('NEW',$r['evidence']['profiles'][0]['state']);
 }
 public function test_activity_is_relative_not_a_universal_day_threshold():void {$this->setupCompany();$m=app(CustomerSalesMath::class);$weekly=array_map(fn($i)=>today()->subDays(30+7*$i)->toDateString(),range(0,9));$monthly=array_map(fn($i)=>today()->subDays(30+45*$i)->toDateString(),range(0,9));$this->assertSame('INACTIVE',$m->cadence($weekly,today()->toDateString())['state']);$this->assertSame('ACTIVE',$m->cadence($monthly,today()->toDateString())['state']);}
 public function test_tiny_or_single_customer_affinity_is_not_promoted():void {$this->setupCompany();$b=[];for($i=0;$i<40;$i++)$b[]=['customer_id'=>1,'products'=>[1=>[],2=>[]],'categories'=>[]];$this->assertEmpty(app(CustomerSalesMath::class)->affinities($b));$b=array_slice($b,0,5);$this->assertEmpty(app(CustomerSalesMath::class)->affinities($b));}
 public function test_draft_requires_review_confirm_and_is_idempotent_without_stock_or_debt_changes():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,24);$o=$this->opportunity($this->refresh(),$c->id);$beforeQty=$p->fresh()->quantity;$this->postJson('/api/customer-sales-intelligence/predictions/'.$o['prediction_id'].'/draft',['quantity'=>2000])->assertStatus(422);$r=$this->postJson('/api/customer-sales-intelligence/predictions/'.$o['prediction_id'].'/review',['quantity'=>2000])->assertOk()->json();$v=['confirm'=>true,'quantity'=>2000,'review_token'=>$r['review_token']];$a=$this->postJson('/api/customer-sales-intelligence/predictions/'.$o['prediction_id'].'/draft',$v)->assertOk()->assertJsonPath('order.status','draft')->json();$b=$this->postJson('/api/customer-sales-intelligence/predictions/'.$o['prediction_id'].'/draft',$v)->assertOk()->json();$this->assertSame($a['order']['id'],$b['order']['id']);$this->assertDatabaseCount('sales_orders',1);$this->assertSame($beforeQty,$p->fresh()->quantity);$this->assertDatabaseCount('stock_movements',0);$this->assertDatabaseCount('customer_debt_transactions',0);$this->assertSame('/fulfillment?order='.$a['order']['id'],$a['url']);
 }
 public function test_price_or_stock_change_requires_a_new_review_and_preserves_no_business_mutation():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,24);$o=$this->opportunity($this->refresh(),$c->id);$url='/api/customer-sales-intelligence/predictions/'.$o['prediction_id'];$r=$this->postJson($url.'/review',['quantity'=>2000])->assertOk()->json();$p->update(['selling_price'=>4]);$this->postJson($url.'/draft',['confirm'=>true,'quantity'=>2000,'review_token'=>$r['review_token']])->assertStatus(409);$r=$this->postJson($url.'/review',['quantity'=>2000])->assertOk()->json();$p->update(['quantity'=>1500]);$this->postJson($url.'/draft',['confirm'=>true,'quantity'=>2000,'review_token'=>$r['review_token']])->assertStatus(409);$this->assertDatabaseCount('sales_orders',0);
 }
 public function test_inactive_customer_fractional_piece_and_unacknowledged_shortage_are_rejected():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product('Handle','pcs',100);$this->history($c,$p,24);$o=$this->opportunity($this->refresh(),$c->id);$url='/api/customer-sales-intelligence/predictions/'.$o['prediction_id'];$this->postJson($url.'/review',['quantity'=>1.5])->assertStatus(422);$r=$this->postJson($url.'/review',['quantity'=>200])->assertOk()->json();$this->postJson($url.'/draft',['confirm'=>true,'quantity'=>200,'review_token'=>$r['review_token']])->assertStatus(422);$c->update(['is_active'=>false]);$this->postJson($url.'/review',['quantity'=>20])->assertStatus(422);
 }
 public function test_missing_identity_is_not_guessed_and_concentration_excludes_unassigned_as_a_customer():void {$this->setupCompany();$p=$this->product();$this->sale(null,1,[[$p,100]]);$c=Customer::create(['name'=>'Named']);$this->sale($c,1,[[$p,100]]);$r=$this->refresh();$this->assertContains('missing_customer_identity',array_column($r['evidence']['health'],'code'));$this->assertSame(50,$r['evidence']['concentration']['top_shares'][1]);$this->assertSame(1,$r['evidence']['profiles'][0]['purchase_count']);}
 public function test_warehouse_only_role_cannot_read_tools_sources_or_customer_evidence():void {$this->setupCompany();$r=$this->refresh();$actor=Auth::user();$actor->update(['role'=>'staff']);Cache::forget('role_permissions:staff');$this->getJson('/api/customer-sales-intelligence')->assertForbidden();$this->postJson('/api/capabilities/get_sales_opportunities/execute',['input'=>[]])->assertForbidden();$this->assertFalse(app(AutomationRegistry::class)->canAccessSource('CustomerSalesSnapshot'));$this->assertNull(app(AutomationRegistry::class)->source('CustomerSalesSnapshot',$r['id']));}
 public function test_foreign_customer_and_prediction_are_tenant_isolated():void {$this->setupCompany();$foreign=Company::factory()->create();$id=DB::table('customers')->insertGetId(['company_id'=>$foreign->id,'name'=>'Foreign','is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);$this->getJson('/api/customer-sales-intelligence/customers/'.$id)->assertNotFound();$this->postJson('/api/customer-sales-intelligence/predictions/99999/review',['quantity'=>1])->assertNotFound();}
 public function test_future_predictions_freeze_deduplicate_and_only_genuine_later_sales_score():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,20);$r=$this->refresh();$count=CustomerSalesPrediction::count();$events=BusinessEvent::where('event_type','like','customer.intelligence.%')->count();$this->refresh();$this->assertSame($count,CustomerSalesPrediction::count());$this->assertSame($events,BusinessEvent::where('event_type','like','customer.intelligence.%')->count());$pred=CustomerSalesPrediction::first();$frozen=$pred->value;$this->assertNull($pred->evaluated_at);$this->travel(5)->days();$this->sale($c,0,[[$p,1800]]);$this->travel(6)->days();$this->refresh();$pred->refresh();$this->assertSame($frozen,$pred->value);$this->assertSame('purchase_in_window',$pred->evaluation['outcome']);$this->assertSame(1800,$pred->evaluation['subsequent_purchase']['quantity']);$this->assertSame(1,app(CustomerSalesIntelligenceService::class)->modelStatus()['genuine_timing_outcomes']);
 }
 public function test_no_retrospective_window_is_fabricated_after_it_already_expired():void {$this->setupCompany();$c=Customer::create(['name'=>'Old Buyer']);$p=$this->product();$this->history($c,$p,90);$this->refresh();$this->assertSame(0,CustomerSalesPrediction::where('prediction_type','reorder_window')->count());$this->assertSame(1,CustomerSalesPrediction::where('prediction_type','activity_window')->count());}
 public function test_unvalidated_challenger_is_not_promoted_and_snapshot_is_immutable():void {$this->setupCompany();$this->refresh();$this->postJson('/api/customer-sales-intelligence/model',['model'=>'median_mad','reason'=>'Try alternative'])->assertStatus(422);$this->expectException(\LogicException::class);CustomerSalesSnapshot::first()->update(['evidence'=>[]]);}
 public function test_finance_and_margin_are_redacted_without_separate_financial_permission():void {$this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,24);$this->refresh();$role=\App\Models\Role::where('slug','admin')->first();$role->permissions()->detach(\App\Models\Permission::where('slug','analytics.finance')->value('id'));Cache::forget('role_permissions:admin');$r=$this->getJson('/api/customer-sales-intelligence')->assertOk()->json();$this->assertArrayNotHasKey('gross_profit',$r['evidence']['profiles'][0]['summary']);$this->assertSame('restricted',$r['evidence']['opportunities'][0]['financial_context']['state']);}
 public function test_seasonality_requires_completed_years_and_repeated_pattern():void {$this->setupCompany();$math=app(CustomerSalesMath::class);$b=[['date'=>'2023-12-01','value'=>'100.00']];foreach([2024,2025] as $year)foreach([3,4] as $month)for($i=1;$i<=6;$i++)$b[]=['date'=>sprintf('%d-%02d-%02d',$year,$month,$i),'value'=>'100.00'];$s=$math->seasonality($b,today()->toDateString());$this->assertTrue($s['seasonal']);$this->assertTrue($s['off_season']);$this->assertFalse($math->seasonality(array_slice($b,1,12),today()->toDateString())['supported']);}
 public function test_late_return_is_separate_from_no_purchase_in_window():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,20);$this->refresh();$pred=CustomerSalesPrediction::where('prediction_type','reorder_window')->first();$frozen=$pred->value;$this->travel(11)->days();$this->refresh();$this->assertSame('no_purchase_in_window',$pred->fresh()->evaluation['outcome']);$this->travel(20)->days();$this->sale($c,0,[[$p,1700]]);$this->refresh();$pred->refresh();$this->assertSame('no_purchase_in_window',$pred->evaluation['outcome']);$this->assertSame(today()->toDateString(),$pred->evaluation['subsequent_purchase']['date']);$this->assertSame($frozen,$pred->value);
 }
 public function test_record_known_before_prediction_is_not_a_genuine_later_outcome():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$this->history($c,$p,20);$this->sale($c,-5,[[$p,100]]);$this->refresh();$this->travel(11)->days();$this->refresh();$this->assertSame(0,app(CustomerSalesIntelligenceService::class)->modelStatus()['genuine_timing_outcomes']);
 }
 public function test_challenger_needs_genuine_independent_timing_improvement_and_audited_rollback():void {
  $this->setupCompany();$p=$this->product();$customers=[];for($i=0;$i<20;$i++){$c=Customer::create(['name'=>'Buyer '.$i]);$customers[]=$c;$this->history($c,$p,20,6);}$this->refresh();$this->travel(5)->days();foreach($customers as $c)$this->sale($c,0,[[$p,1500]]);$this->travel(1)->days();$this->refresh();$status=app(CustomerSalesIntelligenceService::class)->modelStatus();$this->assertSame(20,$status['genuine_timing_outcomes']);$this->assertTrue($status['eligible_for_promotion']);$this->assertEquals(0,$status['challenger_mae_days']);$this->postJson('/api/customer-sales-intelligence/model',['model'=>'median_mad','reason'=>'Completed outcomes improve timing'])->assertOk()->assertJsonPath('model.champion','median_mad');$this->postJson('/api/customer-sales-intelligence/model',['model'=>'interval_iqr_baseline','reason'=>'Audited rollback to baseline'])->assertOk()->assertJsonPath('model.champion','interval_iqr_baseline');$this->assertDatabaseCount('customer_intelligence_policies',2);$this->assertDatabaseHas('audit_logs',['action'=>'customer.intelligence.model_selected']);
 }
 public function test_unknown_cogs_does_not_invent_gross_contribution_and_all_tools_are_registered():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);$p=$this->product();$sale=$this->sale($c,1,[[$p,100]]);$sale->items()->update(['cost_total'=>null]);$r=$this->refresh();$this->assertNull($r['evidence']['profiles'][0]['summary']['gross_profit']);foreach(['get_customer_intelligence','get_customer_activity','get_customer_reorder_opportunities','get_sales_opportunities','get_at_risk_customers','get_customer_product_affinity','get_sales_concentration','get_customer_trend'] as $tool)$this->postJson('/api/capabilities/'.$tool.'/execute',['input'=>['customer_id'=>$c->id]])->assertOk();
 }
}
