<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Cache,Auth};
use Illuminate\Support\Str;
use App\Models\{Product,Category,Supplier,ProductSupplier,Warehouse,WarehouseStock,AnalyticsSnapshot,PurchaseOrder,Shipment,StockTransfer,EnterpriseDecision,BusinessEvent,PurchaseRequest,FinancialAccount,Company,User};
use App\Services\{EnterpriseDecisionService,EnterpriseDecisionRanker,InventoryPlanningService,InventorySnapshotService,AimsToolRegistry,PortableBackupService};

class EnterpriseDecisionTest extends TestCase {
 use RefreshDatabase;
 private function product(bool $history=false):Product {
  $this->actingAsApiUser();$this->getJson('/api/me')->assertOk();$this->travelTo(now()->setDate(2026,10,4)->setTime(12,0));$c=Category::create(['name'=>'Hardware']);
  $p=Product::create(['name'=>'Door handles','sku'=>'DEC-1','category_id'=>$c->id,'unit'=>'pcs','quantity'=>5,'min_quantity'=>20,'high_stock_threshold'=>1000,'purchase_price'=>2,'price'=>5]);$p->forceFill(['created_at'=>now()->subYear()])->save();
  $s=Supplier::create(['name'=>'Reliable factory','is_active'=>true]);ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$s->id,'purchase_price'=>2,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>3,'pack_size'=>5,'minimum_order_quantity'=>10,'is_active'=>true]);
  if($history)for($d=1;$d<=90;$d++)AnalyticsSnapshot::create(['entity_type'=>'demand_observation','entity_id'=>$p->id,'warehouse_id'=>0,'snapshot_date'=>today()->subDays($d),'observed_at'=>today()->subDays($d)->endOfDay(),'feature_version'=>'observed-v2','facts'=>['unit'=>'pcs','demand'=>10,'sales_quantity'=>10,'returns_quantity'=>0,'available'=>100,'stockout'=>false,'quality'=>'observed','complete'=>true,'potentially_censored'=>false]]);
  return $p;
 }
 private function refresh(Product $p,?int $w=null):array {return $this->postJson('/api/analytics/decisions/products/'.$p->id.'/refresh',['warehouse_id'=>$w])->assertOk()->json('decisions');}
 private function counts():array {return collect(['stock_movements','purchase_orders','stock_transfers','journal_entries','financial_account_transactions'])->mapWithKeys(fn($t)=>[$t=>DB::table($t)->count()])->all();}
 public function test_sparse_evidence_uses_thresholds_and_never_fabricates_forecasts():void {
  $p=$this->product();$before=$this->counts();$rows=$this->refresh($p);$this->assertCount(2,$rows);$d=$this->getJson('/api/analytics/decisions/'.$rows[0]['id'])->assertOk()->assertJsonPath('confidence','limited')->assertJsonPath('evidence.forecast.available',false)->json();
  $this->assertEquals(15,$d['evidence']['required_quantity']);$this->assertEquals(15,$d['alternatives'][0]['base_quantity']);$this->assertContains('configured_threshold_not_forecast',$d['alternatives'][0]['assumptions']);$this->assertSame($before,$this->counts());$this->assertDatabaseCount('inventory_forecast_models',0);
 }
 public function test_rank_is_deterministic_unknown_is_not_zero_and_availability_dominates_price():void {
  $base=['action'=>'purchase','feasible'=>true,'base_quantity'=>100,'transfer_quantity'=>0,'supplier_risk'=>[],'impact'=>['stockout_days_after'=>0,'arrival'=>today()->addDays(3)->toDateString()]];
  $a=$base+['key'=>'cheap','base_cost'=>'100.00'];$a['impact']['arrival']=today()->addDays(35)->toDateString();$a['impact']['stockout_days_after']=30;$a['supplier_risk']=['late_delivery_percent'=>70,'quality_acceptance_percent'=>80];
  $b=$base+['key'=>'reliable','base_cost'=>'120.00'];$b['supplier_risk']=['late_delivery_percent'=>5,'quality_acceptance_percent'=>99];$ctx=['required'=>100,'forecast'=>true,'horizon'=>90,'stockout_date'=>today()->addDays(10)->toDateString(),'cash'=>1000];
  $rank=app(EnterpriseDecisionRanker::class)->rank([$a,$b],$ctx);$this->assertSame('reliable',$rank[0]['key']);$this->assertSame($rank,app(EnterpriseDecisionRanker::class)->rank([$a,$b],$ctx));
  $a['supplier_risk']=[];$r=app(EnterpriseDecisionRanker::class)->rank([$a],$ctx)[0];$this->assertEquals(.5,collect($r['score_components'])->firstWhere('criterion','delay')['risk']);
 }
 public function test_versioned_weights_are_bounded():void {
  $this->product();config(['enterprise_decisions.weights.cost'=>90]);$this->expectException(\LogicException::class);app(EnterpriseDecisionRanker::class)->rank([],['required'=>0]);
 }
 public function test_unchanged_decisions_deduplicate_events_and_material_changes_supersede():void {
  $p=$this->product();$first=$this->refresh($p);$events=BusinessEvent::where('event_type','like','intelligence.decision.%')->count();$again=$this->refresh($p);$this->assertSame(array_column($first,'id'),array_column($again,'id'));$this->assertEquals($events,BusinessEvent::where('event_type','like','intelligence.decision.%')->count());
  $old=EnterpriseDecision::find($first[0]['id']);$frozen=$old->evidence;ProductSupplier::first()->update(['purchase_price'=>3]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);$new=$this->refresh($p);$this->assertNotEquals($first[0]['id'],$new[0]['id']);$this->assertSame('superseded',$old->fresh()->status);$this->assertSame($frozen,$old->fresh()->evidence);$this->assertGreaterThan(0,BusinessEvent::where('event_type','intelligence.decision.materially_changed')->count());
 }
 public function test_stale_evidence_reduces_confidence_and_reads_do_not_recalculate():void {
  $p=$this->product(true);$row=$this->refresh($p)[0];$before=EnterpriseDecision::count();$this->travel(25)->hours();$this->getJson('/api/analytics/decisions/'.$row['id'])->assertOk()->assertJsonPath('stale',true)->assertJsonPath('confidence','limited');$this->getJson('/api/analytics/decisions')->assertOk();$this->assertEquals($before,EnterpriseDecision::count());
 }
 public function test_reviewed_threshold_pr_is_idempotent_and_revalidates():void {
  $p=$this->product();$id=$this->refresh($p)[0]['id'];$d=$this->getJson('/api/analytics/decisions/'.$id)->json();$key=$d['alternatives'][0]['key'];$review=$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>$key])->assertOk()->json();$before=$this->counts();
  $payload=['alternative_key'=>$key,'review_token'=>$review['review_token']];$created=$this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',$payload)->assertOk()->assertJsonPath('purchase_request.status','draft')->json('purchase_request.id');$this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',$payload)->assertOk()->assertJsonPath('reused',true)->assertJsonPath('purchase_request.id',$created);$this->assertDatabaseCount('purchase_requests',1);$this->assertSame($before,$this->counts());$this->assertSame('accepted',EnterpriseDecision::find($id)->status);
 }
 public function test_changed_operational_conditions_reject_stale_review_and_keep_history():void {
  $p=$this->product();$id=$this->refresh($p)[0]['id'];$key=EnterpriseDecision::find($id)->alternatives[0]['key'];$review=$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>$key])->assertOk()->json();$p->update(['quantity'=>2]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);
  $this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',['alternative_key'=>$key,'review_token'=>$review['review_token']])->assertStatus(409);$this->assertDatabaseCount('purchase_requests',0);$this->assertSame('reviewed',EnterpriseDecision::find($id)->status);
 }
 public function test_existing_request_prevents_another_and_feedback_records_no_operations():void {
  $p=$this->product();$id=$this->refresh($p)[0]['id'];$before=$this->counts();$this->postJson('/api/analytics/decisions/'.$id.'/feedback',['action'=>'reviewed','note'=>'Supplier called'])->assertOk()->assertJsonPath('status','reviewed');$this->postJson('/api/analytics/decisions/'.$id.'/feedback',['action'=>'dismissed','note'=>'No immediate need'])->assertOk();$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>'supplier-1'])->assertStatus(409);$this->assertSame($before,$this->counts());
 }
 public function test_simulation_is_non_mutating_and_reuses_v4():void {
  $p=$this->product(true);$id=$this->refresh($p)[0]['id'];$counts=$this->counts();$n=EnterpriseDecision::count();$this->postJson('/api/analytics/decisions/'.$id.'/simulate',['scenarios'=>[['base_quantity'=>200,'delay_days'=>2,'demand_multiplier'=>1.2]]])->assertOk()->assertJsonPath('read_only',true)->assertJsonPath('comparison.scenarios.0.base_quantity',200)->assertJsonPath('comparison.scenarios.0.logic_version','inventory-planning-v4.1');$this->assertSame($counts,$this->counts());$this->assertEquals($n,EnterpriseDecision::count());
 }
 public function test_incoming_risk_and_financial_context_are_authoritative_separate_sources():void {
  $p=$this->product();$supplier=ProductSupplier::first()->supplier_id;$po=PurchaseOrder::create(['supplier_id'=>$supplier,'po_number'=>'OPEN-10','status'=>'ordered','ordered_at'=>today(),'expected_at'=>today()->addDays(3),'due_at'=>today()->addDays(10),'total_amount'=>100,'total_paid'=>30,'currency'=>'EUR','exchange_rate'=>1]);$po->items()->create(['product_id'=>$p->id,'description'=>$p->name,'unit'=>'pcs','inventory_unit'=>'pcs','conversion_factor'=>1,'quantity'=>5,'base_quantity'=>5,'unit_price'=>20,'line_total'=>100]);Shipment::create(['purchase_order_id'=>$po->id,'tracking_number'=>'LATE-SEA','status'=>'in_transit','eta'=>today()->addDays(8),'transport_mode'=>'sea']);FinancialAccount::create(['type'=>'cash','name'=>'Till','currency'=>'EUR','opening_balance'=>1000,'opening_date'=>today(),'is_active'=>true]);
  $rows=$this->refresh($p);$risk=collect($rows)->firstWhere('decision_type','INCOMING_STOCK_RISK');$this->assertNotNull($risk);$d=$this->getJson('/api/analytics/decisions/'.$risk['id'])->assertOk()->json();$this->assertEquals('70.00',$d['evidence']['finance']['po_outstanding']);$this->assertEquals('100.00',$d['evidence']['finance']['open_po_commitments']);$this->assertEquals('1000.00',$d['evidence']['finance']['recorded_cash']);$this->assertSame('shipment_eta_late',$d['evidence']['procurement']['orders'][0]['reason']);$this->assertSame('uncertain',$d['evidence']['procurement']['orders'][0]['attribution']);
 }
 public function test_realistic_transfer_supplier_scenario_and_reviewed_draft():void {
  $p=$this->product(true);$safe=ProductSupplier::first()->supplier;$cheap=Supplier::create(['name'=>'Cheap slower','is_active'=>true]);ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$cheap->id,'purchase_price'=>1,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>30,'pack_size'=>10,'is_active'=>true]);
  $a=Warehouse::create(['name'=>'Main','code'=>'M','is_active'=>true]);$b=Warehouse::create(['name'=>'Reserve','code'=>'R','is_active'=>true]);WarehouseStock::create(['product_id'=>$p->id,'warehouse_id'=>$a->id,'location_key'=>0,'quantity'=>5,'available_quantity'=>5]);WarehouseStock::create(['product_id'=>$p->id,'warehouse_id'=>$b->id,'location_key'=>0,'quantity'=>300,'available_quantity'=>300]);
  for($day=1;$day<=90;$day++)foreach([[$a,10],[$b,2]] as [$w,$demand])AnalyticsSnapshot::create(['entity_type'=>'inventory','entity_id'=>$p->id,'warehouse_id'=>$w->id,'snapshot_date'=>today()->subDays($day),'observed_at'=>today()->subDays($day)->endOfDay(),'feature_version'=>'observed','facts'=>['unit'=>'pcs','available'=>100,'demand'=>$demand,'warehouse_demand_complete'=>true,'stockout'=>false,'complete'=>true]]);
  foreach(AnalyticsSnapshot::where('entity_type','demand_observation')->get() as $s){$facts=$s->facts;$facts['demand']=$facts['sales_quantity']=12;$facts['provenance']=['sales'=>['sale:'.$s->id]];DB::table('analytics_snapshots')->where('id',$s->id)->update(['facts'=>json_encode($facts)]);foreach([[$a,10],[$b,2]] as [$w,$qty])\App\Models\StockMovement::create(['product_id'=>$p->id,'warehouse_id'=>$w->id,'type'=>'out','quantity'=>$qty,'quantity_before'=>1000,'quantity_after'=>1000-$qty,'warehouse_quantity_after'=>100,'unit_snapshot'=>'pcs','movement_code'=>'daily_sale','source_type'=>'daily_sale','source_id'=>$s->id,'affects_company_quantity'=>true,'occurred_at'=>$s->snapshot_date->copy()->midDay()]);}
  for($j=0;$j<3;$j++)StockTransfer::create(['transfer_number'=>'OLD-'.$j,'source_warehouse_id'=>$b->id,'destination_warehouse_id'=>$a->id,'status'=>'received','dispatched_at'=>today()->subDays(10+$j),'received_at'=>today()->subDays(9+$j),'created_by'=>Auth::id()]);
  FinancialAccount::create(['type'=>'cash','name'=>'Till','currency'=>'EUR','opening_balance'=>5000,'opening_date'=>today(),'is_active'=>true]);$po=PurchaseOrder::create(['supplier_id'=>$cheap->id,'warehouse_id'=>$a->id,'po_number'=>'INCOMING-LOW','status'=>'ordered','ordered_at'=>today(),'expected_at'=>today()->addDays(45),'due_at'=>today()->addDays(30),'total_amount'=>50,'currency'=>'EUR','exchange_rate'=>1]);$po->items()->create(['product_id'=>$p->id,'description'=>$p->name,'unit'=>'pcs','inventory_unit'=>'pcs','conversion_factor'=>1,'quantity'=>50,'base_quantity'=>50,'unit_price'=>1,'line_total'=>50]);Shipment::create(['purchase_order_id'=>$po->id,'tracking_number'=>'LATE-INCOMING','eta'=>today()->addDays(50),'status'=>'in_transit','transport_mode'=>'sea']);
  $before=$this->counts();$rows=$this->refresh($p,$a->id);$id=collect($rows)->firstWhere('decision_type','TRANSFER_VS_PURCHASE')['id'];$detail=$this->getJson('/api/analytics/decisions/'.$id)->assertOk()->json();$this->assertCount(2,$detail['evidence']['supplier_options']);$this->assertNotEmpty($detail['evidence']['transfers']);$this->assertTrue($detail['evidence']['forecast']['available']);$best=$detail['alternatives'][0];$this->assertGreaterThan(0,$best['transfer_quantity']);$this->assertSame($safe->id,$best['supplier_id']);$this->assertSame('transfer_purchase',$best['action']);
  $this->postJson('/api/analytics/decisions/'.$id.'/simulate',['scenarios'=>[['supplier_id'=>$cheap->id,'base_quantity'=>300,'delay_days'=>5]]])->assertOk();$review=$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>$best['key']])->assertOk()->json();$payload=['alternative_key'=>$best['key'],'review_token'=>$review['review_token']];$this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',$payload)->assertStatus(422);$this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',$payload+['confirm_transfer_assumption'=>true])->assertOk();$this->assertSame($before,$this->counts());$this->assertDatabaseCount('purchase_requests',1);$this->assertNotEmpty(EnterpriseDecision::find($id)->history);
 }
 public function test_company_isolation_permissions_tools_and_safe_redaction():void {
  $p=$this->product();$id=$this->refresh($p)[0]['id'];$names=array_column(app(AimsToolRegistry::class)->catalog(),'name');$this->assertContains('get_open_decisions',$names);$before=EnterpriseDecision::count();$this->assertSame($id,app(AimsToolRegistry::class)->execute('get_decision',['decision_id'=>$id])['data']['id']);$this->assertEquals($before,EnterpriseDecision::count());
  $other=Company::factory()->create();User::factory()->create(['company_id'=>$other->id,'role'=>'admin','email_verified_at'=>now(),'api_token'=>hash('sha256','decision-other')]);$this->withToken('decision-other')->getJson('/api/analytics/decisions/'.$id)->assertNotFound();$this->postJson('/api/analytics/decisions/products/'.$p->id.'/refresh')->assertNotFound();
  $this->withToken('test-token-admin')->getJson('/api/me')->assertOk();$role=\App\Models\Role::where('slug','admin')->first();$permission=\App\Models\Permission::where('slug','analytics.finance')->first();$role->permissions()->detach($permission->id);Cache::forget('role_permissions:admin');$safe=$this->getJson('/api/analytics/decisions/'.$id)->assertOk()->json();$this->assertArrayNotHasKey('finance',$safe['evidence']);$this->assertArrayNotHasKey('base_cost',$safe['alternatives'][0]);$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>$safe['alternatives'][0]['key']])->assertForbidden();
 }
 public function test_excess_and_resolved_lifecycle():void {
  $p=$this->product();$rows=$this->refresh($p);$id=$rows[0]['id'];$p->update(['quantity'=>2000]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);$rows=$this->refresh($p);$this->assertSame('resolved',EnterpriseDecision::find($id)->status);$this->assertSame('EXCESS_INVENTORY_ACTION',$rows[0]['decision_type']);$this->assertEquals(1000,$rows[0]['evidence']['excess_quantity']);
 }
 public function test_decisions_portable_restore_preserves_archive_not_actionable_predictions():void {
  $p=$this->product();$this->refresh($p);$export=app(PortableBackupService::class)->export(['analytics','categories','products','suppliers','warehouses'])->getContent();$other=Company::factory()->create();User::factory()->create(['company_id'=>$other->id,'role'=>'admin','email_verified_at'=>now(),'api_token'=>hash('sha256','decisions-restore')]);$this->withToken('decisions-restore')->getJson('/api/me')->assertOk();$file=\Illuminate\Http\UploadedFile::fake()->createWithContent('decisions.json',$export);$this->post('/api/backup/import',['file'=>$file,'mode'=>'merge'])->assertOk();$d=EnterpriseDecision::where('company_id',$other->id)->firstOrFail();$this->assertSame('superseded',$d->status);$this->assertTrue($d->evidence['archived']);$this->getJson('/api/analytics/decisions/'.$d->id)->assertOk()->assertJsonPath('can_act',false);
 }
 public function test_financial_attention_filter_is_numeric_and_does_not_leak_unpriced_values():void {
  $p=$this->product();$this->refresh($p);$this->getJson('/api/analytics/decisions?view=finance')->assertOk()->assertJsonPath('total',0);config(['enterprise_decisions.high_commitment'=>25]);$this->getJson('/api/analytics/decisions?view=finance')->assertOk()->assertJsonPath('total',2);
 }
 public function test_different_decision_cannot_duplicate_an_open_pr_and_scope_feedback_is_guarded():void {
  $p=$this->product();$rows=$this->refresh($p);$id=$rows[0]['id'];$key=EnterpriseDecision::find($id)->alternatives[0]['key'];$review=$this->postJson('/api/analytics/decisions/'.$id.'/review',['alternative_key'=>$key])->assertOk()->json();$this->postJson('/api/analytics/decisions/'.$id.'/purchase-request',['alternative_key'=>$key,'review_token'=>$review['review_token']])->assertOk();$other=$rows[1]['id'];$review=$this->postJson('/api/analytics/decisions/'.$other.'/review',['alternative_key'=>$key])->assertOk()->json();$this->postJson('/api/analytics/decisions/'.$other.'/purchase-request',['alternative_key'=>$key,'review_token'=>$review['review_token']])->assertStatus(409);$this->assertDatabaseCount('purchase_requests',1);
 }
 public function test_background_reconciliation_is_bounded_and_outcomes_remain_observational():void {
  $p=$this->product();$before=$this->counts();$service=app(EnterpriseDecisionService::class);EnterpriseDecisionService::invalidate($p->company_id,[$p->id]);$this->assertEquals(1,$service->scheduled());$this->assertEmpty(Cache::get('decisions-dirty:'.$p->company_id));$this->assertSame(0,$service->scheduled());$d=EnterpriseDecision::firstOrFail();$out=$service->collectOutcome($d);$this->assertSame('pending_or_incomplete',$out['state']);$this->assertNull($out['stockout_occurred']);$this->assertNull($out['quality_issue_occurred']);$this->assertNull($out['excess_stock_occurred']);$this->assertSame('observational_only_not_causal',$out['qualification']);$this->assertSame($before,$this->counts());
 }
 public function test_bounded_worker_continues_remaining_warehouse_scopes_without_starving_them():void {
  $p=$this->product();for($i=1;$i<=6;$i++){$w=Warehouse::create(['name'=>'Depot '.$i,'code'=>'D'.$i,'is_active'=>true]);WarehouseStock::create(['product_id'=>$p->id,'warehouse_id'=>$w->id,'quantity'=>1,'available_quantity'=>1]);}$s=app(EnterpriseDecisionService::class);EnterpriseDecisionService::invalidate($p->company_id,[$p->id]);$s->scheduled();$this->assertEquals(5,EnterpriseDecision::whereNotNull('warehouse_id')->distinct()->count('warehouse_id'));$this->assertContains($p->id,Cache::get('decisions-dirty:'.$p->company_id));$s->scheduled();$this->assertEquals(6,EnterpriseDecision::whereNotNull('warehouse_id')->distinct()->count('warehouse_id'));$this->assertEmpty(Cache::get('decisions-dirty:'.$p->company_id));
 }
}
