<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{Auth,DB,Cache};
use App\Models\{Customer,CustomerDebtTransaction,FinancialAccount,FinancialAccountTransaction,Supplier,PurchaseOrder,Expense,ExpensePayment,Invoice,PurchaseRequest,Category,Product,Warehouse,WarehouseStock,Shipment,ShipmentIntelligence,FinancialIntelligenceSnapshot,FinancialIntelligenceObservation,Company,User,BusinessEvent};
use App\Services\{FinancialIntelligenceService,FinancialIntelligenceScenario,FinancialPaymentTiming,LocalFinancialTimingProvider,AnalyticsPermissions};

class FinancialIntelligenceTest extends TestCase {
 use RefreshDatabase;
 public function test_dashboard_summary_preserves_authoritative_cash_and_default_response():void {
  $this->setupCompany();$this->cash('100.10');$this->refresh();
  $full=$this->getJson('/api/financial-intelligence?horizon=30')->assertOk()->json();
  $summary=$this->getJson('/api/financial-intelligence?horizon=30&summary_only=1')->assertOk()->json();
  $this->assertSame($full['id'],$summary['id']);$this->assertSame($full['forecast']['currencies']['EUR']['expected_closing_cash'],$summary['forecast']['currencies']['EUR']['expected_closing_cash']);
  $this->assertArrayHasKey('evidence',$full);$this->assertArrayNotHasKey('evidence',$summary);$this->assertArrayNotHasKey('timeline',$summary['forecast']['currencies']['EUR']);
  $this->getJson('/api/financial-intelligence?summary_only=bad')->assertStatus(422);
 }
 private function setupCompany():void {
  $this->actingAsApiUser();$this->getJson('/api/me')->assertOk();AnalyticsPermissions::install();$this->travelTo(now()->setDate(2026,10,4)->setTime(12,0));
  app()->instance(LocalFinancialTimingProvider::class,new class {public function analyze(array $c):array{return ['state'=>'test_local_adapter','customers'=>[]];}});
 }
 private function debt(Customer $c,string $amount,string $due,?int $invoice=null,?string $date=null):CustomerDebtTransaction {
  return CustomerDebtTransaction::create(['customer_id'=>$c->id,'user_id'=>Auth::id(),'type'=>'debt_added','source'=>'manual','amount'=>$amount,'balance_before'=>0,'balance_after'=>$amount,'credit_before'=>0,'credit_after'=>0,'transaction_date'=>$date??today()->toDateString(),'due_date'=>$due,'invoice_id'=>$invoice]);
 }
 private function payment(Customer $c,string $amount,?string $date=null):void {CustomerDebtTransaction::create(['customer_id'=>$c->id,'user_id'=>Auth::id(),'type'=>'payment','source'=>'manual','amount'=>$amount,'balance_before'=>$amount,'balance_after'=>0,'credit_before'=>0,'credit_after'=>0,'transaction_date'=>$date??today()->toDateString()]);}
 private function cash(string $amount='80000',string $currency='EUR'):FinancialAccount{return FinancialAccount::create(['name'=>'Company cash '.$currency,'type'=>'cash','currency'=>$currency,'opening_balance'=>$amount,'opening_date'=>today(),'is_active'=>true]);}
 private function po(Supplier $s,string $amount='28000'):PurchaseOrder{return PurchaseOrder::create(['supplier_id'=>$s->id,'po_number'=>'PO-'.PurchaseOrder::count(),'status'=>'ordered','total_amount'=>$amount,'currency'=>'EUR','total_paid'=>0,'ordered_at'=>today(),'due_at'=>today()->addDays(7)]);}
 private function expense(Supplier $s,string $amount,?PurchaseOrder $po=null):Expense{return Expense::create(['supplier_id'=>$s->id,'vendor_name'=>$s->name,'vendor_key'=>'supplier-'.$s->id,'document_type'=>'purchase_invoice','document_number'=>'DOC-'.Expense::count(),'document_number_normalized'=>'DOC-'.Expense::count(),'status'=>'posted','invoice_date'=>today(),'received_date'=>today(),'due_date'=>today()->addDays(5),'currency'=>'EUR','exchange_rate'=>1,'gross_amount'=>$amount,'gross_amount_eur'=>$amount,'net_amount'=>$amount,'net_amount_eur'=>$amount,'vat_amount'=>0,'purchase_order_id'=>$po?->id,'created_by'=>Auth::id()]);}
 private function refresh():array{try{return $this->withoutExceptionHandling()->postJson('/api/financial-intelligence/refresh')->assertOk()->json();}finally{$this->withExceptionHandling();}}
 private function businessState():array{return collect(['journal_entries','journal_lines','financial_account_transactions','customer_debt_transactions','purchase_orders','stock_movements','expenses'])->mapWithKeys(fn($t)=>[$t=>DB::table($t)->orderBy('id')->get()->toJson()])->all();}
 public function test_remaining_receivable_partial_payment_and_advance_are_not_double_counted():void {
  $this->setupCompany();$this->cash();$c=Customer::create(['name'=>'Buyer','current_debt'=>4000,'current_credit'=>700]);$invoice=Invoice::create(['invoice_number'=>'INV-X','customer_id'=>$c->id,'customer_name'=>$c->name,'document_type'=>'invoice','status'=>'issued','currency'=>'EUR','invoice_date'=>today(),'due_at'=>today()->addDays(10),'grand_total'=>10000,'total_amount'=>10000,'total_paid'=>6000]);$this->debt($c,'10000',today()->addDays(10)->toDateString(),$invoice->id);$this->payment($c,'6000');$before=$this->businessState();$r=$this->refresh();
  $this->assertCount(1,$r['evidence']['receivables']);$this->assertSame('4000.00',$r['forecast']['currencies']['EUR']['inflows']);$this->assertSame('84000.00',$r['forecast']['currencies']['EUR']['expected_closing_cash']);$this->assertSame('700.00',$r['evidence']['customers'][0]['advance']);$this->assertSame($before,$this->businessState());
 }
 public function test_supplier_document_po_deposit_and_direct_payment_reconcile_once():void {
  $this->setupCompany();$this->cash();$s=Supplier::create(['name'=>'Factory']);$po=$this->po($s,'20000');$x=$this->expense($s,'10000',$po);ExpensePayment::create(['expense_id'=>$x->id,'amount'=>5000,'amount_eur'=>5000,'status'=>'completed','payment_date'=>today(),'payment_method'=>'cash','created_by'=>Auth::id()]);
  PurchaseRequest::create(['request_number'=>'PR-1','status'=>'draft','currency'=>'EUR','estimated_total'=>24000,'requested_at'=>today(),'requested_by'=>Auth::id()]);$r=$this->refresh();
  $this->assertSame('15000.00',$r['forecast']['currencies']['EUR']['outflows']);$this->assertCount(2,$r['evidence']['commitments']);$this->assertFalse($r['evidence']['potential'][0]['included_in_forecast']);$this->assertSame('65000.00',$r['forecast']['currencies']['EUR']['expected_closing_cash']);
  $this->assertSame('5000.00',$r['evidence']['payable_observations'][0]['payments'][0]['amount']);$this->assertSame(today()->toDateString(),$r['evidence']['payable_observations'][0]['payments'][0]['payment_date']);$this->assertSame($r['evidence']['payable_observations'],FinancialIntelligenceObservation::first()->facts['payables']);
 }
 public function test_po_allocated_deposit_is_not_subtracted_twice():void {
  $this->setupCompany();$this->cash();$s=Supplier::create(['name'=>'Factory']);$po=$this->po($s,'20000');$po->update(['total_paid'=>6000]);$x=$this->expense($s,'20000',$po);
  $pay=\App\Models\PurchaseOrderPayment::create(['purchase_order_id'=>$po->id,'amount'=>6000,'amount_eur'=>6000,'currency'=>'EUR','payment_date'=>today(),'paid_at'=>now(),'payment_method'=>'cash','user_id'=>Auth::id(),'status'=>'completed']);\App\Models\SupplierInvoicePaymentAllocation::create(['purchase_order_payment_id'=>$pay->id,'expense_id'=>$x->id,'amount'=>6000,'allocated_by'=>Auth::id(),'allocated_at'=>now(),'reason'=>'Deposit']);
  $r=$this->refresh();$this->assertCount(1,$r['evidence']['commitments']);$this->assertSame('14000.00',$r['forecast']['currencies']['EUR']['outflows']);
 }
 public function test_currency_unknown_opening_and_no_fake_working_capital():void {
  $this->setupCompany();$this->cash('100.10');$this->cash('250','USD');$s=Supplier::create(['name'=>'Factory']);$x=$this->expense($s,'10.05');$x->update(['currency'=>'GBP']);$r=$this->refresh();$this->assertSame('100.10',$r['forecast']['currencies']['EUR']['opening_recorded_cash']);$this->assertSame('250.00',$r['forecast']['currencies']['USD']['opening_recorded_cash']);$this->assertNull($r['forecast']['currencies']['GBP']['opening_recorded_cash']);$this->assertSame('-10.05',$r['forecast']['currencies']['GBP']['net_change']);$this->assertNull($r['evidence']['working_capital']['cash_conversion_cycle']);$this->assertFalse($r['evidence']['cash']['complete']);$this->assertNull($r['forecast']['currencies']['EUR']['range']);
 }
 public function test_scenarios_are_non_mutating_fixed_precision_and_immediate_cash_pressure():void {
  $this->setupCompany();$this->cash('100.10');$this->refresh();$before=$this->businessState();$r=$this->postJson('/api/financial-intelligence/scenarios',['currency'=>'EUR','purchase_amount'=>'100.11'])->assertOk()->json();$this->assertSame('-0.01',$r['scenario']['currencies']['EUR']['expected_closing_cash']);$this->assertNotEmpty($r['scenario']['currencies']['EUR']['pressure']);$this->assertTrue($r['read_only']);$this->assertSame($before,$this->businessState());$this->assertDatabaseCount('financial_intelligence_snapshots',1);
 }
 public function test_sparse_missing_due_dates_and_unknown_valuation_are_not_zero_predictions():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer','current_debt'=>200]);$d=$this->debt($c,'200',today()->addDays(10)->toDateString());$d->update(['due_date'=>null]);$r=$this->refresh();$this->assertNull($r['evidence']['receivables'][0]['expected_date']);$this->assertSame('INSUFFICIENT_DATA',$r['evidence']['receivables'][0]['risk']);$this->assertSame('0.00',$r['forecast']['currencies']['EUR']['inflows']);$this->assertNull($r['forecast']['currencies']['EUR']['expected_closing_cash']);$this->assertContains('receivables_undated',array_column($r['evidence']['health'],'code'));
 }
 public function test_inventory_reuses_existing_value_and_warehouse_weighted_cost():void {
  $this->setupCompany();$cat=Category::create(['name'=>'Hardware']);$p=Product::create(['name'=>'Handles','sku'=>'FI-1','unit'=>'pcs','quantity'=>100,'category_id'=>$cat->id,'price'=>5,'purchase_price'=>2,'weighted_average_cost'=>3,'inventory_value'=>300]);$w=Warehouse::create(['name'=>'North','code'=>'N','is_active'=>true]);WarehouseStock::create(['product_id'=>$p->id,'warehouse_id'=>$w->id,'location_key'=>0,'quantity'=>60,'available_quantity'=>60]);$r=$this->refresh();$this->assertSame('300.00',$r['evidence']['inventory']['total']);$this->assertSame('180.00',$r['evidence']['inventory']['warehouses']['North']);$this->assertSame('300.000000',$p->fresh()->inventory_value);
 }
 public function test_payment_history_is_completed_cash_only_and_transparent():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Late buyer']);for($i=0;$i<5;$i++){$due=today()->subDays(80-$i*12);$this->debt($c,'100',$due->toDateString(),null,$due->copy()->subDays(5)->toDateString());$this->payment($c,'100',$due->copy()->addDays(10)->toDateString());}$h=app(FinancialPaymentTiming::class)->history($c);$this->assertTrue($h['eligible']);$this->assertEquals(10,$h['median_delay']);$this->assertSame('frequently_late',$h['segment']);$r=app(FinancialPaymentTiming::class)->predict(today()->addDays(5)->toDateString(),$h,'historical_median');$this->assertSame(today()->addDays(15)->toDateString(),$r['expected_date']);$this->assertSame('WATCH',$r['risk']);
 }
 public function test_predictions_freeze_events_deduplicate_and_future_windows_are_not_scored():void {
  $this->setupCompany();$this->cash();$s=Supplier::create(['name'=>'Factory']);$this->po($s);$r=$this->refresh();$before=BusinessEvent::where('event_type','like','finance.intelligence.%')->count();$again=$this->refresh();$this->assertSame($r['id'],$again['id']);$this->assertEquals($before,BusinessEvent::where('event_type','like','finance.intelligence.%')->count());$this->assertNull($again['evaluation']);$f=FinancialIntelligenceSnapshot::find($r['id']);$this->expectException(\LogicException::class);$f->update(['forecast'=>[]]);
 }
 public function test_tools_and_routes_are_finance_guarded_and_tenant_scoped():void {
  $this->setupCompany();$this->cash('100');$c=Customer::create(['name'=>'Buyer']);$r=$this->refresh();$this->postJson('/api/capabilities/get_cash_forecast/execute',['input'=>['horizon'=>7]])->assertOk()->assertJsonPath('data.id',$r['id']);
  $foreign=Company::factory()->create();$foreignCustomer=Customer::withoutGlobalScopes()->create(['company_id'=>$foreign->id,'name'=>'Foreign']); // Creating under Auth forcibly binds company; insert via query for tenant fixture.
  DB::table('customers')->where('id',$foreignCustomer->id)->update(['company_id'=>$foreign->id]);$this->postJson('/api/capabilities/get_receivable_intelligence/execute',['input'=>['customer_id'=>$foreignCustomer->id]])->assertNotFound();
  $actor=User::where('api_token',hash('sha256','test-token-admin'))->first();$actor->update(['role'=>'staff']);Cache::forget('permissions:role:staff');$this->getJson('/api/financial-intelligence')->assertForbidden();$this->postJson('/api/capabilities/get_cash_forecast/execute',['input'=>[]])->assertForbidden();
 }
 public function test_arrival_shift_requires_documented_related_terms_and_v6_warehouse_eta():void {
  $this->setupCompany();$this->cash();$s=Supplier::create(['name'=>'Factory']);$po=$this->po($s);$ship=Shipment::create(['tracking_number'=>'ARRIVAL-FI','purchase_order_id'=>$po->id,'transport_mode'=>'sea','status'=>'in_transit']);ShipmentIntelligence::create(['shipment_id'=>$ship->id,'version'=>'fi-eta','fingerprint'=>str_repeat('a',64),'risk'=>'DELAYED','confidence'=>'moderate','eta'=>['target'=>'warehouse','predicted'=>today()->addDays(20)->toDateString()],'evidence'=>[],'impact'=>[],'alternatives'=>[],'generated_at'=>now(),'evidence_cutoff'=>now(),'checked_at'=>now()]);
  $r=$this->refresh();$this->assertSame(today()->addDays(7)->toDateString(),$r['evidence']['commitments'][0]['expected_date']);$this->putJson('/api/financial-intelligence/policy',['terms'=>['po:'.$po->id=>['basis'=>'arrival','reference'=>'Signed contract clause 5','shipment_id'=>$ship->id,'offset_days'=>2]]])->assertOk();$r=$this->refresh();$this->assertSame(today()->addDays(22)->toDateString(),$r['evidence']['commitments'][0]['expected_date']);$scenario=$this->postJson('/api/financial-intelligence/scenarios',['currency'=>'EUR','arrival_delay_days'=>14,'horizon'=>60])->assertOk()->json();$this->assertSame(today()->addDays(36)->toDateString(),$scenario['scenario']['currencies']['EUR']['timeline'][0]['date']);$this->assertSame(today()->addDays(7)->toDateString(),$po->fresh()->due_at->toDateString());
 }
 public function test_unqualified_challenger_cannot_be_promoted():void {$this->setupCompany();$this->refresh();$this->postJson('/api/financial-intelligence/model',['model'=>'historical_median','reason'=>'Try better timing'])->assertStatus(422);$this->assertSame('due_date_baseline',app(FinancialIntelligenceService::class)->modelStatus()['champion']);}
 public function test_cash_evaluation_requires_matching_completed_point_in_time_window():void {
  $this->setupCompany();$this->cash('80000');$first=$this->refresh();$frozen=$first['forecast'];$this->travel(7)->days();$this->refresh();$this->assertEmpty(FinancialIntelligenceSnapshot::find($first['id'])->evaluation['cash']);$this->travel(1)->days();$this->refresh();$evaluated=FinancialIntelligenceSnapshot::find($first['id']);$this->assertSame('0.00',$evaluated->evaluation['cash'][7]['currencies']['EUR']['absolute_error']);$this->assertSame($frozen,$evaluated->forecast[30]);$this->assertArrayNotHasKey(30,$evaluated->evaluation['cash']);
 }
 public function test_future_posted_cash_movements_are_scheduled_not_opening_cash():void {
  $this->setupCompany();$account=$this->cash('100.10');FinancialAccountTransaction::create(['financial_account_id'=>$account->id,'type'=>'inflow','amount'=>'12.05','currency'=>'EUR','transaction_date'=>today()->addDays(3),'status'=>'posted','created_by'=>Auth::id(),'idempotency_key'=>'future-cash-test']);$r=$this->refresh();$this->assertSame('100.10',$r['forecast']['currencies']['EUR']['opening_recorded_cash']);$this->assertSame('12.05',$r['forecast']['currencies']['EUR']['inflows']);$this->assertSame('112.15',$r['forecast']['currencies']['EUR']['expected_closing_cash']);
 }
 public function test_split_scenario_validates_permission_constraints_and_string_form_dates():void {
  $this->setupCompany();$this->cash();$cat=Category::create(['name'=>'Hardware']);$s=Supplier::create(['name'=>'Factory','is_active'=>true]);$p=Product::create(['name'=>'Handles','sku'=>'SPLIT-FI','category_id'=>$cat->id,'supplier_id'=>$s->id,'unit'=>'pcs','quantity'=>5,'min_quantity'=>20,'price'=>5,'purchase_price'=>3]);\App\Models\ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$s->id,'purchase_price'=>3,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>7,'pack_size'=>5,'minimum_order_quantity'=>10,'is_active'=>true]);$this->refresh();$payload=['currency'=>'EUR','product_id'=>(string)$p->id,'supplier_id'=>(string)$s->id,'base_quantity'=>'100','split_quantity'=>'50','split_delay_days'=>'10','collection_delay_days'=>'5'];$this->postJson('/api/financial-intelligence/scenarios',$payload)->assertStatus(422);$this->putJson('/api/financial-intelligence/policy',['split_permissions'=>[$s->id=>['allowed'=>true,'reference'=>'Signed supplier agreement']]])->assertOk();$this->refresh();$before=$this->businessState();$r=$this->withoutExceptionHandling()->postJson('/api/financial-intelligence/scenarios',$payload)->assertOk()->json();$this->withExceptionHandling();$this->assertSame('300.00',$r['purchase_commitment']);$this->assertCount(2,$r['scenario']['currencies']['EUR']['timeline']);$this->assertSame($before,$this->businessState());$this->postJson('/api/financial-intelligence/scenarios',array_replace($payload,['split_quantity'=>'4']))->assertStatus(422);
 }
 public function test_invoice_documenting_a_daily_sale_does_not_repeat_its_ledger_receivable():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer','current_debt'=>50]);$sale=\App\Models\DailySale::create(['sale_number'=>'FI-SALE','sale_date'=>today(),'customer_id'=>$c->id,'customer_name'=>$c->name,'total_amount'=>100,'paid_amount'=>50,'created_by'=>Auth::id()]);$debt=$this->debt($c,'100',today()->addDays(5)->toDateString());$debt->update(['daily_sale_id'=>$sale->id]);$this->payment($c,'50');Invoice::create(['invoice_number'=>'FI-SALE-DOC','customer_id'=>$c->id,'customer_name'=>$c->name,'daily_sale_id'=>$sale->id,'document_type'=>'invoice','status'=>'issued','currency'=>'EUR','invoice_date'=>today(),'due_at'=>today()->addDays(5),'grand_total'=>100,'total_amount'=>100,'total_paid'=>50]);$r=$this->refresh();$this->assertCount(1,$r['evidence']['receivables']);$this->assertSame('50.00',$r['evidence']['totals']['EUR']['recorded_receivables']);$this->assertSame('50.00',$r['evidence']['receivables'][0]['allocated_reduction']);$this->assertSame('50.00',$r['evidence']['customers'][0]['recorded_payments'][0]['amount']);$this->assertSame(today()->toDateString(),$r['evidence']['customers'][0]['recorded_payments'][0]['payment_date']);
 }
 public function test_finance_sources_and_tasks_require_cash_permission_not_just_analytics_permission():void {
  $this->setupCompany();$this->cash();$r=$this->refresh();$registry=app(\App\Services\AutomationRegistry::class);$this->assertNotNull($registry->url('FinancialIntelligenceSnapshot',$r['id']));$role=\App\Models\Role::where('slug','admin')->first();$role->permissions()->detach(\App\Models\Permission::where('slug','financial_accounts.view')->value('id'));Cache::forget('role_permissions:admin');$this->assertFalse($registry->canAccessSource('FinancialIntelligenceSnapshot'));$this->assertNull($registry->url('FinancialIntelligenceSnapshot',$r['id']));$this->assertNull($registry->source('FinancialIntelligenceSnapshot',$r['id']));$this->assertCount(0,app(\App\Services\ActionCenterService::class)->tasks(['source_type'=>'FinancialIntelligenceSnapshot'])->items());$this->getJson('/api/financial-intelligence')->assertForbidden();
 }
 public function test_challenger_uses_independent_completed_outcomes_and_supports_audited_rollback():void {
  $this->setupCompany();$c=Customer::create(['name'=>'Buyer']);for($i=0;$i<5;$i++){$due=today()->subDays(80-$i*12);$this->debt($c,'100',$due->toDateString(),null,$due->copy()->subDays(5)->toDateString());$this->payment($c,'100',$due->copy()->addDays(10)->toDateString());}for($i=0;$i<20;$i++)$this->debt($c,'100',today()->addDays(5)->toDateString());$c->update(['current_debt'=>2000]);$this->refresh();$this->travel(15)->days();$this->payment($c,'2000');$c->update(['current_debt'=>0]);$this->refresh();$status=app(FinancialIntelligenceService::class)->modelStatus();$this->assertSame(20,$status['completed_observations']);$this->assertTrue($status['eligible_for_promotion']);$this->assertEquals(10,$status['baseline_mae_days']);$this->assertEquals(0,$status['challenger_mae_days']);$this->postJson('/api/financial-intelligence/model',['model'=>'historical_median','reason'=>'Completed outcomes improve timing'])->assertOk()->assertJsonPath('model.champion','historical_median');$this->postJson('/api/financial-intelligence/model',['model'=>'due_date_baseline','reason'=>'Audited rollback to due date'])->assertOk()->assertJsonPath('model.champion','due_date_baseline');$this->assertDatabaseCount('financial_intelligence_policies',2);$this->assertDatabaseHas('audit_logs',['action'=>'finance.intelligence.model_selected']);
 }
 public function test_v5_keeps_financial_purchase_tradeoffs_advisory_and_preserves_operational_rank():void {
  $this->setupCompany();$this->cash('1000');$this->refresh();$cat=Category::create(['name'=>'Hardware']);$s=Supplier::create(['name'=>'Factory','is_active'=>true]);$p=Product::create(['name'=>'Handles','sku'=>'V7-V5','category_id'=>$cat->id,'supplier_id'=>$s->id,'unit'=>'pcs','quantity'=>5,'min_quantity'=>20,'price'=>5,'purchase_price'=>3]);\App\Models\ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$s->id,'purchase_price'=>3,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>7,'pack_size'=>5,'minimum_order_quantity'=>10,'is_active'=>true]);$before=$this->businessState();$e=app(\App\Services\EnterpriseDecisionEvidence::class)->assemble($p->id);$finance=$e['evidence']['financial_intelligence'];$purchase=collect($finance['purchase_tradeoffs'])->firstWhere('action','purchase');$this->assertNotNull($purchase);$this->assertSame('45.00',$purchase['additional_purchase']);$this->assertSame('955.00',$purchase['expected_cash_if_paid_within_horizon']);$this->assertSame(array_column($e['alternatives'],'key'),array_column($finance['purchase_tradeoffs'],'key'));$this->assertFalse($purchase['coverage_supported']);$this->assertSame($before,$this->businessState());
 }
}
