<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{Auth,DB,Queue,Cache};
use App\Models\{Product,Category,Supplier,ProductSupplier,AnalyticsSnapshot,SupplyOptimizationPlan as Plan,Company,User,PurchaseOrder,PurchaseRequest,StockTransfer,Warehouse,WarehouseStock,OperationalTask,DecisionLearningRecord};
use App\Services\{SupplyOptimizerService as Optimizer,SupplyOptimizationData,SupplyOptimizationCandidates,LocalSupplyOptimizer,AimsToolRegistry,InventoryPlanningService};

class SupplyOptimizerTest extends TestCase {
 use RefreshDatabase;
 private function setupProduct(bool $history=true):Product {
  $this->actingAsApiUser();$this->getJson('/api/me')->assertOk();Queue::fake();$this->travelTo(now()->setDate(2026,10,6)->setTime(12,0));
  $c=Category::create(['name'=>'Hardware']);$p=Product::create(['name'=>'Door handles','sku'=>'OPT-1','category_id'=>$c->id,'unit'=>'pcs','quantity'=>50,'min_quantity'=>20,'high_stock_threshold'=>5000,'purchase_price'=>2,'price'=>5]);$p->forceFill(['created_at'=>now()->subYear()])->save();
  $s=Supplier::create(['name'=>'Factory A','is_active'=>true]);ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$s->id,'purchase_price'=>2,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>3,'pack_size'=>5,'minimum_order_quantity'=>10,'is_active'=>true]);
  if($history)$this->history($p,0);return $p;
 }
 private function history(Product $p,int $w):void {for($d=1;$d<=90;$d++)AnalyticsSnapshot::create(['entity_type'=>'demand_observation','entity_id'=>$p->id,'warehouse_id'=>$w,'snapshot_date'=>today()->subDays($d),'observed_at'=>today()->subDays($d)->endOfDay(),'feature_version'=>'observed-v2','facts'=>['unit'=>'pcs','demand'=>10,'sales_quantity'=>10,'returns_quantity'=>0,'available'=>100,'stockout'=>false,'quality'=>'observed','complete'=>true,'potentially_censored'=>false]]);}
 private function scope(Product $p,array $extra=[]):array {return array_replace(['horizon'=>30,'product_ids'=>[$p->id],'commitment_limit'=>'800.00'],$extra);}
 private function plan(Product $p,array $extra=[]):Plan {$r=app(Optimizer::class)->submit($this->scope($p,$extra));app(Optimizer::class)->run($r['id']);$p=Plan::findOrFail($r['id']);$this->assertNotSame('FAILED',$p->status,$p->error??'');return $p;}
 private function counts():array {return collect(['purchase_orders','stock_movements','journal_entries','financial_account_transactions','purchase_requests','stock_transfers'])->mapWithKeys(fn($t)=>[$t=>DB::table($t)->count()])->all();}
 public function test_async_submit_reuses_pending_and_does_not_mutate_business():void {$p=$this->setupProduct();$before=$this->counts();$a=$this->postJson('/api/supply-optimizer',$this->scope($p))->assertStatus(202)->assertJsonPath('status','QUEUED')->json();$b=$this->postJson('/api/supply-optimizer',$this->scope($p))->assertStatus(202)->json();$this->assertSame($a['id'],$b['id']);Queue::assertPushed(\App\Jobs\RunSupplyOptimization::class,1);$this->assertSame($before,$this->counts());}
 public function test_real_solver_enforces_moq_multiples_and_limit_with_frozen_evidence():void {$p=$this->setupProduct();$before=$this->counts();$plan=$this->plan($p);$this->assertSame('OPTIMAL',$plan->status);foreach($plan->result['plans'] as $a){$this->assertLessThanOrEqual(80000,\App\Support\Money::minor($a['summary']['commitment']));foreach($a['lines'] as $l)foreach($l['purchases'] as $buy){$this->assertGreaterThanOrEqual(10,$buy['base_quantity']);$this->assertEquals(0,fmod($buy['base_quantity'],5));}}$this->assertSame($before,$this->counts());$this->getJson('/api/supply-optimizer/'.$plan->id)->assertOk()->assertJsonMissingPath('input')->assertJsonPath('context.policy.state','PRODUCTION');$this->assertDatabaseHas('decision_learning_records',['kind'=>'optimization','source_id'=>$plan->id]);try{$plan->update(['input'=>[]]);$this->fail('Frozen input changed');}catch(\LogicException){}}
 public function test_explicit_confirmation_and_drafts_only_are_idempotent():void {$p=$this->setupProduct();$plan=$this->plan($p);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>false])->assertUnprocessable();$a=$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertOk()->json();$this->assertCount(1,$a['drafts']['purchase_requests']);$this->assertSame('draft',PurchaseRequest::first()->status);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertOk()->assertJsonPath('drafts',$a['drafts']);$this->assertDatabaseCount('purchase_requests',1);$this->assertDatabaseCount('purchase_orders',0);$this->assertDatabaseCount('stock_movements',0);$this->assertDatabaseCount('journal_entries',0);$this->assertDatabaseCount('operational_tasks',1);$this->assertNull($plan->fresh()->execution);}
 public function test_revalidation_rejects_price_change_without_partial_drafts():void {$p=$this->setupProduct();$plan=$this->plan($p);ProductSupplier::first()->update(['purchase_price'=>3]);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertUnprocessable()->assertJsonValidationErrors('plan');$this->assertDatabaseCount('purchase_requests',0);$this->assertNull($plan->fresh()->approved);}
 public function test_new_open_request_cannot_be_duplicated():void {$p=$this->setupProduct();$plan=$this->plan($p);app(\App\Services\ProcurementService::class)->createRequest(['currency'=>'EUR','items'=>[['product_id'=>$p->id,'description'=>'Existing sourcing','quantity'=>10,'unit'=>'pcs','estimated_unit_price'=>2]]]);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertUnprocessable();$new=$this->plan($p);$this->assertEmpty($new->result['plans'][0]['lines'][0]['purchases']);$this->assertSame('existing_request',$new->result['plans'][0]['lines'][0]['reason']);}
 public function test_material_dirty_event_marks_stale_but_not_every_small_change():void {$p=$this->setupProduct();$plan=$this->plan($p);$p->update(['quantity'=>49]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);Cache::put('optimizer-dirty:'.$p->company_id,true);$this->assertSame(0,app(Optimizer::class)->maintain());$p->update(['quantity'=>10]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);Cache::put('optimizer-dirty:'.$p->company_id,true);$this->assertSame(1,app(Optimizer::class)->maintain());$this->assertSame('STALE',$plan->fresh()->status);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertConflict();$this->assertDatabaseCount('operational_tasks',1);}
 public function test_inactive_supplier_rejected_at_review_and_new_plan_skips_it():void {$p=$this->setupProduct();$plan=$this->plan($p);Supplier::first()->update(['is_active'=>false]);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertUnprocessable();$new=$this->plan($p);$this->assertEmpty($new->result['plans'][0]['lines'][0]['purchases']);}
 public function test_zero_commitment_limit_is_not_silently_violated():void {$p=$this->setupProduct();$plan=$this->plan($p,['commitment_limit'=>0]);$this->assertSame('0.00',$plan->result['plans'][0]['summary']['commitment']);$this->assertGreaterThan(0,$plan->result['plans'][0]['summary']['unresolved_scopes']);}
 public function test_hard_critical_service_constraint_can_be_infeasible():void {$p=$this->setupProduct();$p->update(['quantity'=>0]);$plan=$this->plan($p,['protect_critical'=>true,'commitment_limit'=>0]);$this->assertSame('INFEASIBLE',$plan->status);$this->assertDatabaseCount('purchase_orders',0);}
 public function test_incoming_is_counted_once_and_bridge_only_covers_remaining_gap():void {$p=$this->setupProduct();$s=Supplier::first();$po=PurchaseOrder::create(['supplier_id'=>$s->id,'po_number'=>'IN-1','status'=>'ordered','ordered_at'=>today(),'expected_at'=>today()->addDays(15),'currency'=>'EUR','exchange_rate'=>1,'subtotal'=>600,'total_amount'=>600]);$po->items()->create(['product_id'=>$p->id,'description'=>'Incoming handles','quantity'=>300,'base_quantity'=>300,'unit'=>'pcs','unit_price'=>2,'line_total'=>600]);$data=app(SupplyOptimizationData::class)->collect($this->scope($p));$this->assertEquals(300,array_sum(array_column($data['rows'][0]['input']['firm_incoming'],'quantity')));$c=app(SupplyOptimizationCandidates::class)->build($data);$this->assertLessThanOrEqual(120,$c['groups'][0]['need']);$plan=$this->plan($p);$this->assertLessThanOrEqual(120,$plan->result['plans'][0]['lines'][0]['purchase_quantity']);}
 public function test_shared_transfer_candidates_protect_donor_and_require_known_arrival():void {
  $p=$this->setupProduct();$ws=[];foreach(['A','B','C'] as $n){$w=Warehouse::create(['name'=>$n,'code'=>$n,'is_active'=>true]);$q=$n==='C'?1000:10;WarehouseStock::create(['warehouse_id'=>$w->id,'product_id'=>$p->id,'quantity'=>$q,'available_quantity'=>$q]);$ws[]=$w;}
  foreach(AnalyticsSnapshot::where('entity_type','demand_observation')->get() as $s){$facts=$s->facts;$facts['provenance']=['sales'=>['sale:'.$s->id]];DB::table('analytics_snapshots')->where('id',$s->id)->update(['facts'=>json_encode($facts)]);foreach($ws as $index=>$w){AnalyticsSnapshot::create(['entity_type'=>'inventory','entity_id'=>$p->id,'warehouse_id'=>$w->id,'snapshot_date'=>$s->snapshot_date,'observed_at'=>$s->snapshot_date->copy()->endOfDay(),'feature_version'=>'observed-v1','facts'=>['unit'=>'pcs','available'=>100]]);$q=$index===2?4:3;\App\Models\StockMovement::create(['product_id'=>$p->id,'warehouse_id'=>$w->id,'type'=>'out','quantity'=>$q,'quantity_before'=>1000,'quantity_after'=>1000-$q,'warehouse_quantity_after'=>100,'unit_snapshot'=>'pcs','movement_code'=>'daily_sale','source_type'=>'daily_sale','source_id'=>$s->id,'affects_company_quantity'=>true,'occurred_at'=>$s->snapshot_date->copy()->midDay()]);}}
  InventoryPlanningService::invalidate($p->company_id,[$p->id]);$scope=$this->scope($p,['warehouse_ids'=>[$ws[0]->id,$ws[1]->id],'transfer_lead_days'=>1]);$data=app(SupplyOptimizationData::class)->collect($scope);$resource=$p->id.':'.$ws[2]->id;$this->assertGreaterThan(0,$data['resources'][$resource]);$this->assertLessThanOrEqual(860000,$data['resources'][$resource]);$payload=app(SupplyOptimizationCandidates::class)->build($data);$this->assertTrue(collect($payload['groups'][0]['candidates'])->contains(fn($c)=>$c['transfer_quantity']>0));
  $noDate=app(SupplyOptimizationData::class)->collect($this->scope($p,['warehouse_ids'=>[$ws[0]->id]]));$this->assertEmpty($noDate['rows'][0]['transfers']);
  $plan=$this->plan($p,['warehouse_ids'=>[$ws[0]->id,$ws[1]->id],'transfer_lead_days'=>1]);$before=$this->counts();$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertOk();$this->assertDatabaseCount('stock_transfers',2);$this->assertTrue(StockTransfer::get()->every(fn($t)=>$t->status==='draft'));$this->assertSame($before['stock_movements'],$this->counts()['stock_movements']);
 }
 public function test_unknown_demand_stays_limited_and_does_not_invent_prediction():void {$p=$this->setupProduct(false);$plan=$this->plan($p);$this->assertSame('limited',$plan->result['plans'][0]['summary']['confidence']);$this->assertFalse($plan->result['plans'][0]['lines'][0]['coverage_supported']);$this->assertSame('UNKNOWN',$plan->result['plans'][0]['resilience']);}
 public function test_stress_test_and_new_limit_preserve_original():void {$p=$this->setupProduct();$plan=$this->plan($p);$original=$plan->result;$this->postJson('/api/supply-optimizer/'.$plan->id.'/stress',['alternative'=>'balanced','demand_multiplier'=>1.2])->assertOk()->assertJsonPath('scenario.demand_multiplier',1.2);$new=$this->postJson('/api/supply-optimizer/'.$plan->id.'/simulate',['commitment_limit'=>100])->assertStatus(202)->assertJsonPath('scope.parent_plan_id',$plan->id)->json();$this->assertNotEquals($plan->id,$new['id']);$this->assertSame($original,$plan->fresh()->result);}
 public function test_tenant_isolation_and_role_permissions_apply_to_api_tools_and_source():void {$p=$this->setupProduct();$plan=$this->plan($p);$other=Company::factory()->create();$u=User::factory()->create(['company_id'=>$other->id,'role'=>'admin','api_token'=>hash('sha256','other-opt'),'email_verified_at'=>now()]);$this->withHeader('Authorization','Bearer other-opt')->getJson('/api/supply-optimizer/'.$plan->id)->assertNotFound();$this->postJson('/api/supply-optimizer',['horizon'=>30,'product_ids'=>[$p->id]])->assertUnprocessable();$u->update(['role'=>'employee']);$this->getJson('/api/supply-optimizer')->assertForbidden();$this->assertFalse(collect(app(AimsToolRegistry::class)->catalog())->contains('name','get_supply_optimization_summary'));$this->assertNull(app(\App\Services\AutomationRegistry::class)->source('SupplyOptimizationPlan',$plan->id));}
 public function test_solver_failure_is_visible_and_never_creates_business_records():void {$p=$this->setupProduct();$this->mock(LocalSupplyOptimizer::class,fn($m)=>$m->shouldReceive('solve')->andThrow(new \RuntimeException('Local solver timeout')));$r=app(Optimizer::class)->submit($this->scope($p));app(Optimizer::class)->run($r['id']);$this->getJson('/api/supply-optimizer/'.$r['id'])->assertOk()->assertJsonPath('status','FAILED')->assertJsonPath('error','Local solver timeout');$this->assertDatabaseCount('purchase_orders',0);}
 public function test_multiple_supplier_split_candidates_are_independently_valid():void {$p=$this->setupProduct();$s=Supplier::create(['name'=>'Factory B','is_active'=>true]);ProductSupplier::create(['product_id'=>$p->id,'supplier_id'=>$s->id,'purchase_price'=>2.5,'currency'=>'EUR','exchange_rate_to_base'=>1,'usual_lead_time_days'=>2,'pack_size'=>5,'minimum_order_quantity'=>10,'is_active'=>true]);$data=app(SupplyOptimizationData::class)->collect($this->scope($p));$payload=app(SupplyOptimizationCandidates::class)->build($data);$splits=collect($payload['groups'][0]['candidates'])->where('action','split_purchase');$this->assertNotEmpty($splits);foreach($splits as $c){$this->assertCount(2,array_unique(array_column($c['purchases'],'supplier_id')));foreach($c['purchases'] as $buy){$this->assertGreaterThanOrEqual($buy['moq'],$buy['base_quantity']);$this->assertEquals(0,fmod($buy['base_quantity'],$buy['step']));}}}
 public function test_tools_and_assistant_use_structured_jobs_and_preserve_scenarios():void {$p=$this->setupProduct();$registry=app(AimsToolRegistry::class);$this->assertCount(8,collect($registry->catalog())->whereIn('name',AimsToolRegistry::OPTIMIZER_TOOLS));$planner=app(\App\Services\AssistantPlanner::class)->plan('Optimize purchasing for the next 60 days below €70,000.');$this->assertSame('optimization_run',$planner['intent']);$this->assertSame(60,$planner['optimization']['horizon']);$this->assertEquals(70000,$planner['optimization']['commitment_limit']);$queued=$registry->execute('optimize_supply_plan',$this->scope($p))['data'];$this->assertSame('QUEUED',$queued['status']);$next=$registry->execute('simulate_commitment_limit',['plan_id'=>$queued['id'],'commitment_limit'=>900])['data'];$this->assertNotSame($queued['id'],$next['id']);$this->assertSame($queued['id'],$next['scope']['parent_plan_id']);$this->assertDatabaseCount('purchase_requests',0);$this->assertDatabaseCount('stock_movements',0);}
 public function test_outcome_requires_complete_future_stock_and_is_append_only():void {$p=$this->setupProduct();$plan=$this->plan($p);$this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertOk();$plan->refresh();$out=app(\App\Services\SupplyOptimizationOutcome::class);$this->assertNull($out->capture($plan));$plan->update(['execution'=>['purchase_orders'=>[['id'=>123,'status'=>'ordered']],'transfers'=>[]]]);$from=$plan->evidence_cutoff->copy()->startOfDay()->addDay();$this->travel(32)->days();$this->assertNull($out->capture($plan));for($n=0;$n<30;$n++){ $d=$from->copy()->addDays($n);AnalyticsSnapshot::create(['entity_type'=>'product','entity_id'=>$p->id,'warehouse_id'=>0,'snapshot_date'=>$d,'observed_at'=>$d->copy()->endOfDay(),'feature_version'=>'observed-v1','facts'=>['unit'=>'pcs','available'=>100]]);}$r=$out->capture($plan);$this->assertSame('COMPLETED_OBSERVATION',$r->payload['state']);$this->assertSame(0,$r->payload['rows'][0]['scorecard']['stockout_days']);$this->assertNull($r->payload['rows'][0]['scorecard']['demand_observed']);$this->assertSame($r->id,$out->capture($plan)->id);}
 public function test_named_stress_sources_are_frozen_and_cannot_select_unrelated_records():void {
  $p=$this->setupProduct();$supplier=Supplier::first();$orders=[];
  foreach([3,10] as $index=>$days){$po=PurchaseOrder::create(['supplier_id'=>$supplier->id,'po_number'=>'STRESS-'.$index,'status'=>'ordered','ordered_at'=>today(),'expected_at'=>today()->addDays($days),'currency'=>'EUR','exchange_rate'=>1,'subtotal'=>80,'total_amount'=>80]);$po->items()->create(['product_id'=>$p->id,'description'=>'Handles','quantity'=>40,'base_quantity'=>40,'unit'=>'pcs','unit_price'=>2,'line_total'=>80]);$orders[]=$po;}
  $shipment=\App\Models\Shipment::create(['tracking_number'=>'SH-STRESS','purchase_order_id'=>$orders[0]->id,'status'=>'in_transit','eta'=>$orders[0]->expected_at]);$plan=$this->plan($p);$before=$this->counts();
  $this->getJson('/api/supply-optimizer/'.$plan->id)->assertOk()->assertJsonPath('stress_options.shipments.0.id',$shipment->id);
  $r=$this->postJson('/api/supply-optimizer/'.$plan->id.'/stress',['alternative'=>'balanced','shipment_id'=>$shipment->id,'shipment_delay'=>7])->assertOk()->json();$this->assertSame([$orders[0]->id],$r['scenario']['incoming_order_ids']);
  $this->postJson('/api/supply-optimizer/'.$plan->id.'/stress',['alternative'=>'balanced','shipment_id'=>99999,'shipment_delay'=>7])->assertUnprocessable();$this->postJson('/api/supply-optimizer/'.$plan->id.'/stress',['alternative'=>'balanced','supplier_id'=>99999,'supplier_delay'=>10])->assertUnprocessable();
  $this->assertSame($before,$this->counts());$this->assertSame('in_transit',$shipment->fresh()->status);
 }
 public function test_supplier_stress_assistant_resolves_exact_frozen_name_and_rejects_unknown_name():void {
  $p=$this->setupProduct();$plan=$this->plan($p);$parser=app(\App\Services\AssistantPlanner::class)->plan('What if Supplier Factory A is 10 days late for plan #'.$plan->id.'?');$this->assertSame('optimization_stress',$parser['intent']);$this->assertSame('factory a',$parser['optimization']['supplier_term']);$this->assertSame(10,$parser['optimization']['supplier_delay']);
  $response=$this->postJson('/api/intelligence-assistant/ask',['question'=>'What if Supplier Factory A is 10 days late for plan #'.$plan->id.'?'])->assertOk()->assertJsonPath('intent','optimization_stress')->json();$this->assertTrue(collect($response['sources'])->contains('tool','stress_test_supply_plan'));$this->assertSame('success',$response['state']);
  $bad=$this->postJson('/api/intelligence-assistant/ask',['question'=>'What if Supplier Unknown is 10 days late for plan #'.$plan->id.'?'])->assertOk()->json();$this->assertFalse(collect($bad['sources'])->contains('tool','stress_test_supply_plan'));$this->assertStringContainsString('does not identify',$bad['text']);
  $this->assertDatabaseCount('purchase_requests',0);$this->assertDatabaseCount('purchase_orders',0);
 }
 public function test_quantity_tradeoffs_use_existing_valid_candidates_and_collections_remain_context():void {
  $p=$this->setupProduct();$plan=$this->plan($p);$tradeoff=$plan->result['plans'][0]['lines'][0]['quantity_tradeoff'];$this->assertNotNull($tradeoff['lower']);$this->assertLessThan($plan->result['plans'][0]['lines'][0]['purchase_quantity'],$tradeoff['lower']['purchase_quantity']);$this->assertEquals(0,fmod($tradeoff['lower']['purchase_quantity'],5));
  $this->postJson('/api/supply-optimizer/'.$plan->id.'/stress',['alternative'=>'balanced','collections_delay'=>15])->assertOk()->assertJsonPath('collections_context.state','insufficient_evidence');$this->assertNull($plan->fresh()->approved);
 }
 public function test_revalidation_rejects_changed_safety_floor_without_creating_drafts():void {
  $p=$this->setupProduct();$plan=$this->plan($p);$p->update(['min_quantity'=>200]);
  $this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertUnprocessable()->assertJsonValidationErrors('plan');
  $this->assertDatabaseCount('purchase_requests',0);$this->assertNull($plan->fresh()->approved);
 }
 public function test_changed_planning_thresholds_are_material_even_when_stock_is_unchanged():void {
  $p=$this->setupProduct();$plan=$this->plan($p);$p->update(['safety_stock'=>30]);$live=app(SupplyOptimizationData::class)->collect($plan->scope);
  $this->assertTrue(app(SupplyOptimizationData::class)->material($plan->input,$live));
  Cache::put('optimizer-dirty:'.$p->company_id,true);$this->assertSame(1,app(Optimizer::class)->maintain());$this->assertSame('STALE',$plan->fresh()->status);
 }
 public function test_existing_stock_ceiling_conflict_is_infeasible_not_a_solver_failure():void {
  $p=$this->setupProduct();\App\Models\InventoryPlanningPolicy::create(['product_id'=>$p->id,'scope_key'=>0,'version'=>'v11-ceiling-test','settings'=>['maximum_stock'=>20]]);
  $plan=$this->plan($p);$this->assertSame('INFEASIBLE',$plan->status);$this->assertNull($plan->error);$this->assertDatabaseCount('purchase_requests',0);
 }
 public function test_hard_critical_coverage_requires_actual_demand_evidence():void {
  $p=$this->setupProduct(false);$p->update(['quantity'=>0]);$plan=$this->plan($p,['protect_critical'=>true]);
  $this->assertSame('INFEASIBLE',$plan->status);$this->assertDatabaseCount('purchase_requests',0);
 }
 public function test_maintenance_visits_older_plans_and_keeps_dirty_evidence_for_all_batches():void {
  $p=$this->setupProduct();$old=$this->plan($p);$copy=fn(array $extra)=>Plan::create(array_replace(['version'=>(string)\Illuminate\Support\Str::uuid(),'request_key'=>hash('sha256',uniqid()),'status'=>'OPTIMAL','scope'=>$old->scope,'input'=>$old->input,'result'=>$old->result,'evidence_cutoff'=>now(),'created_by'=>Auth::id()],$extra));
  for($n=0;$n<10;$n++)$copy(['approved'=>['alternative'=>'balanced'],'drafts'=>['purchase_requests'=>[],'transfers'=>[]]]);$new=$copy([]);
  $p->update(['quantity'=>10]);InventoryPlanningService::invalidate($p->company_id,[$p->id]);Cache::put('optimizer-dirty:'.$p->company_id,'first-change');
  $this->assertSame(1,app(Optimizer::class)->maintain());$this->assertSame('STALE',$old->fresh()->status);$this->assertSame('OPTIMAL',$new->fresh()->status);$this->assertTrue(Cache::has('optimizer-dirty:'.$p->company_id));
  $this->assertSame(1,app(Optimizer::class)->maintain());$this->assertSame('STALE',$new->fresh()->status);$this->assertFalse(Cache::has('optimizer-dirty:'.$p->company_id));
  $this->assertDatabaseCount('purchase_requests',0);$this->assertDatabaseCount('stock_movements',0);
 }
 public function test_new_dirty_generation_is_not_lost_when_an_older_sweep_finishes():void {
  $p=$this->setupProduct();$old=$this->plan($p);
  for($n=0;$n<11;$n++)Plan::create(['version'=>(string)\Illuminate\Support\Str::uuid(),'request_key'=>hash('sha256',uniqid()),'status'=>'OPTIMAL','scope'=>$old->scope,'input'=>$old->input,'result'=>$old->result,'evidence_cutoff'=>now(),'created_by'=>Auth::id(),'approved'=>['alternative'=>'balanced'],'drafts'=>['purchase_requests'=>[],'transfers'=>[]]]);
  Cache::put('optimizer-dirty:'.$p->company_id,'first-change');$this->assertSame(0,app(Optimizer::class)->maintain());
  Cache::put('optimizer-dirty:'.$p->company_id,'new-change');$this->assertSame(0,app(Optimizer::class)->maintain());$this->assertSame('new-change',Cache::get('optimizer-dirty:'.$p->company_id));
  $this->assertSame(0,app(Optimizer::class)->maintain());$this->assertSame(0,app(Optimizer::class)->maintain());$this->assertFalse(Cache::has('optimizer-dirty:'.$p->company_id));
 }
 public function test_company_scope_changes_require_reoptimization_before_drafts():void {
  $p=$this->setupProduct();$plan=$this->plan($p,['product_ids'=>[]]);Product::create(['name'=>'New active product','sku'=>'OPT-NEW','category_id'=>$p->category_id,'unit'=>'pcs','quantity'=>10,'min_quantity'=>20,'price'=>5,'purchase_price'=>2]);
  $this->postJson('/api/supply-optimizer/'.$plan->id.'/prepare',['alternative'=>'balanced','confirm'=>true])->assertUnprocessable()->assertJsonValidationErrors('plan');$this->assertDatabaseCount('purchase_requests',0);
 }
}
