import test from 'node:test'
import assert from 'node:assert/strict'
import {serializeAssumption,serializeDefinition,sensitivityValues,inventoryComparison,financeComparison,canPrepareSimulationResponse,simulationLabel,simulationPending,simulationActions,simulationPermissions} from '../src/pages/strategicSimulationPresentation.js'
import {canOpenPage} from '../src/config/pageAccess.js'
import {safeRecordPath} from '../src/components/assistantPresentation.js'
const definition={name:'Test',horizon:90,assumptions:[],scope:{},optimize:true}
test('builder rejects blank numeric values, invalid selections and unapproved service targets',()=>{assert.throws(()=>serializeAssumption({type:'demand',action:'percent',value:''}));assert.throws(()=>serializeAssumption({type:'supplier',action:'lead_days',days:5}));assert.throws(()=>serializeAssumption({type:'inventory',action:'service_level',value:.97}));assert.equal(serializeAssumption({type:'procurement',action:'allow_split',value:1}).value,1);assert.equal(serializeAssumption({type:'procurement',action:'allow_split',value:0}).value,0)})
test('scope and horizons have the same bounds as backend, long extrapolation is explicit',()=>{assert.equal(serializeDefinition(definition).scope.long_horizon_mode,'no_extension');assert.equal(serializeDefinition({...definition,horizon:365,scope:{long_horizon_mode:'repeat_pattern'}}).scope.long_horizon_mode,'repeat_pattern');assert.throws(()=>serializeDefinition({...definition,scope:{warehouse_ids:[1,2,3,4]}}));assert.throws(()=>serializeDefinition({...definition,horizon:120}));assert.throws(()=>serializeDefinition({...definition,assumptions:Array(25).fill({type:'demand',action:'percent',value:20})}))})
test('sensitivity is bounded and does not silently accept unsupported values',()=>{const a={type:'demand',action:'percent',value:20};assert.deepEqual(sensitivityValues('0,10,20,10',a),[0,10,20]);assert.throws(()=>sensitivityValues('0,600',a));assert.throws(()=>sensitivityValues('0',a))})
test('chart alignment keeps missing evidence null and currencies separate',()=>{const rows=inventoryComparison({unit:'m',timeline:[{date:'2026-10-06',balance:2}]},{unit:'m',timeline:[{date:'2026-10-07',balance:1}]});assert.equal(rows[0].baseline,null);assert.deepEqual(inventoryComparison({unit:'pcs'},{unit:'m'}),[]);const f=financeComparison({currencies:{EUR:{timeline:[{date:'2026-10-06',expected_cash:null}]}}},{currencies:{USD:{timeline:[{date:'2026-10-07',expected_cash:'4.00'}]}}});assert.equal(f.length,2);assert.equal(f[0].points[0].baseline,null)})
test('simulation routes require every sensitive permission and remain safe record links',()=>{assert.ok(canOpenPage('/strategic-simulation',simulationPermissions));for(const p of simulationPermissions)assert.equal(canOpenPage('/strategic-simulation',simulationPermissions.filter(q=>q!==p)),false);assert.equal(safeRecordPath('/strategic-simulation?run=12'),'/strategic-simulation?run=12');assert.equal(safeRecordPath('//evil.test/strategic-simulation'),null)})
test('explicit response preparation and pending statuses are not inferred',()=>{assert.ok(canPrepareSimulationResponse({status:'COMPLETED',permissions:{can_prepare_response:true}},{status:'OPTIMAL'}));assert.equal(canPrepareSimulationResponse({status:'RUNNING',permissions:{can_prepare_response:true}},{status:'OPTIMAL'}),false);assert.ok(simulationPending('QUEUED'));assert.ok(simulationPending('RUNNING'));assert.equal(simulationPending('COMPLETED'),false);for(const a of simulationActions){assert.ok(a.en);assert.ok(a.sq)}assert.equal(simulationLabel('completed','sq'),'Përfunduar')})
