import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuthStore } from '../store/authStore'
import { requestAutomation, useAutomationText } from './AutomationStudio'
import './AutomationStudio.css'
import TaskManagement from '../components/TaskManagement'
import { shipmentIntelligenceLabel } from '../components/shipmentIntelligencePresentation'
import ActiveFilters from '../components/ActiveFilters'
import WorkspaceModal from '../components/WorkspaceModal'
import {useUnsavedNavigation} from '../hooks/useUnsavedNavigation'
import {useSessionState} from '../hooks/useSessionState'
import {businessDate} from '../utils/businessFormat'
import {businessStatus} from '../utils/businessStatus'
import {attentionPreview,attentionDescription} from '../lib/actionCenterPresentation'
import {businessError} from '../utils/businessErrors'
import {useSettingsStore} from '../store/settingsStore'

export default function ActionCenter(){
  const t=useAutomationText(),permissions=useAuthStore(s=>s.permissions),[urlParams,setParams]=useSearchParams()
  const language=useSettingsStore(s=>s.language),[savedFilters,setSavedFilters]=useSessionState('tasks.filters','view=mine&status=active'),params=urlParams.size?urlParams:new URLSearchParams(savedFilters)
  const [showAllIssues,setShowAllIssues]=useState(false)
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null)
  const pending=useRef(false)
  const formDirty=Boolean(form&&(form.title||form.description||form.due_at||form.priority!=='normal'))
  useUnsavedNavigation(formDirty,t('Discard unsaved task?','Të hidhet poshtë detyra e paruajtur?'))
  const query=params.toString()
  const load=useCallback(async()=>{setData(await requestAutomation('/action-center?'+query));setError('')},[query])
  useEffect(()=>{let alive=true;requestAutomation('/action-center?'+query).then(r=>alive&&setData(r)).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[query])
  useEffect(()=>{const refresh=()=>load().catch(()=>{});window.addEventListener('database-refresh',refresh);return()=>window.removeEventListener('database-refresh',refresh)},[load])
  async function act(fn){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await fn();await load()}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
  const filter=(key,value)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);next.delete('page');setParams(next);const saved=new URLSearchParams(next);saved.delete('task');saved.delete('source_id');setSavedFilters(saved.toString()||'view=mine&status=active')}
  const status=s=>t(({open:'Open',in_progress:'In progress',completed:'Completed',cancelled:'Cancelled'})[s] || s,({open:'E hapur',in_progress:'Në punë',completed:'Përfunduar',cancelled:'Anuluar'})[s] || s)
  const priority=p=>t(({low:'Low',normal:'Normal',high:'High',urgent:'Urgent'})[p] || p,({low:'E ulët',normal:'Normale',high:'E lartë',urgent:'Urgjente'})[p] || p)
  const issueDescription=x=>String(x.id).startsWith('logistics-')?shipmentIntelligenceLabel(x.description,language):attentionDescription(x,language)
  const issues=attentionPreview(data?.attention),visibleIssues=showAllIssues?issues:issues.slice(0,8)
  useEffect(()=>setShowAllIssues(false),[params.get('area')])
  return <main className="automation-page page-shell"><header className="page-header"><div><h1>{t('Action Center','Qendra e veprimeve')}</h1><p>{t('What needs my attention? Review, act, and record the outcome.','Çfarë kërkon vëmendjen time? Rishiko, vepro dhe regjistro rezultatin.')}</p></div><div className="auto-buttons">{permissions.includes('automations.view')&&<Link to="/automation-studio">{t('Automation Studio','Studio e automatizimit')}</Link>}{permissions.includes('tasks.create')&&<button onClick={()=>setForm({title:'',description:'',priority:'normal',due_at:''})}>{t('New task','Detyrë e re')}</button>}</div></header>
    {error&&<div role="alert" className="page-error"><p>{error}</p><button type="button" className="secondary" disabled={busy} onClick={()=>act(()=>Promise.resolve())}>{t('Retry loading','Provo ngarkimin përsëri')}</button></div>}
    <ActiveFilters onClear={()=>{setSavedFilters('view=mine&status=active');setParams({view:'mine',status:'active'})}} filters={[
      params.get('view')==='mine'&&{key:'view',label:t('My tasks','Detyrat e mia'),remove:()=>filter('view','')},
      params.get('status')&&params.get('status')!=='active'&&{key:'status',label:params.get('status')==='all'?t('All / history','Të gjitha / historiku'):status(params.get('status')),remove:()=>filter('status','')},
      params.get('priority')&&{key:'priority',label:priority(params.get('priority')),remove:()=>filter('priority','')},
      params.get('area')&&{key:'area',label:t('Issue area','Fusha e problemit')+': '+t(({stock:'Stock',procurement:'Purchasing',customer:'Customers',document:'Documents',approval:'Approvals',shipment:'Shipments',finance:'Finance',order:'Orders',system:'System'})[params.get('area')],({stock:'Stoku',procurement:'Blerjet',customer:'Klientët',document:'Dokumentet',approval:'Miratimet',shipment:'Dërgesat',finance:'Financat',order:'Porositë',system:'Sistemi'})[params.get('area')]),remove:()=>filter('area','')},
    ]}/>
    {form&&<WorkspaceModal title={t('New task','Detyrë e re')} onClose={()=>setForm(null)} busy={busy} closeOnBackdrop warnOnUnsaved={formDirty}><form className="auto-panel" onSubmit={e=>{e.preventDefault();act(async()=>{await requestAutomation('/operational-tasks','POST',{...form,due_at:form.due_at || null});setForm(null)})}}><h2>{t('New task','Detyrë e re')}</h2><label>{t('Title','Titulli')}<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>{t('Why / next action','Arsyeja / veprimi vijues')}<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>{t('Due date','Afati')}<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>{t('Priority','Përparësia')}<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','normal','high','urgent'].map(p=><option key={p} value={p}>{priority(p)}</option>)}</select></label><div className="auto-buttons"><button disabled={busy}>{t('Save task','Ruaj detyrën')}</button><button type="button" onClick={()=>{if(!formDirty||confirm(t('Discard unsaved task?','Të hidhet poshtë detyra e paruajtur?')))setForm(null)}}>{t('Cancel','Anulo')}</button></div></form></WorkspaceModal>}
    <div className="auto-filterbar"><label>{t('Tasks','Detyrat')}<select value={params.get('view') || ''} onChange={e=>filter('view',e.target.value)}><option value="">{t('Team tasks','Detyrat e ekipit')}</option><option value="mine">{t('My tasks','Detyrat e mia')}</option></select></label><label>{t('Status','Statusi')}<select value={params.get('status') || 'active'} onChange={e=>filter('status',e.target.value)}><option value="active">{t('Open work','Punët e hapura')}</option><option value="all">{t('All / history','Të gjitha / historiku')}</option>{['open','in_progress','completed','cancelled'].map(s=><option key={s} value={s}>{status(s)}</option>)}</select></label><label>{t('Area','Fusha')}<select value={params.get('source_type') || ''} onChange={e=>filter('source_type',e.target.value)}><option value="">{t('All areas','Të gjitha fushat')}</option>{[['Product','Stock','Stoku'],['SalesOrder','Orders','Porositë'],['Customer','Customers','Klientët'],['PurchaseOrder','Purchasing','Blerjet'],['Shipment','Shipments','Dërgesat'],['Document','Documents','Dokumentet'],['QualityInspection','Quality','Cilësia'],['AccountingException','Finance','Financat'],['IntegrationProvider','System','Sistemi']].map(([v,en,sq])=><option value={v} key={v}>{t(en,sq)}</option>)}</select></label><label>{t('Priority','Përparësia')}<select value={params.get('priority') || ''} onChange={e=>filter('priority',e.target.value)}><option value="">{t('All','Të gjitha')}</option>{['low','normal','high','urgent'].map(p=><option key={p} value={p}>{priority(p)}</option>)}</select></label></div>
    {!data?<p role="status">{t('Loading…','Duke ngarkuar…')}</p>:<><p>{data.summary.tasks} {t('tasks','detyra')} · {data.summary.approvals} {t('approvals waiting','miratime në pritje')}</p><section className="auto-task-grid">{data.tasks.data.map(task=><article key={task.id} data-task-id={task.id} className={`auto-task ${task.priority} ${task.overdue?'overdue':''}`}><small>{task.automation_id?t('Automation-created task','Detyrë nga automatizimi'):task.created_by?t('Manual request','Kërkesë manuale'):t('System-generated action','Veprim nga sistemi')} · {priority(task.priority)} · {status(task.status)}</small><h2>{task.title}</h2><p>{task.description}</p>{task.due_at&&<p>{task.overdue?t('Overdue','Me vonesë'):t('Due','Afati')}: {businessDate(task.due_at,language,{time:true})}</p>}{task.outcome?.note&&<p>{t('Outcome','Rezultati')}: {task.outcome.note}</p>}<div className="auto-buttons">{task.url&&<Link to={task.url}>{t('Open source / take action','Hap burimin / vepro')}</Link>}{task.outcome?.draft?.url&&<Link to={task.outcome.draft.url}>{t('Review purchase request','Rishiko kërkesën për blerje')}</Link>}{task.can_complete&&['open','in_progress'].includes(task.status)&&<><button disabled={busy} onClick={()=>act(()=>requestAutomation(`/operational-tasks/${task.id}`,'PATCH',{status:task.status==='open'?'in_progress':'completed'}))}>{task.status==='open'?t('Start task','Fillo detyrën'):t('Complete task','Përfundo detyrën')}</button><button disabled={busy} onClick={()=>{if(confirm(t('Cancel this task? Its history will be kept.','Anulo këtë detyrë? Historia do të ruhet.')))act(()=>requestAutomation(`/operational-tasks/${task.id}`,'PATCH',{status:'cancelled',outcome_note:t('Request cancelled by the responsible user.','Kërkesa u anulua nga përdoruesi përgjegjës.')}))}}>{t('Cancel task','Anulo detyrën')}</button></>}</div></article>)}</section>{!data.tasks.data.length&&<p>{t('No open work matches this view. Check team tasks or change the filters.','Nuk ka punë të hapura në këtë pamje. Shiko detyrat e ekipit ose ndrysho filtrat.')}</p>}<div className="auto-buttons"><button disabled={data.tasks.current_page<=1} onClick={()=>setParams(p=>{p.set('page',data.tasks.current_page-1);return p})}>{t('Previous','Para')}</button><span>{data.tasks.current_page} / {data.tasks.last_page}</span><button disabled={data.tasks.current_page>=data.tasks.last_page} onClick={()=>setParams(p=>{p.set('page',data.tasks.current_page+1);return p})}>{t('Next','Tjetra')}</button></div>
      <h2>{t('Related approvals and issues','Miratimet dhe problemet e lidhura')}</h2><p>{t('These are live links to existing records, not copies.','Këto janë lidhje me regjistrimet ekzistuese, jo kopje.')}</p><label>{t('Issue area','Fusha e problemit')}<select value={params.get('area') || ''} onChange={e=>filter('area',e.target.value)}><option value="">{t('All issues','Të gjitha problemet')}</option>{[['stock','Stock','Stoku'],['procurement','Purchasing','Blerjet'],['customer','Customers','Klientët'],['document','Documents','Dokumentet'],['approval','Approvals','Miratimet'],['shipment','Shipments','Dërgesat'],['finance','Finance','Financat'],['order','Orders','Porositë'],['system','System','Sistemi']].map(([v,en,sq])=><option key={v} value={v}>{t(en,sq)}</option>)}</select></label><p className="auto-hint">{t('A preview of current issues; open the source for its full list.','Pamje e problemeve aktuale; hap burimin për listën e plotë.')}</p><section className="auto-task-grid">{visibleIssues.map(x=><article className="auto-task" key={x.kind+':'+x.id}><h3>{businessStatus(x.title,language)}</h3><p>{businessError(issueDescription(x),undefined,language)}</p>{x.occurrences>1&&<small>{x.occurrences} {t('related records · open the source to review','regjistrime të lidhura · hap burimin për rishikim')}</small>}<Link to={x.url}>{t('Review and act','Rishiko dhe vepro')}</Link></article>)}</section>{issues.length>8&&<button type="button" className="secondary" onClick={()=>setShowAllIssues(v=>!v)}>{showAllIssues?t('Show fewer issues','Shfaq më pak probleme'):t('Show all related issues','Shfaq të gjitha problemet e lidhura')} ({issues.length})</button>}</>}
    <TaskManagement tasks={data?.tasks?.data || []} onChanged={load}/>
  </main>
}
