import {useEffect,useRef,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts'
import {apiRequest,authenticatedFetch} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import {analyticsLabels as labels} from './analyticsLabels'
import './Analytics.css'

export default function Analytics(){
 const {language}=useTranslation(),permissions=useAuthStore(s=>s.permissions),[params,setParams]=useSearchParams()
 const [catalog,setCatalog]=useState(null),[data,setData]=useState(null),[datasets,setDatasets]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[message,setMessage]=useState('')
 const pending=useRef(false)
 const tab=params.get('tab')||'overview',period=params.get('period')||'30d',from=params.get('from')||'',to=params.get('to')||'',page=Number(params.get('page')||1)
 const t=(en,sq)=>language==='sq'?sq:en, label=k=>labels[k]?.[language==='sq'?1:0]||k
 const canDatasets=permissions.includes('analytics.ml_datasets')&&permissions.includes('analytics.finance')
 useEffect(()=>{let alive=true;apiRequest('/analytics/catalog').then(x=>alive&&setCatalog(x)).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;setError('');setData(null);if(tab==='datasets'){apiRequest('/analytics/datasets').then(x=>alive&&setDatasets(x.data)).catch(e=>alive&&setError(e.message));return()=>{alive=false}}
   if(period==='custom'&&(!from||!to))return
   apiRequest(`/analytics/${tab}?`+new URLSearchParams({period,from,to,page})).then(x=>alive&&setData(x)).catch(e=>alive&&setError(e.message));return()=>{alive=false}
 },[tab,period,from,to,page,revision])
 const change=(k,v)=>setParams(p=>{p.set(k,v);if(k!=='page')p.delete('page');return p})
 const act=async(fn)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await fn();setRevision(x=>x+1)}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
 const value=v=>v===null||v===undefined?'—':typeof v==='boolean'?(v?t('Yes','Po'):t('No','Jo')):typeof v==='number'||(typeof v==='string'&&/^-?\d+(\.\d+)?$/.test(v))?new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(Number(v)):label(String(v))
 const table=rows=>{if(!rows?.length)return <p>{t('No observations in this period.','Nuk ka të dhëna në këtë periudhë.')}</p>;const keys=Object.keys(rows[0]).filter(k=>!['id','url','details'].includes(k)&&(rows[0][k]===null||typeof rows[0][k]!=='object')),hasLinks=rows.some(r=>r.url);return <div className="analytics-table" tabIndex={0} aria-label={t('Scrollable analytics table','Tabela e lëvizshme e analitikës')}><table><thead><tr>{keys.map(k=><th key={k} scope="col">{label(k)}</th>)}{hasLinks&&<th scope="col">{t('Action','Veprimi')}</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{value(r[k])}</td>)}{hasLinks&&<td>{r.url&&<Link to={r.url}>{t('Open record','Hap regjistrimin')}</Link>}</td>}</tr>)}</tbody></table></div>}
 async function download(id,format){const r=await authenticatedFetch(`/analytics/datasets/${id}/export?format=${format}`);if(!r.ok)throw new Error((await r.json()).message);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`aims-demand-${id}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main className="analytics-page"><header><div><h1>{t('Analytics','Analitika')}</h1><p>{t('Recorded facts. Clear decisions.','Fakte të regjistruara. Vendime të qarta.')}</p><Link to="/inventory-intelligence">{t('Inventory Intelligence — advisory forecasts','Inteligjenca e inventarit — parashikime këshilluese')} →</Link></div><button disabled={busy} onClick={()=>setRevision(x=>x+1)}>{t('Refresh','Rifresko')}</button></header>
  <nav aria-label={t('Analytics areas','Fushat e analitikës')}>{(catalog?.areas||[]).concat(canDatasets?['datasets']:[]).map(x=><button key={x} aria-current={tab===x?'page':undefined} onClick={()=>change('tab',x)}>{label(x)}</button>)}</nav>
  <div className="analytics-filters"><label>{t('Period','Periudha')}<select value={period} onChange={e=>change('period',e.target.value)}>{['today','yesterday','7d','30d','90d','month','last_month','quarter','year','custom'].map(x=><option value={x} key={x}>{label(x)}</option>)}</select></label>{(period==='custom'||tab==='datasets')&&<><label>{t('From','Nga')}<input type="date" value={from} onChange={e=>change('from',e.target.value)}/></label><label>{t('To','Deri')}<input type="date" value={to} onChange={e=>change('to',e.target.value)}/></label></>}</div>
  {error&&<p role="alert" className="analytics-error">{error}</p>}{message&&<p role="status">{message}</p>}
  {tab==='datasets'?<section><h2>{t('Point-in-time datasets','Të dhëna sipas momentit historik')}</h2><p>{t('Capture stores today’s observed facts once. Past balances are never fabricated. Labels remain pending until the next 30 days have elapsed. Each build is a new immutable version.','Regjistrimi ruan faktet e sotme vetëm një herë. Gjendjet e kaluara nuk shpiken. Rezultatet mbeten në pritje derisa të kalojnë 30 ditët e ardhshme. Çdo krijim është version i ri i pandryshueshëm.')}</p><div className="analytics-actions"><button disabled={busy} onClick={()=>act(async()=>{await apiRequest('/analytics/snapshots',{method:'POST'});setMessage(t('Today’s observations are saved.','Të dhënat e sotme u ruajtën.'))})}>{t('Capture today','Regjistro sot')}</button><button disabled={busy||!from||!to} onClick={()=>act(()=>apiRequest('/analytics/datasets',{method:'POST',body:JSON.stringify({from,to})}))}>{t('Build demand dataset','Krijo grupin e kërkesës')}</button></div>{datasets.map(d=><article className="analytics-dataset" key={d.id}><h3>{d.name}</h3><p>{d.version}</p><p>{d.row_count} {t('rows','rreshta')} · {d.labelled_count} {t('with outcomes','me rezultate')}</p><p>{d.quality_status==='waiting_for_outcomes'?t('Waiting for future outcomes','Në pritje të rezultateve të ardhshme'):t('Labels available — review data quality before training','Rezultatet janë gati — rishiko cilësinë para trajnimit')}</p>{permissions.includes('analytics.export')&&['csv','json'].map(f=><button key={f} disabled={busy} onClick={()=>act(()=>download(d.id,f))}>{t('Export','Eksporto')} {f.toUpperCase()}</button>)}</article>)}</section>:data?<>
   <p className="analytics-note">{data.period.from} — {data.period.to} · {data.currency} · {t('Updated','Përditësuar')}: {new Date(data.generated_at).toLocaleTimeString()}</p>
   {data.status&&<p role="status"><strong>{label('data_quality')}: {label(data.status)}</strong></p>}
   {['current','balances_current'].includes(data.scope)&&<p className="analytics-note">{t('Balances are current observations; they are not historical balances for the selected period.','Gjendjet janë aktuale; nuk janë gjendje historike për periudhën e zgjedhur.')}</p>}
   {data.scope==='economic_sales'&&<p className="analytics-note">{t('Linked invoices replace, never add to, their daily sale. Orders are excluded from revenue. Unknown costs stay unavailable. Quantities use each product’s inventory unit.','Faturat e lidhura zëvendësojnë shitjen ditore, nuk shtohen mbi të. Porositë nuk numërohen si të ardhura. Kostot e panjohura mbeten pa vlerë. Sasitë përdorin njësinë e produktit.')}</p>}
   {data.scope==='accounting'&&<p>{t('Formal financial figures come directly from Accounting Core.','Shifrat financiare merren drejtpërdrejt nga Bërthama Financiare.')}</p>}
   <section className="analytics-kpis">{Object.entries(data.metrics).map(([k,v])=><article key={k}><span>{label(k)}</span><strong>{value(v)}</strong>{data.comparison?.[k]!=null&&<small>{data.comparison[k]>0?'+':''}{value(data.comparison[k])}% {t('vs previous equivalent period','kundrejt periudhës së mëparshme')}</small>}</article>)}</section>
   {data.trend?.length>1&&<section className="analytics-chart" aria-label={label(data.trend_metric||'revenue')}><h2>{label(data.trend_metric||'revenue')}</h2><ResponsiveContainer width="100%" height={250}><LineChart data={data.trend}><CartesianGrid stroke="var(--border-color)" strokeDasharray="3 3"/><XAxis dataKey="date" stroke="var(--text-muted)"/><YAxis stroke="var(--text-muted)"/><Tooltip contentStyle={{background:'var(--card-bg)',color:'var(--text-color)',border:'1px solid var(--border-color)'}}/><Line name={label(data.trend_metric||'revenue')} type="monotone" dataKey={data.trend_metric||'revenue'} stroke="#329cf2" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></section>}
   {tab==='inventory'&&<p className="analytics-note">{t('Days of supply = available / recent daily demand. Turnover requires captured inventory history. Zero demand has no finite supply estimate. Different units are never combined into a total.','Ditët e furnizimit = sasia në dispozicion / kërkesa ditore. Qarkullimi kërkon historik të regjistruar. Pa kërkesë nuk ka vlerësim të fundëm. Njësitë e ndryshme nuk bashkohen.')}</p>}
   {table(data.rows)}{data.total_rows>50&&<div className="analytics-actions"><button disabled={page===1} onClick={()=>change('page',page-1)}>{t('Previous','Para')}</button><span>{page} / {Math.ceil(data.total_rows/50)}</span><button disabled={page*50>=data.total_rows} onClick={()=>change('page',page+1)}>{t('Next','Tjetra')}</button></div>}
   {Object.entries({...data.groups,warehouses:data.warehouses,prices:data.prices,components:data.components,containers:data.containers,claims:data.claims}).filter(([,rows])=>rows?.length).map(([k,rows])=><details key={k}><summary>{label(k)}</summary>{table(rows)}</details>)}
  </>:!error&&<p role="status">{t('Loading analytics…','Duke ngarkuar analitikën…')}</p>}
 {tab==='logistics'&&data?.shipment_intelligence&&<section><h2>{t('Shipment ETA outcomes','Rezultatet e ETA të dërgesave')}</h2><p>{t('Genuine pre-arrival predictions only; not test or synthetic accuracy.','Vetëm parashikime reale para mbërritjes; jo saktësi nga testet ose të dhëna sintetike.')}</p><p>{t('Completed evaluated shipments','Dërgesa të përfunduara të vlerësuara')}: {value(data.shipment_intelligence.performance.completed_genuine_predictions)} · MAE: {value(data.shipment_intelligence.performance.mae_days)} {t('days','ditë')}</p><Link to="/shipments/my-shipments?view=intelligence">{t('Open Shipment Intelligence','Hap inteligjencën e dërgesave')} →</Link></section>}
 </main>
}
