import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { apiRequest } from '../api/client'
import { useTranslation } from '../hooks/useTranslation'
import { useAuthStore } from '../store/authStore'
import './AutomationStudio.css'
import AutomationMetrics from '../components/AutomationMetrics'

const fieldNames = {
  risk:['Risk','Rreziku'], confidence:['Confidence','Besueshmëria'], predicted_eta:['Predicted arrival','Mbërritja e parashikuar'], freshness:['Signal freshness','Freskia e sinjalit'], model_status:['Model status','Gjendja e modelit'], stockout_date:['Expected stockout','Mungesa e pritshme'], source_quality:['Source quality','Cilësia e burimit'],
  reference:['Reference','Referenca'], available:['Available quantity','Sasia e disponueshme'], minimum:['Minimum stock','Stoku minimal'], shortage:['Stock shortage','Mungesa e stokut'],
  total_amount:['Total amount','Shuma totale'], status:['Status','Statusi'], customer_id:['Customer number','Numri i klientit'], amount:['Payment amount','Shuma e pagesës'],
  overdue:['Overdue balance','Borxhi i vonuar'], total_exposure:['Credit exposure','Ekspozimi i kredisë'], credit_limit:['Credit limit','Kufiri i kredisë'], utilization_percent:['Credit utilization %','Shfrytëzimi i kredisë %'],
  expected_at:['Expected date','Data e pritshme'], affected_value:['Affected value','Vlera e prekur'], eta:['Expected arrival','Mbërritja e pritshme'], delay_days:['Days delayed','Ditë vonesë'],
  expiry_date:['Expiry date','Data e skadimit'], severity:['Severity','Rëndësia'], type:['Type','Lloji'], health_state:['Connection health','Gjendja e lidhjes'], priority:['Priority','Përparësia'], due_at:['Due date','Afati'],
}
const operators={equals:['is','është'],not_equals:['is not','nuk është'],gt:['greater than','më e madhe se'],gte:['at least','së paku'],lt:['less than','më e vogël se'],lte:['at most','më së shumti'],contains:['contains','përmban'],not_contains:['does not contain','nuk përmban'],in:['is one of','është një nga'],not_in:['is not one of','nuk është një nga'],empty:['is empty','është bosh'],not_empty:['is not empty','nuk është bosh'],changed_from:['changed from','ndryshoi nga'],changed_to:['changed to','ndryshoi në']}
export const requestAutomation=(path,method='GET',data)=>apiRequest(path,{method,...(data?{body:JSON.stringify(data)}:{})})
export function useAutomationText(){const {language}=useTranslation();return (en,sq)=>language==='sq'?sq:en}

function ConditionGroup({node,onChange,fields,t,depth=0}) {
  const mode=node.all?'all':'any', children=node[mode] || []
  return <fieldset className="auto-condition"><legend>{t('Conditions','Kushtet')}</legend>
    <select aria-label={t('Match conditions','Përputhja e kushteve')} value={mode} onChange={e=>onChange({[e.target.value]:children})}><option value="all">{t('ALL conditions (AND)','TË GJITHA kushtet (DHE)')}</option><option value="any">{t('ANY condition (OR)','CILIDO kusht (OSE)')}</option></select>
    {children.map((child,i)=><div className="auto-condition-row" key={i}>
      {child.all || child.any ? <ConditionGroup node={child} fields={fields} t={t} depth={depth+1} onChange={value=>onChange({[mode]:children.map((x,j)=>j===i?value:x)})}/> : <>
        <select aria-label={t('Field','Fusha')} value={child.field} onChange={e=>onChange({[mode]:children.map((x,j)=>j===i?{...x,field:e.target.value}:x)})}>{fields.map(f=><option key={f} value={f}>{t(...(fieldNames[f] || [f,f]))}</option>)}</select>
        <select aria-label={t('Comparison','Krahasimi')} value={child.operator} onChange={e=>onChange({[mode]:children.map((x,j)=>j===i?{...x,operator:e.target.value,value:['in','not_in'].includes(e.target.value)?[]:''}:x)})}>{Object.entries(operators).map(([key,label])=><option key={key} value={key}>{t(...label)}</option>)}</select>
        {!['empty','not_empty'].includes(child.operator) && <input aria-label={t('Comparison value','Vlera e krahasimit')} placeholder={['in','not_in'].includes(child.operator)?t('Separate with commas','Ndaji me presje'):t('Value','Vlera')} value={Array.isArray(child.value)?child.value.join(', '):child.value ?? ''} onChange={e=>onChange({[mode]:children.map((x,j)=>j===i?{...x,value:['in','not_in'].includes(x.operator)?e.target.value.split(',').map(s=>s.trim()):e.target.value}:x)})}/>}</>}
      <button type="button" className="secondary" aria-label={t('Remove condition','Hiq kushtin')} onClick={()=>onChange({[mode]:children.filter((_,j)=>j!==i)})}>×</button>
    </div>)}
    <div className="auto-buttons"><button type="button" className="secondary" disabled={children.length>=12} onClick={()=>onChange({[mode]:[...children,{field:fields[0],operator:'equals',value:''}]})}>{t('+ Condition','+ Kusht')}</button>{depth<2 && <button type="button" className="secondary" onClick={()=>onChange({[mode]:[...children,{all:[]}]})}>{t('+ Group','+ Grup')}</button>}</div>
  </fieldset>
}

function Evaluation({value,t}) {
  if (value.children) return <ul>{value.children.map((c,i)=><li key={i}><Evaluation value={c} t={t}/></li>)}</ul>
  return <span>{value.matched?'✓':'–'} {t(...(fieldNames[value.field] || [value.field || 'Source unavailable',value.field || 'Burimi i padisponueshëm']))} {t(...(operators[value.operator] || ['','']))} {String(value.expected ?? '')} · {t('Actual','Aktuale')}: {String(value.actual ?? '—')}</span>
}

export default function AutomationStudio() {
  const t=useAutomationText(), permissions=useAuthStore(s=>s.permissions), can=p=>permissions.includes(p)
  const [params,setParams]=useSearchParams(), [catalog,setCatalog]=useState(null),[rules,setRules]=useState([]),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null),[runs,setRuns]=useState([]),[simulation,setSimulation]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function load(){const [c,r]=await Promise.all([requestAutomation('/automation-catalog'),requestAutomation('/automations')]);setCatalog(c);setRules(r.data)}
  const pending = useRef(false), selectedRequest = useRef(0)
  const [detailLoading, setDetailLoading] = useState(false)
  const [detailRevision, setDetailRevision] = useState(0)
  const selectedId = params.get('automation')
  useEffect(()=>{let active=true;Promise.all([requestAutomation('/automation-catalog'),requestAutomation('/automations')]).then(([c,r])=>{if(active){setCatalog(c);setRules(r.data)}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[])
  useEffect(() => {
    const request = ++selectedRequest.current
    if (!selectedId) { setSelected(null); setRuns([]); setDetailLoading(false); return undefined }
    setDetailLoading(true); setError(''); setDraft(null); setSimulation(null)
    Promise.all([requestAutomation(`/automations/${selectedId}`), can('automations.executions.view') ? requestAutomation(`/automations/${selectedId}/executions`) : Promise.resolve({data:[]})])
      .then(([rule, history]) => { if (request === selectedRequest.current) { setSelected(rule); setRuns(history.data) } })
      .catch(error => { if (request === selectedRequest.current) setError(error.message) })
      .finally(() => { if (request === selectedRequest.current) setDetailLoading(false) })
    return () => { selectedRequest.current++ }
  }, [selectedId, detailRevision])
  async function act(work){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await work()}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
  function inspect(rule){setDraft(null);setSimulation(null);setSelected(null);setRuns([]);setParams({automation:rule.id});setDetailRevision(value=>value+1)}
  const newRule=()=>{setParams({});const trigger=catalog.triggers['inventory.low_stock']?'inventory.low_stock':Object.keys(catalog.triggers)[0];setSelected(null);setSimulation(null);setDraft({name:'',description:'',trigger,conditions:{all:[]},actions:[{type:'create_task',title:'',due_days:1}],priority:'normal',schedule:null})}
  useEffect(()=>{if(catalog && params.get('new')==='1'){newRule();setParams({})}},[Boolean(catalog),params.get('new')])
  const change=(key,value)=>setDraft(d=>({...d,[key]:value})), changeAction=(i,key,value)=>change('actions',draft.actions.map((a,j)=>i===j?{...a,[key]:value}:a))
  return <main className="automation-page page-shell"><header className="page-header"><div><h1>{t('Automation Studio','Studio e automatizimit')}</h1><p>{t('When something happens, check conditions and prepare the next safe action.','Kur diçka ndodh, kontrollo kushtet dhe përgatit veprimin e sigurt vijues.')}</p></div>{catalog&&can('automations.create')&&<button onClick={newRule}>{t('Create automation','Krijo automatizim')}</button>}</header>
    {error&&<p role="alert" className="page-error">{error}</p>}{!catalog&&<p role="status">{t('Loading…','Duke ngarkuar…')}</p>}
    {detailLoading&&<p role="status">{t('Loading automation…','Duke ngarkuar automatizimin…')}</p>}
    {catalog&&<div className="automation-columns"><aside className="auto-panel"><h2>{t('Your automations','Automatizimet tuaja')}</h2>{rules.length===0&&<p>{t('Start with a template below. All templates are disabled until you enable them.','Fillo me një model më poshtë. Modelet janë joaktive derisa t’i aktivizoni.')}</p>}{rules.map(r=><button className={`auto-rule secondary ${selected?.id===r.id?'selected':''}`} key={r.id} onClick={()=>act(()=>inspect(r))}><strong>{r.name}</strong><span>{r.enabled?t('Enabled','Aktiv'):t('Disabled','Joaktiv')} · v{r.version}</span></button>)}
      {can('automations.create')&&<><h2>{t('Use a template','Përdor një model')}</h2>{catalog.templates.map((template,i)=><button className="auto-rule secondary" key={i} onClick={()=>{setSelected(null);setSimulation(null);setDraft({...template,name:t(template.name,template.name_sq),actions:template.actions.map(a=>({...a,title:t(template.name,template.name_sq)}))})}}>{t(template.name,template.name_sq)}<small>{t('Creates a review task · Disabled by default','Krijon detyrë rishikimi · Joaktiv fillimisht')}</small></button>)}</>}
    </aside><section className="auto-panel">
      {draft?<form onSubmit={e=>{e.preventDefault();act(async()=>{const saved=await requestAutomation(draft.id?`/automations/${draft.id}`:'/automations',draft.id?'PUT':'POST',draft);await load();await inspect(saved)})}}>
        <h2>{draft.id?t('Edit automation','Redakto automatizimin'):t('New automation','Automatizim i ri')}</h2><p>{t('Saving creates a disabled version. Review and test it before enabling.','Ruajtja krijon version joaktiv. Rishikoje dhe testo para aktivizimit.')}</p>
        <label>{t('Name','Emri')}<input required maxLength={160} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label>{t('Description','Përshkrimi')}<textarea value={draft.description || ''} onChange={e=>change('description',e.target.value)}/></label>
        <h3>{t('WHEN','KUR')}</h3><label>{t('Business event','Ngjarja e biznesit')}<select value={draft.trigger} onChange={e=>setDraft({...draft,trigger:e.target.value,schedule:null,conditions:{all:[]},actions:[{type:'create_task',title:'',due_days:1}]})}>{Object.values(catalog.triggers).map(x=><option key={x.key} value={x.key}>{t(x.label,x.label_sq)}</option>)}</select></label>
        {catalog.triggers[draft.trigger]?.scheduled&&<><label>{t('Scheduled checks (installation timezone)','Kontrolle periodike (zona kohore e instalimit)')}<select value={draft.schedule?.frequency || ''} onChange={e=>change('schedule',e.target.value?{frequency:e.target.value,time:'08:00',weekday:1}:null)}><option value="">{t('As events arrive','Kur mbërrijnë ngjarjet')}</option><option value="daily">{t('Every day','Çdo ditë')}</option><option value="weekly">{t('Every Monday','Çdo të hënë')}</option><option value="month_end">{t('Month end','Fundi i muajit')}</option></select></label>{draft.schedule&&<label>{t('Time','Ora')}<input type="time" required value={draft.schedule.time} onChange={e=>change('schedule',{...draft.schedule,time:e.target.value})}/></label>}</>}
        <h3>{t('IF','NËSE')}</h3><ConditionGroup t={t} fields={catalog.triggers[draft.trigger]?.fields || []} node={draft.conditions} onChange={x=>change('conditions',x)}/>
        <h3>{t('THEN','ATËHERË')}</h3>{draft.actions.map((a,i)=><fieldset key={i}><legend>{t('Action','Veprimi')} {i+1}</legend><label>{t('Action type','Lloji i veprimit')}<select value={a.type} onChange={e=>changeAction(i,'type',e.target.value)}>{Object.entries(catalog.actions).filter(([,x])=>!x.source || x.source===catalog.triggers[draft.trigger]?.source).map(([key,x])=><option key={key} value={key}>{t(x.label,x.label_sq)}</option>)}</select></label><label>{t('Title','Titulli')}<input required maxLength={160} value={a.title} onChange={e=>changeAction(i,'title',e.target.value)}/></label><label>{t('Instructions / why this matters','Udhëzime / pse ka rëndësi')}<textarea value={a.description || ''} onChange={e=>changeAction(i,'description',e.target.value)}/></label>
          {can('tasks.assign')&&<label>{t('Assign to','Cakto për')}<select value={a.assigned_user_id || ''} onChange={e=>changeAction(i,'assigned_user_id',e.target.value?Number(e.target.value):null)}><option value="">{t('Rule creator / team task','Krijuesi / detyrë e ekipit')}</option>{catalog.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}
          {a.type==='create_task'&&<label>{t('Due in days','Afati në ditë')}<input type="number" min="0" max="365" value={a.due_days ?? 1} onChange={e=>changeAction(i,'due_days',Number(e.target.value))}/></label>}
          {a.type==='create_task'&&can('tasks.assign')&&!a.assigned_user_id&&<label>{t('Responsible role','Roli përgjegjës')}<select value={a.assigned_role || ''} onChange={e=>changeAction(i,'assigned_role',e.target.value || null)}><option value="">{t('Rule creator','Krijuesi i rregullit')}</option><option value="admin">{t('Administrator','Administratori')}</option><option value="manager">{t('Manager','Menaxheri')}</option><option value="staff">{t('Staff','Stafi')}</option></select></label>}
          {a.type==='purchase_request_draft'&&<label>{t('Quantity to request (inventory unit)','Sasia e kërkuar (njësia e inventarit)')}<input required type="number" min="0.001" step="0.001" value={a.quantity ?? ''} onChange={e=>changeAction(i,'quantity',e.target.value)}/></label>}
          {draft.actions.length>1&&<button type="button" className="secondary" onClick={()=>change('actions',draft.actions.filter((_,j)=>j!==i))}>{t('Remove action','Hiq veprimin')}</button>}
        </fieldset>)}<button type="button" className="secondary" disabled={draft.actions.length>=8} onClick={()=>change('actions',[...draft.actions,{type:'create_task',title:'',due_days:1}])}>{t('+ Add action','+ Shto veprim')}</button>
        <label>{t('Priority','Përparësia')}<select value={draft.priority} onChange={e=>change('priority',e.target.value)}>{[['low','Low','E ulët'],['normal','Normal','Normale'],['high','High','E lartë'],['urgent','Urgent','Urgjente']].map(([v,en,sq])=><option value={v} key={v}>{t(en,sq)}</option>)}</select></label>
        <div className="auto-buttons"><button disabled={busy}>{busy?t('Saving…','Duke ruajtur…'):t('Save disabled draft','Ruaj draftin joaktiv')}</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>{t('Cancel','Anulo')}</button></div>
      </form>:selected?<><h2>{selected.name}</h2><p>{selected.description}</p><p>{t('Version','Versioni')} {selected.version} · {selected.enabled?t('Enabled','Aktiv'):t('Disabled','Joaktiv')} · {t('Executions','Ekzekutimet')}: {selected.run_count} · {t('Failed','Dështuar')}: {selected.failure_count}</p><p>{t('Last run','Ekzekutimi i fundit')}: {selected.last_run_at?new Date(selected.last_run_at).toLocaleString():'—'}</p>
        <div className="auto-buttons">{can('automations.edit')&&<button className="secondary" onClick={()=>setDraft(selected)}>{t('Edit','Redakto')}</button>}{can('automations.test')&&<button disabled={busy} onClick={()=>act(async()=>setSimulation(await requestAutomation(`/automations/${selected.id}/simulate`,'POST',{})))}>{t('Test against recent history','Testo mbi historikun e fundit')}</button>}{can(selected.enabled?'automations.disable':'automations.enable')&&<button disabled={busy} onClick={()=>act(async()=>{const r=await requestAutomation(`/automations/${selected.id}/toggle`,'POST',{enabled:!selected.enabled});await load();setSelected(r)})}>{selected.enabled?t('Disable','Çaktivizo'):t('Enable','Aktivizo')}</button>}{can('automations.create')&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{const r=await requestAutomation(`/automations/${selected.id}/duplicate`,'POST',{});await load();await inspect(r)})}>{t('Duplicate','Dupliko')}</button>}</div>
        {simulation&&<section className="auto-result" aria-live="polite"><h3>{t('Simulation — no actions performed','Simulim — asnjë veprim nuk u krye')}</h3><p>{simulation.evaluated} {t('events checked','ngjarje të kontrolluara')} · {simulation.matched} {t('matched','u përputhën')}</p><p>{t('Up to 100 events from 30 days. Missing event fields use the current record; unavailable sources do not match.','Deri 100 ngjarje nga 30 ditë. Fushat që mungojnë lexohen nga regjistrimi aktual; burimet e padisponueshme nuk përputhen.')}</p>{simulation.results.map(x=><details key={x.event_id}><summary>{x.reference || '#'+x.event_id} · {x.evaluation.matched?'✓':'–'}</summary><Evaluation value={x.evaluation} t={t}/>{x.would_execute.map((a,i)=><p key={i}>{t('Would execute','Do të kryhej')}: {t(catalog.actions[a.type]?.label || a.type,catalog.actions[a.type]?.label_sq || a.type)} — {a.title}</p>)}</details>)}</section>}
        <h3>{t('Execution history','Historiku i ekzekutimeve')}</h3>{runs.length===0&&<p>{t('No executions yet.','Ende nuk ka ekzekutime.')}</p>}{runs.map(r=><details key={r.id}><summary>#{r.id} · {t(r.status,({succeeded:'Sukses',failed:'Dështuar',blocked:'Bllokuar',skipped:'Anashkaluar',running:'Në punë',queued:'Në radhë'})[r.status] || r.status)} · v{r.version} · {new Date(r.created_at).toLocaleString()}</summary>{r.conditions_evaluated&&<Evaluation value={r.conditions_evaluated} t={t}/>}<p>{r.error}</p>{(r.results || []).map((x,i)=><p key={i}>{x.type} #{x.id} {x.url&&<a href={x.url}>{t('Open result','Hap rezultatin')}</a>}</p>)}{r.status==='failed'&&r.attempts<3&&can('automations.edit')&&<button disabled={busy} onClick={()=>act(async()=>{await requestAutomation(`/automation-executions/${r.id}/retry`,'POST',{});await inspect(selected)})}>{t('Retry safely','Riprovo në mënyrë të sigurt')}</button>}</details>)}</>:<p>{t('Choose an automation or template to begin.','Zgjidh një automatizim ose model për të filluar.')}</p>}
    {!draft&&selected&&<AutomationMetrics rule={selected}/>}</section></div>}
  </main>
}
