import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {Link,useSearchParams} from 'react-router-dom'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useDialog} from '../hooks/useDialog'
import SearchField from '../components/SearchField'
import {customerSalesTabs,customerSalesLabel,customerSalesMoney,filterCustomerProfiles} from './customerSalesPresentation'
import './CustomerSalesIntelligence.css'
const root='/customer-sales-intelligence'
export default function CustomerSalesIntelligence(){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,label=k=>customerSalesLabel(k,language),[params,setParams]=useSearchParams()
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState(params.get('view')||'overview'),[q,setQ]=useState(''),[kind,setKind]=useState('products'),[review,setReview]=useState(null),[sort,setSort]=useState('value'),[trendType,setTrendType]=useState('customers')
 const active=useRef(true),pending=useRef(false),money=v=>customerSalesMoney(v,data?.evidence?.currency,language)
 useEffect(()=>{active.current=true;apiRequest(root).then(r=>{if(active.current)setData(r)}).catch(e=>{if(active.current)setError(e.message)});return()=>{active.current=false}},[])
 const refresh=async()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const r=await apiRequest(root+'/refresh',{method:'POST'});if(active.current)setData(r)}catch(e){if(active.current)setError(e.message)}finally{pending.current=false;if(active.current)setBusy(false)}}
 const e=data?.evidence,profiles=filterCustomerProfiles(e?.profiles||[],q,tab==='atRisk').sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Number(b.summary.revenue)-Number(a.summary.revenue)),opportunities=(e?.opportunities||[]).filter(o=>!q||[o.customer,o.product].some(v=>v.toLowerCase().includes(q.toLowerCase())))
 const chooseTab=v=>{setTab(v);setQ('');setParams({view:v},{replace:true})}
 return <main className="customer-sales-intelligence">
  <header className="csi-header"><div><small>{t('CUSTOMER & SALES ANALYSIS','ANALIZA E KLIENTËVE DHE SHITJEVE')}</small><h1>{t('Customer & Sales Intelligence','Inteligjenca e klientëve dhe shitjeve')}</h1><p>{t('Understand buying patterns. Review the evidence. Keep every commercial action human-controlled.','Kupto modelet e blerjeve. Rishiko të dhënat. Mbaje çdo veprim tregtar në kontroll njerëzor.')}</p></div><button type="button" disabled={busy} onClick={refresh}>{busy?t('Calculating…','Duke llogaritur…'):t('Refresh evidence','Përditëso të dhënat')}</button></header>
  {error&&<p role="alert" className="csi-error">{error}</p>}
  {data?.state==='not_calculated'&&<section className="csi-panel"><h2>{label('INSUFFICIENT_DATA')}</h2><p>{t('Use Refresh evidence to calculate from existing transactions. No customer is contacted.','Përdor Përditëso të dhënat për llogaritje nga transaksionet ekzistuese. Asnjë klient nuk kontaktohet.')}</p></section>}
  {!data&&!error&&<p aria-busy="true">{t('Loading saved evidence…','Duke ngarkuar të dhënat e ruajtura…')}</p>}
  {e&&<><p className="csi-muted">{t('Evidence as of','Të dhënat deri më')} {data.as_of} • {e.history_from} → {data.as_of} {data.stale&&<span className="csi-badge">{t('Refresh recommended','Rekomandohet përditësimi')}</span>}</p><nav className="csi-tabs" aria-label={t('Customer intelligence sections','Seksionet e inteligjencës së klientëve')}>{customerSalesTabs.map(v=><button key={v} type="button" aria-pressed={tab===v} onClick={()=>chooseTab(v)}>{label(v)}</button>)}</nav>
   {['opportunities','atRisk','trends'].includes(tab)&&<SearchField value={q} onChange={event=>setQ(event.target.value)} placeholder={t('Search customers or products…','Kërko klientë ose produkte…')} aria-label={t('Search customer evidence','Kërko të dhënat e klientit')}/>}
   {tab==='overview'&&<><section className="csi-metrics"><Metric title={t('Recorded baskets','Blerje të regjistruara')} value={e.canonical_baskets}/><Metric title={t('Customers with history','Klientë me historik')} value={e.profiles.filter(p=>p.purchase_count).length}/><Metric title={t('Opportunities to review','Mundësi për rishikim')} value={e.opportunities.length}/><Metric title={t('Unusually inactive','Aktivitet i pazakontë')} value={filterCustomerProfiles(e.profiles,'',true).length}/></section><section className="csi-panel"><h2>{t('Customers to review today','Klientët për rishikim sot')}</h2><p>{t('Ranked by personal reorder timing, then recorded historical value. Related-product evidence follows. Stock and payment warnings do not silently change prices or credit rules.','Renditur sipas kohës personale të riporositjes, pastaj vlerës historike. Më pas vijnë produktet e lidhura. Paralajmërimet e stokut dhe pagesave nuk ndryshojnë çmimet ose rregullat e kredisë.')}</p><OpportunityCards rows={opportunities.slice(0,4)} t={t} label={label} money={money} onReview={setReview}/></section><section className="csi-panel"><h2>{t('What these signals do not mean','Çfarë nuk nënkuptojnë këto sinjale')}</h2><p>{t('A reorder window is not a guaranteed sale. Inactivity is relative to recorded buying cadence, not a permanent churn label. Customer signals explain—not add to—company demand forecasts.','Afati i riporositjes nuk garanton shitje. Joaktiviteti varet nga blerjet historike dhe nuk nënkupton humbje përfundimtare të klientit. Sinjalet shpjegojnë, por nuk shtohen mbi parashikimin e kërkesës së kompanisë.')}</p></section></>}
   {tab==='opportunities'&&<OpportunityCards rows={opportunities} t={t} label={label} money={money} onReview={setReview}/>}
   {tab==='trends'&&<label className="csi-sort">{t('Trend view','Pamja e trendit')}<select value={trendType} onChange={event=>{setTrendType(event.target.value);setQ('')}}><option value="customers">{t('Customers','Klientët')}</option><option value="products">{t('Products','Produktet')}</option><option value="categories">{t('Categories','Kategoritë')}</option></select></label>}
   {tab==='trends'&&trendType!=='customers'&&<ResourceTrends rows={e.resource_trends?.[trendType]||[]} query={q} t={t} label={label} money={money}/>}
   {(tab==='atRisk'||tab==='trends'&&trendType==='customers')&&<><label className="csi-sort">{t('Sort','Rendit')}<select value={sort} onChange={event=>setSort(event.target.value)}><option value="value">{t('Recorded sales','Shitjet e regjistruara')}</option><option value="name">{t('Customer name','Emri i klientit')}</option></select></label><div className="csi-table"><table><thead><tr>{[t('Customer','Klienti'),t('Activity','Aktiviteti'),t('Last purchase','Blerja e fundit'),t('Typical interval','Intervali tipik'),t('Recorded net sales','Shitjet neto të regjistruara'),t('Trend','Trendi'),t('Review','Rishiko')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td>{p.name}<small>{label(p.segment)}</small></td><td>{label(p.state)}</td><td>{p.last_purchase||'—'}</td><td>{p.cadence.eligible?`${p.cadence.q25_days}–${p.cadence.q75_days} ${t('days','ditë')}`:label('INSUFFICIENT_DATA')}</td><td>{money(p.summary.revenue)}</td><td>{label(p.trend.state)}<small>{p.trend.supported&&p.trend.change_percent!==null?`${p.trend.change_percent}%`:t('Limited comparable history','Historik krahasues i kufizuar')}</small></td><td><Link to={`/customer-debts?customer=${p.id}`}>{t('Review customer','Rishiko klientin')}</Link></td></tr>)}</tbody></table>{!profiles.length&&<Empty t={t}/>}</div></>}
   {tab==='affinity'&&<section className="csi-panel"><h2>{t('Genuine basket associations','Lidhjet nga blerjet reale')}</h2><p>{t('Requires 30 baskets, 5 co-purchases across 3 customers, support ≥10%, association confidence ≥35% and lift ≥1.2. Association is not a personal purchase forecast.','Kërkon 30 blerje, 5 blerje të përbashkëta nga 3 klientë, mbështetje ≥10%, lidhje ≥35% dhe lift ≥1.2. Kjo nuk është parashikim personal blerjeje.')}</p><select aria-label={t('Association type','Lloji i lidhjes')} value={kind} onChange={event=>setKind(event.target.value)}><option value="products">{t('Products','Produktet')}</option><option value="categories">{t('Categories','Kategoritë')}</option></select><div className="csi-table"><table><thead><tr>{[t('Bought item','Produkti i blerë'),t('Related item','Produkti i lidhur'),t('Co-purchases','Blerje së bashku'),t('Customers','Klientë'),t('Support','Mbështetje'),t('Association','Lidhja'),'Lift'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{e.affinity[kind].map(a=><tr key={`${a.source_id}-${a.target_id}`}><td>{a.source_name}</td><td>{a.target_name}</td><td>{a.pair_baskets}/{a.basket_count}</td><td>{a.customer_count}</td><td>{(100*a.support).toFixed(1)}%</td><td>{(100*a.association_confidence).toFixed(1)}%</td><td>{a.lift}</td></tr>)}</tbody></table>{!e.affinity[kind].length&&<Empty t={t}/>}</div></section>}
   {tab==='concentration'&&<section className="csi-panel"><h2>{t('Recorded sales concentration','Përqendrimi i shitjeve të regjistruara')}</h2><p>{e.concentration.from} → {e.concentration.to} • {t('Net sales','Shitjet neto')}: {money(e.concentration.net_sales)}</p><section className="csi-metrics">{[1,5,10].map(n=><Metric key={n} title={`${t('Top','Kryesorët')} ${n}`} value={e.concentration.top_shares[n]===null?'—':`${e.concentration.top_shares[n]}%`}/>)}</section><p>{t('Descriptive dependency—not automatically a danger label. Unassigned sales and returns stay in the denominator.','Varësi përshkruese, jo etiketim automatik rreziku. Shitjet pa klient dhe kthimet mbeten në total.')}</p>{Object.entries(e.concentration.groups).map(([group,rows])=><div key={group}><h3>{t({customers:'Customers',products:'Products',categories:'Categories'}[group],{customers:'Klientët',products:'Produktet',categories:'Kategoritë'}[group])}</h3><div className="csi-table"><table><thead><tr><th>{t('Name','Emri')}</th><th>{t('Net sales','Shitjet neto')}</th><th>{t('Share','Pjesa')}</th></tr></thead><tbody>{rows.slice(0,20).map((r,i)=><tr key={r.id||i}><td>{r.name}</td><td>{money(r.revenue)}</td><td>{r.share_percent===null?'—':`${r.share_percent}%`}</td></tr>)}</tbody></table></div></div>)}</section>}
   {tab==='health'&&<ModelHealth data={data} t={t} label={label} onChanged={setData}/>}
  </>}
  {review&&<OpportunityReview opportunity={review} data={data} t={t} label={label} money={money} onClose={()=>setReview(null)} onRefresh={()=>apiRequest(root).then(setData)}/>}
 </main>
}
function Metric({title,value}){return <div className="csi-panel csi-metric"><small>{title}</small><strong>{value}</strong></div>}
function ResourceTrends({rows,query,t,label,money}){
 const visible=rows.filter(r=>r.name?.toLowerCase().includes(query.toLowerCase()))
 return <section className="csi-panel"><p>{t('Recorded purchase activity before returns, compared with the previous 90 days or the same period last year when repeated seasonality is supported. Returns remain separate in net-sales summaries.','Aktiviteti i blerjeve para kthimeve, krahasuar me 90 ditët paraprake ose periudhën e njëjtë vitin e kaluar kur sezonaliteti mbështetet. Kthimet mbeten të ndara në përmbledhjet neto.')}</p><div className="csi-table"><table><thead><tr>{[t('Product / category','Produkti / kategoria'),t('Trend','Trendi'),t('Recent purchases','Blerjet e fundit'),t('Previous period','Periudha paraprake'),t('Evidence','Të dhënat')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.name}</td><td>{label(r.trend.state)}</td><td>{money(r.trend.recent_sales)}<small>{r.trend.recent_count} {t('baskets','blerje')}</small></td><td>{money(r.trend.previous_sales)}<small>{r.trend.previous_count} {t('baskets','blerje')}</small></td><td>{r.trend.supported?t('Comparable observations available','Të dhëna krahasuese në dispozicion'):label('INSUFFICIENT_DATA')}<small>{r.trend.comparison==='same_period_previous_year'?t('Same period last year','Periudha e njëjtë vitin e kaluar'):t('Previous 90 days','90 ditët paraprake')}</small></td></tr>)}</tbody></table>{!visible.length&&<Empty t={t}/>}</div></section>
}
function Empty({t}){return <p className="csi-muted">{t('No supported signals in this view. AIMS does not invent recommendations from sparse data.','Nuk ka sinjale të mbështetura në këtë pamje. AIMS nuk shpik rekomandime nga të dhëna të pakta.')}</p>}
function OpportunityCards({rows,t,label,money,onReview}){return rows.length?<div className="csi-grid">{rows.map(o=><article key={o.key} className="csi-panel"><small>{label(o.kind)}</small><h3>{o.customer}</h3><strong>{o.product}</strong><p>{o.window?`${o.window.start} → ${o.window.end}`:t('Related item not recorded in this customer’s history','Produkt i lidhur që nuk është regjistruar në historikun e këtij klienti')}</p>{o.quantity_range&&<p>{t('Historical purchase range','Intervali historik i blerjes')}: {o.quantity_range.join('–')} {o.unit} • {o.value_range.map(money).join('–')}</p>}<p>{t('Available to promise','Në dispozicion për shitje')}: {o.inventory.available_to_promise} {o.unit} • {t('Incoming','Në ardhje')}: {o.inventory.incoming}</p><div className="csi-tags">{o.decisions.slice(1).map(v=><span className="csi-badge" key={v}>{label(v)}</span>)}<span className="csi-badge">{t('Confidence','Besueshmëria')}: {label(o.confidence)}</span></div>{o.draft?<Link to={`/fulfillment?order=${o.draft.id}`}>{t('Open Order Draft','Hap draftin e porosisë')} {o.draft.order_number}</Link>:<button type="button" onClick={()=>onReview(o)}>{t('Review opportunity','Rishiko mundësinë')}</button>}</article>)}</div>:<Empty t={t}/>}
function OpportunityReview({opportunity:o,data,t,label,money,onClose,onRefresh}){
 const [quantity,setQuantity]=useState(''),[ack,setAck]=useState(false),[result,setResult]=useState(null),[created,setCreated]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),pending=useRef(false),alive=useRef(true),dialog=useDialog(onClose,busy)
 useEffect(()=>()=>{alive.current=false},[])
 const request=async(draft=false)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const r=await apiRequest(`${root}/predictions/${o.prediction_id}/${draft?'draft':'review'}`,{method:'POST',body:JSON.stringify({quantity,acknowledge_shortage:ack,...(draft?{confirm:true,review_token:result.review_token}:{})})});if(!alive.current)return;if(draft){setCreated(r);onRefresh()}else setResult(r)}catch(e){if(alive.current){setError(e.message);if(draft)setResult(null)}}finally{pending.current=false;if(alive.current)setBusy(false)}}
 return createPortal(<div className="csi-overlay"><section ref={dialog} className="csi-dialog" role="dialog" aria-modal="true" aria-labelledby="csi-review-title"><header className="csi-header"><h2 id="csi-review-title">{t('Review opportunity','Rishiko mundësinë')}</h2><button type="button" aria-label={t('Close','Mbyll')} disabled={busy} onClick={onClose}>×</button></header><h3>{o.customer} • {o.product}</h3><p>{label(o.kind)} • {label(o.confidence)}</p>{o.window&&<p>{o.window.start} → {o.window.end}</p>}<ul><li>{o.cadence?t(`${o.cadence.count} purchase dates; personal interval ${o.cadence.q25_days}–${o.cadence.q75_days} days.`,`${o.cadence.count} data blerjesh; interval personal ${o.cadence.q25_days}–${o.cadence.q75_days} ditë.`):t(`${o.association.pair_baskets} co-purchases across ${o.association.customer_count} customers. Lift ${o.association.lift}.`,`${o.association.pair_baskets} blerje të përbashkëta nga ${o.association.customer_count} klientë. Lift ${o.association.lift}.`)}</li><li>{t('Historical evidence is not a guaranteed sale or a suggested quantity to accept blindly.','Të dhënat historike nuk garantojnë shitje ose sasi për t’u pranuar pa rishikim.')}</li></ul><p>{t('Available','Në dispozicion')}: {o.inventory.available_to_promise} {o.unit} • {t('Incoming','Në ardhje')}: {o.inventory.incoming}</p>{o.inventory.incoming_schedule.map((v,i)=><p key={i}>{v.expected_at||v.date||'—'}: {v.qty??v.quantity} {o.unit}</p>)}<FinanceContext context={result?.financial_context||o.financial_context} t={t} label={label} money={money}/><Link to={`/customer-debts?customer=${o.customer_id}`}>{t('Review customer sheet','Rishiko fletën e klientit')}</Link>
  {error&&<p role="alert" className="csi-error">{error}</p>}{created?<section role="status"><h3>{t('Order draft created','Drafti i porosisë u krijua')}</h3><p>{created.order.order_number} • {created.order.status}</p><Link to={created.url}>{t('Open Order Draft','Hap draftin e porosisë')}</Link></section>:data.can_draft&&o.prediction_id?<><label className="csi-field">{t('Your chosen quantity','Sasia e zgjedhur nga ju')} ({o.unit})<input type="number" min="0.001" step={o.unit==='m'?'0.001':'1'} value={quantity} disabled={busy} onChange={event=>{setQuantity(event.target.value);setResult(null)}}/></label><label className="csi-check"><input type="checkbox" checked={ack} disabled={busy} onChange={event=>{setAck(event.target.checked);setResult(null)}}/>{t('I acknowledge any stock shortage; this is a draft, not a fulfillment promise.','Pranoj mungesën eventuale të stokut; ky është draft, jo premtim furnizimi.')}</label>{result&&<section className="csi-panel"><h3>{t('Confirm current facts','Konfirmo të dhënat aktuale')}</h3><p>{result.quantity} {result.unit} × {money(result.unit_price)} = {money(result.total)}</p><p>{t('Available to promise','Në dispozicion për shitje')}: {result.available_to_promise}</p>{result.shortage&&<p className="csi-error">{t('Quantity exceeds available stock.','Sasia tejkalon stokun e disponueshëm.')}</p>}</section>}<p className="csi-muted">{t('Creating a draft does not reserve stock, create debt or contact the customer. Existing order confirmation checks still apply.','Krijimi i draftit nuk rezervon stok, krijon borxh ose kontakton klientin. Kontrollet ekzistuese zbatohen gjatë konfirmimit të porosisë.')}</p><button type="button" disabled={busy||!quantity||Number(quantity)<=0||(result?.shortage&&!ack)} onClick={()=>request(Boolean(result))}>{busy?t('Processing…','Duke përpunuar…'):result?t('Confirm & Create Order Draft','Konfirmo dhe krijo draftin'):t('Review current price & stock','Rishiko çmimin dhe stokun aktual')}</button></>:null}</section></div>,document.body)
}
export function FinanceContext({context:c,t,label,money}){if(!c||c.state==='restricted')return <p className="csi-muted">{t('Financial context is restricted by permissions.','Konteksti financiar është i kufizuar nga lejet.')}</p>;return <section className="csi-finance"><p>{t('Debt','Borxhi')}: {money(c.debt)} • {t('Advance','Parapagimi')}: {money(c.advance)} • {t('Overdue','Në vonesë')}: {money(c.overdue)}</p><p>{label(c.payment_segment)} ({c.completed_payments} {t('completed payments','pagesa të përfunduara')})</p>{c.review_required&&<span className="csi-badge">{label('CUSTOMER_FINANCIAL_CONFLICT')}</span>}</section>}
function ModelHealth({data,t,label,onChanged}){
 const m=data.model,[choice,setChoice]=useState(m.champion),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),pending=useRef(false)
 const change=async()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{onChanged(await apiRequest(root+'/model',{method:'POST',body:JSON.stringify({model:choice,reason})}))}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
 return <section className="csi-panel"><h2>{t('Data and model health','Gjendja e të dhënave dhe modelit')}</h2><p>{t('Baseline and champion','Modeli bazë dhe modeli aktiv')}: {label(m.champion)}</p><p>{t('Challenger','Modeli krahasues')}: {label(m.challenger)} • {m.genuine_timing_outcomes}/{m.minimum_completed} {t('genuine timing outcomes','rezultate reale të kohës')}</p><p>{t('Completed forecast windows','Afate parashikimi të përfunduara')}: {m.completed_windows} • {t('Baseline timing error / Challenger','Gabimi kohor bazë / krahasues')}: {m.baseline_mae_days??'—'} / {m.challenger_mae_days??'—'} {t('days','ditë')}</p><p>{t('No production accuracy claim is made without genuine later observations. Local statistics are interpretable; no trained churn model is claimed.','Nuk pretendohet saktësi në prodhim pa rezultate reale të mëvonshme. Statistikat lokale shpjegohen; nuk pretendohet model i trajnuar për humbjen e klientëve.')}</p><p>{t('Local Python diagnostic','Diagnostikimi lokal Python')}: {label(data.evidence.local_model.state)}</p><p>{t('Minimum cadence: 6 distinct purchase dates. Seasonal evidence: repeated purchases across at least two completed calendar years.','Minimumi për intervalin: 6 data të ndryshme blerjesh. Sezonaliteti: blerje të përsëritura në të paktën dy vite kalendarike të përfunduara.')}</p>{data.evidence.health.length?<ul>{data.evidence.health.map(h=><li key={h.code}>{label(h.code)}: {h.count}</li>)}</ul>:<p>{t('No missing-identity or product-reference warnings found in the selected history.','Nuk u gjetën paralajmërime për identitetin ose produktet në historikun e zgjedhur.')}</p>}{data.can_model&&<><label className="csi-field">{t('Model selection / rollback','Zgjedhja e modelit / rikthimi')}<select value={choice} onChange={event=>setChoice(event.target.value)}><option value="interval_iqr_baseline">{label('interval_iqr_baseline')}</option><option value="median_mad" disabled={!m.eligible_for_promotion}>{label('median_mad')}</option></select></label><label className="csi-field">{t('Audit reason','Arsyeja për auditim')}<input value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="button" disabled={busy||reason.trim().length<5||choice===m.champion} onClick={change}>{t('Confirm model selection','Konfirmo zgjedhjen e modelit')}</button></>}{error&&<p role="alert">{error}</p>}</section>
}
