export const customerSalesTabs = ['overview', 'opportunities', 'atRisk', 'trends', 'affinity', 'concentration', 'health']
const copy = {
 overview:['Overview','Përmbledhje'],opportunities:['Opportunities','Mundësitë'],atRisk:['At-Risk Customers','Klientët për rishikim'],trends:['Customer Trends','Trendet e klientëve'],affinity:['Product Affinity','Produktet që blihen së bashku'],concentration:['Concentration','Përqendrimi'],health:['Data / Model Health','Të dhënat / Gjendja e modelit'],
 ACTIVE:['Active','Aktiv'],NEW:['New','I ri'],AT_RISK:['Below usual activity','Nën aktivitetin e zakonshëm'],INACTIVE:['Unusually inactive','Joaktiv sipas historikut'],SEASONAL_PAUSE:['Seasonal pause','Pushim sezonal'],INSUFFICIENT_DATA:['Collecting history','Duke mbledhur historikun'],COLLECTING_HISTORY:['Collecting history','Duke mbledhur historikun'],ESTABLISHED_BUYER:['Established buyer','Blerës i rregullt'],HIGH_VALUE_FREQUENT:['High-value frequent buyer','Blerës i shpeshtë me vlerë të lartë'],HIGH_VALUE_OCCASIONAL:['High-value occasional buyer','Blerës i herëpashershëm me vlerë të lartë'],GROWING:['Growing','Në rritje'],DECLINING:['Declining','Në rënie'],STABLE:['Stable','I qëndrueshëm'],REORDER_OPPORTUNITY:['Likely reorder review','Rishikim i riporositjes së mundshme'],RELATED_PRODUCT:['Related product opportunity','Mundësi për produkt të lidhur'],SALES_INVENTORY_CONFLICT:['Stock constraint','Kufizim i stokut'],CUSTOMER_FINANCIAL_CONFLICT:['Review financial exposure','Rishiko ekspozimin financiar'],CUSTOMER_INACTIVITY:['Review customer activity','Rishiko aktivitetin e klientit'],CUSTOMER_CONCENTRATION:['Concentration awareness','Vëmendje ndaj përqendrimit'],moderate:['Moderate','Mesatare'],limited:['Limited','E kufizuar'],interval_iqr_baseline:['Personal interval baseline','Modeli bazë i intervalit personal'],median_mad:['Median timing challenger','Modeli krahasues i kohës mesatare'],insufficient_history:['Collecting payment history','Duke mbledhur historikun e pagesave'],consistent_payer:['Consistent recorded payments','Pagesa të regjistruara të rregullta'],frequently_late:['Frequently late recorded payments','Pagesa shpesh me vonesë'],variable_payer:['Variable payment timing','Afate të ndryshueshme pagesash'],normal:['Normal','Normal'],warning:['Warning','Paralajmërim'],blocked:['Blocked','I bllokuar'],available:['Available','I disponueshëm'],unavailable:['Unavailable','I padisponueshëm'],missing_customer_identity:['Sales without a customer identity','Shitje pa identitet klienti'],missing_product_reference:['Missing product references','Referenca të produkteve mungojnë'],foreign_currency_documents:['Foreign currency excluded','Valutat e huaja të përjashtuara'],possible_duplicate_identity:['Matching names need manual review','Emrat e njëjtë kërkojnë rishikim manual']
}
export const customerSalesLabel=(key, language='en')=>copy[key]?.[language==='sq'?1:0] || key
export const customerSalesMoney=(value,currency='EUR',language='en')=>value===null||value===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value))
export function filterCustomerProfiles(profiles,q='',riskOnly=false){return profiles.filter(p=>(!riskOnly||['AT_RISK','INACTIVE'].includes(p.state))&&p.name.toLocaleLowerCase().includes(q.toLocaleLowerCase()))}
export const customerSalesAccess=permissions=>['analytics.view','customers.manage','daily_sales.manage'].every(p=>permissions.includes(p))
