const labels={
 inventory:['Inventory','Inventari'],supplier:['Supplier','Furnitori'],shipment:['Shipment','Dërgesa'],finance:['Finance','Financat'],customer:['Customer','Klienti'],
 overview:['Overview','Përmbledhja'],performance:['Recommendation Performance','Performanca e rekomandimeve'],humans:['Human Decisions','Vendimet e përdoruesve'],outcomes:['Outcomes','Rezultatet'],challengers:['Champion vs Challenger','Politika aktive dhe kandidati'],suggestions:['Policy Suggestions','Sugjerimet e politikave'],sufficiency:['Data Sufficiency','Mjaftueshmëria e të dhënave'],
 ACCEPTED:['Accepted','Pranuar'],MODIFIED:['Modified','Ndryshuar'],DISMISSED:['Dismissed','Refuzuar'],NOT_REVIEWED:['Not reviewed','Pa rishikim'],SUPERSEDED:['Superseded','Zëvendësuar'],EXPIRED:['Expired','Skaduar'],PRODUCTION:['Production champion','Politika aktive'],EXPERIMENTAL:['Experimental shadow','Kandidat eksperimental'],SHADOW:['Shadow experiment','Eksperiment në hije'],SUGGESTED:['Suggested — not applied','Sugjerim — nuk është zbatuar'],REVIEW:['Review needed','Kërkohet rishikim'],
 COLLECTING_DECISION_OUTCOMES:['Collecting decision outcomes','Duke mbledhur rezultatet e vendimeve'],OBSERVED_HISTORY:['Observed history available','Ka historik të vëzhguar'],COMPLETED_OBSERVATION:['Completed observed window','Periudhë e vëzhguar e përfunduar'],WAITING_FOR_GENUINE_OUTCOME:['Waiting for genuine outcome','Në pritje të rezultatit real'],READY_FOR_HUMAN_REVIEW:['Ready for authorized review','Gati për rishikim të autorizuar'],CLOSED_OR_CHAMPION_CHANGED:['Closed / champion changed','Mbyllur / politika aktive ndryshoi'],NOT_CAPTURED:['Not captured yet','Ende pa regjistrim'],
 REPLENISHMENT_DECISION:['Replenishment','Rifurnizimi'],PURCHASE_TIMING:['Purchase timing','Koha e blerjes'],SUPPLIER_SELECTION:['Supplier selection','Zgjedhja e furnitorit'],TRANSFER_VS_PURCHASE:['Transfer or purchase','Transferim ose blerje'],INCOMING_STOCK_RISK:['Incoming stock risk','Rreziku i furnizimit'],EXCESS_INVENTORY_ACTION:['Excess inventory review','Rishikim i stokut të tepërt'],
 demand_forecast:['Demand prediction','Parashikimi i kërkesës'],eta_prediction:['Arrival prediction','Parashikimi i mbërritjes'],cash_forecast:['Cash forecast','Parashikimi i parasë'],collections_forecast:['Payment timing','Koha e arkëtimit'],reorder_window:['Customer reorder window','Periudha e riporositjes së klientit'],activity_window:['Customer activity window','Periudha e aktivitetit të klientit'],quantity_calibration:['Quantity review','Rishikimi i sasive'],performance_review:['Service review','Rishikimi i shërbimit'],
 stockout_days:['Stockout days','Ditë me mungesë stoku'],excess_mean_quantity:['Mean quantity above declared ceiling','Sasia mesatare mbi kufirin e deklaruar'],purchase_cost:['Estimated purchase cost','Kosto e vlerësuar e blerjes'],
 ending_available:['Ending available quantity','Sasia e disponueshme në fund'],recorded_shortage_hours:['Recorded shortage hours (partial evidence)','Orët e regjistruara të mungesës (dëshmi të pjesshme)'],HISTORICAL_PREDICTION:['Historical frozen prediction','Parashikim historik i ngrirë'],supplier_lead:['Supplier lead prediction','Parashikimi i afatit të furnitorit'],
 excess_quantity:['Ending excess above original safety stock (V4)','Teprica në fund mbi stokun e sigurisë (V4)'],
 inventory_plan:['Inventory Planning V4 advice','Këshilla nga Planifikimi V4'],replenishment_advice:['Inventory V1 replenishment advice','Këshilla e rifurnizimit V1'],
}
export const learningLabel=(key,language='en')=>labels[key]?.[language==='sq'?1:0]||String(key||'—').replaceAll('_',' ')
export const learningNumber=(value,language='en')=>value===null||value===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:2}).format(Number(value))
export function outcomeCells(row){const d=row?.data||{};return {response:d.response?.state||'NOT_REVIEWED',recommended:d.response?.recommended_quantity??d.recommended?.base_quantity??null,chosen:d.response?.chosen_quantity??null,actual:d.chain?.actual_ordered_quantity??null,stockout:d.scorecard?.stockout_days??null,excess:d.scorecard?.excess_quantity??null,prediction:['prediction','prediction_outcome'].includes(row?.kind),complete:d.state==='COMPLETED_OBSERVATION'}}
export const canPromote=experiment=>experiment?.comparison?.eligible_for_human_review===true&&experiment?.closed===false
