import { useCallback,useEffect,useRef,useState } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { createPortal } from 'react-dom'
import { FileText,Upload,ArrowLeft,Download,X } from 'lucide-react'
import { useAuthStore } from '../store/authStore'
import { useSettingsStore } from '../store/settingsStore'
import * as api from '../api/documents'
import './Documents.css'
import LegacyDocuments from '../components/LegacyDocuments'
import DocumentPdfPreview from '../components/DocumentPdfPreview'
const typeName=(type,t)=>type?.labels?.[t('en','sq')]||type?.name||'—'

const documentLabels = {
  product:['Product','Produkti'],customer:['Customer','Klienti'],supplier:['Supplier','Furnitori'],
  'purchase-request':['Purchase request','Kërkesa për blerje'],rfq:['RFQ','Kërkesa për ofertë'],
  'purchase-order':['Purchase order','Porosia e blerjes'],'goods-receipt':['Goods receipt','Pranimi i mallit'],
  'quality-inspection':['Quality inspection','Inspektimi i cilësisë'],'supplier-claim':['Supplier claim','Ankesa ndaj furnitorit'],
  shipment:['Shipment','Dërgesa'],container:['Container','Kontejneri'],'sales-order':['Sales order','Porosia e shitjes'],
  delivery:['Delivery','Dorëzimi'],'outbound-return':['Customer return','Kthimi nga klienti'],return:['Return','Kthimi'],
  invoice:['Invoice','Fatura'],payment:['Payment','Pagesa'],expense:['Expense','Shpenzimi'],journal:['Journal','Ditari kontabël'],
  normal:['Normal','Normal'],internal:['Internal','I brendshëm'],confidential:['Confidential','Konfidencial'],restricted:['Restricted','I kufizuar'],
  valid:['Valid','I vlefshëm'],missing:['Missing','Mungon'],mismatch:['Checksum mismatch','Mospërputhje e gjurmës'],unavailable:['Unavailable','I padisponueshëm'],
  created:['Uploaded','Ngarkuar'],version_created:['New version','Version i ri'],linked:['Linked','Lidhur'],unlinked:['Unlinked','Shkëputur'],
  review_requested:['Review requested','Kërkuar shqyrtim'],approved:['Approved','Miratuar'],rejected:['Rejected','Refuzuar'],
  archived:['Archived','Arkivuar'],restored:['Restored','Rikthyer'],downloaded:['Downloaded','Shkarkuar'],previewed:['Previewed','Paraqitur'],
  metadata_updated:['Metadata updated','Të dhënat u ndryshuan'],hold_changed:['Legal hold changed','Ndalimi ligjor u ndryshua'],verified:['Integrity verified','Integriteti u verifikua']
}
const documentLabel=(value,t)=>documentLabels[value]?t(...documentLabels[value]):value.replaceAll('_',' ').replaceAll('-',' ')
export default function Documents(){
  const [params,setParams]=useSearchParams(),id=params.get('document'),sq=useSettingsStore(s=>s.language)==='sq',permissions=useAuthStore(s=>s.permissions)
  const t=(en,al)=>sq?al:en,can=p=>permissions.includes(`documents.${p}`)
  const [cfg,setCfg]=useState(null),[rows,setRows]=useState(null),[doc,setDoc]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(params.has('upload')),[preview,setPreview]=useState(null),[edit,setEdit]=useState(false),[settings,setSettings]=useState(false)
  const lock=useRef(false),generation=useRef(0),previewRef=useRef(null)
  useEffect(()=>{if(!preview)return;const previous=document.body.style.overflow,focused=document.activeElement;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape')setPreview(null);if(e.key==='Tab'){const items=previewRef.current?.querySelectorAll('button:not(:disabled),iframe');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);focused?.focus?.()}},[preview])
  const filters=Object.fromEntries(params.entries())
  const load=useCallback(async()=>{const g=++generation.current;try{const data=id?await api.detail(id):await api.documents(Object.fromEntries(params.entries()));if(g===generation.current){if(id)setDoc(data);else setRows(data)}}catch(e){if(g===generation.current)setError(e.message)}},[id,params])
  useEffect(()=>{api.config().then(setCfg).catch(e=>setError(e.message))},[])
  useEffect(()=>{setPreview(null);setDoc(null);setEdit(false);setUploading(params.has('upload'));setError('');load();return()=>{generation.current++}},[load,params])
  useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url)},[preview])
  async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');const g=generation.current;try{await fn();if(g===generation.current)await load()}catch(e){if(g===generation.current)setError(e.message)}finally{lock.current=false;setBusy(false)}}
  const filter=(key,value)=>{const n=new URLSearchParams(params);if(value)n.set(key,value);else n.delete(key);n.delete('page');setParams(n)}
  async function openFile(version,inline=false){await run(async()=>{const url=await api.file(id,version.version,inline);if(inline)setPreview({url,mime:version.mime_type});else{const a=document.createElement('a');a.href=url;a.download=version.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}})}
  const status=s=>({active:t('Active','Aktiv'),draft:t('Draft','Draft'),under_review:t('Under review','Në shqyrtim'),approved:t('Approved','Miratuar'),rejected:t('Rejected','Refuzuar'),archived:t('Archived','Arkivuar'),superseded:t('Superseded','Zëvendësuar'),normal:t('Normal','Normal'),internal:t('Internal','I brendshëm'),confidential:t('Confidential','Konfidencial'),restricted:t('Restricted','I kufizuar')})[s]||s
  return <main className="documents-page"><header className="documents-heading"><div><small>AIMS</small><h1><FileText/>{t('Document Center','Qendra e Dokumenteve')}</h1><p>{t('Business evidence, version history and secure relationships.','Dokumentet e biznesit, historiku i versioneve dhe lidhjet e sigurta.')}</p></div><div className="doc-actions">{id?<button disabled={busy} onClick={()=>setParams({})}><ArrowLeft size={16}/>{t('All documents','Të gjitha dokumentet')}</button>:can('upload')&&<button onClick={()=>setUploading(!uploading)}><Upload size={16}/>{t('Upload document','Ngarko dokument')}</button>}{can('manage')&&<button onClick={()=>setSettings(!settings)}>{t('Settings','Cilësimet')}</button>}</div></header>
    {error&&<p role="alert" className="doc-error">{error}</p>}
    {settings&&can('manage')&&<LegacyDocuments t={t}/>}
    {settings&&cfg&&<DocumentSettings cfg={cfg} t={t} onSave={d=>run(async()=>setCfg(await api.configure(d)))}/>}
    {uploading&&cfg&&<UploadForm cfg={cfg} t={t} id={id} entityType={params.get('entity_type')} entityId={params.get('entity_id')} onClose={()=>setUploading(false)} onSuccess={d=>{setUploading(false);setDoc(d);if(String(d.id)!==String(id))setParams({document:d.id.toString()})}}/>}
    {!id&&<><section className="doc-panel doc-filters"><label>{t('Search documents','Kërko dokumente')}<input type="search" value={filters.q||''} onChange={e=>filter('q',e.target.value)} placeholder={t('Title, reference, issuer, tags','Titulli, referenca, lëshuesi, etiketat')}/></label><label>{t('Type','Lloji')}<select value={filters.document_type_id||''} onChange={e=>filter('document_type_id',e.target.value)}><option value="">{t('All types','Të gjitha llojet')}</option>{cfg?.types.map(x=><option key={x.id} value={x.id}>{typeName(x,t)}</option>)}</select></label><label>{t('Status','Statusi')}<select value={filters.status||''} onChange={e=>filter('status',e.target.value)}><option value="">{t('All','Të gjitha')}</option>{['active','draft','under_review','approved','rejected','archived'].map(s=><option key={s} value={s}>{status(s)}</option>)}</select></label><label>{t('Expiry / retention','Skadimi / ruajtja')}<select value={filters.expiry||''} onChange={e=>filter('expiry',e.target.value)}><option value="">{t('All','Të gjitha')}</option><option value="soon">{t('Expiring soon','Skadon së shpejti')}</option><option value="expired">{t('Expired','Skaduar')}</option><option value="retention">{t('Retention review due','Afati i shqyrtimit të ruajtjes')}</option></select></label><label>{t('Sort','Rendit')}<select value={filters.sort||'created_at'} onChange={e=>filter('sort',e.target.value)}><option value="created_at">{t('Newest first','Më të rejat')}</option><option value="title">{t('Title','Titulli')}</option><option value="expiry_date">{t('Expiry date','Data e skadimit')}</option></select></label><label>{t('Confidentiality','Konfidencialiteti')}<select value={filters.confidentiality||''} onChange={e=>filter('confidentiality',e.target.value)}><option value="">{t('All','Të gjitha')}</option>{['normal','internal','confidential','restricted'].map(s=><option key={s} value={s}>{status(s)}</option>)}</select></label></section>
      <details className="doc-panel"><summary>{t('Filter by business record or date','Filtro sipas regjistrit ose datës')}</summary><EntityLink cfg={cfg} t={t} actionLabel={t('Filter records','Filtro regjistrat')} onLink={d=>{const n=new URLSearchParams(params);n.set('entity_type',d.entity_type);n.set('entity_id',d.entity_id);n.delete('page');setParams(n)}}/><div className="doc-filters"><label>{t('Uploaded from','Ngarkuar nga data')}<input type="date" value={filters.from||''} onChange={e=>filter('from',e.target.value)}/></label><label>{t('Uploaded until','Ngarkuar deri më')}<input type="date" value={filters.to||''} onChange={e=>filter('to',e.target.value)}/></label><label>{t('Created by user ID','Krijuar nga përdoruesi ID')}<input type="number" min="1" value={filters.created_by||''} onChange={e=>filter('created_by',e.target.value)}/></label></div></details>
      {filters.entity_type&&<p>{t('Related to','Lidhur me')}: {filters.entity_type} #{filters.entity_id} <button onClick={()=>setParams({})}>{t('Clear filter','Hiq filtrin')}</button></p>}
      <section className="doc-list" aria-label={t('Documents','Dokumentet')}>{rows?rows.data.length?rows.data.map(d=><article key={d.id} className="doc-card"><FileText size={28}/><div><Link to={`/documents?document=${d.id}`}><h2>{d.title}</h2></Link><p>{typeName(d.type,t)} · {d.reference||'—'}</p><small>v{d.current_version} · {status(d.status)} · {status(d.confidentiality)}</small>{d.expiry_date&&<p>{t('Expiry','Skadimi')}: {d.expiry_date}</p>}</div><Link to={`/documents?document=${d.id}`}>{t('Open','Hap')}</Link></article>):<p>{t('No documents match these filters.','Nuk ka dokumente për këta filtra.')}</p>:<p role="status">{t('Loading…','Duke ngarkuar…')}</p>}</section><div className="doc-actions"><button disabled={!rows||rows.current_page<=1} onClick={()=>{const p=new URLSearchParams(params);p.set('page',rows.current_page-1);setParams(p)}}>{t('Previous','Prapa')}</button><span>{rows?.current_page||1} / {rows?.last_page||1}</span><button disabled={!rows||rows.current_page>=rows.last_page} onClick={()=>{const p=new URLSearchParams(params);p.set('page',rows.current_page+1);setParams(p)}}>{t('Next','Tjetra')}</button></div></>}
    {id&&doc&&<><section className="doc-panel"><header className="documents-heading"><div><h2>{doc.title}</h2><p>{typeName(doc.type,t)} · v{doc.current_version} · {status(doc.status)} · {status(doc.confidentiality)}</p></div><div className="doc-actions">{can('update_metadata')&&<button disabled={busy} onClick={()=>setEdit(!edit)}>{t('Edit metadata','Ndrysho të dhënat')}</button>}{can('new_version')&&doc.status!=='archived'&&<button onClick={()=>setUploading(true)}>{t('New version','Version i ri')}</button>}{can('archive')&&<button disabled={busy} onClick={()=>run(()=>api.action(id,doc.status==='archived'?'restore':'archive'))}>{doc.status==='archived'?t('Restore','Rikthe'):t('Archive','Arkivo')}</button>}</div></header><p>{doc.description}</p><dl className="doc-metadata">{[[t('Reference','Referenca'),doc.reference],[t('Issuer','Lëshuesi'),doc.issuer],[t('Document date','Data e dokumentit'),doc.document_date],[t('Expiry','Skadimi'),doc.expiry_date],[t('Retain until','Ruaj deri më'),doc.retain_until||t('Indefinitely','Pa afat')],[t('Legal hold','Ndalim ligjor'),doc.legal_hold?t('Yes','Po'):t('No','Jo')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>{doc.expiry_state==='expired'&&<p role="status">{t('This document has expired.','Ky dokument ka skaduar.')}</p>}{doc.retain_until&&doc.retention_review_due&&<p>{t('Eligible for retention review. No automatic deletion.','Gati për shqyrtim të ruajtjes. Pa fshirje automatike.')}</p>}{edit&&<MetadataForm doc={doc} cfg={cfg} t={t} busy={busy} onSave={d=>run(async()=>{await api.update(id,d);setEdit(false)})}/>}</section>
      <section className="doc-panel"><h2>{t('Versions & preview','Versionet dhe pamja')}</h2>{doc.versions.map(v=><article className="doc-version" key={v.id}><div><strong>v{v.version} {v.version===doc.current_version?'• '+t('Current','Aktual'):''}</strong><p>{v.filename} · {(v.size/1024).toFixed(1)} KB</p><small>{v.created_at} · {v.change_note}</small><details><summary>SHA-256</summary><code>{v.checksum}</code></details><p>{t('Integrity','Integriteti')}: {v.integrity_status?documentLabel(v.integrity_status,t):t('Not verified','Pa verifikuar')}</p>{v.approval&&<p>{t('Approval','Miratimi')}: {status(v.approval.status)}</p>}</div><div className="doc-actions">{can('download')&&<><button disabled={busy} onClick={()=>openFile(v)}><Download size={16}/>{t('Download','Shkarko')}</button>{['application/pdf','image/jpeg','image/png','image/webp'].includes(v.mime_type)&&<button disabled={busy} onClick={()=>openFile(v,true)}>{t('Preview','Shiko')}</button>}</>}</div></article>)}{can('manage')&&<button disabled={busy} onClick={()=>run(()=>api.action(id,'verify'))}>{t('Verify file integrity','Verifiko integritetin e skedarit')}</button>}</section>
      <section className="doc-panel"><h2>{t('Review & protection','Shqyrtimi dhe mbrojtja')}</h2><div className="doc-actions">{can('review')&&doc.status!=='archived'&&<button disabled={busy} onClick={()=>run(()=>api.action(id,'review'))}>{t('Request review','Kërko shqyrtim')}</button>}{doc.status==='under_review'&&can('review')&&permissions.includes('approvals.decide')&&['approved','rejected'].map(d=><button key={d} disabled={busy} onClick={()=>run(()=>api.action(id,'decide',{decision:d}))}>{d==='approved'?t('Approve','Mirato'):t('Reject','Refuzo')}</button>)}</div>{can('manage')&&<form className="doc-actions" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>api.action(id,'hold',{legal_hold:!doc.legal_hold,hold_reason:f.get('reason')}))}}><input name="reason" required maxLength={2000} aria-label={t('Legal hold reason','Arsyeja e ndalimit ligjor')} placeholder={t('Reason for hold / release','Arsyeja e ndalimit / lirimit')}/><button disabled={busy}>{doc.legal_hold?t('Release hold','Liro ndalimin'):t('Place legal hold','Vendos ndalim ligjor')}</button></form>}</section>
      <section className="doc-panel"><h2>{t('Related business records','Regjistrat e lidhur të biznesit')}</h2>{doc.links.map(l=><p key={l.link_id}><Link to={l.url}>{l.label}</Link> · {l.type} {can('update_metadata')&&!doc.legal_hold&&<button disabled={busy} onClick={()=>run(()=>api.action(id,'unlink',{link_id:l.link_id}))}>{t('Unlink','Hiq lidhjen')}</button>}</p>)}{can('update_metadata')&&<EntityLink cfg={cfg} t={t} busy={busy} onLink={data=>run(()=>api.action(id,'link',data))}/>}</section>
      <section className="doc-panel"><h2>{t('Activity history','Historiku i aktiviteteve')}</h2><ol>{doc.activity.map(a=><li key={a.id}><strong>{documentLabel(a.event_type.replace('document.',''),t)}</strong> · {new Date(a.occurred_at).toLocaleString()}</li>)}</ol></section></>}
    {preview&&createPortal(<div className="doc-preview" ref={previewRef} role="dialog" aria-modal="true" aria-label={t('Document preview','Pamja e dokumentit')} onKeyDown={e=>{if(e.key==='Escape')setPreview(null)}}><button autoFocus onClick={()=>setPreview(null)}><X size={20}/>{t('Close preview','Mbyll pamjen')}</button>{preview.mime==='application/pdf'?<DocumentPdfPreview url={preview.url} t={t}/>:<img src={preview.url} alt={doc?.title||''}/>}</div>,document.body)}
  </main>
}

function EntityLink({cfg,t,busy,onLink,actionLabel}){const[type,setType]=useState(''),[query,setQuery]=useState(''),[options,setOptions]=useState([]),[id,setId]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;setId('');if(type){const timer=setTimeout(()=>api.entities(type,query).then(x=>{if(active)setOptions(x)}).catch(e=>{if(active)setError(e.message)}),200);return()=>{active=false;clearTimeout(timer)}}setOptions([])},[type,query]);return <form className="doc-filters" onSubmit={e=>{e.preventDefault();onLink({entity_type:type,entity_id:id})}}>{error&&<p role="alert">{error}</p>}<label>{t('Entity type','Lloji i regjistrit')}<select required value={type} onChange={e=>setType(e.target.value)}><option value="">{t('Select','Zgjidh')}</option>{cfg?.entities.map(x=><option key={x} value={x}>{documentLabel(x,t)}</option>)}</select></label><label>{t('Search related record','Kërko regjistrin')}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{t('Record','Regjistri')}<select required value={id} onChange={e=>setId(e.target.value)}><option value="">{t('Select','Zgjidh')}</option>{options.map(o=><option value={o.id} key={o.id}>{o.label}</option>)}</select></label><button disabled={busy||!id}>{actionLabel||t('Link document','Lidh dokumentin')}</button></form>}

function MetadataForm({doc={},cfg,t,busy,onSave}){return <form className="doc-form" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.tags=(d.tags||'').split(',').map(x=>x.trim()).filter(Boolean);onSave(d)}}><div className="doc-filters"><label>{t('Title','Titulli')}<input name="title" required defaultValue={doc.title} maxLength={255}/></label><label>{t('Type','Lloji')}<select name="document_type_id" defaultValue={doc.document_type_id}>{cfg?.types.map(x=><option key={x.id} value={x.id}>{typeName(x,t)}</option>)}</select></label><label>{t('Reference','Referenca')}<input name="reference" defaultValue={doc.reference}/></label><label>{t('Issuer','Lëshuesi')}<input name="issuer" defaultValue={doc.issuer}/></label><label>{t('Document date','Data e dokumentit')}<input type="date" name="document_date" defaultValue={doc.document_date}/></label><label>{t('Expiry date','Data e skadimit')}<input type="date" name="expiry_date" defaultValue={doc.expiry_date}/></label><label>{t('Retain until (blank = indefinitely)','Ruaj deri më (bosh = pa afat)')}<input type="date" name="retain_until" defaultValue={doc.retain_until}/></label><label>{t('Tags (comma separated)','Etiketat (ndaj me presje)')}<input name="tags" defaultValue={doc.tags?.join(', ')}/></label><label>{t('Confidentiality','Konfidencialiteti')}<select name="confidentiality" defaultValue={doc.confidentiality||'internal'}>{['normal','internal','confidential','restricted'].map(x=><option key={x} value={x}>{documentLabel(x,t)}</option>)}</select></label></div><label>{t('Description / notes','Përshkrimi / shënimet')}<textarea name="description" maxLength={5000} defaultValue={doc.description}/></label><button disabled={busy}>{t('Save metadata','Ruaj të dhënat')}</button></form>}

function UploadForm({cfg,t,id,entityType,entityId,onClose,onSuccess}){const[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[duplicates,setDuplicates]=useState(null),[values,setValues]=useState(null);const lock=useRef(false);async function send(data,allow=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{for(const file of files){const d=await api.upload(file,{...data,title:data.title||file.name,entity_type:entityType,entity_id:entityId,allow_duplicate:allow},id,setProgress);onSuccess(d)}setDuplicates(null)}catch(e){if(e.duplicate){setDuplicates(e.duplicate);setValues(data)}else setError(e.message)}finally{lock.current=false;setBusy(false)}}return <section className="doc-panel"><header className="documents-heading"><h2>{id?t('Upload new version','Ngarko version të ri'):t('Upload document','Ngarko dokument')}</h2><button disabled={busy} onClick={onClose}>{t('Close','Mbyll')}</button></header>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();send(Object.fromEntries(new FormData(e.currentTarget)))}}><label className="doc-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles(Array.from(e.dataTransfer.files).slice(0,1))}}>{t('Choose a file or drop it here','Zgjidh skedarin ose lëshoje këtu')}<input aria-label={t('Document file','Skedari i dokumentit')} type="file" accept={cfg.extensions.map(x=>'.'+x).join(',')} onChange={e=>setFiles(Array.from(e.target.files))}/>{files.map(f=><span key={f.name}>{f.name}</span>)}<small>{t('Maximum','Maksimumi')} {cfg.settings.max_file_mb} MB</small></label>{!id&&<div className="doc-filters"><label>{t('Title (optional)','Titulli (opsional)')}<input name="title" maxLength={255}/></label><label>{t('Type','Lloji')}<select name="document_type_id" required>{cfg.types.map(x=><option value={x.id} key={x.id}>{typeName(x,t)}</option>)}</select></label><label>{t('Expiry date','Data e skadimit')}<input type="date" name="expiry_date"/></label></div>}{id&&<label>{t('What changed?','Çfarë ndryshoi?')}<input name="change_note" required maxLength={2000}/></label>}<button disabled={busy||!files.length}>{busy?t('Uploading…','Duke ngarkuar…'):t('Upload','Ngarko')}</button>{busy&&<progress value={progress} max={100} aria-label={t('Upload progress','Progresi i ngarkimit')}/>}</form>{duplicates&&<div role="alert"><p>{t('These exact bytes already exist. Open and link an existing document, or create a separate document identity.','Këto të dhëna ekzistojnë. Hap dhe lidh dokumentin ekzistues, ose krijo një identitet të veçantë.')}</p>{duplicates.map(d=><p key={d.id}><Link to={`/documents?document=${d.id}`}>{d.title}</Link></p>)}<button disabled={busy} onClick={()=>send(values,true)}>{t('Keep as separate document','Mbaje si dokument të veçantë')}</button></div>}</section>}

function DocumentSettings({cfg,t,onSave}) {
  return <section className="doc-panel">
    <h2>{t('Document settings','Cilësimet e dokumenteve')}</h2>
    <form className="doc-form" onSubmit={e=>{
      e.preventDefault()
      const f=new FormData(e.currentTarget)
      onSave({max_file_mb:Number(f.get('max')),expiry_notice_days:Number(f.get('days')),allowed_extensions:f.getAll('extensions')})
    }}>
      <div className="doc-filters">
        <label>{t('Maximum file size (MB)','Madhësia maksimale (MB)')}<input name="max" type="number" min="1" max="50" required defaultValue={cfg.settings.max_file_mb}/></label>
        <label>{t('Expiry notice days','Ditët e njoftimit para skadimit')}<input name="days" type="number" min="1" max="365" required defaultValue={cfg.settings.expiry_notice_days}/></label>
      </div>
      <fieldset><legend>{t('Allowed file types','Llojet e lejuara të skedarëve')}</legend><div className="doc-actions">
        {cfg.extensions.map(ext=><label className="doc-checkbox" key={ext}><input type="checkbox" name="extensions" value={ext} defaultChecked={(cfg.settings.allowed_extensions||cfg.extensions).includes(ext)}/>{ext.toUpperCase()}</label>)}
      </div></fieldset>
      <button>{t('Save','Ruaj')}</button>
    </form>
    <form className="doc-filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({type_name:f.get('name'),requires_review:f.get('review')==='on'})}}>
      <label>{t('Add / update document type','Shto / ndrysho llojin')}<input name="name" required maxLength={100}/></label>
      <label className="doc-checkbox"><input name="review" type="checkbox"/>{t('Requires review','Kërkon shqyrtim')}</label><button>{t('Save type','Ruaj llojin')}</button>
    </form>
    <form className="doc-filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({entity_type:f.get('entity'),document_type_id:f.get('type'),requires_review:f.get('review')==='on',remove_requirement:f.get('remove')==='on'})}}>
      <label>{t('Entity','Regjistri')}<select name="entity">{cfg.entities.map(x=><option key={x} value={x}>{documentLabel(x,t)}</option>)}</select></label>
      <label>{t('Required document type','Lloji i kërkuar')}<select name="type">{cfg.types.map(x=><option value={x.id} key={x.id}>{typeName(x,t)}</option>)}</select></label>
      <label className="doc-checkbox"><input name="review" type="checkbox"/>{t('Approval required','Kërkohet miratim')}</label>
      <label className="doc-checkbox"><input name="remove" type="checkbox"/>{t('Remove requirement','Hiq kërkesën')}</label>
      <button>{t('Save requirement','Ruaj kërkesën')}</button>
    </form>
  </section>
}
