import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import {createPortal} from 'react-dom'
import { useSearchParams, Link } from 'react-router-dom'
import { Package, Truck, ClipboardCheck, Plus, ArrowLeft, RefreshCw } from 'lucide-react'
import { useSettingsStore } from '../store/settingsStore'
import { useAuthStore } from '../store/authStore'
import { apiRequest, buildApiUrl } from '../api/client'
import * as api from '../api/fulfillment'
import './Fulfillment.css'
import EntityDocuments from '../components/EntityDocuments'
import {DeliveryEditor, ReturnRequest, TaskAssignments, FulfillmentMetrics} from '../components/FulfillmentExtras'

const BarcodeScanner=lazy(()=>import('../components/BarcodeScanner'))
const num=v=>Number(v||0)
const key=()=>crypto.randomUUID()
export default function Fulfillment(){
  const sq=useSettingsStore(s=>s.language)==='sq';const t=(en,al)=>sq?al:en
  const permissions=useAuthStore(s=>s.permissions);const manage=permissions.includes('fulfillment.manage'),pick=permissions.includes('fulfillment.pick'),dispatch=permissions.includes('fulfillment.dispatch')
  const [params,setParams]=useSearchParams();const id=params.get('order')
  const [list,setList]=useState({data:[]}),[detail,setDetail]=useState(null),[queue,setQueue]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[credit,setCredit]=useState(null),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[creating,setCreating]=useState(false),[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[productSearch,setProductSearch]=useState(''),[customerSearch,setCustomerSearch]=useState(''),[form,setForm]=useState({customer_id:'',order_date:new Date().toISOString().slice(0,10),requested_delivery_date:'',priority:2,payment_type:'cash',notes:'',items:[]}),[packRows,setPackRows]=useState({}),[selectedPackages,setSelectedPackages]=useState([]),[suggestions,setSuggestions]=useState(null),[selectedTasks,setSelectedTasks]=useState([])
  const [editing,setEditing]=useState(false),[assignedTo,setAssignedTo]=useState(''),[warehouseOptions,setWarehouseOptions]=useState([]),[packageInfo,setPackageInfo]=useState({type:'box',weight:'',dimensions:'',notes:''}),[dispatchInfo,setDispatchInfo]=useState({driver:'',vehicle:'',notes:''})
  const [taskPage,setTaskPage]=useState(1)
  const queueFilters={task_page:taskPage,wave:params.get('wave'),warehouse_id:params.get('warehouse_id')}
  const routeFilters=Object.fromEntries(['view','wave','customer_id','product_id','warehouse_id'].filter(k=>params.get(k)).map(k=>[k,params.get(k)]))
  const routeKey=JSON.stringify(routeFilters)
  useEffect(()=>{setStatus(params.get('status')||'');setPage(1)},[params.get('status'),routeKey])
  useEffect(()=>{setCreating(!id&&params.get('new')==='1');setEditing(false)},[id,params.get('new')])
  const pending=useRef(false),request=useRef(0),createKey=useRef(key())
  const statusText=s=>({draft:t('Draft','Draft'),ready_to_allocate:t('Ready to allocate','Gati për caktim'),partially_allocated:t('Partially allocated','Pjesërisht e caktuar'),allocated:t('Allocated','E caktuar'),partially_picked:t('Partially picked','Pjesërisht e mbledhur'),picked:t('Picked','E mbledhur'),partially_packed:t('Partially packed','Pjesërisht e paketuar'),packed:t('Packed','E paketuar'),partially_dispatched:t('Partially dispatched','Pjesërisht e nisur'),dispatched:t('Dispatched','E nisur'),partially_delivered:t('Partially delivered','Pjesërisht e dorëzuar'),delivered:t('Delivered','E dorëzuar'),cancelled:t('Cancelled','E anuluar'),assigned:t('Assigned','E caktuar'),failed:t('Failed','Dështuar'),pending:t('Pending','Në pritje'),approved:t('Approved','Miratuar'),consumed:t('Approved for this order','Miratuar për këtë porosi'),rejected:t('Rejected','Refuzuar'),in_progress:t('In progress','Në proces'),completed:t('Completed','Përfunduar'),exception:t('Exception','Problem'),requested:t('Requested','Kërkuar'),authorized:t('Authorized','Autorizuar'),received:t('Received','Pranuar'),resolved:t('Resolved','Zgjidhur')})[s]||s
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{api.orders({search,status,page,...routeFilters}).then(x=>active&&setList(x)).catch(e=>active&&setError(e.message));api.queues(queueFilters).then(x=>active&&setQueue(x)).catch(e=>active&&setError(e.message))},200);return()=>{active=false;clearTimeout(timer)}},[search,status,page,routeKey,taskPage])
  useEffect(()=>{const version=++request.current;setError('');setCredit(null);setDetail(null);setSelectedPackages([]);setSuggestions(null);setPackRows({});setAssignedTo('');if(id)api.order(id).then(x=>version===request.current&&setDetail(x)).catch(e=>version===request.current&&setError(e.message));return()=>{request.current++}},[id])
  useEffect(()=>{if(!creating)return;let active=true;const timer=setTimeout(()=>{apiRequest(buildApiUrl('/products',{search:productSearch,per_page:25})).then(x=>active&&setProducts(x.data||x)).catch(e=>active&&setError(e.message));apiRequest(buildApiUrl('/customers',{search:customerSearch,per_page:25})).then(x=>active&&setCustomers(x.data||x)).catch(e=>active&&setError(e.message));apiRequest('/warehouses').then(x=>active&&setWarehouseOptions(x.data||x)).catch(e=>active&&setError(e.message))},200);return()=>{active=false;clearTimeout(timer)}},[creating,productSearch,customerSearch])
  async function run(name,data={}){if(pending.current)return;pending.current=true;setBusy(true);setError('');setCredit(null);const version=request.current;try{const updated=await api.action(id,name,{...data,idempotency_key:key()});if(version!==request.current)return;setSelectedPackages([]);setPackRows({});setDetail(updated);setQueue(await api.queues(queueFilters));setList(await api.orders({search,status,page,...routeFilters}));if(name==='reserve'&&suggestions)setSuggestions({...suggestions,rows:await api.candidates(suggestions.item.id)})}catch(e){if(version===request.current){setError(e.message);setCredit(e.credit)}}finally{pending.current=false;setBusy(false)}}
  function editDraft(){setForm({customer_id:detail.customer_id,order_date:detail.order_date,requested_delivery_date:detail.requested_delivery_date||'',priority:detail.priority,payment_type:detail.payment_type,warehouse_id:detail.warehouse_id||'',notes:detail.notes||'',items:detail.items.map(i=>({product_id:i.product_id,name:i.product.name,unit:i.unit,quantity:i.quantity,unit_price:i.unit_price,units:[{code:i.product.unit},...(i.product.units||[])]}))});setCustomers([detail.customer]);setCustomerSearch(detail.customer.name);setProductSearch('');setEditing(true);setCreating(true);window.scrollTo({top:0,behavior:'auto'})}
  async function save(e){e.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const data={...form,warehouse_id:form.warehouse_id||null,requested_delivery_date:form.requested_delivery_date||null,idempotency_key:editing?key():createKey.current};const o=editing?await api.action(id,'edit',data):await api.create(data);setCreating(false);setEditing(false);createKey.current=key();setDetail(o);setParams({order:o.id});setList(await api.orders({}));}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
  async function createWave(){if(pending.current)return;pending.current=true;setBusy(true);try{const tasks=queue.tasks.data.filter(x=>selectedTasks.includes(x.id));await api.wave({warehouse_id:tasks[0].warehouse_id,task_ids:selectedTasks});setQueue(await api.queues(queueFilters));setSelectedTasks([])}catch(e){setError(e.message)}finally{pending.current=false;setBusy(false)}}
  const button=(label,action,data={},disabled=false)=><button type="button" disabled={busy||disabled} onClick={()=>run(action,data)}>{label}</button>
  return <main className="fulfillment-page">
    <header className="fulfillment-heading"><div><small>AIMS · {t('Outbound warehouse','Daljet e magazinës')}</small><h1><Package size={27}/>{t('Orders & Fulfillment','Porositë & Përmbushja')}</h1><p>{t('Reserve, pick, pack and deliver customer orders.','Rezervoni, mblidhni, paketoni dhe dorëzoni porositë e klientëve.')}</p></div>{!id&&manage&&<button onClick={()=>{setEditing(false);setCreating(!creating)}}><Plus size={18}/>{t('New sales order','Porosi e re shitjeje')}</button>}{id&&<button onClick={()=>{setParams({});setDetail(null)}}><ArrowLeft size={17}/>{t('All orders','Të gjitha porositë')}</button>}</header>
    {id&&detail&&<EntityDocuments entityType="sales-order" entityId={detail.id}/>}
    {error&&<div role="alert" className="fulfillment-error">{error}</div>}
    {credit&&<section className="fulfillment-panel"><strong>{t('Credit control','Kontrolli i kredisë')}</strong><p>{t('Current exposure','Ekspozimi aktual')}: {credit.current_exposure} · {t('Projected','I parashikuar')}: {credit.projected_exposure} · {t('Limit','Limiti')}: {credit.credit_limit??'—'}</p>{manage&&button(t('Request credit override','Kërko miratim kredie'),'credit-override',{reason:t('Fulfill this customer order','Përmbush këtë porosi të klientit')})}</section>}
      {creating&&manage&&<form className="fulfillment-panel" onSubmit={save}><div className="fulfillment-toolbar"><h2>{editing?t('Edit sales order','Ndrysho porosinë e shitjes'):t('New sales order','Porosi e re shitjeje')}</h2><button type="button" disabled={busy} onClick={()=>setCreating(false)}>{t('Cancel editing','Anulo ndryshimin')}</button></div><div className="fulfillment-grid">
        <label>{t('Find customer','Kërko klientin')}<input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)}/></label>
        <label>{t('Customer','Klienti')}<select required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">{t('Select customer','Zgjidh klientin')}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label>{t('Order date','Data e porosisë')}<input type="date" required value={form.order_date} onChange={e=>setForm({...form,order_date:e.target.value})}/></label><label>{t('Requested delivery','Dorëzimi i kërkuar')}<input type="date" value={form.requested_delivery_date} onChange={e=>setForm({...form,requested_delivery_date:e.target.value})}/></label>
        <label>{t('Payment','Pagesa')}<select value={form.payment_type} onChange={e=>setForm({...form,payment_type:e.target.value})}><option value="cash">{t('Cash on dispatch','Pagesë në nisje')}</option><option value="credit">{t('Customer credit','Borxh i klientit')}</option><option value="prepaid">{t('Recorded customer advance','Parapagim i regjistruar')}</option></select></label>
        <label>{t('Preferred warehouse','Magazina e preferuar')}<select value={form.warehouse_id||''} onChange={e=>setForm({...form,warehouse_id:e.target.value})}><option value="">{t('Any warehouse','Çdo magazinë')}</option>{warehouseOptions.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>{t('Priority','Prioriteti')}<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="1">{t('High','I lartë')}</option><option value="2">{t('Normal','Normal')}</option><option value="3">{t('Low','I ulët')}</option></select></label></div>
        <label>{t('Find product','Kërko produktin')}<input value={productSearch} onChange={e=>setProductSearch(e.target.value)}/></label><label>{t('Add product','Shto produkt')}<select value="" onChange={e=>{const p=products.find(x=>String(x.id)===e.target.value);if(p)setForm({...form,items:[...form.items,{product_id:p.id,name:p.name,unit:p.unit,quantity:'1',unit_price:p.selling_price||p.price||'0',units:[{code:p.unit},...(p.units||[])]}]})}}><option value="">{t('Select product','Zgjidh produktin')}</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.sku}</option>)}</select></label>
        {form.items.map((line,i)=><div className="fulfillment-line" key={i}><strong>{line.name}</strong><label>{t('Unit','Njësia')}<select value={line.unit} onChange={e=>setForm({...form,items:form.items.map((x,j)=>j===i?{...x,unit:e.target.value}:x)})}>{line.units.map((u,j)=><option key={j} value={u.code}>{u.code}</option>)}</select></label><label>{t('Quantity','Sasia')}<input aria-label={`${t('Quantity','Sasia')} ${i+1}`} type="number" min="0.001" step="0.001" required value={line.quantity} onChange={e=>setForm({...form,items:form.items.map((x,j)=>j===i?{...x,quantity:e.target.value}:x)})}/></label><label>{t('Unit price','Çmimi për njësi')}<input type="number" min="0" step="0.01" required value={line.unit_price} onChange={e=>setForm({...form,items:form.items.map((x,j)=>j===i?{...x,unit_price:e.target.value}:x)})}/></label><button type="button" onClick={()=>setForm({...form,items:form.items.filter((_,j)=>j!==i)})}>{t('Remove','Hiq')}</button></div>)}
        <label>{t('Notes','Shënime')}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button disabled={busy||!form.items.length}>{t('Save sales order','Ruaj porosinë e shitjes')}</button>
      </form>}
    {!id&&<>
      <div className="fulfillment-metrics">{[[t('Awaiting allocation','Në pritje të caktimit'),queue?.counts?.ready_to_allocate],[t('Ready to pick','Gati për mbledhje'),queue?.counts?.allocated],[t('Picking in progress','Mbledhje në proces'),queue?.counts?.partially_picked],[t('Packing required','Paketim i nevojshëm'),num(queue?.counts?.picked)+num(queue?.counts?.partially_packed)],[t('Ready to dispatch','Gati për nisje'),queue?.counts?.packed],[t('Late orders','Porosi të vonuara'),queue?.late_orders],[t('Failed deliveries','Dorëzime të dështuara'),queue?.failed_deliveries],[t('Returns awaiting action','Kthime në pritje'),queue?.returns_awaiting_action]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value||0}</strong></article>)}</div>

      <FulfillmentMetrics metrics={queue?.metrics} t={t}/>
      {Object.keys(routeFilters).length>0&&<p>{t('Filtered view','Pamje e filtruar')}: {routeFilters.view==='returns'?t('Returns awaiting action','Kthime në pritje'):routeFilters.view==='late'?t('Late orders','Porosi të vonuara'):Object.entries(routeFilters).map(([k,v])=>`${k}: ${v}`).join(' · ')} <button onClick={()=>setParams({})}>{t('Clear filters','Hiq filtrat')}</button></p>}
      <section className="fulfillment-panel"><div className="fulfillment-toolbar"><input aria-label={t('Search orders','Kërko porositë')} placeholder={t('Order or customer…','Porosia ose klienti…')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select aria-label={t('Order status','Statusi i porosisë')} value={status} onChange={e=>{const p=new URLSearchParams(params);e.target.value?p.set('status',e.target.value):p.delete('status');setParams(p);setPage(1)}}><option value="">{t('All statuses','Të gjitha statuset')}</option>{['draft','ready_to_allocate','partially_allocated','allocated','partially_picked','picked','partially_packed','packed','partially_dispatched','dispatched','partially_delivered','delivered','cancelled'].map(s=><option key={s} value={s}>{statusText(s)}</option>)}</select></div>
      <div className="fulfillment-table"><table><thead><tr>{[t('Order','Porosia'),t('Customer','Klienti'),t('Delivery date','Data e dorëzimit'),t('Status','Statusi'),t('Total','Totali'),''].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{list.data.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.customer?.name}</td><td>{o.requested_delivery_date||'—'}</td><td>{statusText(o.status)}</td><td>{o.total_amount} {o.currency}</td><td><button onClick={()=>setParams({order:o.id})}>{t('Open order','Hap porosinë')}</button></td></tr>)}</tbody></table></div>{!list.data.length&&<p>{t('No orders found.','Nuk u gjetën porosi.')}</p>}<div className="fulfillment-toolbar"><button disabled={page===1} onClick={()=>setPage(page-1)}>{t('Previous','Para')}</button><span>{page} / {list.last_page||1}</span><button disabled={page>=(list.last_page||1)} onClick={()=>setPage(page+1)}>{t('Next','Tjetër')}</button></div></section>
      <section className="fulfillment-panel"><h2><ClipboardCheck/>{t('Pick queue','Radha e mbledhjes')}</h2>{queue?.tasks?.data?.map(task=><div className="fulfillment-task" key={task.id}><label><input type="checkbox" disabled={!['pending','assigned'].includes(task.status)||!!task.pick_wave_id} checked={selectedTasks.includes(task.id)} onChange={e=>setSelectedTasks(e.target.checked?[...selectedTasks,task.id]:selectedTasks.filter(x=>x!==task.id))}/>{task.reference}</label><span>{task.order?.customer?.name} · {statusText(task.status)}</span><button onClick={()=>setParams({order:task.sales_order_id})}>{t('Open pick task','Hap detyrën')}</button></div>)}{manage&&<button disabled={busy||!selectedTasks.length} onClick={createWave}>{t('Group selected tasks into a wave','Grupo detyrat në valë')}</button>}<div className="fulfillment-toolbar"><button disabled={taskPage<=1} onClick={()=>{setTaskPage(taskPage-1);setSelectedTasks([])}}>{t('Previous tasks','Detyrat e mëparshme')}</button><span>{taskPage} / {queue?.tasks?.last_page||1}</span><button disabled={taskPage>=(queue?.tasks?.last_page||1)} onClick={()=>{setTaskPage(taskPage+1);setSelectedTasks([])}}>{t('Next tasks','Detyrat vijuese')}</button></div>{queue?.waves?.map(w=><p key={w.id}><Link to={`/fulfillment?wave=${w.id}`}>{w.reference}</Link> · {w.tasks_count} {t('tasks','detyra')}</p>)}</section>
    </>}
    {id&&!detail&&!error&&<p role="status">{t('Loading order…','Duke ngarkuar porosinë…')}</p>}
    {detail&&<>
      <section className="fulfillment-panel"><div className="fulfillment-toolbar"><h2>{detail.order_number}</h2><strong className="fulfillment-badge">{statusText(detail.status)}</strong><button disabled={busy} onClick={()=>api.order(id).then(setDetail).catch(e=>setError(e.message))}><RefreshCw size={16}/>{t('Refresh','Përditëso')}</button></div><p><Link to={`/customer-debts?customer=${detail.customer_id}`}>{detail.customer?.name}</Link> · {detail.total_amount} {detail.currency}</p>
      <div className="fulfillment-grid"><span>{t('Exposure','Ekspozimi')}: {detail.credit?.total_exposure}</span><span>{t('Advance','Parapagimi')}: {detail.credit?.advance}</span><span>{t('Available credit','Kredia në dispozicion')}: {detail.credit?.available_credit??'—'}</span></div>{detail.approval&&<p>{t('Credit override','Miratimi i kredisë')}: {statusText(detail.approval.status)} · <Link to="/procurement">{t('Open approvals','Hap miratimet')}</Link></p>}
      {manage&&<div className="fulfillment-toolbar">{!detail.confirmed_at&&<button disabled={busy} onClick={editDraft}>{t('Edit draft','Ndrysho draftin')}</button>}{!detail.confirmed_at&&detail.status!=='cancelled'&&button(t('Confirm order','Konfirmo porosinë'),'confirm')}{detail.confirmed_at&&detail.status!=='cancelled'&&<>{button(t('Reserve available stock','Rezervo stokun në dispozicion'),'reserve')}<label>{t('Assign new tasks to','Cakto detyrat e reja te')}<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">{t('Unassigned','Pa caktuar')}</option>{queue?.pickers?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{button(t('Create pick tasks','Krijo detyrat e mbledhjes'),'allocate',{assigned_to:assignedTo||null})}{button(t('Release unpicked reservations','Liro rezervimet e pambeldhura'),'release')}</>}{detail.status!=='cancelled'&&button(t('Cancel order','Anulo porosinë'),'cancel')}</div>}
      <div className="fulfillment-table"><table><thead><tr>{[t('Product','Produkti'),t('Requested','Kërkuar'),t('Available now','Në dispozicion'),t('ATP by delivery','ATP deri në dorëzim'),t('Reserved','Rezervuar'),t('Picked','Mbledhur'),t('Packed','Paketuar'),t('Dispatched','Nisur'),t('Delivered','Dorëzuar')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{detail.items.map(i=><tr key={i.id}><td>{i.product?.name}<small>{i.product?.unit}</small>{manage&&<button onClick={()=>api.candidates(i.id).then(rows=>setSuggestions({item:i,rows})).catch(e=>setError(e.message))}>{t('Locations','Lokacionet')}</button>}</td><td>{i.base_quantity}</td><td>{detail.availability?.[i.product_id]?.available}</td><td>{detail.availability?.[i.product_id]?.available_to_promise_by_as_of}<small>{t('Incoming','Në ardhje')}: {detail.availability?.[i.product_id]?.incoming??'—'}</small><small>{t('Expected availability','Disponueshmëria e pritur')}: {detail.availability?.[i.product_id]?.expected_availability_date||'—'}</small></td>{['reserved','picked','packed','dispatched','delivered'].map(s=><td key={s}>{i[s+'_quantity']}</td>)}</tr>)}</tbody></table></div></section>
      {suggestions&&<section className="fulfillment-panel"><h3>{suggestions.item.product?.name} · {t('Eligible stock','Stoku i përshtatshëm')}</h3>{detail.allocations.filter(a=>a.sales_order_item_id===suggestions.item.id&&a.status!=='released'&&num(a.quantity)>num(a.picked_quantity)).map(a=><div className="fulfillment-task" key={a.id}><span>{a.warehouse?.name} · {a.location?.path||'—'} · {a.lot?.lot_number||'—'} · {t('Reserved','Rezervuar')}: {a.quantity}</span>{button(t('Release this allocation','Liro këtë caktim'),'release',{allocation_id:a.id})}</div>)}{suggestions.rows.map((c,i)=><ManualAllocation key={i} c={c} t={t} busy={busy} onSave={(quantity,reason)=>run('reserve',{allocations:[{...c,sales_order_item_id:suggestions.item.id,quantity}],reason})}/>)}<button onClick={()=>setSuggestions(null)}>{t('Close','Mbyll')}</button></section>}
      <section className="fulfillment-panel"><h2><ClipboardCheck/>{t('Pick & verify','Mblidh & verifiko')}</h2>{manage&&<TaskAssignments tasks={detail.tasks} pickers={queue?.pickers||[]} t={t} busy={busy} statusText={statusText} onSave={d=>run('assign',d)}/>}<div className="fulfillment-pick-grid">{detail.allocations.filter(a=>a.status!=='released'&&a.pick_task_id).map(a=><PickCard key={a.id} a={a} t={t} busy={busy||!pick} onSave={d=>run('pick',d)}/>)}</div></section>
      <section className="fulfillment-panel"><h2><Package/>{t('Packing','Paketimi')}</h2>{detail.allocations.filter(a=>num(a.picked_quantity)>num(a.packed_quantity)).map(a=><label key={a.id} className="fulfillment-pack-line">{a.item?.product?.name} · {t('Unpacked','Pa paketuar')}: {num(a.picked_quantity)-num(a.packed_quantity)}<input aria-label={`${t('Pack quantity','Sasia për paketim')} ${a.id}`} type="number" min="0" step="0.001" max={num(a.picked_quantity)-num(a.packed_quantity)} value={packRows[a.id]??''} onChange={e=>setPackRows({...packRows,[a.id]:e.target.value})}/></label>)}{pick&&<div className="fulfillment-grid">{[['type',t('Package type','Lloji i pakos')],['weight',t('Weight (kg, optional)','Pesha (kg, opsionale)')],['dimensions',t('Dimensions (optional)','Përmasat (opsionale)')],['notes',t('Package notes','Shënime të pakos')]].map(([field,label])=><label key={field}>{label}<input type={field==='weight'?'number':'text'} min={field==='weight'?'0.001':undefined} step={field==='weight'?'0.001':undefined} value={packageInfo[field]} onChange={e=>setPackageInfo({...packageInfo,[field]:e.target.value})}/></label>)}</div>}{pick&&button(t('Create package','Krijo pakon'),'pack',{...packageInfo,weight:packageInfo.weight||null,items:Object.entries(packRows).filter(([,q])=>num(q)>0).map(([allocation_id,quantity])=>({allocation_id,quantity}))},!Object.values(packRows).some(q=>num(q)>0))}
      {detail.packages.map(p=><div className="fulfillment-task" key={p.id}><label><input type="checkbox" disabled={!!p.outbound_dispatch_id} checked={selectedPackages.includes(p.id)} onChange={e=>setSelectedPackages(e.target.checked?[...selectedPackages,p.id]:selectedPackages.filter(x=>x!==p.id))}/>{p.reference}</label><span>{p.items?.map(x=>x.quantity).join(' + ')}</span>{!p.outbound_dispatch_id&&pick&&button(t('Unpack / correct','Çpaketo / korrigjo'),'unpack',{package_id:p.id})}</div>)}{dispatch&&<div className="fulfillment-grid">{[['driver',t('Driver','Shoferi')],['vehicle',t('Vehicle','Automjeti')],['notes',t('Dispatch notes / reference','Shënime / referencë e nisjes')]].map(([field,label])=><label key={field}>{label}<input value={dispatchInfo[field]} onChange={e=>setDispatchInfo({...dispatchInfo,[field]:e.target.value})}/></label>)}</div>}<div className="fulfillment-toolbar"><button disabled={busy} onClick={()=>api.slip(id).catch(e=>setError(e.message))}>{t('Download packing slip','Shkarko fletëpaketimin')}</button>{dispatch&&button(t('Dispatch selected packages','Nis pakot e zgjedhura'),'dispatch',{...dispatchInfo,package_ids:selectedPackages},!selectedPackages.length)}</div></section>
      <section className="fulfillment-panel"><h2><Truck/>{t('Deliveries','Dorëzimet')}</h2>{detail.dispatches.map(d=><div key={d.id}><DeliveryEditor d={d} detail={detail} statusText={statusText} t={t} busy={busy||!dispatch} onSave={data=>run('delivery',data)}/><EntityDocuments compact entityType="delivery" entityId={d.id}/></div>)}</section>
      <section className="fulfillment-panel"><h2>{t('Customer returns','Kthimet e klientit')}</h2>{manage&&<ReturnRequest detail={detail} t={t} busy={busy} onSave={d=>run('return',d)}/>} {detail.returns.map(r=><div key={r.id}><ReturnCard guest={!detail.customer_id} r={r} t={t} busy={busy||!manage} statusText={statusText} onSave={data=>run('return',data)}/><EntityDocuments compact entityType="outbound-return" entityId={r.id}/></div>)}</section>
    </>}
  </main>
}
function PickCard({a,t,busy,onSave}){const [scanning,setScanning]=useState(false);useEffect(()=>{if(!scanning)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow}},[scanning]);const [qty,setQty]=useState(a.picked_quantity),[barcode,setBarcode]=useState(''),[manual,setManual]=useState(false),[reason,setReason]=useState('');return <form className="fulfillment-pick-card" onSubmit={e=>{e.preventDefault();onSave({allocation_id:a.id,quantity:qty,barcode,manual_verification:manual,location_id:a.location_id,inventory_lot_id:a.inventory_lot_id,reason})}}>{a.item?.product?.image_url&&<img src={a.item.product.image_url} alt=""/>}<h3>{a.item?.product?.name}</h3><p>{a.item?.product?.sku} · {a.warehouse?.name} · {a.location?.path||t('Default location','Lokacioni bazë')}</p><p>{a.lot?.lot_number||a.lot?.serial_number||'—'} · {a.lot?.expiry_at?.slice(0,10)||''}</p><strong>{t('Required','Kërkuar')}: {a.quantity} {a.item?.product?.unit}</strong><label>{t('Barcode','Barkodi')}<input value={barcode} onChange={e=>setBarcode(e.target.value)} autoComplete="off"/></label><button type="button" disabled={busy} onClick={()=>setScanning(true)}>{t('Scan with camera','Skano me kamerë')}</button>{scanning&&createPortal(<Suspense fallback={<p role="status">{t('Opening scanner…','Duke hapur skanerin…')}</p>}><BarcodeScanner onClose={()=>setScanning(false)} onScanSuccess={code=>{setBarcode(code);setScanning(false)}}/></Suspense>,document.body)}<label className="fulfillment-check"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/>{t('I verified the product, location and lot','Verifikova produktin, lokacionin dhe lotin')}</label><label>{t('Total picked','Gjithsej mbledhur')}<input required type="number" min={a.picked_quantity} max={a.quantity} step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></label><label>{t('Short-pick reason (if needed)','Arsyeja e mungesës (nëse duhet)')}<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>{t('Verify pick','Verifiko mbledhjen')}</button></form>}
function ManualAllocation({c,t,busy,onSave}){const[q,setQ]=useState(''),[reason,setReason]=useState('');return <form className="fulfillment-line" onSubmit={e=>{e.preventDefault();onSave(q,reason)}}><span>{c.warehouse} · {c.location||'—'} · {c.lot||'—'} · {c.expiry||'—'} · {t('Available','Në dispozicion')}: {c.available}</span><input aria-label={t('Reserve quantity','Sasia për rezervim')} type="number" min="0.001" step="0.001" max={c.available} required value={q} onChange={e=>setQ(e.target.value)}/><input aria-label={t('Override reason','Arsyeja e ndryshimit')} placeholder={t('Override reason','Arsyeja e ndryshimit')} required value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={busy}>{t('Reserve here','Rezervo këtu')}</button></form>}
function ReturnCard({r,t,busy,statusText,onSave,guest}){const[disposition,setDisposition]=useState('quarantine'),[account,setAccount]=useState(''),[accounts,setAccounts]=useState([]),[refundError,setRefundError]=useState('');useEffect(()=>{if(guest&&r.status==='received')import('../api/client').then(({apiRequest})=>apiRequest('/finance/accounts')).then(x=>setAccounts(x.data||x)).catch(e=>setRefundError(e.message))},[guest,r.status]);const stage={requested:'authorized',authorized:'received',received:'resolved'}[r.status];return <div className="fulfillment-task"><strong>{r.reference} · {r.quantity}</strong><span>{statusText(r.status)}</span>{r.status==='received'&&<select aria-label={t('Return disposition','Gjendja e kthimit')} value={disposition} onChange={e=>setDisposition(e.target.value)}><option value="quarantine">{t('Quarantine','Karantinë')}</option><option value="sellable">{t('Available after inspection','I disponueshëm pas kontrollit')}</option><option value="damaged">{t('Damaged','I dëmtuar')}</option><option value="scrap">{t('Scrap','Skrap')}</option></select>}{guest&&r.status==='received'&&<label>{t('Guest refund account','Llogaria e rimbursimit të mysafirit')}<select aria-label={t('Guest refund account','Llogaria e rimbursimit të mysafirit')} value={account} onChange={e=>setAccount(e.target.value)}><option value="">—</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select>{refundError&&<span role="alert">{refundError}</span>}</label>}{stage&&<button disabled={busy||(guest&&stage==='resolved'&&!account)} onClick={()=>onSave({return_id:r.id,stage,disposition,...(guest&&account?{financial_account_id:Number(account)}:{})})}>{({authorized:t('Authorize return','Autorizo kthimin'),received:t('Receive return','Prano kthimin'),resolved:t('Inspect & resolve','Kontrollo & zgjidh')})[stage]}</button>}</div>}
