import {useEffect,useRef,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {useAuthStore} from '../store/authStore'
import './InventoryIntelligence.css'
import IntelligencePerformance from '../components/IntelligencePerformance'
import InventoryPlanning from '../components/InventoryPlanning'
import DecisionCenter from '../components/DecisionCenter'
import WorkflowGuide from '../components/WorkflowGuide'

export default function InventoryIntelligence(){
 const [params,setParams]=useSearchParams(),{language}=useTranslation(),planning=params.get('view')==='planning',decisions=params.get('view')==='decisions',rec=params.get('recommendation')
 useEffect(()=>{if(!rec||planning||decisions)return;let live=true;apiRequest(`/analytics/intelligence/recommendations/${rec}`).then(r=>{if(live&&r.planning)setParams(p=>{p.set('view','planning');p.set('product',r.product_id);if(r.warehouse_id)p.set('warehouse_id',r.warehouse_id);return p})}).catch(()=>{});return()=>{live=false}},[rec,planning,decisions,setParams])
 return <><nav className="intelligence-nav" aria-label={language==='sq'?'Pamjet e inteligjencës':'Intelligence views'}><Link aria-current={!planning&&!decisions?'page':undefined} to="/inventory-intelligence"><strong>{language==='sq'?'Parashikimi i kërkesës':'Demand forecasts'}</strong><small>{language==='sq'?'Çfarë do të shitet?':'What will sell?'}</small></Link><Link aria-current={planning?'page':undefined} to="/inventory-intelligence?view=planning"><strong>{language==='sq'?'Planifikimi i inventarit':'Inventory Planning'}</strong><small>{language==='sq'?'Sa të porosis?':'How much to order?'}</small></Link><Link aria-current={decisions?'page':undefined} to="/inventory-intelligence?view=decisions"><strong>{language==='sq'?'Qendra e vendimeve':'Decision Center'}</strong><small>{language==='sq'?'Çfarë të bëj më parë?':'What to do first?'}</small></Link></nav>{decisions?<DecisionCenter/>:planning?<InventoryPlanning/>:<ForecastWorkspace/>}</>
}
function ForecastWorkspace(){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,permissions=useAuthStore(s=>s.permissions)
 const [params,setParams]=useSearchParams(),product=params.get('product'),horizon=params.get('horizon')||'30'
 const [q,setQ]=useState(''),[risk,setRisk]=useState(''),[data,setData]=useState(null),[detail,setDetail]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
 const [supplier,setSupplier]=useState(''),[unit,setUnit]=useState(''),[quantity,setQuantity]=useState(''),[note,setNote]=useState(''),[warehouse,setWarehouse]=useState(''),[page,setPage]=useState(1)
 const pending=useRef(false),canTrain=permissions.includes('analytics.ml_datasets')&&permissions.includes('analytics.finance'),canDraft=permissions.includes('procurement.manage')
 const viewed=useRef(new Set()),detailRef=useRef(null),recommendationId=params.get('recommendation')
 const linkedModel=params.get('model'),linkedAlert=params.get('alert')
 useEffect(()=>{if(product||(!linkedModel&&!linkedAlert))return;let live=true;apiRequest(`/analytics/intelligence/${linkedModel?'models':'alerts'}/${linkedModel||linkedAlert}`).then(r=>{if(live)setParams(p=>{p.set('product',r.product_id);p.set('horizon',r.horizon||30);return p})}).catch(e=>live&&setError(e.message));return()=>{live=false}},[product,linkedModel,linkedAlert,setParams])
 useEffect(()=>{if(detail?.product?.id)detailRef.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},[detail?.product?.id])
 useEffect(()=>{if(product||!recommendationId)return;let live=true;apiRequest(`/analytics/intelligence/recommendations/${recommendationId}`).then(r=>{if(live)setParams(p=>{p.set('product',r.product_id);p.set('horizon',r.horizon);return p})}).catch(e=>live&&setError(e.message));return()=>{live=false}},[product,recommendationId,setParams])
 useEffect(()=>{const id=detail?.recommendation?.id;if(!id||viewed.current.has(id))return;viewed.current.add(id);apiRequest(`/analytics/intelligence/recommendations/${id}/feedback`,{method:'POST',body:JSON.stringify({action:'viewed'})}).catch(()=>{})},[detail?.recommendation?.id])
 const label=x=>({normal:t('Normal','Normal'),high:t('High risk','Rrezik i lartë'),watch:t('Watch','Për t’u vëzhguar'),uncertain_inbound:t('Uncertain arrivals','Mbërritje të pasigurta'),insufficient_data:t('Insufficient data','Të dhëna të pamjaftueshme'),seasonal_mean:t('Seasonal mean baseline','Mesatarja sezonale bazë'),ridge:t('Learned ridge model','Modeli i mësuar ridge'),unvalidated_baseline:t('Unvalidated fallback','Vlerësim pa validim'),evaluated:t('Evaluated','I vlerësuar')}[x]||x)
 const n=x=>x===null||x===undefined?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(Number(x))
 function select(id){setDetail(null);setSupplier('');setUnit('');setQuantity('');setNote('');setMessage('');setParams(p=>{p.set('product',id);p.delete('recommendation');return p})}
 useEffect(()=>{let live=true;const timer=setTimeout(()=>apiRequest('/analytics/intelligence?'+new URLSearchParams({q,risk,horizon,page,warehouse_id:warehouse})).then(r=>live&&setData(r)).catch(e=>live&&setError(e.message)),200);return()=>{live=false;clearTimeout(timer)}},[q,risk,horizon,warehouse,page,revision])
 useEffect(()=>{if(!product){setDetail(null);return}let live=true;const query=new URLSearchParams({horizon,...(supplier?{supplier_id:supplier}:{}),...(unit?{unit}: {})});apiRequest(`/analytics/intelligence/products/${product}?${query}`).then(r=>{if(live){setDetail(r);setQuantity(r.current?.quantity==null?'':String(r.current.quantity))}}).catch(e=>live&&setError(e.message));return()=>{live=false}},[product,horizon,supplier,unit,revision])
 async function act(fn){if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await fn();setRevision(x=>x+1)}catch(e){setError(e.message);setRevision(x=>x+1)}finally{pending.current=false;setBusy(false)}}
 async function train(){await act(async()=>{const r=await apiRequest(`/analytics/intelligence/products/${product}/train`,{method:'POST'});setMessage(r.status==='production_refreshed'?t('Not enough new observations for another candidate. Approved forecasts were retained or refreshed where supported.','Nuk ka mjaft vëzhgime të reja për një kandidat tjetër. Parashikimet e miratuara u ruajtën ose u përditësuan kur ishte e mundur.'):{kind:r.status==='insufficient_data'?'insufficient':'candidate',observed:r.quality?.observed_days})})}
 const current=detail?.current,prediction=detail?.prediction,rec=detail?.recommendation
 const chart=[...(detail?.history||[]).slice(-90).map(d=>({date:d.date,history:d.demand,recorded:d.gross_recorded})),...(prediction?.value?.daily||[]).map(d=>({date:d.date,forecast:d.quantity}))]
 const metrics=prediction?.value?.evaluation??detail?.model?.metrics
 return <main className="intelligence-page">
  <header><div><p className="eyebrow">{t('DEMAND & STOCK COVERAGE','KËRKESA DHE MBULIMI I STOKUT')}</p><h1>{t('Inventory Intelligence','Inteligjenca e inventarit')}</h1><p>{t('Measured history. Advisory forecasts. Human purchasing decisions.','Historik i matur. Parashikime këshilluese. Vendime blerjeje nga përdoruesi.')}</p></div><Link to="/analytics">{t('Analytics','Analitika')} →</Link></header>
  <WorkflowGuide workflow="forecasts"/>
  <div className="intelligence-toolbar"><label>{t('Search products','Kërko produktet')}<input type="search" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><label>{t('Forecast horizon','Periudha e parashikimit')}<select value={horizon} onChange={e=>setParams(p=>{p.set('horizon',e.target.value);return p})}>{[7,30,90].map(h=><option key={h} value={h}>{h} {t('days','ditë')}</option>)}</select></label><label>{t('Risk','Rreziku')}<select value={risk} onChange={e=>{setRisk(e.target.value);setPage(1)}}><option value="">{t('All','Të gjitha')}</option>{['high','watch','normal','uncertain_inbound'].map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><button disabled={busy} onClick={()=>setRevision(x=>x+1)}>{t('Refresh','Rifresko')}</button></div>
  {error&&<p role="alert" className="intelligence-error">{error}</p>}{message&&<p role="status" className="intelligence-message">{typeof message==='string'?message:message.kind==='insufficient'?`${label('insufficient_data')}: ${message.observed} ${t('observed days; at least 14 recent, uncensored days are required.','ditë të regjistruara; duhen të paktën 14 ditë të fundit pa mungesë stoku.')}`:t('Candidate prepared for review. Production is unchanged until you confirm promotion.','Kandidati u përgatit për rishikim. Modeli aktiv mbetet i pandryshuar deri në konfirmimin tuaj.')}</p>}
  {!data&&!error&&<p role="status">{t('Loading products…','Duke ngarkuar produktet…')}</p>}
  {Boolean(data?.accuracy?.groups.length)&&<details><summary>{t('Company forecast accuracy','Saktësia e parashikimeve të kompanisë')}</summary><p>{t('Complete, non-overlapping measured periods only. Different units and horizons are not mixed.','Vetëm periudha të matura, të plota dhe pa mbivendosje. Njësitë dhe periudhat e ndryshme nuk përzihen.')}</p>{data.accuracy.groups.map(g=><p key={g.unit}>{g.products} {t('products','produkte')} · {g.unit} · {g.horizon} {t('days','ditë')} · MAE {n(g.mae)} · WAPE {g.wape==null?'—':n(g.wape)+'%'} · {t('Bias','Devijimi')} {n(g.bias)}</p>)}</details>}
  <section className="intelligence-table" aria-label={t('Product forecasts','Parashikimet e produkteve')}><table><thead><tr>{[t('Product','Produkti'),t('Forecast demand','Kërkesa e parashikuar'),t('Risk','Rreziku'),t('Expected stockout','Mungesa e pritshme'),t('Suggested quantity','Sasia e sugjeruar'),t('Action','Veprimi')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data?.rows.map(r=><tr key={r.id} className={String(r.id)===product?'is-selected':''}><td><strong>{r.name}</strong><small>{r.sku}</small></td><td>{n(r.prediction?.value?.total)} {r.unit}</td><td>{label(r.recommendation?.risk||'insufficient_data')}{r.prediction&&new Date(r.prediction.valid_until)<new Date()&&<small>{t('Expired — refresh','Skaduar — rifresko')}</small>}</td><td>{r.recommendation?.explanation?.stockout_date||'—'}</td><td>{n(r.recommendation?.explanation?.quantity)} {r.recommendation?.explanation?.unit}</td><td><button onClick={()=>select(r.id)}>{t('Review','Rishiko')}</button></td></tr>)}</tbody></table>{data?.rows.length===0&&<p>{t('No matching products.','Nuk ka produkte që përputhen.')}</p>}</section>
  {data?.last_page>1&&<div className="intelligence-toolbar"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>{t('Previous','Para')}</button><span>{page} / {data.last_page}</span><button disabled={page===data.last_page} onClick={()=>setPage(x=>x+1)}>{t('Next','Tjetra')}</button></div>}
  {product&&!detail&&!error&&<p role="status">{t('Loading product evidence…','Duke ngarkuar të dhënat e produktit…')}</p>}
  {product&&detail&&<section ref={detailRef} className="intelligence-detail"><header><div><h2>{detail.product.name}</h2><p>{t('Company-wide demand; warehouse-level forecasts are not inferred.','Kërkesa në nivel kompanie; nuk supozohen parashikime për secilën depo.')}</p></div>{canTrain&&<button disabled={busy} onClick={train}>{busy?t('Working…','Duke punuar…'):t('Update forecast','Përditëso parashikimin')}</button>}</header>
   {current?.supplier_id&&<aside className="intelligence-candidate"><Link to={`/suppliers?supplier=${current.supplier_id}`}>{t('Review supplier delivery evidence','Rishiko provat e dorëzimit të furnitorit')}</Link><p>{t('Planning lead time / uncertain incoming','Afati i planifikimit / stoku i pasigurt në ardhje')}: {n(current.lead_time_days)} {t('days','ditë')} / {n(current.uncertain_incoming)} {detail.product.unit}</p>{!!current.at_risk_purchase_orders?.length&&<p>{t('Excluded from firm arrivals because delivery is at risk:','Përjashtuar nga mbërritjet e sigurta sepse dorëzimi është në rrezik:')} {current.at_risk_purchase_orders.map(id=><Link key={id} to={`/purchase-orders?po=${id}`}>#{id} </Link>)}</p>}{current.lead_time_source==='completed_receipts_p90'&&<p>{t('Planning uses the longer of the catalogue lead time and measured completed-delivery P90. Consider ordering earlier or reviewing another existing supplier.','Planifikimi përdor afatin më të gjatë ndërmjet katalogut dhe P90 të dorëzimeve të përfunduara. Konsidero porositjen më herët ose rishikimin e një furnitori tjetër ekzistues.')}</p>}</aside>}
   {!prediction&&<div className="intelligence-empty"><strong>{t('This product does not have a usable forecast yet.','Ky produkt ende nuk ka parashikim të përdorshëm.')}</strong><p>{t('Record and finalize daily sales to build measured history. If history already exists, use Update forecast and open Forecast setup & accuracy below to review the candidate. Missing days are not assumed to be zero sales.','Regjistro dhe përfundo shitjet ditore për historik të matur. Nëse historiku ekziston, përdor Përditëso parashikimin dhe hap Konfigurimi dhe saktësia më poshtë për kandidatin. Ditët që mungojnë nuk supozohen si shitje zero.')}</p></div>}
   {detail.stale&&<p role="status" className="intelligence-error">{t('This forecast is stale. Generate a new forecast before creating a request.','Ky parashikim është i vjetruar. Gjeneroni një të ri para krijimit të kërkesës.')}</p>}
   <div className="intelligence-chart"><ResponsiveContainer width="100%" height={290}><LineChart data={chart}><CartesianGrid stroke="var(--border-color)" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={50} stroke="var(--text-muted)"/><YAxis stroke="var(--text-muted)"/><Tooltip contentStyle={{background:'var(--card-bg)',color:'var(--text-color)',border:'1px solid var(--border-color)'}}/><Line name={t('Observed demand','Kërkesa e vëzhguar')} type="linear" dataKey="history" stroke="#16a085" dot={false} connectNulls={false} isAnimationActive={false}/><Line name={t('Forecast','Parashikimi')} type="linear" dataKey="forecast" stroke="#469ff5" strokeDasharray="6 3" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
   {prediction&&<><div className="intelligence-metrics">{[[t('Demand','Kërkesa'),n(prediction.value.total)+' '+detail.product.unit],[t('Available','Në dispozicion'),n(current?.available)+' '+detail.product.unit],[t('Reserved','Rezervuar'),n(current?.reserved)+' '+detail.product.unit],[t('Incoming','Në ardhje'),n(current?.incoming)+' '+detail.product.unit],[t('Stockout date','Data e mungesës'),current?.stockout_date||'—'],[t('Risk','Rreziku'),label(current?.risk)]].map(([k,v])=><article key={k}><span>{k}</span><strong>{v}</strong></article>)}</div>
    <div className="intelligence-columns"><article><h3>{t('Replenishment review','Rishikimi i furnizimit')}</h3><label>{t('Supplier','Furnitori')}<select value={supplier||current?.supplier_id||''} onChange={e=>setSupplier(e.target.value)}><option value="">{t('Select supplier','Zgjidh furnitorin')}</option>{detail.suppliers.map(s=><option value={s.supplier_id} key={s.id}>{s.name} · {s.purchase_price??'—'} {s.currency} · {s.usual_lead_time_days??'—'} {t('days','ditë')}</option>)}</select></label><label>{t('Purchase unit','Njësia e blerjes')}<select value={unit||detail.product.unit} onChange={e=>setUnit(e.target.value)}><option value={detail.product.unit}>{detail.product.unit}</option>{detail.units.filter(u=>u.conversion_mode==='fixed').map(u=><option value={u.code} key={u.code}>{u.code} = {u.factor_to_base} {detail.product.unit}</option>)}</select></label><label>{t('Request quantity','Sasia e kërkesës')}<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><p>{t('Reorder / expected arrival','Porositja / mbërritja e pritshme')}: {current?.reorder_date||'—'} / {current?.expected_date||'—'}</p><p>{t('Estimated cost','Kostoja e vlerësuar')}: {n(current?.estimated_cost)} {current?.currency}</p><p>{t('Safety stock / review days','Stoku i sigurisë / ditët e rishikimit')}: {n(current?.safety_stock)} / {current?.review_days}</p>{!current?.coverage_supported&&<p>{t('More forecast history or a shorter lead/review period is needed. No quantity is invented beyond forecast coverage.','Nevojitet më shumë historik ose periudhë më e shkurtër furnizimi/rishikimi. Nuk shpiket sasi përtej parashikimit.')}</p>}<label>{t('Review note','Shënim rishikimi')}<textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label>
     {rec?.purchase_request_id?<Link to={`/procurement?view=requests&request=${rec.purchase_request_id}`}>{t('Open Purchase Request','Hap kërkesën e blerjes')} →</Link>:<button title={t('Requires permission, a current forecast, a supplier and a positive quantity within supported coverage.','Kërkon leje, parashikim aktual, furnitor dhe sasi pozitive brenda mbulimit të mbështetur.')} disabled={!canDraft||busy||detail.stale||!current?.coverage_supported||!current?.supplier_id||!(Number(quantity)>0)||!['open','viewed'].includes(rec?.status)} onClick={()=>act(async()=>{const r=await apiRequest(`/analytics/intelligence/recommendations/${rec.id}/purchase-request`,{method:'POST',body:JSON.stringify({fingerprint:current.fingerprint,supplier_id:Number(supplier||current.supplier_id),unit:unit||detail.product.unit,quantity:Number(quantity),note})});setMessage(t('Purchase Request Draft created: ','Draft kërkese blerjeje u krijua: ')+r.purchase_request.request_number)})}>{t('Create Purchase Request Draft','Krijo draft kërkese blerjeje')}</button>}
     {rec&&['open','viewed'].includes(rec.status)&&<button className="secondary" disabled={busy} onClick={()=>act(()=>apiRequest(`/analytics/intelligence/recommendations/${rec.id}/feedback`,{method:'POST',body:JSON.stringify({action:'dismissed',note})}))}>{t('Dismiss recommendation','Mbyll rekomandimin')}</button>}
    </article>
    <details><summary>{t('Technical details and model evidence','Detajet teknike dhe provat e modelit')}</summary><p>{label(detail.model?.algorithm)} · {label(prediction.value.status)}</p><p>{t('Observed / unknown / stockout days','Ditë të vëzhguara / të panjohura / pa stok')}: {prediction.value.quality.observed_days} / {prediction.value.quality.unknown_days} / {prediction.value.quality.censored_days}</p><p>MAE: {n(metrics?.mae)} · WAPE: {metrics?.wape==null?'—':n(metrics.wape)+'%'} · {t('Bias','Devijimi')}: {n(metrics?.bias)}</p><p>{t('No calibrated probability or confidence interval is claimed. Validation errors are not guarantees.','Nuk pretendohet probabilitet i kalibruar ose interval besimi. Gabimet e validimit nuk janë garanci.')}</p><small>{t('Training cutoff','Kufiri i trajnimit')}: {detail.model?.training_cutoff?.slice(0,10)}<br/>{t('Model version','Versioni i modelit')}: {prediction.model_version}<br/>{t('Generated / expires','Gjeneruar / skadon')}: {new Date(prediction.generated_at).toLocaleString()} / {new Date(prediction.valid_until).toLocaleString()}</small></details></div>
    <details><summary>{t('Calculation and supplier facts','Llogaritja dhe faktet e furnitorëve')}</summary><p>{t('Forecast demand through lead time + review, plus the greater of minimum and safety stock, plus unreserved backorders, minus available stock and dated incoming supply. Round up to supplier minimum and fixed pack multiples.','Kërkesa gjatë furnizimit dhe rishikimit, plus maksimumi i stokut minimal dhe të sigurisë, plus porositë pa rezervim, minus stoku në dispozicion dhe furnizimet me datë. Rrumbullakohet sipas minimumit dhe paketimeve fikse.')}</p><p>{t('Reservations are already excluded from available stock. Undated/late deliveries are not firm supply. Daily snapshots are sampled availability, not continuous monitoring.','Rezervimet janë përjashtuar nga stoku në dispozicion. Dërgesat pa datë ose të vonuara nuk janë furnizim i sigurt. Regjistrimet ditore nuk janë monitorim i vazhdueshëm.')}</p>{detail.suppliers.map(s=><p key={s.id}><Link to="/suppliers">{s.name}</Link> · MOQ {s.minimum_order_quantity} · {t('Pack','Paketim')} {s.pack_size} · {t('Existing scorecard','Vlerësimi ekzistues')}: {n(s.performance?.overall_score)} · {t('Price','Çmimi')}: {s.purchase_price??'—'} {s.currency}</p>)}{current?.incoming_schedule.map((r,i)=><p key={i}><Link to={`/purchase-orders?po=${r.purchase_order_id}`}>PO #{r.purchase_order_id}</Link> · {n(r.quantity)} {detail.product.unit} · {r.expected_at||t('No confirmed date','Pa datë të konfirmuar')}</p>)}</details>
    <details><summary>{t('Measured outcomes','Rezultatet e matura')}</summary><p>{detail.accuracy.summary.evaluated} {t('complete horizons; incomplete/stockout horizons excluded:','periudha të plota; periudha jo të plota/pa stok të përjashtuara:')} {detail.accuracy.summary.excluded}</p>{detail.accuracy.outcomes.map(o=><p key={o.id}>{o.horizon} {t('days','ditë')} · MAE {n(o.evaluation.mae)} · WAPE {n(o.evaluation.wape)} · {o.evaluation.eligible?t('Complete','E plotë'):t('Incomplete — not scored as complete','Jo e plotë — nuk vlerësohet si e plotë')}</p>)}</details>
   </>}
   <IntelligencePerformance product={product} horizon={horizon} revision={revision} onChange={()=>setRevision(v=>v+1)}/>
   <footer><Link to={`/products?product=${detail.product.id}`}>{t('Product','Produkti')} →</Link><Link to="/warehouse-operations">{t('Stock Locator','Gjetësi i stokut')} →</Link>{detail.warehouses.map((w,i)=><button key={i} onClick={()=>{setWarehouse(String(w.warehouse_id));setPage(1)}}>{w.warehouse?.name}: {n(w.available_quantity)} {detail.product.unit}</button>)}{warehouse&&<button onClick={()=>setWarehouse('')}>{t('Clear warehouse filter','Hiq filtrin e depos')}</button>}</footer>
   {prediction&&<details><summary>{t('Supplier delivery and quality evidence','Të dhënat e dërgesave dhe cilësisë së furnitorëve')}</summary>{detail.suppliers.map(s=><article key={s.id}><h4>{s.name}</h4><p>{t('Observed lead time / average days late','Koha e vëzhguar e furnizimit / ditët mesatare vonesë')}: {n(s.performance?.delivery?.average_lead_time_days)} / {n(s.performance?.delivery?.average_days_late)}</p><p>{t('On-time delivery / defect rate','Dërgesa në kohë / shkalla e defekteve')}: {n(s.performance?.delivery?.on_time_delivery_percent)}% / {n(s.performance?.quality?.defect_rate)}%</p></article>)}<p>{t('A dash means unmeasured, not zero. Catalogue lead time is preferred; historical receipt lead time is used only when catalogue lead time is missing. Prices remain estimates for human review.','Viza tregon të pamatur, jo zero. Përdoret koha e katalogut; historiku i pranimeve përdoret vetëm kur koha e katalogut mungon. Çmimet mbeten vlerësime për rishikim nga përdoruesi.')}</p></details>}
  </section>}
 </main>
}
