import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Inbox, RefreshCw, Plus, ArrowRight, Settings2 } from 'lucide-react'
import { orderHub as api } from '../api/orderHub'
import { useAuthStore } from '../store/authStore'
import { useSettingsStore } from '../store/settingsStore'
import EntityDocuments from '../components/EntityDocuments'
import OrderEditor from '../components/OrderEntry'
import OrderConnections from '../components/OrderConnections'
import { orderEventLabel } from '../lib/orderEventLabels'
import OrderChannelMappings from '../components/OrderChannelMappings'
import OrderPriceRules from '../components/OrderPriceRules'
import {OrderHubActions,OrderAcceptanceRule} from '../components/OrderHubActions'
import { OrderHubPresets,OrderHubImport,OrderHubReport } from '../components/OrderHubExtras'
import './Fulfillment.css'
import './OrderHub.css'

const states={refunded:['Refunded','Rimbursuar'],partially_refunded:['Partially refunded','Pjesërisht rimbursuar'],received:['Received','Pranuar'],validated:['Validated','Validuar'],accepted:['Accepted','Pranuar'],attention:['Needs attention','Kërkon vëmendje'],draft:['Draft','Draft'],confirmed:['Confirmed','Konfirmuar'],unpaid:['Unpaid','Papaguar'],paid:['Paid','Paguar'],partially_paid:['Partially paid','Pjesërisht paguar'],planned:['Planned','Planifikuar'],in_transit:['In transit','Në transit'],delivered:['Delivered','Dorëzuar'],cancelled:['Cancelled','Anuluar'],ready_to_allocate:['Ready to fulfill','Gati për përmbushje'],allocated:['Allocated','Caktuar'],partially_allocated:['Partially allocated','Pjesërisht caktuar'],picked:['Picked','Mbledhur'],partially_picked:['Partially picked','Pjesërisht mbledhur'],packed:['Packed','Paketuar'],partially_packed:['Partially packed','Pjesërisht paketuar'],dispatched:['Dispatched','Nisur'],partially_dispatched:['Partially dispatched','Pjesërisht nisur'],partially_delivered:['Partially delivered','Pjesërisht dorëzuar'],failed:['Failed','Dështuar'],synced:['Synced','Sinkronizuar'],review:['Review','Shqyrtim'],late:['Late','Vonuar'],on_track:['On track','Në rregull'],not_started:['Not started','Pa filluar'],pending:['Pending','Në pritje'],approved:['Approved','Miratuar'],rejected:['Rejected','Refuzuar'],consumed:['Applied','Zbatuar']}
const views=[['','All orders','Të gjitha porositë'],['new','New','Të reja'],['paid','Paid','Paguar'],['unpaid','Unpaid','Papaguar'],['partially_paid','Partially paid','Pjesërisht paguar'],['attention','Needs attention','Kërkojnë vëmendje'],['awaiting_payment','Awaiting advance','Në pritje parapagimi'],['ready_to_allocate','Ready to fulfill','Gati për përmbushje'],['packed','Ready to dispatch','Gati për nisje'],['dispatched','In transit','Në transit'],['delivered','Completed','Përfunduar'],['cancelled','Cancelled','Anuluar'],['returns','Returns','Kthime'],['late','Late','Vonuar'],['backorders','Stock shortage','Mungesë stoku']]

export default function OrderHub(){
  const language=useSettingsStore(s=>s.language),currency=useSettingsStore(s=>s.base_currency)
  const t=(en,sq)=>language==='sq'?sq:en, label=value=>states[value]?t(...states[value]):value?.replaceAll('_',' ')
  const permissions=useAuthStore(s=>s.permissions),manage=permissions.includes('fulfillment.manage'),integrations=permissions.includes('integrations.manage')
  const [params,setParams]=useSearchParams(),id=params.get('intake'),view=params.get('view')||'',creating=params.has('new'),settings=params.has('channels')
  const [channels,setChannels]=useState([]),[list,setList]=useState({data:[]}),[detail,setDetail]=useState(null),[search,setSearch]=useState(''),[channel,setChannel]=useState(''),[page,setPage]=useState(1)
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(false),[tracking,setTracking]=useState(''),[note,setNote]=useState('')
  const lock=useRef(false),version=useRef(0)
  const customerFilter=params.get('customer'),productFilter=params.get('product')
  const load=useCallback(async()=>{const current=++version.current;const value=id?await api.show(id):await api.list({search,view,channel_id:channel,page,customer_id:customerFilter,product_id:productFilter});if(current===version.current){if(id)setDetail(value);else setList(value)}},[id,search,view,channel,page,customerFilter,productFilter])
  useEffect(()=>{api.channels().then(setChannels).catch(e=>setError(e.message))},[])
  useEffect(()=>{setEditing(false);setTracking('');setDetail(null);setError('')},[id])
  useEffect(()=>{const timer=setTimeout(()=>load().catch(e=>setError(e.message)),200);const interval=setInterval(()=>{if(document.visibilityState==='visible'&&!lock.current)load().catch(()=>{})},30000);return()=>{clearTimeout(timer);clearInterval(interval);version.current++}},[load])
  const run=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const result=await fn();await load();return result}catch(e){setError(e.message);return null}finally{lock.current=false;setBusy(false)}}
  const action=(name,data={})=>run(async()=>{const result=await api.action(id,name,data);if(name==='tracking-link')setTracking(`${location.origin}/order-tracking/${result.token}`);else setNotice(t('Saved successfully.','U ruajt me sukses.'));return result})
  const submit=async data=>{const result=await run(()=>editing?api.resolve(id,data):api.create(data.channel_id,data));if(result){setEditing(false);setParams({intake:result.id})}}
  return <main className="fulfillment-page order-hub"><header className="fulfillment-heading"><div><h1><Inbox/>{t('Orders','Porositë')}</h1><p>{t('Create, prepare and deliver orders — without entering the same sale twice.','Krijoni, përgatitni dhe dorëzoni porositë — pa regjistruar të njëjtën shitje dy herë.')}</p></div><div className="fulfillment-toolbar"><Link to="/fulfillment">{t('Warehouse fulfillment','Përmbushja në depo')}</Link>{manage&&<button onClick={()=>setParams({new:1})}><Plus size={17}/>{t('New order','Porosi e re')}</button>}{manage&&<button onClick={()=>setParams({channels:1})}><Settings2 size={17}/>{t('Channels','Kanalet')}</button>}<button aria-label={t('Refresh','Përditëso')} disabled={busy} onClick={()=>run(load)}><RefreshCw size={17}/></button></div></header>
    {(id||creating||settings)&&<button className="hub-back" onClick={()=>setParams({})}>{t('Back to inbox','Kthehu te porositë')}</button>}
    {!creating&&!editing&&!settings&&<OrderHubPresets {...{t,run,busy}} intakeId={id} filters={{view,search,channel_id:channel||null}} onView={p=>{setSearch(p.search||'');setChannel(p.channel_id||'');setPage(1);setParams(p.view?{view:p.view}:{})}} onOrder={id=>setParams({intake:id})}/>}
    {!id&&!creating&&!settings&&<><OrderHubReport {...{t,run,busy}}/>{manage&&<OrderHubImport {...{t,channels,run,busy}} onImported={()=>setNotice(t('Import completed. Review the resulting orders in the inbox.','Importi përfundoi. Shqyrtoni porositë në kuti hyrëse.'))}/>}</>}
    {!id&&!creating&&!settings&&<OrderHubActions rows={list.data} filters={{view,search,channel_id:channel}} {...{t,language,manage,run,busy}}/>}
    {settings&&permissions.includes('approvals.manage')&&<OrderAcceptanceRule {...{t,run,busy}}/>}
    {error&&<div role="alert" className="fulfillment-error">{error}</div>}{notice&&<p role="status">{notice}</p>}
    {settings?<ChannelSettings {...{channels,setChannels,run,busy,t,currency,integrations}}/>:creating||editing?<OrderEditor {...{t,busy,channels}} initial={editing?{...detail?.payload,customer:detail?.order?.customer||detail?.payload?.customer,items:(detail?.payload?.items||[]).map((item,n)=>({...item,name:detail?.order?.items?.[n]?.product?.name,unit_price:item.unit_price??detail?.order?.items?.[n]?.unit_price,unit:item.unit||detail?.order?.items?.[n]?.unit}))}:null} onSubmit={submit} onCancel={()=>editing?setEditing(false):setParams({})}/>:id?detail?<>
      <section className="fulfillment-panel"><div className="fulfillment-toolbar"><div><h2>{detail.order?.order_number||detail.external_id||`#${detail.id}`}</h2><p>{detail.channel.name} · {detail.order?.customer?.name||detail.payload.customer?.name||'—'}</p></div><strong>{detail.order?.total_amount??'—'} {detail.order?.currency||detail.payload.currency}</strong></div>
        <details><summary>{t("Payment, fulfillment & delivery status","Gjendja e pagesës, përmbushjes & dorëzimit")}</summary><div className="hub-states">{[['order','Order','Porosia'],['payment','Payment','Pagesa'],['fulfillment','Fulfillment','Përmbushja'],['delivery','Delivery','Dorëzimi'],['sync','Sync','Sinkronizimi'],['health','Health','Gjendja']].map(([key,en,sq])=><div key={key}><small>{t(en,sq)}</small><strong>{label(detail.states[key])}</strong></div>)}</div></details>
        {!!detail.issues?.length&&<div className="hub-attention"><h3>{t('Review before acceptance','Shqyrto para pranimit')}</h3><ul>{detail.issues.map((issue,n)=><li key={n}>{issue.line?`${t('Line','Rreshti')} ${issue.line}: `:''}{issue.message}{issue.expected&&` (${issue.submitted} → ${issue.expected})`}</li>)}</ul></div>}
        {detail.last_error&&<p role="alert">{detail.last_error}</p>}
        {!!detail.risk_flags?.length&&<ul className="hub-attention">{detail.risk_flags.map((r,n)=><li key={n}>{t(r.en,r.sq)}</li>)}</ul>}
        {detail.confirmation_due_at&&!detail.order?.confirmed_at&&<p>{t('Confirmation deadline','Afati i konfirmimit')}: {new Date(detail.confirmation_due_at).toLocaleString(language==='sq'?'sq-AL':'en-GB')}</p>}
        {detail.order?.payment_type!=='cash'&&detail.order?.credit&&<div className="hub-states">{[['credit_limit','Credit limit','Limiti i kredisë'],['current_exposure','Current exposure','Ekspozimi aktual'],['projected_exposure','Projected exposure','Ekspozimi i parashikuar'],['advance','Recorded advance','Parapagimi i regjistruar']].map(([key,en,sq])=><div key={key}><small>{t(en,sq)}</small><strong>{detail.order.credit[key]??'—'} {detail.order.currency}</strong></div>)}</div>}
        {detail.acceptance_approval_required&&<p>{t('Order acceptance approval','Miratimi i pranimit të porosisë')}: {label(detail.acceptance_approval?.status||'pending')} · <Link to="/procurement?view=approvals">{t('Open approvals','Hap miratimet')}</Link></p>}
        {detail.order?.approval&&<p>{t('Credit approval','Miratimi i kredisë')}: {label(detail.order.approval.status)} · <Link to="/procurement?view=approvals">{t('Open approvals','Hap miratimet')}</Link></p>}
        {manage&&<div className="fulfillment-toolbar">
          {!detail.order?.confirmed_at&&<>
            <button disabled={busy} onClick={()=>setEditing(true)}>{t('Review / edit','Shqyrto / ndrysho')}</button>
            <button disabled={busy} onClick={()=>action('retry')}>{t('Retry matching','Riprovo përputhjen')}</button>
            {detail.acceptance_approval_required&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Reason for order approval','Arsyeja e miratimit të porosisë'));if(reason)action('request-approval',{reason})}}>{t('Request order approval','Kërko miratim porosie')}</button>}
            <button disabled={busy||!detail.order||!!detail.issues?.length} onClick={()=>action('confirm')}>{t('Confirm & reserve','Konfirmo & rezervo')}</button>
            {detail.order&&detail.channel.oversale_policy==='require_review'&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Reason for accepting a possible backorder','Arsyeja për pranimin e porosisë në pritje stoku'));if(reason)action('review-stock',{reason})}}>{t('Review backorder','Shqyrto mungesën e stokut')}</button>}
            {detail.order?.payment_type==='credit'&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Credit override reason','Arsyeja e tejkalimit të kredisë'));if(reason)action('credit-override',{reason})}}>{t('Request credit override','Kërko miratim kredie')}</button>}
          </>}
          {detail.order&&<>
            <button disabled={busy} onClick={()=>run(async()=>{const result=await api.action(id,'reorder');setParams({intake:result.id});return result})}>{t('Reorder at current prices','Riporosit me çmimet aktuale')}</button>
            <button disabled={busy} onClick={()=>action('tracking-link')}>{t('Create tracking link','Krijo lidhjen e gjurmimit')}</button>
            {detail.order.status!=='cancelled'&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Reason for cancellation','Arsyeja e anulimit'));if(reason)action('cancel',{reason})}}>{t('Cancel order','Anulo porosinë')}</button>}
          </>}
        </div>}
        {tracking&&<p className="hub-wrap">{t('Private tracking link (90 days):','Lidhja private e gjurmimit (90 ditë):')} <a href={tracking} target="_blank" rel="noreferrer">{tracking}</a></p>}
        {detail.order&&<Link className="hub-primary" to={`/fulfillment?order=${detail.order.id}`}>{t('Open pick, pack, dispatch & returns','Hap mbledhjen, paketimin, nisjen & kthimet')} <ArrowRight size={17}/></Link>}
      </section>
      <OrderConnections key={detail.id} {...{detail,t,language,permissions,busy,run}}/>
      {detail.order&&<section className="fulfillment-panel"><h2>{t('Products & availability','Produktet & disponueshmëria')}</h2><div className="fulfillment-table"><table><thead><tr>{[t('Product','Produkti'),t('Ordered','Porositur'),t('Price','Çmimi'),t('Reserved','Rezervuar'),t('Dispatched','Nisur'),t('Expected availability','Disponueshmëria e pritur')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{detail.order.items.map(i=><tr key={i.id}><td>{i.product?.name}</td><td>{i.quantity} {i.unit}</td><td>{i.unit_price}</td><td>{i.reserved_quantity}</td><td>{i.dispatched_quantity}</td><td>{detail.order.availability?.[i.product_id]?.expected_availability_date||'—'}</td></tr>)}</tbody></table></div>{detail.order.customer_id&&<Link to={`/customer-debts?customer=${detail.order.customer_id}`}>{t('Customer balance, credit & payments','Gjendja, kredia & pagesat e klientit')}</Link>}</section>}
      <section className="fulfillment-panel"><h2>{t('Order timeline','Historia e porosisë')}</h2>{manage&&<form className="fulfillment-toolbar" onSubmit={e=>{e.preventDefault();action('note',{notes:note}).then(()=>setNote(''))}}><input required maxLength={4000} aria-label={t('Internal note','Shënim i brendshëm')} placeholder={t('Internal note — never visible to customers','Shënim i brendshëm — nuk shfaqet te klientët')} value={note} onChange={e=>setNote(e.target.value)}/><button disabled={busy}>{t('Add note','Shto shënim')}</button></form>}<ol className="hub-timeline">{detail.timeline.map(event=><li key={event.id}><time>{new Date(event.occurred_at).toLocaleString(language==='sq'?'sq-AL':'en-GB')}</time><strong>{orderEventLabel(event.event_type,language)}</strong>{event.metadata?.note&&<p>{event.metadata.note}</p>}</li>)}</ol></section>
      {detail.order&&permissions.includes('documents.view')&&<EntityDocuments entityType="sales-order" entityId={detail.order.id}/>}
    </>:<p role="status">{t('Loading order…','Duke ngarkuar porosinë…')}</p>:<>
      <nav className="hub-views" aria-label={t('Order views','Pamjet e porosive')}>{views.map(([key,en,sq])=><button key={key} aria-pressed={view===key} onClick={()=>{setPage(1);setParams(key?{view:key}:{})}}>{t(en,sq)}</button>)}</nav>
      <section className="fulfillment-panel"><div className="fulfillment-toolbar"><input aria-label={t('Search orders','Kërko porositë')} placeholder={t('Order, customer or external reference…','Porosia, klienti ose referenca e jashtme…')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select aria-label={t('Filter channel','Filtro kanalin')} value={channel} onChange={e=>{setChannel(e.target.value);setPage(1)}}><option value="">{t('All channels','Të gjitha kanalet')}</option>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="fulfillment-table"><table><thead><tr>{[t('Order','Porosia'),t('Channel','Kanali'),t('Customer','Klienti'),t('State','Gjendja'),t('Delivery','Dorëzimi'),t('Total','Totali'),''].map((x,n)=><th key={n}>{x}</th>)}</tr></thead><tbody>{list.data.map(i=><tr key={i.id}><td>{i.order?.order_number||i.external_id||`#${i.id}`}<small>{i.external_id}</small></td><td>{i.channel?.name}</td><td>{i.customer||'—'}</td><td><span className="fulfillment-badge">{label(i.states?.health==='on_track'?(i.states?.fulfillment||i.state):i.states?.health||i.state)}</span></td><td>{i.order?.requested_delivery_date||'—'}</td><td>{i.order?.total_amount??'—'} {i.order?.currency}</td><td><button onClick={()=>setParams({intake:i.id})}>{t('Open order','Hap porosinë')}</button></td></tr>)}</tbody></table></div>{!list.data.length&&<p>{t('No orders in this view. Select New order to get started.','Nuk ka porosi në këtë pamje. Zgjidhni Porosi e re për të filluar.')}</p>}<div className="fulfillment-toolbar"><button disabled={page<=1} onClick={()=>setPage(page-1)}>{t('Previous','Para')}</button><span>{page} / {list.last_page||1}</span><button disabled={page>=(list.last_page||1)} onClick={()=>setPage(page+1)}>{t('Next','Tjetër')}</button></div></section>
    </>}
  </main>
}


function ChannelSettings({channels,setChannels,run,busy,t,currency,integrations}){
  const empty={name:'',type:'manual',enabled:true,currency:currency||'EUR',allow_guest:false,acceptance:'review',oversale_policy:'require_review',price_tolerance:'0.00'}
  const [form,setForm]=useState(empty),[secret,setSecret]=useState(null),[keys,setKeys]=useState([]),[keyChannel,setKeyChannel]=useState(null),[warehouses,setWarehouses]=useState([]),[customers,setCustomers]=useState([]),[customerSearch,setCustomerSearch]=useState(''),[boundCustomer,setBoundCustomer]=useState('')
  useEffect(()=>{api.lookups('warehouse').then(setWarehouses).catch(()=>{})},[])
  useEffect(()=>{let live=true;const timer=setTimeout(()=>api.lookups('customer',customerSearch).then(r=>{if(live)setCustomers(r)}).catch(()=>{}),200);return()=>{live=false;clearTimeout(timer)}},[customerSearch])
  const set=(key,value)=>setForm({...form,[key]:value})
  return <><section className="fulfillment-panel"><h2>{t('Order channels','Kanalet e porosive')}</h2>{channels.map(c=><div className="fulfillment-task" key={c.id}><div><strong>{c.name}</strong><p>{c.enabled?t('Enabled','Aktiv'):t('Disabled','Joaktiv')} · {c.intakes_count||0} {t('orders','porosi')} · {c.attention_count||0} {t('need attention','kërkojnë vëmendje')}</p></div><button onClick={()=>{setForm(c);setSecret(null)}}>{t('Edit','Ndrysho')}</button>{integrations&&<button disabled={busy} onClick={()=>run(async()=>{setKeyChannel(c);setSecret(null);setKeys(await api.keys(c.id))})}>{t('API credentials','Kredencialet API')}</button>}</div>)}</section>
    <section className="fulfillment-panel"><label>{t('Confirmation deadline in hours (optional)','Afati i konfirmimit në orë (opsionale)')}<input type="number" min="1" max="720" step="1" value={form.configuration?.confirmation_hours||''} onChange={e=>set('configuration',{...form.configuration,confirmation_hours:e.target.value?Number(e.target.value):null})}/></label></section>
    <OrderPriceRules t={t} value={form.configuration?.price_rules||[]} onChange={price_rules=>set('configuration',{...form.configuration,price_rules})}/>
    {(form.id||channels[0])&&<OrderChannelMappings key={form.id||channels[0].id} channel={form.id?form:channels[0]} {...{t,run,busy}}/>}
    {keyChannel&&<section className="fulfillment-panel"><h3>{t('Customer portal access','Qasja në portalin e klientit')}</h3><p>{t('Choose a customer before issuing a portal credential. Leave empty only for a trusted channel integration.','Zgjidhni klientin para krijimit të kredencialit të portalit. Lëreni bosh vetëm për integrim të besuar.')}</p><label>{t('Find portal customer','Gjej klientin e portalit')}<input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)}/></label><label>{t('Bind credential to customer','Lidh kredencialin me klientin')}<select value={boundCustomer} onChange={e=>setBoundCustomer(e.target.value)}><option value="">{t('Channel integration (all channel orders)','Integrim kanali (të gjitha porositë e kanalit)')}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Link to="/order-portal">{t('Open customer portal','Hap portalin e klientit')}</Link></section>}
    {keyChannel&&<section className="fulfillment-panel"><h3>{keyChannel.name} · {t('API access','Qasja API')}</h3><p>{t('Tokens grant access only to this channel. Save the new secret securely; it is shown once.','Tokenët lejojnë qasje vetëm në këtë kanal. Ruajeni sekretin në mënyrë të sigurt; shfaqet vetëm një herë.')}</p><button disabled={busy} onClick={()=>run(async()=>{setSecret(await api.key(keyChannel.id,{scopes:['orders:create','orders:read','orders:cancel','catalog:read'],customer_id:boundCustomer?Number(boundCustomer):null,expires_at:new Date(Date.now()+90*86400000).toISOString()}));setKeys(await api.keys(keyChannel.id))})}>{t('Issue 90-day credential','Krijo kredencial 90-ditor')}</button>{secret&&<div className="hub-secret"><label>{t('API token','Tokeni API')}<input readOnly value={secret.token}/></label><label>{t('Webhook signing secret','Sekreti i nënshkrimit webhook')}<input readOnly value={secret.webhook_secret}/></label><button onClick={()=>setSecret(null)}>{t('Hide secrets','Fshih sekretet')}</button></div>}{keys.map(k=><div className="fulfillment-task" key={k.id}><span>#{k.id} · {new Date(k.expires_at).toLocaleDateString()} · {k.revoked_at?t('Revoked','Revokuar'):t('Active','Aktiv')}</span><button disabled={busy||!!k.revoked_at} onClick={()=>run(async()=>{await api.revoke(keyChannel.id,k.id);setKeys(await api.keys(keyChannel.id))})}>{t('Revoke','Revoko')}</button></div>)}</section>}
    <section className="fulfillment-panel"><h3>{t('Routing & contact requirements','Drejtimi & kërkesat e kontaktit')}</h3><label>{t('Default fulfillment warehouse','Depoja e parazgjedhur për përmbushje')}<select value={form.warehouse_id||''} onChange={e=>set('warehouse_id',e.target.value?Number(e.target.value):null)}><option value="">{t('Automatic across eligible warehouses','Automatik nga depot e përshtatshme')}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="fulfillment-check"><input type="checkbox" checked={!!form.configuration?.require_address} onChange={e=>set('configuration',{...form.configuration,require_address:e.target.checked})}/>{t('Require delivery address','Kërko adresën e dorëzimit')}</label></section>
    <form className="fulfillment-panel" onSubmit={e=>{e.preventDefault();run(async()=>{await api.channel(form,form.id);setChannels(await api.channels());setForm(empty)})}}><h2>{form.id?t('Edit channel','Ndrysho kanalin'):t('Create channel','Krijo kanal')}</h2><div className="fulfillment-grid"><label>{t('Name','Emri')}<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>{t('Type','Lloji')}<select value={form.type} onChange={e=>set('type',e.target.value)}>{[['manual','Manual','Manual'],['webstore','Webstore','Dyqan online'],['b2b_portal','B2B portal','Portali B2B'],['api','API','API'],['marketplace','Marketplace','Treg online'],['import','Import','Import'],['other','Other','Tjetër']].map(([v,en,sq])=><option key={v} value={v}>{t(en,sq)}</option>)}</select></label><label>{t('Currency','Valuta')}<input required maxLength={3} value={form.currency} onChange={e=>set('currency',e.target.value.toUpperCase())}/></label><label>{t('Stock shortage policy','Politika e mungesës së stokut')}<select value={form.oversale_policy} onChange={e=>set('oversale_policy',e.target.value)}><option value="require_review">{t('Require review','Kërko shqyrtim')}</option><option value="do_not_accept">{t('Do not accept','Mos prano')}</option><option value="accept_backorder">{t('Accept backorder','Prano porosi në pritje stoku')}</option></select></label><label>{t('Acceptance','Pranimi')}<select value={form.acceptance} onChange={e=>set('acceptance',e.target.value)}><option value="review">{t('Review first','Shqyrto fillimisht')}</option><option value="automatic">{t('Automatic after validation','Automatik pas validimit')}</option></select></label><label>{t('Price tolerance','Toleranca e çmimit')}<input required type="number" min="0" step="0.01" value={form.price_tolerance} onChange={e=>set('price_tolerance',e.target.value)}/></label></div><label className="fulfillment-check"><input type="checkbox" checked={form.enabled} onChange={e=>set('enabled',e.target.checked)}/>{t('Enabled','Aktiv')}</label><label className="fulfillment-check"><input type="checkbox" checked={form.allow_guest} onChange={e=>set('allow_guest',e.target.checked)}/>{t('Allow named cash guests','Lejo mysafirë me emër dhe pagesë në dorë')}</label><div className="fulfillment-toolbar"><button disabled={busy}>{t('Save channel','Ruaj kanalin')}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{t('New channel','Kanal i ri')}</button>}</div></form></>
}
