import {useEffect,useRef,useState} from 'react'
import {buildApiUrl} from '../api/client'
import {useSettingsStore} from '../store/settingsStore'
import './Fulfillment.css'
import './OrderHub.css'

// Customer credentials remain in memory; never put them in URLs, localStorage,
// employee authentication, analytics, or an exported document.
export default function OrderPortal(){
  const language=useSettingsStore(s=>s.language),t=(en,sq)=>language==='sq'?sq:en
  const [credential,setCredential]=useState(''),[token,setToken]=useState(''),[portal,setPortal]=useState(null),[catalog,setCatalog]=useState({data:[]}),[search,setSearch]=useState(''),[page,setPage]=useState(1),[basket,setBasket]=useState([]),[address,setAddress]=useState(''),[payment,setPayment]=useState('cash'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const lock=useRef(false),key=useRef(crypto.randomUUID())
  async function request(path,body,access=token){
    const response=await fetch(buildApiUrl(`/order-api/v1${path}`),{method:body?'POST':'GET',headers:{Accept:'application/json',Authorization:`Bearer ${access}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})
    const data=await response.json();if(!response.ok)throw new Error(Object.values(data.errors||{}).flat().join(' ')||data.message||t('Request failed.','Kërkesa dështoi.'));return data
  }
  async function run(work){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work()}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
  useEffect(()=>{if(!token)return;let live=true;const timer=setTimeout(()=>request(`/catalog?search=${encodeURIComponent(search)}&page=${page}`).then(x=>{if(live)setCatalog(x)}).catch(e=>{if(live)setError(e.message)}),250);return()=>{live=false;clearTimeout(timer)}},[token,search,page])
  const add=p=>setBasket(rows=>rows.some(x=>x.product_id===p.id)?rows:[...rows,{product_id:p.id,name:p.name,unit:p.unit,quantity:'1',units:[{code:p.unit},...(p.units||[])]}])
  return <main className="fulfillment-page order-hub hub-portal"><header className="fulfillment-heading"><div><h1>AIMS · {t('Customer orders','Porositë e klientit')}</h1><p>{t('Browse products, place orders and follow your deliveries.','Shfletoni produktet, porositni dhe ndiqni dorëzimet.')}</p></div>{token&&<button onClick={()=>{setToken('');setPortal(null);setCatalog({data:[]});setBasket([]);setNotice('');setError('')}}>{t('Sign out','Dil')}</button>}</header>{error&&<p className="fulfillment-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {!token?<form className="fulfillment-panel" onSubmit={e=>{e.preventDefault();run(async()=>{const access=credential.trim();const result=await request('/portal',null,access);setPortal(result);setToken(access);setCredential('')})}}><h2>{t('Secure customer access','Qasje e sigurt për klientin')}</h2><p>{t('Use the customer access credential supplied by your vendor. This is not an AIMS staff password.','Përdorni kredencialin e klientit nga furnizuesi juaj. Kjo nuk është fjalëkalimi i stafit AIMS.')}</p><label>{t('Customer access credential','Kredenciali i klientit')}<input type="password" autoComplete="off" required value={credential} onChange={e=>setCredential(e.target.value)}/></label><button disabled={busy}>{t('Open my account','Hap llogarinë time')}</button></form>:<>
      <section className="fulfillment-panel"><h2>{portal?.customer.name}</h2><div className="hub-states">{[['current_debt','Debt','Borxhi'],['advance','Advance','Parapagimi'],['available_credit','Available credit','Kredia në dispozicion']].map(([key,en,sq])=><div key={key}><small>{t(en,sq)}</small><strong>{portal?.credit[key]??'—'}</strong></div>)}</div></section>
      <section className="fulfillment-panel"><h2>{t('Product catalog','Katalogu i produkteve')}</h2><input aria-label={t('Search catalog','Kërko katalogun')} placeholder={t('Search products…','Kërko produkte…')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><div className="fulfillment-table"><table><thead><tr>{[t('Product','Produkti'),t('Price','Çmimi'),t('Available','Në dispozicion'),''].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{catalog.data.map(p=><tr key={p.id}><td>{p.name}<small>{p.sku}</small></td><td>{p.price} {p.currency} / {p.unit}</td><td>{p.availability?.available??'—'}</td><td><button disabled={busy||basket.some(x=>x.product_id===p.id)} onClick={()=>add(p)}>{t('Add to order','Shto në porosi')}</button></td></tr>)}</tbody></table></div><div className="fulfillment-toolbar"><button disabled={page<=1} onClick={()=>setPage(page-1)}>{t('Previous','Para')}</button><span>{page} / {catalog.last_page||1}</span><button disabled={page>=(catalog.last_page||1)} onClick={()=>setPage(page+1)}>{t('Next','Tjetër')}</button></div></section>
      <form className="fulfillment-panel" onSubmit={e=>{e.preventDefault();run(async()=>{const result=await request('/orders',{idempotency_key:key.current,order_date:new Date().toLocaleDateString('en-CA'),payment_type:payment,delivery_address:address,items:basket.map(x=>({product_id:x.product_id,unit:x.unit,quantity:x.quantity}))});setNotice(`${t('Order received','Porosia u pranua')}: ${result.reference||result.id}. ${t('Your vendor will validate price, stock and payment before fulfillment.','Furnizuesi do të validojë çmimin, stokun dhe pagesën para përmbushjes.')}`);setBasket([]);key.current=crypto.randomUUID();setPortal(await request('/portal'))})}}><h2>{t('Your order','Porosia juaj')}</h2>{basket.map((item,n)=><div className="fulfillment-line" key={item.product_id}><strong>{item.name}</strong><label>{t('Quantity','Sasia')}<input type="number" min="0.001" step="0.001" required value={item.quantity} onChange={e=>setBasket(rows=>rows.map((x,i)=>i===n?{...x,quantity:e.target.value}:x))}/></label><label>{t('Unit','Njësia')}<select value={item.unit} onChange={e=>setBasket(rows=>rows.map((x,i)=>i===n?{...x,unit:e.target.value}:x))}>{item.units.map(u=><option key={u.code} value={u.code}>{u.code}{u.factor_to_base?` × ${u.factor_to_base}`:''}</option>)}</select></label><button type="button" onClick={()=>setBasket(rows=>rows.filter((_,i)=>i!==n))}>{t('Remove','Hiq')}</button></div>)}<label>{t('Delivery address','Adresa e dorëzimit')}<input maxLength={1000} value={address} onChange={e=>setAddress(e.target.value)}/></label><label>{t('Payment','Pagesa')}<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">{t('Cash on dispatch','Para në dorë në nisje')}</option><option value="credit">{t('Customer credit','Kredi e klientit')}</option><option value="prepaid">{t('Existing advance','Parapagim ekzistues')}</option></select></label><button disabled={busy||!basket.length}>{t('Submit order for validation','Dërgo porosinë për validim')}</button></form>
      <section className="fulfillment-panel"><div className="fulfillment-toolbar"><h2>{t('My orders','Porositë e mia')}</h2><button disabled={busy} onClick={()=>run(async()=>setPortal(await request('/portal')))}>{t('Refresh orders','Përditëso porositë')}</button></div>{portal?.orders.data.map(o=><article className="fulfillment-task" key={o.id}><div><h3>{o.reference||`#${o.id}`}</h3><p>{o.total??'—'} {o.currency} · {o.states?.fulfillment}</p><ul>{o.items?.map((x,n)=><li key={n}>{x.name} · {x.quantity} {x.unit}</li>)}</ul>{o.deliveries?.map((d,n)=><p key={n}>{d.reference} · {d.status}</p>)}</div>{!['cancelled','delivered'].includes(o.states?.order)&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Cancellation reason','Arsyeja e anulimit'));if(reason)run(async()=>{await request(`/orders/${o.id}/cancel`,{reason,idempotency_key:crypto.randomUUID()});setPortal(await request('/portal'))})}}>{t('Request cancellation','Kërko anulim')}</button>}</article>)}<div className="fulfillment-toolbar"><button disabled={busy||portal?.orders.current_page<=1} onClick={()=>run(async()=>setPortal(await request(`/portal?page=${portal.orders.current_page-1}`)))}>{t('Previous','Para')}</button><button disabled={busy||portal?.orders.current_page>=portal?.orders.last_page} onClick={()=>run(async()=>setPortal(await request(`/portal?page=${portal.orders.current_page+1}`)))}>{t('Next','Tjetër')}</button></div></section>
    </>}
  </main>
}
