import {useEffect,useRef,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {createPortal} from 'react-dom'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend,ReferenceLine,CartesianGrid} from 'recharts'
import {X,Plus,FlaskConical} from 'lucide-react'
import {useTranslation} from '../hooks/useTranslation'
import {useDialog} from '../hooks/useDialog'
import PageHeader from '../components/PageHeader'
import ScopePicker from '../components/ScopePicker'
import {simulationApi as api} from '../api/strategicSimulation'
import {simulationActions,simulationHorizons,simulationLabel,simulationPending,serializeDefinition,serializeAssumption,assumptionAction,assumptionLabel,inventoryComparison,financeComparison,formatSimulationMoney,canPrepareSimulationResponse,sensitivityValues} from './strategicSimulationPresentation'
import './StrategicSimulation.css'

const empty=()=>({name:'',description:'',horizon:90,optimize:true,scope:{product_ids:[],warehouse_ids:[],supplier_ids:[],category_ids:[],allow_transfers:true,long_horizon_mode:'no_extension',transfer_lead_days:''},assumptions:[]})
const collections={product_id:'products',category_id:'categories',supplier_id:'suppliers',customer_id:'customers',shipment_id:'shipments',warehouse_id:'warehouses',source_warehouse_id:'warehouses'}
function Review({title,children,busy,onClose,onConfirm,confirmText,t}) {
 const [checked,setChecked]=useState(false),ref=useDialog(onClose,busy)
 return createPortal(<div className="simulation-overlay"><section ref={ref} role="dialog" aria-modal="true" aria-labelledby="simulation-review-title" className="simulation-dialog"><div className="simulation-heading"><h2 id="simulation-review-title">{title}</h2><button type="button" aria-label={t('Close','Mbyll')} disabled={busy} onClick={onClose}><X size={18}/></button></div>{children}<label className="simulation-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={busy}/><span>{t('I reviewed the scope, assumptions and limitations.','Rishikova shtrirjen, supozimet dhe kufizimet.')}</span></label><div className="simulation-actions"><button disabled={busy} onClick={onClose}>{t('Go back','Kthehu')}</button><button className="simulation-primary" disabled={busy||!checked} onClick={onConfirm}>{busy?t('Working…','Duke punuar…'):confirmText}</button></div></section></div>,document.body)
}
function Chart({points,lines,t}) {
 if(!points.length)return <p>{t('No dated evidence for this comparison.','Nuk ka dëshmi me data për këtë krahasim.')}</p>
 return <div className="simulation-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid stroke="var(--border-color)" strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={s=>s.slice(5)} minTickGap={30}/><YAxis width={62}/><Tooltip contentStyle={{background:'var(--card-bg)',color:'var(--text-color)',borderColor:'var(--border-color)'}}/><Legend/><ReferenceLine y={0} stroke="var(--text-secondary)"/>{lines.map(([key,name,color,dash])=><Line key={key} dataKey={key} name={name} type="stepAfter" stroke={color} strokeDasharray={dash} dot={false} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>
}
export default function StrategicSimulation() {
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,label=k=>simulationLabel(k,language),money=(v,c)=>formatSimulationMoney(v,c,language)
 const [params,setParams]=useSearchParams(),id=params.get('run')
 const [options,setOptions]=useState(null),[history,setHistory]=useState([]),[run,setRun]=useState(null),[form,setForm]=useState(empty),[assumption,setAssumption]=useState({type:'demand',action:'percent',value:''}),[editIndex,setEditIndex]=useState(null),[derived,setDerived]=useState(null),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[chosen,setChosen]=useState('do_nothing'),[productKey,setProductKey]=useState(''),[selected,setSelected]=useState([]),[comparison,setComparison]=useState(null),[sensitivity,setSensitivity]=useState(null),[sensitivityForm,setSensitivityForm]=useState({index:0,values:'0, 10, 20, 30'})
 const latch=useRef(false),alive=useRef(true),builder=useRef(null)
 const act=async(fn)=>{if(latch.current)return;latch.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(alive.current)setError(e.code?label(e.code):e.message)}finally{latch.current=false;if(alive.current)setBusy(false)}}
 useEffect(()=>{alive.current=true;let live=true;Promise.all([api.options(),api.list()]).then(([o,h])=>{if(live){setOptions(o);setHistory(h.rows)}}).catch(e=>live&&setError(e.message));return()=>{live=false;alive.current=false}},[])
 useEffect(()=>{if(!id){setRun(null);return}let live=true,timer,version;setRun(null);setChosen('do_nothing');setSensitivity(null);setReview(null);const poll=async()=>{try{const state=await api.state(id);if(!live)return;if(!version||version!==`${state.status}:${state.stage}:${state.updated_at}`){const full=await api.get(id);if(!live)return;setRun(full);version=`${state.status}:${state.stage}:${state.updated_at}`}if(simulationPending(state.status))timer=setTimeout(poll,2500);else api.list().then(h=>live&&setHistory(h.rows)).catch(()=>{})}catch(e){if(live){setError(e.message);timer=setTimeout(poll,10000)}}};poll();return()=>{live=false;clearTimeout(timer)}},[id])
 const result=run?.result,alternative=result?.alternatives?.find(a=>a.key===chosen),view=alternative??result?.scenario,spec=assumptionAction(assumption)
 const rows=view?.rows??[],baseRows=result?.baseline?.rows??[],row=rows.find(r=>r.key===productKey)??rows[0],baseRow=baseRows.find(r=>r.key===row?.key)
 const finance=financeComparison(result?.baseline?.finance,result?.scenario?.finance,alternative?.finance),numeric=v=>v==null?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(v)
 const update=(k,v)=>setForm(f=>({...f,[k]:v})),scope=(k,v)=>setForm(f=>({...f,scope:{...f.scope,[k]:v}}))
 const add=()=>{try{const a=serializeAssumption(assumption);setForm(f=>({...f,assumptions:editIndex===null?[...f.assumptions,a]:f.assumptions.map((v,i)=>i===editIndex?a:v)}));setEditIndex(null);setAssumption({type:'demand',action:'percent',value:''});setError('')}catch(e){setError(label(e.code))}}
 const openRun=r=>{setRun(r);setParams({run:String(r.id)});setReview(null)}
 const runScenario=()=>act(async()=>{const def=serializeDefinition(form);openRun(derived?await api.derive(derived,def):await api.create(def));setDerived(null)})
 const reviewRun=()=>{try{serializeDefinition(form);setError('');setReview('run')}catch(e){setError(label(e.code))}}
 const loadDefinition=()=>{setForm({...run.definition,scope:{...empty().scope,...run.definition.scope},name:run.name+' '+t('variation','variant')});setDerived(run.id);setEditIndex(null);builder.current?.scrollIntoView({behavior:'smooth',block:'start'})}
 const selectors=(key)=>{const collection=options?.[collections[key]]??[];return <label key={key}>{label(key)}<select aria-label={label(key)} value={assumption[key]??''} onChange={e=>setAssumption(a=>({...a,[key]:e.target.value}))}><option value="">{spec.required.includes(key)?t('Select…','Zgjidh…'):t('All / not selected','Të gjitha / pa përzgjedhje')}</option>{collection.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 const totals=(summary,key)=>Object.entries(summary?.[key]??{}).map(([c,v])=><span key={c}>{money(v,c)}</span>)
 return <main className="strategic-simulation">
  <PageHeader eyebrow={t('INTELLIGENCE · HYPOTHETICAL SCENARIOS','INTELIGJENCA · SKENARË HIPOTETIKË')} title={t('Strategic Simulation','Simulimi strategjik')} description={t('Explore consequences before committing stock or money. Scenarios never create orders, transfers or payments.','Shqyrto pasojat para angazhimit të stokut ose parave. Skenarët nuk krijojnë porosi, transferime ose pagesa.')} actions={<FlaskConical aria-hidden="true"/>}/>
  {error&&<div className="simulation-error" role="alert">{error}<button aria-label={t('Dismiss error','Mbyll gabimin')} onClick={()=>setError('')}><X size={16}/></button></div>}
  <section className="simulation-panel" ref={builder} aria-label={t('Scenario builder','Krijimi i skenarit')}><div className="simulation-heading"><h2>{derived?t('Change assumptions · same frozen baseline','Ndrysho supozimet · e njëjta bazë e ngrirë'):t('1. Build your scenario','1. Krijo skenarin')}</h2>{derived&&<button onClick={()=>{setDerived(null);setForm(empty())}}>{t('New current-data scenario','Skenar i ri me të dhëna aktuale')}</button>}</div>
   <p className="simulation-muted">{t('Templates are suggestions. Review every value and select the actual supplier/customer before running.','Modelet janë sugjerime. Rishiko çdo vlerë dhe zgjidh furnitorin/klientin real para ekzekutimit.')}</p>
   <div className="simulation-templates">{options?.templates.map(template=><button key={template.key} disabled={busy||!!derived} onClick={()=>{setForm(f=>({...f,name:label(template.key),assumptions:template.assumptions}));setEditIndex(null)}}>{label(template.key)}</button>)}</div>
   <div className="simulation-form"><label>{t('Scenario name','Emri i skenarit')}<input maxLength={150} value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>{t('Horizon','Periudha')}<select disabled={!!derived} value={form.horizon} onChange={e=>update('horizon',Number(e.target.value))}>{simulationHorizons.map(n=><option key={n} value={n}>{n} {t('days','ditë')}</option>)}</select></label><label>{t('Description (optional)','Përshkrimi (opsional)')}<input maxLength={2000} value={form.description} onChange={e=>update('description',e.target.value)}/></label></div>
   <details className="simulation-details"><summary>{t('Scope: products, warehouses and suppliers','Shtrirja: produktet, depot dhe furnitorët')}</summary><p>{t('Up to 40 products, 3 warehouses and 6 suppliers. Empty selection uses the current company scope.','Deri në 40 produkte, 3 depo dhe 6 furnitorë. Pa përzgjedhje përdoret shtrirja e kompanisë.')}</p><div className="simulation-form">{options&&[['product_ids','products',t('Products','Produktet')],['warehouse_ids','warehouses',t('Warehouses','Depot')],['supplier_ids','suppliers',t('Eligible suppliers','Furnitorët e përshtatshëm')],['category_ids','categories',t('Categories','Kategoritë')]].map(([key,collection,title])=><ScopePicker key={key} label={title} options={options[collection]} value={form.scope[key]} disabled={busy||!!derived} onChange={v=>scope(key,v)}/>)}</div><label className="simulation-check"><input disabled={!!derived} type="checkbox" checked={form.scope.allow_transfers} onChange={e=>scope('allow_transfers',e.target.checked)}/><span>{t('Consider protected warehouse transfers','Shqyrto transferime të mbrojtura mes depove')}</span></label><label>{t('Declared transfer transit days (when history is missing)','Ditë të deklaruara transferimi (kur mungon historiku)')}<input disabled={!!derived} type="number" min="0" max="30" value={form.scope.transfer_lead_days??''} onChange={e=>scope('transfer_lead_days',e.target.value)}/></label></details>
   {form.horizon>90&&<div className="simulation-notice"><strong>{t('Long-range strategic estimate','Vlerësim strategjik afatgjatë')}</strong><p>{t('Without extrapolation, unsupported dates remain unknown. Supply optimization covers only the first 90 days.','Pa ekstrapolim, datat e pambështetura mbeten të panjohura. Optimizimi mbulon vetëm 90 ditët e para.')}</p><label className="simulation-check"><input disabled={!!derived} type="checkbox" checked={form.scope.long_horizon_mode==='repeat_pattern'} onChange={e=>scope('long_horizon_mode',e.target.checked?'repeat_pattern':'no_extension')}/><span>{t('Explicitly assume the frozen demand pattern repeats (not a forecast).','Supozo shprehimisht përsëritjen e kërkesës së ngrirë (jo parashikim).')}</span></label></div>}
   <h3>{t('2. Add assumptions','2. Shto supozime')}</h3><div className="simulation-chips">{form.assumptions.map((a,i)=><div key={i}><button onClick={()=>{setAssumption(a);setEditIndex(i)}}>{assumptionLabel(a,language,options??{})}</button><button aria-label={t('Remove assumption','Hiq supozimin')+' '+(i+1)} onClick={()=>{setForm(f=>({...f,assumptions:f.assumptions.filter((_,n)=>n!==i)}));setEditIndex(null)}}><X size={14}/></button></div>)}</div>
   <div className="simulation-assumption"><div className="simulation-form"><label>{t('What changes?','Çfarë ndryshon?')}<select aria-label={t('What changes?','Çfarë ndryshon?')} value={spec?.key??'demand.percent'} onChange={e=>{const a=simulationActions.find(s=>s.key===e.target.value);setAssumption({type:a.type,action:a.action,[a.field==='boolean'?'value':a.field??'value']:a.field==='boolean'?1:''})}}>{simulationActions.map(a=><option key={a.key} value={a.key}>{language==='sq'?a.sq:a.en}</option>)}</select></label>{spec?.field==='boolean'?<label>{t('Split purchasing','Blerje të ndara')}<select value={assumption.value??1} onChange={e=>setAssumption(a=>({...a,value:Number(e.target.value)}))}><option value={1}>{t('Allowed','Të lejuara')}</option><option value={0}>{t('Not allowed','Jo të lejuara')}</option></select></label>:spec?.action==='service_level'?<label>{t('Target','Objektivi')}<select value={assumption.value??''} onChange={e=>setAssumption(a=>({...a,value:e.target.value}))}><option value="">{t('Select…','Zgjidh…')}</option>{[.9,.95,.98,.99].map(v=><option key={v} value={v}>{v*100}%</option>)}</select></label>:spec?.field&&<label>{spec.field==='days'?t('Days','Ditë'):t('Value','Vlera')}<input type="number" min={spec.min} max={spec.max} step={spec.field==='days'?1:'any'} value={assumption[spec.field]??''} onChange={e=>setAssumption(a=>({...a,[spec.field]:e.target.value}))}/></label>}{spec&&[...spec.required,...spec.optional].filter(k=>!k.startsWith('route_')).map(selectors)}{spec?.optional.includes('route_from')&&['route_from','route_to'].map(k=><label key={k}>{label(k)}<input maxLength={120} value={assumption[k]??''} onChange={e=>setAssumption(a=>({...a,[k]:e.target.value}))}/></label>)}</div>
    {['demand','customer'].includes(assumption.type)&&<details><summary>{t('Specific period (optional)','Periudhë specifike (opsionale)')}</summary><div className="simulation-form">{['start_day','end_day'].map((k,i)=><label key={k}>{i?t('Last day offset','Zhvendosja e ditës së fundit'):t('First day offset (0 = baseline day)','Zhvendosja e ditës së parë (0 = dita bazë)')}<input type="number" min="0" max="364" value={assumption[k]??''} onChange={e=>setAssumption(a=>({...a,[k]:e.target.value}))}/></label>)}</div></details>}
    <button disabled={busy||form.assumptions.length>=24&&editIndex===null} onClick={add}><Plus size={16}/>{editIndex===null?t('Add assumption','Shto supozimin'):t('Save assumption','Ruaj supozimin')}</button>
   </div><div className="simulation-actions"><label className="simulation-check"><input type="checkbox" checked={form.optimize} onChange={e=>update('optimize',e.target.checked)}/><span>{t('Compare supply responses with the local optimizer','Krahaso strategji furnizimi me optimizuesin lokal')}</span></label><button className="simulation-primary" disabled={busy||!options} onClick={reviewRun}>{t('Review & run','Rishiko dhe ekzekuto')}</button></div>
  </section>
  {run&&<section className="simulation-panel" aria-label={t('Simulation result','Rezultati i simulimit')}><div className="simulation-heading"><div><h2>{run.name} <small>#{run.id}</small></h2><p className="simulation-muted">{label(run.status)} · {run.baseline_at?new Date(run.baseline_at).toLocaleString():t('Baseline pending','Baza në pritje')}</p></div><div className="simulation-actions">{run.parent_id&&<Link to={'/strategic-simulation?run='+run.parent_id}>{t('Original run','Simulimi origjinal')} #{run.parent_id}</Link>}{simulationPending(run.status)?<button disabled={busy} onClick={()=>act(async()=>setRun(await api.cancel(run.id)))}>{t('Cancel simulation','Anulo simulimin')}</button>:<><button disabled={busy} onClick={()=>act(async()=>openRun(await api.rerun(run.id,{})))}>{t('Run against current data','Ekzekuto me të dhënat aktuale')}</button>{run.baseline_summary&&<button disabled={busy} onClick={loadDefinition}>{t('Change assumptions','Ndrysho supozimet')}</button>}</>}</div></div>
   {simulationPending(run.status)&&<p role="status" className="simulation-notice">{label(run.stage)}. {t('Running in the background; your inputs and page stay in place.','Në proces në sfond; të dhënat dhe faqja jote mbeten në vend.')}</p>}{run.error&&<p role="alert" className="simulation-error">{run.error}</p>}
   {result&&<><h3>{t('3. Executive impact','3. Ndikimi kryesor')}</h3><p className="simulation-notice">{t('Scenario, not guaranteed future. Known-price totals exclude unknown costs. Confidence','Skenar, jo e ardhme e garantuar. Totalet përjashtojnë kostot e panjohura. Besueshmëria')}: {label(result.confidence.state)}.</p><div className="simulation-kpis">{['stockout_exposures','below_target_scopes','unsupported_scopes'].map(k=><article key={k}><small>{label(k)}</small><strong>{result.baseline.summary[k]} → {result.scenario.summary[k]}</strong><span>{t('Baseline → scenario','Baza → skenari')}</span></article>)}{['purchase_requirement_by_currency','inventory_value_by_currency','required_inventory_capital_by_currency'].map(k=><article key={k}><small>{label(k)}</small><strong>{totals(result.baseline.summary,k)} → {totals(result.scenario.summary,k)}</strong></article>)}</div>
    <h3>{t('4. Compare response strategies','4. Krahaso strategjitë')}</h3><div className="simulation-strategies"><button className={chosen==='do_nothing'?'is-selected':''} aria-pressed={chosen==='do_nothing'} onClick={()=>setChosen('do_nothing')}><strong>{label('do_nothing')}</strong><span>{numeric(result.scenario.summary.stockout_exposures)} {t('stockout scopes','shtrirje me mungesë')}</span></button>{result.alternatives.map(a=><button key={a.key} className={chosen===a.key?'is-selected':''} aria-pressed={chosen===a.key} onClick={()=>setChosen(a.key)}><strong>{label(a.key)}</strong><span>{label(a.status)}</span><b>{money(a.summary?.commitment,a.summary?.currency)}</b><span>{numeric(a.summary?.stockout_exposures)} {t('stockout scopes','shtrirje me mungesë')} · {numeric(a.summary?.transfer_lines)} {t('transfers','transferime')}</span></button>)}</div>
    {!result.alternatives.length&&<button disabled={busy} onClick={()=>act(async()=>openRun(await api.derive(run.id,{optimize:true})))}>{t('Optimize response on this baseline','Optimizo përgjigjen mbi këtë bazë')}</button>}
    {alternative?.lines?.length>0&&<div className="simulation-table"><table><thead><tr>{[t('Product / warehouse','Produkti / depo'),t('Purchases','Blerjet'),t('Transfers','Transferimet'),t('Timing','Afatet')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{alternative.lines.map(l=><tr key={l.id}><td>{l.product.name}<small>{l.warehouse?.name??t('Company','Kompania')}</small></td><td>{l.purchases.map((p,i)=><div key={i}>{p.supplier_name} · {numeric(p.base_quantity)} {l.product.unit}<small>{money(p.base_cost,alternative.summary.currency)} · MOQ {numeric(p.moq)}</small></div>)}</td><td>{l.transfers.map((tr,i)=><div key={i}>{tr.source_warehouse_name} → {l.warehouse?.name}: {numeric(tr.quantity)} {l.product.unit}</div>)}</td><td>{l.purchases.map((p,i)=><small key={i}>{p.order_date} → {p.expected_at}</small>)}{l.transfers.map((tr,i)=><small key={i}>{tr.expected_at}</small>)}</td></tr>)}</tbody></table></div>}
    <div className="simulation-actions">{canPrepareSimulationResponse(run,alternative)&&!run.response_plan&&<button disabled={busy} onClick={()=>setReview('response')}>{t('Prepare Response Plan','Përgatit planin e përgjigjes')}</button>}{run.response_plan&&<Link to={run.response_plan.url}>{t('Open current-data purchasing review','Hap rishikimin e blerjeve me të dhëna aktuale')} ↗</Link>}</div>
    <h3>{t('Inventory trajectory','Ecuria e inventarit')}</h3><label>{t('Product / warehouse','Produkti / depo')}<select value={row?.key??''} onChange={e=>setProductKey(e.target.value)}>{rows.map(r=><option key={r.key} value={r.key}>{r.product.name} · {r.warehouse?.name??t('Company','Kompania')} ({r.unit})</option>)}</select></label><Chart points={inventoryComparison(baseRow,row)} lines={[["baseline",t('Baseline','Baza'),'#64748b'],['scenario',alternative?label(chosen):t('Scenario','Skenari'),'#0284c7'],['target',t('Safety stock','Stoku i sigurisë'),'#d97706','4 4'],['incoming',t('Incoming quantity','Sasia në ardhje'),'#059669','2 3']]} t={t}/>{row&&<p className="simulation-muted">{numeric(row.coverage_days)} {t('days supported','ditë të mbështetura')} · {t('Unit','Njësia')}: {row.unit} · {t('Required inventory','Inventari i nevojshëm')}: {numeric(row.required_base_quantity)} {row.unit}</p>}
    <h3>{t('Financial consequences by currency','Pasojat financiare sipas monedhës')}</h3><p className="simulation-muted">{t('Response purchases assume full payment on order date. Missing opening cash stays unknown; no future sales revenue is invented.','Blerjet e përgjigjes supozojnë pagesë të plotë në datën e porosisë. Paratë fillestare që mungojnë mbeten të panjohura; nuk hamendësohen të ardhura nga shitjet e ardhshme.')}</p>{finance.map(f=><section key={f.currency}><h4>{f.currency}</h4>{f.points.some(p=>p.baseline!=null||p.scenario!=null||p.response!=null)?<Chart points={f.points} lines={[["baseline",t('Baseline cash','Paratë bazë'),'#64748b'],['scenario',t('Scenario cash','Paratë e skenarit'),'#0284c7'],['response',t('Response cash','Paratë me përgjigje'),'#059669']]} t={t}/>:<p>{t('Recorded opening cash is incomplete. Payment timing is available below, but an absolute cash balance cannot be claimed.','Paratë fillestare të regjistruara janë të paplota. Afatet e pagesave gjenden më poshtë, por nuk mund të pretendohet bilanc absolut.')}</p>}<details><summary>{t('Dated collections and payments','Arkëtimet dhe pagesat sipas datës')}</summary><div className="simulation-table"><table><thead><tr><th>{t('Date','Data')}</th><th>{t('Collections','Arkëtimet')}</th><th>{t('Payments','Pagesat')}</th><th>{t('Expected cash','Paratë e pritshme')}</th></tr></thead><tbody>{(view?.finance?.currencies?.[f.currency]?.timeline??[]).map(d=><tr key={d.date}><td>{d.date}</td><td>{money(d.inflows,f.currency)}</td><td>{money(d.outflows,f.currency)}</td><td>{money(d.expected_cash,f.currency)}</td></tr>)}</tbody></table></div></details></section>)}
    <div className="simulation-two"><section><h3>{t('Where the plan is vulnerable','Ku është i cenueshëm plani')}</h3>{result.bottlenecks.rows.slice(0,12).map((b,i)=><div className="simulation-bottleneck" key={i}><strong>{b.product.name} · {b.warehouse?.name??t('Company','Kompania')}</strong><p>{b.stockout_days} {t('shortage days','ditë mungesë')} · {b.first_stockout??'—'} · {numeric(b.required_quantity)} {b.unit}</p><small>{b.reason==='no_eligible_supplier'?t('No eligible supplier','Nuk ka furnitor të përshtatshëm'):b.reason==='insufficient_demand_evidence'?t('Demand evidence missing','Mungojnë dëshmitë e kërkesës'):t('Dated demand exceeds available supply','Kërkesa sipas datës tejkalon furnizimin')}</small></div>)}{!result.bottlenecks.rows.length&&<p>{t('No target gap in the supported scope.','Nuk ka mungesë ndaj objektivit në shtrirjen e mbështetur.')}</p>}<small>{t('Ranked by observed consequence, not a causal score.','Renditur sipas pasojës së vërejtur, jo pikëzimit shkakor.')}</small></section><section><h3>{t('Test a sensitivity threshold','Testo pragun e ndjeshmërisë')}</h3><label>{t('Assumption','Supozimi')}<select value={sensitivityForm.index} onChange={e=>setSensitivityForm(f=>({...f,index:Number(e.target.value)}))}>{run.definition.assumptions.map((a,i)=>assumptionAction(a)?.field&&!['allow_split'].includes(a.action)&&<option key={i} value={i}>{assumptionLabel(a,language,options??{})}</option>)}</select></label><label>{t('Values to test (2–15, comma separated)','Vlera për testim (2–15, ndarë me presje)')}<input value={sensitivityForm.values} onChange={e=>setSensitivityForm(f=>({...f,values:e.target.value}))}/></label><button disabled={busy||!run.definition.assumptions.length} onClick={()=>act(async()=>setSensitivity(await api.sensitivity(run.id,{assumption_index:sensitivityForm.index,values:sensitivityValues(sensitivityForm.values,run.definition.assumptions[sensitivityForm.index])})))}>{t('Compare tested values','Krahaso vlerat e testuara')}</button>{sensitivity&&<><div className="simulation-table"><table><thead><tr><th>{t('Value','Vlera')}</th><th>{t('Stockout scopes','Shtrirje me mungesë')}</th><th>{t('Below target','Nën objektiv')}</th></tr></thead><tbody>{sensitivity.points.map(p=><tr key={p.value}><td>{p.value}</td><td>{p.summary.stockout_exposures}</td><td>{p.summary.below_target_scopes}</td></tr>)}</tbody></table></div><small>{t('Discrete tested values, not an exact breakpoint.','Vlera diskrete të testuara, jo prag i saktë.')}</small></>}</section></div>
    <details className="simulation-details"><summary>{t('Evidence, assumptions and limitations','Dëshmitë, supozimet dhe kufizimet')}</summary><div className="simulation-two">{Object.entries(result.known_predicted??{}).map(([k,v])=><section key={k}><h4>{label(k)}</h4><ul>{v.map(x=><li key={x}>{x}</li>)}</ul></section>)}<section><h4>{label('assumed')}</h4><ul>{run.definition.assumptions.map((a,i)=><li key={i}>{assumptionLabel(a,language,options??{})}</li>)}</ul></section></div><h4>{t('How changes propagate','Si përhapen ndryshimet')}</h4><ol>{result.dependency_graph.map(x=><li key={x}>{x}</li>)}</ol><ul>{result.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul><p>{result.stochastic.reason}</p><p>{t('Engine','Motori')}: {run.engine_version} · {result.performance.seconds}s</p><dl>{Object.entries(result.versions??{}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{Array.isArray(v)?v.join(', '):v??'—'}</dd></div>)}</dl><p>{t('Referenced records only; models and policies are not modified.','Vetëm regjistrime të referuara; modelet dhe politikat nuk ndryshohen.')}</p></details>
   </>}
  </section>}
  <section className="simulation-panel"><div className="simulation-heading"><h2>{t('Saved run history','Historiku i simulimeve të ruajtura')}</h2><button disabled={busy||selected.length<2} onClick={()=>act(async()=>setComparison(await api.compare(selected)))}>{t('Compare selected runs','Krahaso simulimet e zgjedhura')} ({selected.length}/4)</button></div><p className="simulation-muted">{t('Every run saves automatically. A rerun creates a new version and never replaces a historical result.','Çdo simulim ruhet automatikisht. Riekzekutimi krijon version të ri dhe nuk zëvendëson rezultatin historik.')}</p><div className="simulation-table"><table><thead><tr><th>{t('Compare','Krahaso')}</th><th>{t('Scenario','Skenari')}</th><th>{t('Baseline','Baza')}</th><th>{t('Status','Statusi')}</th></tr></thead><tbody>{history.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={t('Compare run','Krahaso simulimin')+' '+r.id} checked={selected.includes(r.id)} disabled={r.status!=='COMPLETED'||selected.length>=4&&!selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(n=>n!==r.id))}/></td><td><Link to={'/strategic-simulation?run='+r.id}>{r.name} #{r.id}</Link></td><td>{r.baseline_at?new Date(r.baseline_at).toLocaleString():'—'}</td><td>{label(r.status)}</td></tr>)}</tbody></table></div>{!history.length&&<p>{t('No saved scenarios yet. Build your first scenario above.','Nuk ka skenarë të ruajtur. Krijo skenarin e parë më lart.')}</p>}{comparison&&<div><h3>{t('Selected scenario comparison','Krahasimi i skenarëve të zgjedhur')}</h3>{!comparison.same_baseline&&<p className="simulation-notice">{t('These runs use different frozen data; differences are not only caused by assumptions.','Këto simulime përdorin të dhëna të ndryshme të ngrira; ndryshimet nuk shkaktohen vetëm nga supozimet.')}</p>}<div className="simulation-table"><table><thead><tr><th>{t('Metric','Matësi')}</th>{comparison.runs.map(r=><th key={r.id}>{r.name} #{r.id}</th>)}</tr></thead><tbody>{['stockout_exposures','below_target_scopes','unsupported_scopes','purchase_requirement_by_currency'].map(k=><tr key={k}><th>{label(k)}</th>{comparison.runs.map(r=><td key={r.id}>{k.endsWith('currency')?totals(r.result?.scenario?.summary,k):numeric(r.result?.scenario?.summary?.[k])}</td>)}</tr>)}</tbody></table></div></div>}</section>
  {review==='run'&&<Review title={t('Review simulation — no operational actions','Rishiko simulimin — pa veprime operative')} busy={busy} onClose={()=>setReview(null)} onConfirm={runScenario} confirmText={t('Confirm & run simulation','Konfirmo dhe ekzekuto simulimin')} t={t}><h3>{form.name}</h3><p>{form.horizon} {t('days','ditë')} · {derived?t('Original frozen baseline','Baza origjinale e ngrirë'):t('Current company facts will freeze in the background.','Faktet aktuale të kompanisë do të ngrihen në sfond.')}</p><ul>{form.assumptions.map((a,i)=><li key={i}>{assumptionLabel(a,language,options??{})}</li>)}</ul><p>{t('Only simulation records are saved. Forecasts, stock, finances and production policies are unchanged.','Ruhen vetëm regjistrimet e simulimit. Parashikimet, stoku, financat dhe politikat operative nuk ndryshojnë.')}</p></Review>}
  {review==='response'&&<Review title={t('Separate real planning review','Rishikim i veçantë i planifikimit real')} busy={busy} onClose={()=>setReview(null)} confirmText={t('Open fresh purchasing review','Hap rishikimin e ri të blerjeve')} t={t} onConfirm={()=>act(async()=>{const response=await api.prepareResponse(run.id,{alternative:alternative.key,confirm:true});setRun(r=>({...r,response_plan:response}));setReview(null)})}><p>{t('A new V11 plan will use current actual data. Hypothetical quantities and prices will not become orders. You must separately review any proposed drafts in Supply Optimizer.','Një plan i ri V11 do të përdorë të dhënat reale aktuale. Sasite dhe çmimet hipotetike nuk bëhen porosi. Draftet duhet të rishikohen veçmas në Optimizuesin e furnizimit.')}</p><strong>{label(alternative.key)} · {money(alternative.summary.commitment,alternative.summary.currency)}</strong><p>{t('This amount describes the scenario only, not the fresh real plan.','Kjo shumë përshkruan vetëm skenarin, jo planin e ri real.')}</p></Review>}
 </main>
}
