import {useEffect,useRef,useState} from 'react'
import {useSearchParams,Link} from 'react-router-dom'
import {createPortal} from 'react-dom'
import {ChevronDown} from 'lucide-react'
import {apiRequest} from '../api/client'
import {useTranslation} from '../hooks/useTranslation'
import {optimizerLabel,optimizerPending,canPreparePlan,purchaseGroups,stressPayload,stressSuppliers} from './supplyOptimizerPresentation'
import './SupplyOptimizer.css'
import ScopePicker from '../components/ScopePicker'
import PageHeader from '../components/PageHeader'

const root='/supply-optimizer'
const post=(path,body)=>apiRequest(path,{method:'POST',body:JSON.stringify(body)})
export default function SupplyOptimizer(){
 const {language}=useTranslation(),t=(en,sq)=>language==='sq'?sq:en,label=k=>optimizerLabel(k,language)
 const [params,setParams]=useSearchParams(),id=params.get('plan')
 const [options,setOptions]=useState(null),[history,setHistory]=useState([]),[plan,setPlan]=useState(null),[chosen,setChosen]=useState('balanced'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(false),[confirmed,setConfirmed]=useState(false),[stress,setStress]=useState(null),[search,setSearch]=useState('')
 const [form,setForm]=useState({horizon:60,product_ids:[],warehouse_ids:[],supplier_ids:[],category_ids:[],commitment_limit:'',allow_transfers:true,protect_critical:false,transfer_lead_days:''})
 const [scenarioLimit,setScenarioLimit]=useState('')
 const [stressForm,setStressForm]=useState({demand_percent:120,supplier_delay:0,supplier_id:'',shipment_delay:0,shipment_id:'',collections_delay:0})
 const pending=useRef(false),alive=useRef(true),reviewRef=useRef(null)
 useEffect(()=>{alive.current=true;let active=true;Promise.all([apiRequest(root+'/options'),apiRequest(root)]).then(([o,h])=>{if(active){setOptions(o);setHistory(h.rows)}}).catch(e=>active&&setError(e.message));return()=>{active=false;alive.current=false}},[])
 useEffect(()=>{if(!id){setPlan(null);return}let live=true,timer,version;const status=async()=>{try{const r=await apiRequest(`${root}/${id}/state`);if(!live)return;if(r.updated_at!==version){const full=await apiRequest(root+'/'+id);if(!live)return;version=full.updated_at;setPlan(full)}if(['OPTIMAL','FEASIBLE'].includes(r.status))timer=setTimeout(status,30000)}catch{if(live)timer=setTimeout(status,30000)}};const read=()=>apiRequest(root+'/'+id).then(r=>{if(!live)return;version=r.updated_at;setPlan(r);if(optimizerPending(r.status))timer=setTimeout(read,2000);else{apiRequest(root).then(h=>live&&setHistory(h.rows)).catch(()=>{});if(['OPTIMAL','FEASIBLE'].includes(r.status))timer=setTimeout(status,30000)}}).catch(e=>live&&setError(e.message));setStress(null);setReview(false);setChosen('balanced');read();return()=>{live=false;clearTimeout(timer)}},[id])
 const alternatives=plan?.result?.plans??[],alternative=alternatives.find(a=>a.key===chosen)??alternatives[0],groups=purchaseGroups(alternative?.lines)
 const n=v=>v==null?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{maximumFractionDigits:3}).format(Number(v))
 const money=(v,c=plan?.context?.currency??'EUR')=>v==null?'—':new Intl.NumberFormat(language==='sq'?'sq-AL':'en-GB',{style:'currency',currency:c}).format(Number(v))
 const act=async(fn)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(alive.current)setError(e.message)}finally{pending.current=false;if(alive.current)setBusy(false)}}
 const optimize=()=>act(async()=>{const payload={...form};for(const k of ['commitment_limit','transfer_lead_days']){if(payload[k]==='')delete payload[k];else payload[k]=Number(payload[k])}const p=await post(root,payload);if(alive.current){setPlan(p);setParams({plan:String(p.id)})}})
 const toggle=(key,value)=>setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(v=>v!==value):[...f[key],value]}))
 const select=(key,collection,title)=><ScopePicker label={title} options={collection} value={form[key]} disabled={busy} onChange={value=>setForm(f=>({...f,[key]:value}))}/>
 const prepare=()=>act(async()=>{const p=await post(`${root}/${plan.id}/prepare`,{alternative:alternative.key,confirm:confirmed});if(alive.current){setPlan(p);setReview(false);setConfirmed(false)}})
 const testStress=()=>act(async()=>{const r=await post(`${root}/${plan.id}/stress`,stressPayload(stressForm,alternative.key));if(alive.current)setStress(r)})
 const simulateLimit=()=>act(async()=>{const p=await post(`${root}/${plan.id}/simulate`,{commitment_limit:Number(scenarioLimit)});if(alive.current){setPlan(p);setParams({plan:String(p.id)})}})
 useEffect(()=>{if(!review)return;const prior=document.activeElement;reviewRef.current?.focus();const close=e=>{if(e.key==='Escape'&&!pending.current)setReview(false);if(e.key==='Tab'){const controls=[...reviewRef.current?.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href]')??[]];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===reviewRef.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===reviewRef.current)){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',close);return()=>{window.removeEventListener('keydown',close);if(prior?.isConnected)prior.focus()}},[review])
 return <main className="supply-optimizer">
  <PageHeader eyebrow={t('PURCHASING & TRANSFER PLANNING','PLANIFIKIMI I BLERJEVE DHE TRANSFERIMEVE')} title={t('Supply Optimizer','Optimizuesi i furnizimit')} description={t('Compare coordinated supply plans. Nothing is ordered or moved until you review and confirm a draft.','Krahaso plane të koordinuara furnizimi. Asgjë nuk porositet apo lëviz pa rishikimin dhe konfirmimin e draftit.')}/>
  <ol className="optimizer-steps">{[t('Scope','Shtrirja'),t('Constraints','Kufizimet'),t('Optimize','Optimizo'),t('Compare','Krahaso'),t('Details','Detajet'),t('Prepare','Përgatit')].map((s,i)=><li key={i} className={(plan?.result?i<5:i<2)?'is-active':''}><span>{i+1}</span>{s}</li>)}</ol>
  {error&&<div role="alert" className="optimizer-error">{error}</div>}
  <details className="optimizer-builder" open={!plan}><summary>{t('Plan a purchase / change planning inputs','Planifiko një blerje / ndrysho të dhënat')}</summary><section className="optimizer-panel"><h2>{t('Planning scope & constraints','Shtrirja dhe kufizimet')}</h2>
   <div className="optimizer-form"><label>{t('Horizon','Periudha')}<select value={form.horizon} onChange={e=>setForm(f=>({...f,horizon:Number(e.target.value)}))}>{[30,60,90].map(h=><option key={h} value={h}>{h} {t('days','ditë')}</option>)}</select></label>
    <label>{t('Purchasing commitment limit','Kufiri i angazhimit të blerjeve')}<input aria-label={t('Purchasing commitment limit','Kufiri i angazhimit të blerjeve')} type="number" min="0" step="0.01" value={form.commitment_limit} placeholder={t('Optional — no imposed cash limit','Opsionale — jo kufi i parasë')} onChange={e=>setForm(f=>({...f,commitment_limit:e.target.value}))}/><small>{t('Maximum NEW purchasing commitment in company currency; not available cash.','Angazhimi maksimal i RI në monedhën e kompanisë; jo paratë e disponueshme.')}</small></label>
    {options&&select('warehouse_ids',options.warehouses,t('Warehouses','Depot'))}
   </div>
   {!options&&!error&&<p role="status">{t('Loading available products and warehouses…','Duke ngarkuar produktet dhe depot…')}</p>}
   <details className="optimizer-advanced"><summary><span>{t('Supplier, category & transfer constraints','Kufizimet e furnitorëve, kategorive dhe transferimeve')}</span>{(form.supplier_ids.length+form.category_ids.length>0||form.transfer_lead_days!==''||form.protect_critical)&&<span className="optimizer-status">{t('Customized','Të personalizuara')}</span>}<ChevronDown size={16} aria-hidden="true"/></summary><div className="optimizer-form">
    {options&&<>{select('supplier_ids',options.suppliers,t('Eligible suppliers','Furnitorët e përshtatshëm'))}{select('category_ids',options.categories,t('Categories','Kategoritë'))}</>}
    <label>{t('Declared transfer transit days','Ditët e deklaruara të transferimit')}<input type="number" min="0" max="30" value={form.transfer_lead_days} placeholder={t('Optional','Opsionale')} onChange={e=>setForm(f=>({...f,transfer_lead_days:e.target.value}))}/><small>{t('Used only when route history is missing.','Përdoret vetëm kur mungon historiku i rrugës.')}</small></label>
    <label className="optimizer-check"><input type="checkbox" checked={form.protect_critical} onChange={e=>setForm(f=>({...f,protect_critical:e.target.checked}))}/><span>{t('Require no projected stockout for critical products','Kërko pa mungesë të parashikuar për produktet kritike')}</span></label>
   </div></details>
   <details><summary>{t('Manual product selection','Zgjedhja manuale e produkteve')} ({form.product_ids.length}/40)</summary><input aria-label={t('Find products','Gjej produktet')} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('Filter products…','Filtro produktet…')}/><div className="optimizer-products">{options?.products.filter(p=>(p.name+' '+(p.sku??'')).toLowerCase().includes(search.toLowerCase())).map(p=><label key={p.id} className="optimizer-check"><input type="checkbox" checked={form.product_ids.includes(p.id)} disabled={!form.product_ids.includes(p.id)&&form.product_ids.length>=40} onChange={()=>toggle('product_ids',p.id)}/><span>{p.name}</span></label>)}</div><small>{t('Empty selection means company/category/supplier scope, up to 40 products.','Pa zgjedhje përdoret shtrirja e kompanisë/kategorisë/furnitorit, deri në 40 produkte.')}</small></details>
   <div className="optimizer-controls"><label className="optimizer-check"><input type="checkbox" checked={form.allow_transfers} onChange={e=>setForm(f=>({...f,allow_transfers:e.target.checked}))}/><span>{t('Consider protected transfers','Shqyrto transferimet e mbrojtura')}</span></label>
    <button className="optimizer-primary" disabled={busy||!options||optimizerPending(plan?.status)} onClick={optimize}>{busy?t('Working…','Duke punuar…'):t('Generate plans','Gjenero planet')}</button></div>
  </section></details>
  {plan&&<section className="optimizer-panel"><div className="optimizer-title"><h2>{t('Plan','Plani')} #{plan.id}</h2><span className={'optimizer-status status-'+plan.status}>{label(plan.status)}</span><small>{plan.evidence_cutoff?new Date(plan.evidence_cutoff).toLocaleString():t('Background job queued','Puna në sfond është në radhë')}</small></div>
   {optimizerPending(plan.status)&&<p role="status">{t('Optimization is running in the background. You can continue working; only this status updates.','Optimizimi kryhet në sfond. Mund të vazhdosh punën; përditësohet vetëm ky status.')}</p>}
   {plan.error&&<p role="alert">{plan.error}</p>}
   {plan.scope.parent_plan_id&&<p><Link to={'/supply-optimizer?plan='+plan.scope.parent_plan_id}>{t('Open original plan','Hap planin origjinal')} #{plan.scope.parent_plan_id}</Link></p>}
   {plan.status==='STALE'&&<p role="alert">{t('Material evidence changed. The frozen result remains historical; generate a fresh plan before preparing drafts.','Dëshmitë ndryshuan ndjeshëm. Rezultati i ngrirë mbetet historik; gjenero plan të ri para përgatitjes.')}</p>}
   <div className="optimizer-alternatives">{alternatives.map(a=><button key={a.key} className={a.key===alternative?.key?'is-selected':''} onClick={()=>{setChosen(a.key);setStress(null);setStressForm(f=>({...f,supplier_id:''}))}}><h3>{label(a.key)}</h3>{a.recommended&&<span>{t('Recommended · approved policy','I rekomanduar · politika e miratuar')}</span>}<strong>{money(a.summary?.commitment)}</strong><p>{label(a.status)}</p><small>{n(a.summary?.purchase_lines)} {t('purchase lines','rreshta blerjeje')} · {n(a.summary?.transfer_lines)} {t('transfers','transferime')}</small><p>{n(a.summary?.unresolved_scopes)} {t('scopes below target','shtrirje nën objektiv')}</p><small>{t('Confidence','Besueshmëria')}: {label(a.summary?.confidence)}</small>{a.equivalent_profiles?.length>0&&<p>{t('Same valid actions for','Veprime të njëjta për')}: {a.equivalent_profiles.map(label).join(', ')}</p>}</button>)}</div>
   {alternative&&['INFEASIBLE','TIME_LIMIT','FAILED'].includes(alternative.status)&&<div role="alert" className="optimizer-note"><p>{alternative.message}</p><p>{t('Review the purchasing commitment limit, required critical coverage and available valid supplier/transfer arrivals before re-optimizing. No constraint was silently relaxed.','Rishiko kufirin e angazhimit, mbulimin e detyrueshëm kritik dhe mbërritjet e vlefshme nga furnitorët/transferimet para rioptimizimit. Asnjë kufizim nuk u zbut në heshtje.')}</p></div>}
   {alternative?.lines?.length>0&&<>
    <p className="optimizer-note">{t('Optimal means optimal within the frozen, bounded candidate set—not every possible continuous supply-network decision. Other profiles are scenarios and do not change the V10 champion.','Optimal do të thotë optimal brenda kandidatëve të ngrirë e të kufizuar—jo çdo vendim i mundshëm i rrjetit. Profilet e tjera janë skenarë dhe nuk ndryshojnë politikën aktive V10.')}</p>
    <div className="optimizer-table-wrap"><table><thead><tr>{[t('Product / warehouse','Produkti / depo'),t('Stock / incoming','Stoku / në ardhje'),t('Need','Nevoja'),t('Transfer','Transferimi'),t('Purchase','Blerja'),t('Timing','Afati'),t('Risk / explanation','Rreziku / shpjegimi')].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{alternative.lines.map(l=><tr key={l.id}><td><strong>{l.product.name}</strong><small>{l.warehouse?.name??t('Company','Kompania')} · {l.product.unit}</small></td><td>{n(l.current_stock)} / {n(l.incoming)}</td><td>{n(l.projected_need)}</td><td>{n(l.transfer_quantity)}</td><td>{n(l.purchase_quantity)}<small>{money(l.cost_minor/100)}</small></td><td>{label(l.timing)}</td><td><details><summary>{l.coverage_supported?`${n(l.stockout_days)} ${t('shortage days','ditë mungesë')}`:t('Evidence missing','Mungojnë dëshmitë')}</summary><p>{label(l.reason)}</p><p>{t('Preferred-target gap','Mungesa ndaj objektivit')}: {n(l.unmet_target)} {l.product.unit}</p>{l.purchases.map((p,i)=><p key={i}>{p.supplier_name} · {n(p.quantity)} {p.unit} · {money(p.unit_price,p.currency)} · {t('Arrival','Mbërritja')} {p.expected_at} · {t('Lead days','Ditët e furnizimit')} {n(p.lead_days)} · MOQ {n(p.moq)}, {t('multiple','shumëfishi')} {n(p.step)}</p>)}{l.transfers.map((tr,i)=><p key={i}>{tr.source_warehouse_name} → {l.warehouse?.name} · {n(tr.quantity)} · {tr.expected_at}{tr.assumed_route_days?' · '+t('Declared transit assumption','Supozim i deklaruar i udhëtimit'):''}</p>)}</details></td></tr>)}</tbody></table></div>
    <div className="optimizer-context-grid"><section><h3>{t('Supplier consolidation','Konsolidimi i furnitorëve')}</h3>{alternative.supplier_summary?.map(g=><div key={g.supplier_id+g.currency}><strong>{g.supplier_name}</strong><p>{g.products.length} {t('lines','rreshta')} · {money(g.quote_total,g.currency)}</p><small>{g.arrival_from} — {g.arrival_to}</small><small>{t('Supplier capacity / payment terms: not recorded','Kapaciteti / afatet e pagesës së furnitorit: të paregjistruara')}</small><small>{t('Potential consolidation; shipping savings and payment terms not inferred.','Mundësi konsolidimi; kursimet e transportit dhe afatet e pagesës nuk hamendësohen.')}</small></div>)}</section>
     <section><h3>{t('Financial context','Konteksti financiar')}</h3><p>{t('Existing recorded PO commitments','Angazhimet ekzistuese të regjistruara')}: {money(plan.context?.finance?.open_po_commitments)}</p><p>{t('Proposed NEW commitment','Angazhimi i RI i propozuar')}: {money(alternative.summary.commitment)}</p><p>{t('Recorded PO outstanding','Detyrimet e regjistruara të porosive')}: {money(plan.context?.finance?.po_outstanding)}</p><small>{t('Separate sources, not cash spent or proof of affordability. V7 snapshot','Burime të ndara, jo para të shpenzuara apo provë e mundësisë financiare. Pamja V7')}: {plan.context?.v7?.as_of??'—'}</small></section></div>
    <p className="optimizer-note">{t('V7 expected closing cash / if new purchases were fully paid in the horizon','V7 para të parashikuara në mbyllje / nëse blerjet e reja paguhen plotësisht gjatë periudhës')}: {money(alternative.financial_context?.baseline_expected_closing_cash)} / {money(alternative.financial_context?.if_fully_paid_in_horizon)}. {t('Hypothetical payment scenario only, not a payment schedule or proof of affordability.','Vetëm skenar hipotetik pagese, jo orar pagesash ose provë e mundësisë financiare.')}</p>
    <details><summary>{t('Quantity trade-offs','Kompromiset e sasive')}</summary>
     <p className="optimizer-note">{t('Nearby valid quantities with the same suppliers and timing. A larger local quantity may displace another product under the shared limit; these are not new whole-company solutions.','Sasi të afërta me të njëjtët furnitorë dhe afate. Sasia më e madhe mund të zëvendësojë një produkt tjetër nën kufirin e përbashkët; këto nuk janë zgjidhje të reja për kompaninë.')}</p>
     {alternative.lines.filter(l=>l.quantity_tradeoff?.lower||l.quantity_tradeoff?.higher).map(l=><div key={l.id}><strong>{l.product.name} · {l.warehouse?.name??t('Company','Kompania')} · {t('Selected','E zgjedhur')}: {n(l.purchase_quantity)} {l.product.unit}</strong>{['lower','higher'].map(k=>{const v=l.quantity_tradeoff[k];return v&&<p key={k}>{t(k==='lower'?'Less':'More',k==='lower'?'Më pak':'Më shumë')}: {n(v.purchase_quantity)} {l.product.unit} · {money(v.cost_minor/100)} · {n(v.stockout_days)} {t('shortage days','ditë mungesë')} · {t('Target gap','Mungesa ndaj objektivit')} {n(v.unmet_target)} · {t('Average excess','Teprica mesatare')} {n(v.excess_mean)}</p>})}</div>)}
    </details>
    <section><h3>{t('Defined stress tests','Testet e përcaktuara të stresit')}</h3><p>{label(alternative.resilience)}</p><div className="optimizer-context-grid">{Object.entries(alternative.stress_tests??{}).map(([k,v])=><div key={k}><strong>{k==='demand_plus_20'?t('Demand +20%','Kërkesa +20%'):k==='supplier_plus_10_days'?t('Supplier deliveries +10 days','Furnizimet +10 ditë'):t('Dated incoming PO +7 days','Porositë në ardhje +7 ditë')}</strong><p>{n(v.affected_scopes)} {t('scopes with more shortage days','shtrirje me më shumë ditë mungesë')}</p></div>)}</div><small>{t('Named scenarios, not arbitrary scores. Missing data cannot prove resilience.','Skenarë të emërtuar, jo vlerësime arbitrare. Të dhënat e mangëta nuk provojnë qëndrueshmëri.')}</small>
     <details><summary>{t('Choose a stress scenario','Zgjidh një skenar stresi')}</summary><div className="optimizer-form">
      <label>{t('Demand (% of baseline)','Kërkesa (% e bazës)')}<input type="number" min="50" max="200" value={stressForm.demand_percent} onChange={e=>setStressForm(f=>({...f,demand_percent:e.target.value}))}/></label>
      <label>{t('Supplier delay (days)','Vonesa e furnitorit (ditë)')}<input type="number" min="0" max="30" value={stressForm.supplier_delay} onChange={e=>setStressForm(f=>({...f,supplier_delay:e.target.value}))}/></label>
      <label>{t('Supplier affected','Furnitori i prekur')}<select aria-label={t('Supplier affected','Furnitori i prekur')} value={stressForm.supplier_id} onChange={e=>setStressForm(f=>({...f,supplier_id:e.target.value}))}><option value="">{t('All proposed suppliers','Të gjithë furnitorët e propozuar')}</option>{stressSuppliers(alternative).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
      <label>{t('Incoming delay (days)','Vonesa e furnizimit në ardhje (ditë)')}<input type="number" min="0" max="30" value={stressForm.shipment_delay} onChange={e=>setStressForm(f=>({...f,shipment_delay:e.target.value}))}/></label>
      <label>{t('Shipment affected','Dërgesa e prekur')}<select aria-label={t('Shipment affected','Dërgesa e prekur')} value={stressForm.shipment_id} onChange={e=>setStressForm(f=>({...f,shipment_id:e.target.value}))}><option value="">{t('All dated incoming POs','Të gjitha porositë e datuara në ardhje')}</option>{plan.stress_options?.shipments.map(s=><option value={s.id} key={s.id}>{s.reference??`#${s.id}`}</option>)}</select></label>
      <label>{t('Collections delay (days)','Vonesa e arkëtimeve (ditë)')}<input type="number" min="0" max="60" value={stressForm.collections_delay} onChange={e=>setStressForm(f=>({...f,collections_delay:e.target.value}))}/></label>
     </div></details>
     <button disabled={busy} onClick={testStress}>{t('Inspect stress scenario','Shiko skenarin e stresit')}</button>{stress&&<div role="status"><ul>{stress.rows.map((r,i)=><li key={i}>{r.product.name}: {n(r.baseline_stockout_days)} → {n(r.stressed_stockout_days)} {t('shortage days','ditë mungesë')}</li>)}</ul>{stress.collections_context&&<p>{t('V7 expected closing cash — baseline / scenario','V7 para të parashikuara në mbyllje — bazë / skenar')}: {money(stress.collections_context.baseline?.currencies?.[plan.context.currency]?.expected_closing_cash)} / {money(stress.collections_context.scenario?.currencies?.[plan.context.currency]?.expected_closing_cash)}<small>{t('Frozen dated collections only, not a purchasing budget. Missing evidence is shown as —.','Vetëm arkëtime të datuara e të ngrira, jo buxhet blerjeje. Dëshmitë që mungojnë shfaqen si —.')}</small></p>}</div>}
    </section>
    <div className="optimizer-controls"><button className="optimizer-primary" disabled={busy||!canPreparePlan(plan,alternative,options?.permissions)} onClick={()=>{setConfirmed(false);setReview(true)}}>{t('Review & prepare drafts','Rishiko dhe përgatit draftet')}</button><Link to="/decision-learning">{t('Decision Learning','Mësimi i vendimeve')}</Link></div>
    <div className="optimizer-controls"><label>{t('Compare another commitment limit','Krahaso një kufi tjetër angazhimi')}<input type="number" min="0" step="0.01" value={scenarioLimit} onChange={e=>setScenarioLimit(e.target.value)}/></label><button disabled={busy||scenarioLimit===''||Number(scenarioLimit)<0} onClick={simulateLimit}>{t('Create new limit scenario','Krijo skenar me kufi të ri')}</button><small>{t('Keeps this plan unchanged and reuses its scope.','E mban planin të pandryshuar dhe ripërdor shtrirjen e tij.')}</small></div>
   </>}
   {plan.drafts&&<section className="optimizer-success" role="status"><h3>{t('Reviewed drafts prepared — not executed','Draftet e rishikuara u përgatitën — jo të realizuara')}</h3>{plan.drafts.purchase_requests.map(d=><p key={d.id}><Link to={d.url}>{t('Open Purchase Request','Hap kërkesën e blerjes')} {d.reference}</Link> · {d.supplier} · {money(d.total,d.currency)}</p>)}{plan.drafts.transfers.map(d=><p key={d.id}><Link to={d.url}>{t('Open Transfer','Hap transferimin')} {d.reference}</Link></p>)}{plan.execution?.purchase_orders.map(o=><p key={o.id}><Link to={o.url}>{o.reference}</Link> · {o.status} · {money(o.total,o.currency)}</p>)}</section>}
   {plan.approved&&<section><h3>{t('Plan vs execution','Plani kundrejt realizimit')}</h3><p>{t('Human-reviewed commitment','Angazhimi i rishikuar nga përdoruesi')}: {money(plan.approved.summary.commitment)}</p><p>{t('Observed PO / dispatched transfer counts','Numri i porosive / transferimeve të nisura të vëzhguara')}: {plan.execution?.purchase_orders?.length??0} / {plan.execution?.transfers?.length??0}</p>{plan.outcome?<><p>{t('Completed observation window','Periudha e përfunduar e vëzhgimit')}: {plan.outcome.window.from} — {plan.outcome.window.to}</p><ul>{plan.outcome.rows.map(r=><li key={r.product_id+':'+r.warehouse_id}>#{r.product_id} · {n(r.scorecard.stockout_days)} {t('sampled stockout days','ditë mungesë të mostruara')} · {t('Ending available stock','Stoku në dispozicion në fund')}: {n(r.scorecard.ending_available)}</li>)}</ul></>:<small>{t('Outcomes require real execution and complete future stock observations. Prepared drafts are not proof of success.','Rezultatet kërkojnë realizim real dhe vëzhgime të plota të stokut në të ardhmen. Draftet nuk janë provë e suksesit.')}</small>}</section>}
   {plan.result&&<details><summary>{t('Methodology & technical details','Metodologjia & hollësitë teknike')}</summary><small>{plan.result.solver} · {plan.result.version} · {n(plan.result.seconds)} s · {n(plan.result.variables)} {t('candidates','kandidatë')} · {t('Approved policy','Politika e miratuar')}: {plan.context?.policy?.version}</small></details>}
  </section>}
  <section className="optimizer-panel"><h2>{t('Recent plans','Planet e fundit')}</h2>{history.length?history.map(p=><button className="optimizer-history" key={p.id} onClick={()=>setParams({plan:String(p.id)})}>#{p.id} · {p.scope.horizon} {t('days','ditë')} · {label(p.status)}</button>):<p>{t('Generate your first plan. No business data is changed by optimization.','Gjenero planin e parë. Optimizimi nuk ndryshon të dhënat e biznesit.')}</p>}</section>
  <details className="optimizer-panel"><summary>{t('Data limitations & safe use','Kufizimet e të dhënave dhe përdorimi i sigurt')}</summary><ul><li>{t('No invented supplier capacity, freight savings, holding cost or lost-sales money.','Pa kapacitete furnitori, kursime transporti, kosto mbajtjeje ose shitje të humbura të shpikura.')}</li><li>{t('Catalogue prices are estimates; existing quotes and approvals remain authoritative in procurement.','Çmimet e katalogut janë vlerësime; ofertat dhe miratimet ekzistuese mbeten autoritative në prokurim.')}</li><li>{t('Unknown donor demand or transfer arrival excludes the transfer. Risky/undated incoming is not counted as reliable on-time stock.','Kërkesa e panjohur e depos burimore ose afati i panjohur përjashton transferimin. Furnizimi i rrezikuar/pa datë nuk llogaritet si stok i sigurt në kohë.')}</li><li>{t('Optimization, review, prepared drafts and actual execution are separate frozen evidence stages.','Optimizimi, rishikimi, draftet dhe realizimi janë etapa të ndara dëshmish të ngrira.')}</li></ul></details>
  {review&&alternative&&createPortal(<div className="optimizer-overlay" role="presentation"><section ref={reviewRef} tabIndex={-1} className="optimizer-modal" role="dialog" aria-modal="true" aria-labelledby="optimizer-review-title"><h2 id="optimizer-review-title">{t('Confirm draft preparation','Konfirmo përgatitjen e drafteve')}</h2><p>{label(alternative.key)} · {money(alternative.summary.commitment)}</p><p>{alternative.summary.purchase_lines} {t('purchase lines','rreshta blerjeje')} · {alternative.summary.transfer_lines} {t('transfer lines','rreshta transferimi')}</p>{groups.map(g=><div key={g.supplier+g.currency}><h3>{g.supplier} · {g.currency}</h3>{g.lines.map((p,i)=><p key={i}>{p.product.name}: {n(p.quantity)} {p.unit} × {money(p.unit_price,p.currency)} → {money(p.quote_cost,p.currency)} · {p.warehouse_name??t('Company','Kompania')} · {p.expected_at}</p>)}</div>)}<p>{t('Live stock, incoming, supplier eligibility, prices, units and sourcing will be revalidated. No final PO, payment or stock movement is created.','Stoku, furnizimet, furnitorët, çmimet, njësitë dhe kërkesat do të rivlerësohen. Nuk krijohet porosi përfundimtare, pagesë ose lëvizje stoku.')}</p><label className="optimizer-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{t('I reviewed these proposals and want workflow drafts only.','I rishikova propozimet dhe dua vetëm draftet e rrjedhave.')}</span></label><div className="optimizer-controls"><button disabled={busy} onClick={()=>setReview(false)}>{t('Go back','Kthehu')}</button><button className="optimizer-primary" disabled={busy||!confirmed} onClick={prepare}>{busy?t('Preparing…','Duke përgatitur…'):t('Confirm & prepare drafts','Konfirmo dhe përgatit draftet')}</button></div>{error&&<p role="alert">{error}</p>}</section></div>,document.body)}
 </main>
}
