const statuses = {
 REPLENISHMENT_DECISION:['Restocking review','Rishikim i furnizimit'],TRANSFER_VS_PURCHASE:['Transfer or purchase review','Transfer apo blerje'],SUPPLIER_SELECTION:['Supplier choice','Zgjedhja e furnitorit'],PURCHASE_TIMING:['Purchase timing','Koha e blerjes'],INCOMING_STOCK_RISK:['Incoming stock risk','Rreziku i stokut në ardhje'],EXCESS_INVENTORY_ACTION:['Excess stock review','Rishikim i stokut të tepërt'],
 short_pick:['Picking quantity short','Sasi e pamjaftueshme për mbledhje'],milestone_overdue:['Shipment step overdue','Hap i dërgesës me vonesë'],order_overdue:['Order delivery overdue','Dorëzimi i porosisë me vonesë'],
 draft:['Draft','Draft'],open:['Open','E hapur'],pending:['Waiting','Në pritje'],in_progress:['In progress','Në punë'],completed:['Completed','Përfunduar'],cancelled:['Cancelled','Anuluar'],blocked:['Blocked','Bllokuar'],warning:['Needs attention','Kërkon vëmendje'],normal:['Normal','Normale'],over_limit:['Over credit limit','Mbi limitin e kredisë'],
 received:['Received','Pranuar'],validated:['Ready for confirmation','Gati për konfirmim'],accepted:['Confirmed','Konfirmuar'],confirmed:['Confirmed','Konfirmuar'],approved:['Approved','Miratuar'],rejected:['Rejected','Refuzuar'],consumed:['Applied','Zbatuar'],ordered:['Ordered','Porositur'],in_transit:['In transit','Në transit'],arrived:['Arrived','Ka mbërritur'],delivered:['Delivered','Dorëzuar'],partially_received:['Partially received','Pranuar pjesërisht'],paid:['Paid','Paguar'],unpaid:['Unpaid','Papaguar'],partially_paid:['Partially paid','Paguar pjesërisht'],overdue:['Overdue','Me vonesë'],failed:['Needs review','Kërkon rishikim'],attention:['Needs attention','Kërkon vëmendje'],
 ready_to_allocate:['Ready to fulfill','Gati për përmbushje'],allocated:['Reserved for picking','Rezervuar për mbledhje'],partially_allocated:['Partially reserved','Rezervuar pjesërisht'],picked:['Picked','Mbledhur'],packed:['Ready to dispatch','Gati për nisje'],dispatched:['Dispatched','Nisur'],on_track:['On track','Në rregull'],replenishment:['Restocking review','Rishikim i furnizimit'],supplier_switch:['Supplier review','Rishikim furnitori'],stockout:['Stock shortage risk','Rrezik i mungesës së stokut'],purchase:['Purchase review','Rishikim blerjeje'],transfer:['Stock transfer review','Rishikim transferimi'],
}
export const businessStatus = (value,language='en') => value==null||value===''?'—':statuses[value]?.[language==='sq'?1:0]||String(value).replaceAll('_',' ')
export const businessSubtitle = (value,language='en') => String(value||'').split(' · ').map(part=>businessStatus(part,language)).join(' · ')
